In [36]:
from dotenv import load_dotenv
import os
from pathlib import Path
from openai import AzureOpenAI
from embeddings import UserDocumentCollection
import os, json, re
import pandas as pd

import numpy as np
from pypdf import PdfReader
import win32com.client as win32
from time import sleep

In [37]:
load_dotenv()

True

In [38]:
raw_path = os.environ.get("RAW_PATH")
folder_path = os.environ.get("FOLDER_PATH")
data_path= Path(folder_path) / "PC"

In [39]:
files = [p for p in Path(raw_path).iterdir() if p.is_file()]
print("Number of files:", len(files))

Number of files: 92

In [40]:
from pathlib import Path
import re

raw_path = Path(raw_path)  # or Path(r"...full\path\here")

prefixes = set()

for p in raw_path.iterdir():
    if p.is_file() and p.suffix.lower() == ".pdf":
        prefix = re.split(r"[-_]", p.stem, maxsplit=1)[0]
        prefixes.add(prefix)

print("Number of unique PDF numbers:", len(prefixes))

Number of unique PDF numbers: 68

In [41]:
from pypdf import PdfReader, PdfWriter
import shutil
import re
from pathlib import Path

SKIP_NAME = "F33073064-Dutch_vision_on_biotechnology__ENGLISH.pdf"

def merge_pdfs(input_paths, output_path):
    writer = PdfWriter()
    for pdf_path in input_paths:
        reader = PdfReader(pdf_path)
        for page in reader.pages:
            writer.add_page(page)
    with open(output_path, "wb") as f:
        writer.write(f)

groups = {}

# 1) First, handle PDFs: group by prefix (before first "-" or "_")
for p in Path(raw_path).iterdir():
    if p.is_file():
        # ⬇️ skip this specific file
        if p.name == SKIP_NAME:
            continue

        if p.suffix.lower() == ".pdf":
            prefix = re.split(r"[-_]", p.stem, maxsplit=1)[0]
            groups.setdefault(prefix, []).append(p)
  

# 3) Now create exactly ONE PDF per prefix in output folder
for prefix, files in groups.items():
    files = sorted(files)
    out_pdf = data_path / f"{prefix}.pdf"

    if len(files) == 1:
        shutil.copy2(files[0], out_pdf)
        print(f"Copied single PDF for prefix '{prefix}' -> {out_pdf}")
    else:
        merge_pdfs(files, out_pdf)
        print(f"Merged {len(files)} PDFs for prefix '{prefix}' -> {out_pdf}")

Merged 2 PDFs for prefix 'F33073064' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33073064.pdf
Copied single PDF for prefix 'F33083732' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33083732.pdf
Copied single PDF for prefix 'F33094597' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33094597.pdf
Copied single PDF for prefix 'F33096176' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33096176.pdf
Copied single PDF for prefix 'F33097445' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33097445.pdf
Copied single PDF for prefix 'F33104014' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33104014.pdf
Copied single PDF for prefix 'F33105185' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33105185.pdf
Copied single PDF for prefix 'F33113117' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33113117.pdf
Merged 4 PDFs for prefix 'F33113340' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33113340.pdf
Copied single PDF for prefix 'F33113596' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33113596.pdf
Merged 2 PDFs for prefix 'F33113733' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33113733.pdf
Copied single PDF for prefix 'F33113897' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33113897.pdf
Copied single PDF for prefix 'F33114274' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114274.pdf
Copied single PDF for prefix 'F33114282' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114282.pdf
Copied single PDF for prefix 'F33114287' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114287.pdf
Copied single PDF for prefix 'F33114296' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114296.pdf
Copied single PDF for prefix 'F33114368' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114368.pdf
Copied single PDF for prefix 'F33114380' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114380.pdf
Copied single PDF for prefix 'F33114405' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114405.pdf
Merged 2 PDFs for prefix 'F33114469' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114469.pdf
Copied single PDF for prefix 'F33114476' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114476.pdf
Copied single PDF for prefix 'F33114485' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114485.pdf
Copied single PDF for prefix 'F33114492' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114492.pdf
Merged 3 PDFs for prefix 'F33114494' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114494.pdf
Copied single PDF for prefix 'F33114498' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114498.pdf
Copied single PDF for prefix 'F33114505' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114505.pdf
Copied single PDF for prefix 'F33114507' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114507.pdf
Copied single PDF for prefix 'F33114508' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114508.pdf
Copied single PDF for prefix 'F33114513' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114513.pdf
Copied single PDF for prefix 'F33114514' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114514.pdf
Copied single PDF for prefix 'F33114518' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114518.pdf
Copied single PDF for prefix 'F33114522' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114522.pdf
Copied single PDF for prefix 'F33114528' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114528.pdf
Copied single PDF for prefix 'F33114535' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114535.pdf
Copied single PDF for prefix 'F33114543' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114543.pdf
Copied single PDF for prefix 'F33114550' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114550.pdf
Copied single PDF for prefix 'F33114580' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114580.pdf
Copied single PDF for prefix 'F33114601' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114601.pdf
Merged 6 PDFs for prefix 'F33114700' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114700.pdf
Copied single PDF for prefix 'F33114703' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114703.pdf
Copied single PDF for prefix 'F33114714' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114714.pdf
Copied single PDF for prefix 'F33114715' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114715.pdf
Copied single PDF for prefix 'F33114716' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114716.pdf
Copied single PDF for prefix 'F33114718' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114718.pdf
Merged 2 PDFs for prefix 'F33114871' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114871.pdf
Copied single PDF for prefix 'F33114902' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114902.pdf
Copied single PDF for prefix 'F33114933' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114933.pdf
Copied single PDF for prefix 'F33114947' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114947.pdf
Copied single PDF for prefix 'F33114949' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114949.pdf
Copied single PDF for prefix 'F33114950' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114950.pdf
Copied single PDF for prefix 'F33114951' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114951.pdf
Copied single PDF for prefix 'F33114960' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114960.pdf
Copied single PDF for prefix 'F33114961' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33114961.pdf
Copied single PDF for prefix 'F33115064' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33115064.pdf
Copied single PDF for prefix 'F33115326' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33115326.pdf
Copied single PDF for prefix 'F33115617' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33115617.pdf
Copied single PDF for prefix 'F33115928 (2)' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33115928 (2).pdf
Copied single PDF for prefix 'F33115932' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33115932.pdf
Copied single PDF for prefix 'F33116245' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33116245.pdf
Copied single PDF for prefix 'F33116494' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33116494.pdf
Copied single PDF for prefix 'F33116813' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33116813.pdf
Copied single PDF for prefix 'F33116818' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33116818.pdf
Copied single PDF for prefix 'F33116821' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33116821.pdf
Copied single PDF for prefix 'F33117138' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33117138.pdf
Copied single PDF for prefix 'F33117395' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33117395.pdf
Copied single PDF for prefix 'F33117397' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33117397.pdf
Merged 2 PDFs for prefix 'F33117687' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F33117687.pdf
Copied single PDF for prefix 'F3593805' -> C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\data\PC\F3593805.pdf

In [20]:
container_name="brussels-docs"
colect = UserDocumentCollection(container_name)


for p in sorted([p for p in Path(data_path).iterdir() if p.is_file()]):
    file_path = str(p)
    with open(file_path, "rb") as file_obj:
        colect.add_file_to_blob_container(file_path, file_obj)

colect.create_user_search_index()
colect.create_data_source_connection()
colect.create_user_skillset()
colect.create_user_indexer()

2025-12-01 12:10:53.869 | INFO     | embeddings:get_container:66 - Container 'brussels-docs' already exists.
2025-12-01 12:10:54.002 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33073064.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.030 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33083732.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.047 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33091336.docx' to container 'brussels-docs'.
2025-12-01 12:10:54.065 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33094597.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.082 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33096176.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.101 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33097445.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.188 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33104014.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.228 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33105185.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.248 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33113117.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.298 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33113340.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.401 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33113596.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.447 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33113733.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.524 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33113897.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.541 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33113962.docx' to container 'brussels-docs'.
2025-12-01 12:10:54.576 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114274.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.601 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114282.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.621 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114287.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.639 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114296.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.682 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114368.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.736 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114380.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.753 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114394.docx' to container 'brussels-docs'.
2025-12-01 12:10:54.815 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114405.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.833 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114466.docx' to container 'brussels-docs'.
2025-12-01 12:10:54.864 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114469.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.926 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114476.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.942 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114478.docx' to container 'brussels-docs'.
2025-12-01 12:10:54.963 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114485.pdf' to container 'brussels-docs'.
2025-12-01 12:10:54.996 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114492.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.086 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114494.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.113 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114498.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.151 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114505.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.179 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114507.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.210 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114508.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.229 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114513.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.257 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114514.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.276 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114518.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.293 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114522.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.324 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114528.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.346 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114535.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.391 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114543.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.412 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114550.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.440 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114580.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.458 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114601.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.510 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114700.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.530 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114703.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.619 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114714.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.639 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114715.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.658 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114716.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.676 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114718.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.753 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114871.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.772 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114902.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.788 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114919.docx' to container 'brussels-docs'.
2025-12-01 12:10:55.806 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114933.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.824 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114947.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.879 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114949.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.899 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114950.pdf' to container 'brussels-docs'.
2025-12-01 12:10:55.994 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114951.pdf' to container 'brussels-docs'.
2025-12-01 12:10:56.011 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114960.pdf' to container 'brussels-docs'.
2025-12-01 12:10:56.029 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33114961.pdf' to container 'brussels-docs'.
2025-12-01 12:10:56.048 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33115064.pdf' to container 'brussels-docs'.
2025-12-01 12:10:56.074 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33115326.pdf' to container 'brussels-docs'.
2025-12-01 12:10:56.104 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33115617.pdf' to container 'brussels-docs'.
2025-12-01 12:10:56.132 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33115928 (2).pdf' to container 'brussels-docs'.
2025-12-01 12:10:56.151 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33115932.pdf' to container 'brussels-docs'.
2025-12-01 12:10:56.221 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33116245.pdf' to container 'brussels-docs'.
2025-12-01 12:10:56.239 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33116494.pdf' to container 'brussels-docs'.
2025-12-01 12:10:56.267 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33116813.pdf' to container 'brussels-docs'.
2025-12-01 12:10:56.286 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33116818.pdf' to container 'brussels-docs'.
2025-12-01 12:10:56.304 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33116821.pdf' to container 'brussels-docs'.
2025-12-01 12:10:56.323 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33117138.pdf' to container 'brussels-docs'.
2025-12-01 12:10:56.372 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33117395.pdf' to container 'brussels-docs'.
2025-12-01 12:10:56.414 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33117397.pdf' to container 'brussels-docs'.
2025-12-01 12:10:56.444 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F33117687.pdf' to container 'brussels-docs'.
2025-12-01 12:10:56.486 | INFO     | embeddings:add_file_to_blob_container:96 - Uploaded 'F3593805.pdf' to container 'brussels-docs'.
2025-12-01 12:10:57.058 | INFO     | embeddings:create_user_search_index:130 - ✅ Index 'brussels-docs_index' created or updated successfully.
2025-12-01 12:10:57.275 | INFO     | embeddings:create_data_source_connection:168 - ✅ Data source connection 'brussels-docs-ds' created or updated successfully.
2025-12-01 12:10:57.483 | INFO     | embeddings:create_user_skillset:208 - ✅ Skillset 'brussels-docs-ss' created or updated successfully.
2025-12-01 12:11:00.476 | INFO     | embeddings:create_user_indexer:237 - ✅ Indexer 'brussels-docs-indexer' created or updated successfully.

In [22]:
colect.reset_and_run_indexer()

2025-12-01 12:12:33.812 | INFO     | embeddings:reset_and_run_indexer:252 - 🧹 Indexer 'brussels-docs-indexer' checkpoint reset successfully.
2025-12-01 12:12:34.013 | INFO     | embeddings:reset_and_run_indexer:256 - 🚀 Indexer 'brussels-docs-indexer' started successfully.

In [23]:
user_prompt = """
Extract the following fields ONLY from that document; do not invent facts.

Return ONE JSON object with exactly these keys and types:
- "title": string (Do not give back the document name. Instead, find what is the title that appears in the first page of document ?)
- "organisation": array of strings (What is the organizations that wrote this the document)
- "summary": string (summarise the document that you already possess in 4-6 sentences capturing the essentials; suitable for one spreadsheet cell, written in British English)
- "main themes": array of up to 10 short theme phrases (ranked by prominence, written in British English; do not pad with guesses)

Rules:
- Base your answer ONLY on the provided content; do not rely on outside knowledge.
- If a field is not present, set it to null (or [] for arrays).
- Preserve the document's original title (do not translate it); the "summary" and "main_themes" must be in British English.
- Output VALID JSON and NOTHING ELSE (no markdown fences, no prose, no citations like [doc1])."""

In [24]:
pillars_prompt = """Below are concise definitions of five challenges that motivate a new Biotechnology Act:

- VC (Access to Capital): Biotech requires large upfront funding for long R&D, trials, regulation, and scale-up; early bootstrapping helps, but VC/PE/strategic capital typically catalyze growth and Europe faces persistent risk-capital gaps and foreign exits.
- Clusters (Biotech clusters & technology centers): Co-located hubs concentrate talent, infrastructure, and investment, enabling public–private partnerships, sector specialization, shared services (regulatory/funding/market access), and internationalization.
- Skills (Reskilling & upskilling): Biomanufacturing needs deep process expertise (e.g., fermentation, molecular methods) plus cross-cutting data/AI, sustainability, systems thinking, and entrepreneurship; agile VET/HE and lifelong learning are critical.
- AI/data (Use of data & AI): AI (incl. GenAI) turns large scientific/process datasets into gains across discovery, engineering, and operations (e.g., target ID, CRISPR guide design, digital twins), with outcomes dependent on data quality, validation, and governance.
- Dual-use/security (Awareness of misuse risks): Attention to potential dual-use concerns and biosecurity, including risks of misuse such as development of bioweapons, uncontrolled pathogens, or other harmful applications. May appear in the context of regulation, funding decisions, or calls for responsible innovation and safeguards.


TASK: For each challenge, check whether the document makes a substantive reference to it. 
If yes, return a MAXIMUM TWO-SENTENCE summary in BRITISH ENGLISH of how the document addresses that challenge (what it says, proposes, or evidences). If not present, set the value to null.
Return ONE JSON object with EXACTLY these keys (values are either a string ≤2 sentences or null):
{
  "VC": <string or null>,
  "clusters": <string or null>,
  "skills": <string or null>,
  "AI/data": <string or null>,
  "dual_use/security": <string or null>
}

Rules:
- Base your answer ONLY on the provided content; do not rely on outside knowledge.
- Do not invent facts; if uncertain, use null.
- Output VALID JSON and NOTHING ELSE (no markdown fences, no prose, no citations)."""

In [25]:
client = AzureOpenAI(
    azure_endpoint=os.environ["AZURE_COGNITIVE_SERVICES_ENDPOINT"],
    api_key=os.environ["AZURE_COGNITIVE_API"],
    api_version="2024-10-21",  # 2024-02-01+ supports data_sources
)

### FIRST TEST BY FILTERING FOR A SINGLE DOCUMENT

In [26]:

def odata_escape(s: str) -> str:
    # OData string literals escape single quotes by doubling them
    return s.replace("'", "''")

In [32]:
#doc_name = 'F3554271-Koppert submission for the biotech act consultations.pdf'        
doc_name="F33114469.pdf"

completion = client.chat.completions.create(
    model="gpt-4.1",
    messages=[{"role": "user", 
               "content": user_prompt}],
    extra_body={
        "data_sources": [
            {
                "type": "azure_search",
                "parameters": {
                    "endpoint": os.environ["AZURE_AI_SEARCH_ENDPOINT"],
                    "index_name": f"{container_name}_index",
                    "authentication": {
                        "type": "api_key",
                        "key": os.environ["AZURE_AI_SEARCH_API_KEY"],
                    },

                    # Map fields so citations show nice titles/paths (optional but handy)
                    "fields_mapping": {
                        "title_field": "title",
                        "filepath_field": "filepath",
                        "url_field": "url",
                        
                    },

                    # B) If you stored the doc name in a custom field
                    "filter": f"title eq '{odata_escape(doc_name)}'",


                    "in_scope": True,        # keep the answer grounded to retrieved docs
                    # "strictness": 4,       # (optional) tighten relevance
                    # "top_n_documents": 5,  # (optional) fewer chunks for stricter focus
                },
            }
        ],
    },
)

print(completion.choices[0].message.content)

{
  "title": null,
  "organisation": [],
  "summary": null,
  "main themes": []
}

In [31]:
def extract_information(doc_name):
    completion = client.chat.completions.create(
        model="gpt-4.1",
        messages=[{"role": "user", "content": f"You already possess the document {doc_name} that contain all necessary information to answer following questions. \n" + user_prompt, }],
        response_format={"type": "json_object"},
        extra_body={
            "data_sources": [
                {
                    "type": "azure_search",
                    "parameters": {
                        "endpoint": os.environ["AZURE_AI_SEARCH_ENDPOINT"],
                        "index_name": f"{container_name}_index",
                        "authentication": {
                            "type": "api_key",
                            "key": os.environ["AZURE_AI_SEARCH_API_KEY"],
                        },
                        "fields_mapping": {
                            "title_field": "title",
                            "filepath_field": "filepath",
                            "url_field": "url",
                        },
                        "filter": f"title eq '{odata_escape(doc_name)}'",
                        "in_scope": True,
                        # "strictness": 4,
                        # "top_n_documents": 5,
                    },
                }
            ],
        },
    )
    raw = completion.choices[0].message.content or ""
    try:
        return json.loads(raw)  # now it should be valid JSON
    except json.JSONDecodeError:
        # Fallback: return your schema with nulls so the loop doesn't crash
        return {
            "title": None,
            "organization": [],
            "summary": None,
            "main themes": [],
        }

In [30]:
def extract_pillars(doc_name):
    completion = client.chat.completions.create(
        model="gpt-4.1",
        messages=[{"role": "user", "content": f"You already possess the document {doc_name} that contain all necessary information to answer following questions. \n" + pillars_prompt, }],
        response_format={"type": "json_object"},
        extra_body={
            "data_sources": [
                {
                    "type": "azure_search",
                    "parameters": {
                        "endpoint": os.environ["AZURE_AI_SEARCH_ENDPOINT"],
                        "index_name": f"{container_name}_index",
                        "authentication": {
                            "type": "api_key",
                            "key": os.environ["AZURE_AI_SEARCH_API_KEY"],
                        },
                        "fields_mapping": {
                            "title_field": "title",
                            "filepath_field": "filepath",
                            "url_field": "url",
                        },
                        "filter": f"title eq '{odata_escape(doc_name)}'",
                        "in_scope": True,
                        # "strictness": 4,
                        # "top_n_documents": 5,
                    },
                }
            ],
        },
    )
    raw = completion.choices[0].message.content or ""
    try:
        return json.loads(raw)  # now it should be valid JSON
    except json.JSONDecodeError:
        # Fallback: return your schema with nulls so the loop doesn't crash
        return {
            "VC": None,
            "clusters": None,
            "skills": None,
            "AI/data": None,
            "dual_use/security": None
        }

In [34]:
doc_name='F33114405.pdf'
extract_information(doc_name)

{'title': 'VTT messages for the EU Biotechnology act',
 'organisation': ['VTT Technical Research Centre of Finland'],
 'summary': "The document presents VTT's recommendations for the development of the European Biotech Act, emphasising the need for efficient feedstock use, diversified production, and circular economy solutions to support economic security and ecosystem protection. It highlights the importance of aligning regulation, innovation, and industrial policies to fully harness biotechnology's potential for market products and European competitiveness. Key areas include investment in computational design, DNA engineering, bioprocess scale-up, and the integration of AI and machine learning. The document calls for improved access to capital, streamlined regulatory processes, and the creation of supportive infrastructure for biomanufacturing. It also details VTT's role in supporting start-ups and scale-ups through incubation, funding, and access to technology infrastructures. Examples of successful VTT spin-offs in bio-based innovation are provided, illustrating the impact of these strategies.",
 'main themes': ['Biotechnology regulation and policy',
  'Sustainable feedstock and circular economy',
  'Investment in biomanufacturing infrastructure',
  'Integration of AI and machine learning',
  'Support for start-ups and scale-ups',
  'Streamlining EU regulatory processes',
  'Public-private collaboration',
  'Deep-tech innovation and commercialisation',
  'Bio-based product development',
  'Examples of successful spin-offs']}

## LOOP OVER ALL DOCUMENTS

In [35]:

from time import sleep, strftime
from openai import APIConnectionError, BadRequestError
import re

def call_once_with_wait(fn, *args, delay=10, label=None, **kwargs):
    who = f"[{label}]" if label else ""
    print(f"{strftime('%H:%M:%S')} {who} waiting {delay}s before call...", flush=True)
    sleep(delay)
    try:
        out = fn(*args, **kwargs)
        print(f"{strftime('%H:%M:%S')} {who} call OK", flush=True)
        return out
    except BadRequestError as e:
        s = str(e)
        if "Rate limit is exceeded" in s:
            m = re.search(r"Try again in\s+(\d+)\s+seconds?", s, re.I)
            wait_s = int(m.group(1)) + 1 if m else max(5, delay)
            print(f"{strftime('%H:%M:%S')} {who} 429 rate limit → waiting {wait_s}s, then retrying once...", flush=True)
            sleep(wait_s)
            out = fn(*args, **kwargs)
            print(f"{strftime('%H:%M:%S')} {who} retry OK", flush=True)
            return out
        print(f"{strftime('%H:%M:%S')} {who} BadRequestError (not rate-limit): {e}", flush=True)
        raise
    except APIConnectionError as e:
        print(f"{strftime('%H:%M:%S')} {who} connection error → waiting 5s, then retrying once... ({e})", flush=True)
        sleep(5)
        out = fn(*args, **kwargs)
        print(f"{strftime('%H:%M:%S')} {who} retry OK", flush=True)
        return out
    except Exception as e:
        print(f"{strftime('%H:%M:%S')} {who} unexpected error: {e}", flush=True)
        raise

In [ ]:
dir_path = Path(data_path)  # folder_path already exists
docs = sorted([p.name for p in dir_path.iterdir() if p.is_file()])

results = []
for doc in docs:
    doc_name = doc
    info    = call_once_with_wait(extract_information, doc_name, delay=10, label=f"info:{doc_name}")
    pillars = call_once_with_wait(extract_pillars, doc_name, delay=10, label=f"pillars:{doc_name}")
    results.append({**info, **pillars})

In [42]:
from tqdm.auto import tqdm

dir_path = Path(data_path)
docs = sorted([p.name for p in dir_path.iterdir() if p.is_file()])

results, errors = [], []
pbar = tqdm(docs, desc="Processing documents", unit="doc", total=len(docs))

for doc in pbar:
    pbar.set_postfix_str(doc)  # show current file name on the bar
    try:
        info    = call_once_with_wait(extract_information, doc, delay=10, label=f"info:{doc}")
        pillars = call_once_with_wait(extract_pillars,     doc, delay=10, label=f"pillars:{doc}")
        results.append({**info, **pillars})
    except Exception as e:
        errors.append((doc, repr(e)))
        pbar.write(f"[ERROR] {doc}: {e}")

# Optional: inspect errors afterwards
# print(errors)

c:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\AIPC_general_app\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Processing documents:   0%|          | 0/74 [00:00<?, ?doc/s, F33073064.pdf]

13:44:17 [info:F33073064.pdf] waiting 10s before call...
13:44:34 [info:F33073064.pdf] call OK
13:44:34 [pillars:F33073064.pdf] waiting 10s before call...
13:44:50 [pillars:F33073064.pdf] call OK

Processing documents:   1%|▏         | 1/74 [00:32<39:57, 32.84s/doc, F33083732.pdf]

13:44:50 [info:F33083732.pdf] waiting 10s before call...
13:45:06 [info:F33083732.pdf] call OK
13:45:06 [pillars:F33083732.pdf] waiting 10s before call...
13:45:20 [pillars:F33083732.pdf] call OK

Processing documents:   3%|▎         | 2/74 [01:02<37:11, 30.99s/doc, F33091336.docx]

13:45:20 [info:F33091336.docx] waiting 10s before call...
13:45:35 [info:F33091336.docx] call OK
13:45:35 [pillars:F33091336.docx] waiting 10s before call...
13:45:49 [pillars:F33091336.docx] call OK

Processing documents:   4%|▍         | 3/74 [01:31<35:36, 30.09s/doc, F33094597.pdf]

13:45:49 [info:F33094597.pdf] waiting 10s before call...
13:46:04 [info:F33094597.pdf] call OK
13:46:04 [pillars:F33094597.pdf] waiting 10s before call...
13:46:18 [pillars:F33094597.pdf] call OK

Processing documents:   5%|▌         | 4/74 [02:00<34:37, 29.68s/doc, F33096176.pdf]

13:46:18 [info:F33096176.pdf] waiting 10s before call...
13:46:33 [info:F33096176.pdf] call OK
13:46:33 [pillars:F33096176.pdf] waiting 10s before call...
13:46:48 [pillars:F33096176.pdf] call OK

Processing documents:   7%|▋         | 5/74 [02:30<34:23, 29.90s/doc, F33097445.pdf]

13:46:48 [info:F33097445.pdf] waiting 10s before call...
13:47:03 [info:F33097445.pdf] call OK
13:47:03 [pillars:F33097445.pdf] waiting 10s before call...
13:47:16 [pillars:F33097445.pdf] call OK

Processing documents:   8%|▊         | 6/74 [02:58<32:56, 29.07s/doc, F33104014.pdf]

13:47:16 [info:F33104014.pdf] waiting 10s before call...
13:47:31 [info:F33104014.pdf] call OK
13:47:31 [pillars:F33104014.pdf] waiting 10s before call...
13:47:45 [pillars:F33104014.pdf] call OK

Processing documents:   9%|▉         | 7/74 [03:27<32:26, 29.06s/doc, F33105185.pdf]

13:47:45 [info:F33105185.pdf] waiting 10s before call...
13:47:59 [info:F33105185.pdf] call OK
13:47:59 [pillars:F33105185.pdf] waiting 10s before call...
13:48:12 [pillars:F33105185.pdf] call OK

Processing documents:  11%|█         | 8/74 [03:54<31:21, 28.51s/doc, F33113117.pdf]

13:48:12 [info:F33113117.pdf] waiting 10s before call...
13:48:27 [info:F33113117.pdf] call OK
13:48:27 [pillars:F33113117.pdf] waiting 10s before call...
13:48:45 [pillars:F33113117.pdf] call OK

Processing documents:  12%|█▏        | 9/74 [04:27<32:19, 29.84s/doc, F33113340.pdf]

13:48:45 [info:F33113340.pdf] waiting 10s before call...
13:49:01 [info:F33113340.pdf] call OK
13:49:01 [pillars:F33113340.pdf] waiting 10s before call...
13:49:15 [pillars:F33113340.pdf] call OK

Processing documents:  14%|█▎        | 10/74 [04:57<31:52, 29.88s/doc, F33113596.pdf]

13:49:15 [info:F33113596.pdf] waiting 10s before call...
13:49:30 [info:F33113596.pdf] call OK
13:49:30 [pillars:F33113596.pdf] waiting 10s before call...
13:49:46 [pillars:F33113596.pdf] call OK

Processing documents:  15%|█▍        | 11/74 [05:28<31:49, 30.30s/doc, F33113733.pdf]

13:49:46 [info:F33113733.pdf] waiting 10s before call...
13:50:02 [info:F33113733.pdf] call OK
13:50:02 [pillars:F33113733.pdf] waiting 10s before call...
13:50:15 [pillars:F33113733.pdf] call OK

Processing documents:  16%|█▌        | 12/74 [05:58<31:01, 30.03s/doc, F33113897.pdf]

13:50:15 [info:F33113897.pdf] waiting 10s before call...
13:50:33 [info:F33113897.pdf] call OK
13:50:33 [pillars:F33113897.pdf] waiting 10s before call...
13:50:48 [pillars:F33113897.pdf] call OK

Processing documents:  18%|█▊        | 13/74 [06:30<31:14, 30.73s/doc, F33113962.docx]

13:50:48 [info:F33113962.docx] waiting 10s before call...
13:51:03 [info:F33113962.docx] call OK
13:51:03 [pillars:F33113962.docx] waiting 10s before call...
13:51:18 [pillars:F33113962.docx] call OK

Processing documents:  19%|█▉        | 14/74 [07:01<30:40, 30.68s/doc, F33114274.pdf]

13:51:18 [info:F33114274.pdf] waiting 10s before call...
13:51:33 [info:F33114274.pdf] call OK
13:51:33 [pillars:F33114274.pdf] waiting 10s before call...
13:51:51 [pillars:F33114274.pdf] call OK

Processing documents:  20%|██        | 15/74 [07:34<30:56, 31.46s/doc, F33114282.pdf]

13:51:52 [info:F33114282.pdf] waiting 10s before call...
13:52:07 [info:F33114282.pdf] call OK
13:52:07 [pillars:F33114282.pdf] waiting 10s before call...
13:52:21 [pillars:F33114282.pdf] call OK

Processing documents:  22%|██▏       | 16/74 [08:03<29:43, 30.75s/doc, F33114287.pdf]

13:52:21 [info:F33114287.pdf] waiting 10s before call...
13:52:35 [info:F33114287.pdf] call OK
13:52:35 [pillars:F33114287.pdf] waiting 10s before call...
13:52:49 [pillars:F33114287.pdf] call OK

Processing documents:  23%|██▎       | 17/74 [08:31<28:25, 29.92s/doc, F33114296.pdf]

13:52:49 [info:F33114296.pdf] waiting 10s before call...
13:53:04 [info:F33114296.pdf] call OK
13:53:04 [pillars:F33114296.pdf] waiting 10s before call...
13:53:16 [pillars:F33114296.pdf] call OK

Processing documents:  24%|██▍       | 18/74 [08:58<27:15, 29.21s/doc, F33114368.pdf]

13:53:16 [info:F33114368.pdf] waiting 10s before call...
13:53:31 [info:F33114368.pdf] call OK
13:53:31 [pillars:F33114368.pdf] waiting 10s before call...
13:53:44 [pillars:F33114368.pdf] call OK

Processing documents:  26%|██▌       | 19/74 [09:27<26:29, 28.90s/doc, F33114380.pdf]

13:53:44 [info:F33114380.pdf] waiting 10s before call...
13:54:00 [info:F33114380.pdf] call OK
13:54:00 [pillars:F33114380.pdf] waiting 10s before call...
13:54:15 [pillars:F33114380.pdf] call OK

Processing documents:  27%|██▋       | 20/74 [09:58<26:37, 29.57s/doc, F33114394.docx]

13:54:15 [info:F33114394.docx] waiting 10s before call...
13:54:31 [info:F33114394.docx] call OK
13:54:31 [pillars:F33114394.docx] waiting 10s before call...
13:54:45 [pillars:F33114394.docx] call OK

Processing documents:  28%|██▊       | 21/74 [10:27<26:09, 29.61s/doc, F33114405.pdf]

13:54:45 [info:F33114405.pdf] waiting 10s before call...
13:55:01 [info:F33114405.pdf] call OK
13:55:01 [pillars:F33114405.pdf] waiting 10s before call...
13:55:17 [pillars:F33114405.pdf] call OK

Processing documents:  30%|██▉       | 22/74 [11:00<26:22, 30.43s/doc, F33114466.docx]

13:55:17 [info:F33114466.docx] waiting 10s before call...
13:55:34 [info:F33114466.docx] call OK
13:55:34 [pillars:F33114466.docx] waiting 10s before call...
13:55:47 [pillars:F33114466.docx] call OK

Processing documents:  31%|███       | 23/74 [11:29<25:39, 30.18s/doc, F33114469.pdf]

13:55:47 [info:F33114469.pdf] waiting 10s before call...
13:56:04 [info:F33114469.pdf] call OK
13:56:04 [pillars:F33114469.pdf] waiting 10s before call...
13:56:18 [pillars:F33114469.pdf] call OK

Processing documents:  32%|███▏      | 24/74 [12:01<25:23, 30.47s/doc, F33114476.pdf]

13:56:18 [info:F33114476.pdf] waiting 10s before call...
13:56:35 [info:F33114476.pdf] call OK
13:56:35 [pillars:F33114476.pdf] waiting 10s before call...
13:56:47 [pillars:F33114476.pdf] call OK

Processing documents:  34%|███▍      | 25/74 [12:29<24:30, 30.00s/doc, F33114478.docx]

13:56:47 [info:F33114478.docx] waiting 10s before call...
13:57:04 [info:F33114478.docx] call OK
13:57:04 [pillars:F33114478.docx] waiting 10s before call...
13:57:19 [pillars:F33114478.docx] call OK

Processing documents:  35%|███▌      | 26/74 [13:02<24:30, 30.63s/doc, F33114485.pdf]

13:57:19 [info:F33114485.pdf] waiting 10s before call...
13:57:35 [info:F33114485.pdf] call OK
13:57:35 [pillars:F33114485.pdf] waiting 10s before call...
13:57:49 [pillars:F33114485.pdf] call OK

Processing documents:  36%|███▋      | 27/74 [13:32<23:50, 30.44s/doc, F33114492.pdf]

13:57:49 [info:F33114492.pdf] waiting 10s before call...
13:58:05 [info:F33114492.pdf] call OK
13:58:05 [pillars:F33114492.pdf] waiting 10s before call...
13:58:18 [pillars:F33114492.pdf] call OK

Processing documents:  38%|███▊      | 28/74 [14:01<23:01, 30.03s/doc, F33114494.pdf]

13:58:18 [info:F33114494.pdf] waiting 10s before call...
13:58:36 [info:F33114494.pdf] call OK
13:58:36 [pillars:F33114494.pdf] waiting 10s before call...
13:58:52 [pillars:F33114494.pdf] call OK

Processing documents:  39%|███▉      | 29/74 [14:34<23:14, 30.99s/doc, F33114498.pdf]

13:58:52 [info:F33114498.pdf] waiting 10s before call...
13:59:08 [info:F33114498.pdf] call OK
13:59:08 [pillars:F33114498.pdf] waiting 10s before call...
13:59:20 [pillars:F33114498.pdf] call OK

Processing documents:  41%|████      | 30/74 [15:03<22:15, 30.35s/doc, F33114505.pdf]

13:59:20 [info:F33114505.pdf] waiting 10s before call...
13:59:36 [info:F33114505.pdf] call OK
13:59:36 [pillars:F33114505.pdf] waiting 10s before call...
13:59:51 [pillars:F33114505.pdf] call OK

Processing documents:  42%|████▏     | 31/74 [15:33<21:45, 30.35s/doc, F33114507.pdf]

13:59:51 [info:F33114507.pdf] waiting 10s before call...
14:00:04 [info:F33114507.pdf] call OK
14:00:04 [pillars:F33114507.pdf] waiting 10s before call...
14:00:17 [pillars:F33114507.pdf] call OK

Processing documents:  43%|████▎     | 32/74 [15:59<20:20, 29.07s/doc, F33114508.pdf]

14:00:17 [info:F33114508.pdf] waiting 10s before call...
14:00:34 [info:F33114508.pdf] call OK
14:00:34 [pillars:F33114508.pdf] waiting 10s before call...
14:00:48 [pillars:F33114508.pdf] call OK

Processing documents:  45%|████▍     | 33/74 [16:31<20:21, 29.79s/doc, F33114513.pdf]

14:00:48 [info:F33114513.pdf] waiting 10s before call...
14:01:04 [info:F33114513.pdf] call OK
14:01:04 [pillars:F33114513.pdf] waiting 10s before call...
14:01:19 [pillars:F33114513.pdf] call OK

Processing documents:  46%|████▌     | 34/74 [17:02<20:04, 30.12s/doc, F33114514.pdf]

14:01:19 [info:F33114514.pdf] waiting 10s before call...
14:01:35 [info:F33114514.pdf] call OK
14:01:35 [pillars:F33114514.pdf] waiting 10s before call...
14:01:49 [pillars:F33114514.pdf] call OK

Processing documents:  47%|████▋     | 35/74 [17:31<19:25, 29.89s/doc, F33114518.pdf]

14:01:49 [info:F33114518.pdf] waiting 10s before call...
14:02:04 [info:F33114518.pdf] call OK
14:02:04 [pillars:F33114518.pdf] waiting 10s before call...
14:02:18 [pillars:F33114518.pdf] call OK

Processing documents:  49%|████▊     | 36/74 [18:00<18:47, 29.66s/doc, F33114522.pdf]

14:02:18 [info:F33114522.pdf] waiting 10s before call...
14:02:33 [info:F33114522.pdf] call OK
14:02:33 [pillars:F33114522.pdf] waiting 10s before call...
14:02:46 [pillars:F33114522.pdf] call OK

Processing documents:  50%|█████     | 37/74 [18:28<17:59, 29.16s/doc, F33114528.pdf]

14:02:46 [info:F33114528.pdf] waiting 10s before call...
14:03:01 [info:F33114528.pdf] call OK
14:03:01 [pillars:F33114528.pdf] waiting 10s before call...
14:03:16 [pillars:F33114528.pdf] call OK

Processing documents:  51%|█████▏    | 38/74 [18:59<17:47, 29.64s/doc, F33114535.pdf]

14:03:16 [info:F33114535.pdf] waiting 10s before call...
14:03:32 [info:F33114535.pdf] call OK
14:03:32 [pillars:F33114535.pdf] waiting 10s before call...
14:03:44 [pillars:F33114535.pdf] call OK

Processing documents:  53%|█████▎    | 39/74 [19:26<16:54, 28.98s/doc, F33114543.pdf]

14:03:44 [info:F33114543.pdf] waiting 10s before call...
14:04:00 [info:F33114543.pdf] call OK
14:04:00 [pillars:F33114543.pdf] waiting 10s before call...
14:04:16 [pillars:F33114543.pdf] call OK

Processing documents:  54%|█████▍    | 40/74 [19:59<17:01, 30.04s/doc, F33114550.pdf]

14:04:16 [info:F33114550.pdf] waiting 10s before call...
14:04:34 [info:F33114550.pdf] call OK
14:04:34 [pillars:F33114550.pdf] waiting 10s before call...
14:04:48 [pillars:F33114550.pdf] call OK

Processing documents:  55%|█████▌    | 41/74 [20:31<16:49, 30.60s/doc, F33114580.pdf]

14:04:48 [info:F33114580.pdf] waiting 10s before call...
14:05:04 [info:F33114580.pdf] call OK
14:05:04 [pillars:F33114580.pdf] waiting 10s before call...
14:05:18 [pillars:F33114580.pdf] call OK

Processing documents:  57%|█████▋    | 42/74 [21:00<16:09, 30.31s/doc, F33114601.pdf]

14:05:18 [info:F33114601.pdf] waiting 10s before call...
14:05:33 [info:F33114601.pdf] call OK
14:05:33 [pillars:F33114601.pdf] waiting 10s before call...
14:05:48 [pillars:F33114601.pdf] call OK

Processing documents:  58%|█████▊    | 43/74 [21:30<15:33, 30.12s/doc, F33114700.pdf]

14:05:48 [info:F33114700.pdf] waiting 10s before call...
14:06:04 [info:F33114700.pdf] call OK
14:06:04 [pillars:F33114700.pdf] waiting 10s before call...
14:06:19 [pillars:F33114700.pdf] call OK

Processing documents:  59%|█████▉    | 44/74 [22:02<15:17, 30.58s/doc, F33114703.pdf]

14:06:19 [info:F33114703.pdf] waiting 10s before call...
14:06:34 [info:F33114703.pdf] call OK
14:06:34 [pillars:F33114703.pdf] waiting 10s before call...
14:06:49 [pillars:F33114703.pdf] call OK

Processing documents:  61%|██████    | 45/74 [22:31<14:40, 30.36s/doc, F33114714.pdf]

14:06:49 [info:F33114714.pdf] waiting 10s before call...
14:07:06 [info:F33114714.pdf] call OK
14:07:06 [pillars:F33114714.pdf] waiting 10s before call...
14:07:21 [pillars:F33114714.pdf] call OK

Processing documents:  62%|██████▏   | 46/74 [23:03<14:22, 30.80s/doc, F33114715.pdf]

14:07:21 [info:F33114715.pdf] waiting 10s before call...
14:07:36 [info:F33114715.pdf] call OK
14:07:36 [pillars:F33114715.pdf] waiting 10s before call...
14:07:49 [pillars:F33114715.pdf] call OK

Processing documents:  64%|██████▎   | 47/74 [23:31<13:26, 29.89s/doc, F33114716.pdf]

14:07:49 [info:F33114716.pdf] waiting 10s before call...
14:08:05 [info:F33114716.pdf] call OK
14:08:05 [pillars:F33114716.pdf] waiting 10s before call...
14:08:21 [pillars:F33114716.pdf] call OK

Processing documents:  65%|██████▍   | 48/74 [24:03<13:17, 30.66s/doc, F33114718.pdf]

14:08:21 [info:F33114718.pdf] waiting 10s before call...
14:08:37 [info:F33114718.pdf] call OK
14:08:37 [pillars:F33114718.pdf] waiting 10s before call...
14:08:50 [pillars:F33114718.pdf] call OK

Processing documents:  66%|██████▌   | 49/74 [24:32<12:31, 30.05s/doc, F33114871.pdf]

14:08:50 [info:F33114871.pdf] waiting 10s before call...
14:09:08 [info:F33114871.pdf] call OK
14:09:08 [pillars:F33114871.pdf] waiting 10s before call...
14:09:21 [pillars:F33114871.pdf] call OK

Processing documents:  68%|██████▊   | 50/74 [25:03<12:10, 30.44s/doc, F33114902.pdf]

14:09:21 [info:F33114902.pdf] waiting 10s before call...
14:09:39 [info:F33114902.pdf] call OK
14:09:39 [pillars:F33114902.pdf] waiting 10s before call...
14:09:55 [pillars:F33114902.pdf] call OK

Processing documents:  69%|██████▉   | 51/74 [25:37<12:00, 31.34s/doc, F33114919.docx]

14:09:55 [info:F33114919.docx] waiting 10s before call...
14:10:10 [info:F33114919.docx] call OK
14:10:10 [pillars:F33114919.docx] waiting 10s before call...
14:10:23 [pillars:F33114919.docx] call OK

Processing documents:  70%|███████   | 52/74 [26:05<11:07, 30.33s/doc, F33114933.pdf]

14:10:23 [info:F33114933.pdf] waiting 10s before call...
14:10:38 [info:F33114933.pdf] call OK
14:10:38 [pillars:F33114933.pdf] waiting 10s before call...
14:10:51 [pillars:F33114933.pdf] call OK

Processing documents:  72%|███████▏  | 53/74 [26:33<10:23, 29.68s/doc, F33114947.pdf]

14:10:51 [info:F33114947.pdf] waiting 10s before call...
14:11:06 [info:F33114947.pdf] call OK
14:11:06 [pillars:F33114947.pdf] waiting 10s before call...
14:11:19 [pillars:F33114947.pdf] call OK

Processing documents:  73%|███████▎  | 54/74 [27:02<09:46, 29.34s/doc, F33114949.pdf]

14:11:19 [info:F33114949.pdf] waiting 10s before call...
14:11:35 [info:F33114949.pdf] call OK
14:11:35 [pillars:F33114949.pdf] waiting 10s before call...
14:11:51 [pillars:F33114949.pdf] call OK

Processing documents:  74%|███████▍  | 55/74 [27:33<09:31, 30.10s/doc, F33114950.pdf]

14:11:51 [info:F33114950.pdf] waiting 10s before call...
14:12:09 [info:F33114950.pdf] call OK
14:12:09 [pillars:F33114950.pdf] waiting 10s before call...
14:12:28 [pillars:F33114950.pdf] call OK

Processing documents:  76%|███████▌  | 56/74 [28:11<09:40, 32.26s/doc, F33114951.pdf]

14:12:28 [info:F33114951.pdf] waiting 10s before call...
14:12:43 [info:F33114951.pdf] call OK
14:12:43 [pillars:F33114951.pdf] waiting 10s before call...
14:12:58 [pillars:F33114951.pdf] call OK

Processing documents:  77%|███████▋  | 57/74 [28:41<08:57, 31.60s/doc, F33114960.pdf]

14:12:58 [info:F33114960.pdf] waiting 10s before call...
14:13:13 [info:F33114960.pdf] call OK
14:13:13 [pillars:F33114960.pdf] waiting 10s before call...
14:13:26 [pillars:F33114960.pdf] call OK

Processing documents:  78%|███████▊  | 58/74 [29:08<08:04, 30.26s/doc, F33114961.pdf]

14:13:26 [info:F33114961.pdf] waiting 10s before call...
14:13:41 [info:F33114961.pdf] call OK
14:13:41 [pillars:F33114961.pdf] waiting 10s before call...
14:13:58 [pillars:F33114961.pdf] call OK

Processing documents:  80%|███████▉  | 59/74 [29:40<07:41, 30.77s/doc, F33115064.pdf]

14:13:58 [info:F33115064.pdf] waiting 10s before call...
14:14:13 [info:F33115064.pdf] call OK
14:14:13 [pillars:F33115064.pdf] waiting 10s before call...
14:14:29 [pillars:F33115064.pdf] call OK

Processing documents:  81%|████████  | 60/74 [30:11<07:14, 31.01s/doc, F33115326.pdf]

14:14:29 [info:F33115326.pdf] waiting 10s before call...
14:14:44 [info:F33115326.pdf] call OK
14:14:44 [pillars:F33115326.pdf] waiting 10s before call...
14:14:59 [pillars:F33115326.pdf] call OK

Processing documents:  82%|████████▏ | 61/74 [30:41<06:38, 30.67s/doc, F33115617.pdf]

14:14:59 [info:F33115617.pdf] waiting 10s before call...
14:15:15 [info:F33115617.pdf] call OK
14:15:15 [pillars:F33115617.pdf] waiting 10s before call...
14:15:29 [pillars:F33115617.pdf] call OK

Processing documents:  84%|████████▍ | 62/74 [31:12<06:07, 30.62s/doc, F33115928 (2).pdf]

14:15:30 [info:F33115928 (2).pdf] waiting 10s before call...
14:15:44 [info:F33115928 (2).pdf] call OK
14:15:44 [pillars:F33115928 (2).pdf] waiting 10s before call...
14:15:59 [pillars:F33115928 (2).pdf] call OK

Processing documents:  85%|████████▌ | 63/74 [31:42<05:34, 30.37s/doc, F33115932.pdf]

14:15:59 [info:F33115932.pdf] waiting 10s before call...
14:16:14 [info:F33115932.pdf] call OK
14:16:14 [pillars:F33115932.pdf] waiting 10s before call...
14:16:28 [pillars:F33115932.pdf] call OK

Processing documents:  86%|████████▋ | 64/74 [32:10<04:58, 29.90s/doc, F33116245.pdf]

14:16:28 [info:F33116245.pdf] waiting 10s before call...
14:16:44 [info:F33116245.pdf] call OK
14:16:44 [pillars:F33116245.pdf] waiting 10s before call...
14:16:57 [pillars:F33116245.pdf] call OK

Processing documents:  88%|████████▊ | 65/74 [32:40<04:27, 29.68s/doc, F33116494.pdf]

14:16:57 [info:F33116494.pdf] waiting 10s before call...
14:17:13 [info:F33116494.pdf] call OK
14:17:13 [pillars:F33116494.pdf] waiting 10s before call...
14:17:27 [pillars:F33116494.pdf] call OK

Processing documents:  89%|████████▉ | 66/74 [33:09<03:58, 29.75s/doc, F33116813.pdf]

14:17:27 [info:F33116813.pdf] waiting 10s before call...
14:17:44 [info:F33116813.pdf] call OK
14:17:44 [pillars:F33116813.pdf] waiting 10s before call...
14:17:59 [pillars:F33116813.pdf] call OK

Processing documents:  91%|█████████ | 67/74 [33:41<03:32, 30.29s/doc, F33116818.pdf]

14:17:59 [info:F33116818.pdf] waiting 10s before call...
14:18:14 [info:F33116818.pdf] call OK
14:18:14 [pillars:F33116818.pdf] waiting 10s before call...
14:18:29 [pillars:F33116818.pdf] call OK

Processing documents:  92%|█████████▏| 68/74 [34:11<03:00, 30.14s/doc, F33116821.pdf]

14:18:29 [info:F33116821.pdf] waiting 10s before call...
14:18:44 [info:F33116821.pdf] call OK
14:18:44 [pillars:F33116821.pdf] waiting 10s before call...
14:18:57 [pillars:F33116821.pdf] call OK

Processing documents:  93%|█████████▎| 69/74 [34:39<02:27, 29.55s/doc, F33117138.pdf]

14:18:57 [info:F33117138.pdf] waiting 10s before call...
14:19:12 [info:F33117138.pdf] call OK
14:19:12 [pillars:F33117138.pdf] waiting 10s before call...
14:19:26 [pillars:F33117138.pdf] call OK

Processing documents:  95%|█████████▍| 70/74 [35:09<01:58, 29.56s/doc, F33117395.pdf]

14:19:26 [info:F33117395.pdf] waiting 10s before call...
14:19:43 [info:F33117395.pdf] call OK
14:19:43 [pillars:F33117395.pdf] waiting 10s before call...
14:19:57 [pillars:F33117395.pdf] call OK

Processing documents:  96%|█████████▌| 71/74 [35:39<01:29, 29.82s/doc, F33117397.pdf]

14:19:57 [info:F33117397.pdf] waiting 10s before call...
14:20:11 [info:F33117397.pdf] call OK
14:20:11 [pillars:F33117397.pdf] waiting 10s before call...
14:20:23 [pillars:F33117397.pdf] call OK

Processing documents:  97%|█████████▋| 72/74 [36:06<00:57, 28.90s/doc, F33117687.pdf]

14:20:23 [info:F33117687.pdf] waiting 10s before call...
14:20:39 [info:F33117687.pdf] call OK
14:20:39 [pillars:F33117687.pdf] waiting 10s before call...
14:20:52 [pillars:F33117687.pdf] call OK

Processing documents:  99%|█████████▊| 73/74 [36:34<00:28, 28.82s/doc, F3593805.pdf]

14:20:52 [info:F3593805.pdf] waiting 10s before call...
14:21:08 [info:F3593805.pdf] call OK
14:21:08 [pillars:F3593805.pdf] waiting 10s before call...
14:21:21 [pillars:F3593805.pdf] call OK

Processing documents: 100%|██████████| 74/74 [37:03<00:00, 30.05s/doc, F3593805.pdf]

In [43]:
# --- make a DataFrame with your exact columns ---
def _tolist(x):
    if isinstance(x, list):
        return x
    return [x] if x else []

def _tostr_or_none(x):
    if x is None:
        return None
    return x if isinstance(x, str) else str(x)

rows = []
for r in results:
    rows.append({
        "title": r.get("title"),
        "organisation": _tolist(r.get("organisation")),     # keep as list
        "page_number": r.get("page_number"),
        "summary": r.get("summary"),
        "main themes": _tolist(r.get("main themes")),       # keep as list
        "VC": _tostr_or_none(r.get("VC")),                  # strings or None
        "clusters": _tostr_or_none(r.get("clusters")),
        "skills": _tostr_or_none(r.get("skills")),
        "AI/data": _tostr_or_none(r.get("AI/data")),
        "dual_use/security":_tostr_or_none(r.get("dual_use/security"))
    })

df = pd.DataFrame(
    rows,
    columns=["title", "organisation", "page_number", "summary", "main themes",
             "VC", "clusters", "skills", "AI/data","dual_use/security"]
)

In [44]:
df

,title,organisation,page_number,summary,main themes,VC,clusters,skills,AI/data,dual_use/security
0,Government’s vision on Biotechnology 2025 - 2040,"[Ministry of Economic Affairs, Ministry of Inf...",None,This document outlines the Dutch government's ...,"[Long-term biotechnology strategy, Economic an...",The document highlights the persistent funding...,The document emphasises the importance of impr...,The document notes the need for sufficient tal...,The document discusses the increasing risks po...,The document addresses dual-use concerns by no...
1,Biotechnology for a more sustainable wood econ...,"[European Commission, Joint Research Centre, U...",None,This document discusses the role of biotechnol...,"[Sustainable wood economy, Wood preservation t...",The document highlights that long regulatory t...,None,None,None,None
2,RENEWABLE RECYCLED RESPONSIBLE EUROPEAN,[CEPI],None,The document is a contribution from CEPI urgin...,"[Broader scope for the European Biotech Act, F...",The document highlights that without targeted ...,The document advocates for the full integratio...,None,None,None
3,BIC contribution to the call for evidence on E...,[BIC],None,The document advocates for expanding the scope...,"[Expanding the EU Biotech Act scope, Biomanufa...",The document highlights the need for tailored ...,None,The document stresses the importance of invest...,None,None
4,TORINO STATEMENT,[],None,The document highlights the importance of the ...,"[circular bioeconomy, regulatory challenges, b...",The document highlights a persistent lack of f...,The document emphasises the importance of crea...,The document stresses the need for enough comp...,"The document identifies data as key, advocatin...",None
...,...,...,...,...,...,...,...,...,...,...
69,From Lab to Market: How the Biotech Act Can Ac...,[Fraunhofer Group for Resource Technologies an...,None,This document discusses the importance of the ...,"[Bridging research and industry, De-risking co...",The document highlights that financing for hig...,It proposes the establishment of Europe-wide j...,The document stresses the importance of empowe...,None,None
70,CO2 Value Europe’s response to the Commission’...,[CO2 Value Europe AISBL],None,This document is CO2 Value Europe’s response t...,"[Inclusion of CCU in the Biotech Act, Regulato...",The document highlights the need for clear fun...,None,None,None,None
71,SIOPE Response to EU Biotech Act Consultation ...,[SIOPE],None,The document compiles sources relevant to the ...,"[Paediatric oncology, CAR T-cell therapy, Biot...",None,None,None,None,None
72,TRACELESS MATERIALS | Position Paper. Biotech ...,[traceless],None,This position paper addresses regulatory chall...,"[Regulatory barriers for natural polymers, Pac...",The document highlights that the natural polym...,None,None,None,None
73,European food security through natural ferment...,[Farmless],None,The document outlines Farmless's innovative ap...,"[Natural fermentation for protein production, ...",Farmless has successfully raised €9 million fr...,None,None,None,None

### Using PdfReader for page count

In [46]:
paths = sorted([p for p in Path(data_path).iterdir() if p.is_file()])[:len(df)]

# Optional: DOCX/DOC via Microsoft Word (Windows only)
try:
    WORD_AVAILABLE = True
    word = win32.gencache.EnsureDispatch("Word.Application")
    word.Visible = False
except Exception:
    WORD_AVAILABLE = False
    word = None

def count_pages(p: Path):
    suf = p.suffix.lower()
    if suf == ".pdf":
        try:
            with open(p, "rb") as f:
                r = PdfReader(f)
                if getattr(r, "is_encrypted", False):
                    try: r.decrypt("")
                    except Exception: return np.nan
                return len(r.pages)
        except Exception:
            return np.nan
    if suf in (".docx", ".doc") and WORD_AVAILABLE:
        try:
            doc = word.Documents.Open(str(p))
            pages = int(doc.ComputeStatistics(2))  # 2 = wdStatisticPages
            doc.Close(False)
            return pages
        except Exception:
            return np.nan
    return np.nan

page_counts = pd.Series([count_pages(p) for p in paths], index=df.index).astype("Int64")

if word: 
    try: word.Quit()
    except Exception: pass

if "page_number" in df.columns:
    df = df.drop(columns=["page_number"])
df.insert(2, "page_number", page_counts)


df.insert(0, "file_name", pd.Series(docs[:len(df)], index=df.index))

Ignoring wrong pointing object 16 0 (offset 0)
Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 9 0 (offset 0)
Ignoring wrong pointing object 11 0 (offset 0)
Ignoring wrong pointing object 13 0 (offset 0)
Ignoring wrong pointing object 29 0 (offset 0)
Ignoring wrong pointing object 35 0 (offset 0)
Ignoring wrong pointing object 37 0 (offset 0)
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 44 0 (offset 0)
Ignoring wrong pointing object 46 0 (offset 0)
Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 25 0 (offset 0)
Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 16 0 (offset 0)
Ignoring wrong pointing object 19 0 (offset 0)
Ignoring wrong pointing object 21 0 (offset 0)
Ignoring wrong pointing object 36 0 (offset 0)
Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 13 0 (offset 0)
Ignoring wrong pointing object 16 0 (offset 0)

In [48]:
len(df)

74

In [49]:
# Rename column
df = df.rename(columns={"file_name": "feedback_reference"})

# Split at the period and take the first chunk
df["feedback_reference"] = df["feedback_reference"].str.split(".", n=1).str[0]
df.head()

,feedback_reference,title,organisation,page_number,summary,main themes,VC,clusters,skills,AI/data,dual_use/security
0,F33073064,Government’s vision on Biotechnology 2025 - 2040,"[Ministry of Economic Affairs, Ministry of Inf...",51,This document outlines the Dutch government's ...,"[Long-term biotechnology strategy, Economic an...",The document highlights the persistent funding...,The document emphasises the importance of impr...,The document notes the need for sufficient tal...,The document discusses the increasing risks po...,The document addresses dual-use concerns by no...
1,F33083732,Biotechnology for a more sustainable wood econ...,"[European Commission, Joint Research Centre, U...",3,This document discusses the role of biotechnol...,"[Sustainable wood economy, Wood preservation t...",The document highlights that long regulatory t...,None,None,None,None
2,F33091336,RENEWABLE RECYCLED RESPONSIBLE EUROPEAN,[CEPI],2,The document is a contribution from CEPI urgin...,"[Broader scope for the European Biotech Act, F...",The document highlights that without targeted ...,The document advocates for the full integratio...,None,None,None
3,F33094597,BIC contribution to the call for evidence on E...,[BIC],2,The document advocates for expanding the scope...,"[Expanding the EU Biotech Act scope, Biomanufa...",The document highlights the need for tailored ...,None,The document stresses the importance of invest...,None,None
4,F33096176,TORINO STATEMENT,[],2,The document highlights the importance of the ...,"[circular bioeconomy, regulatory challenges, b...",The document highlights a persistent lack of f...,The document emphasises the importance of crea...,The document stresses the need for enough comp...,"The document identifies data as key, advocatin...",None

In [50]:
output_folder = Path(folder_path).parent / "results"
xlsx_path = Path(output_folder) / "RAG_task3_results.xlsx"

df.to_excel(xlsx_path, index=False)
print(f"Saved: {xlsx_path}")

Saved: C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\RAG_task3_results.xlsx

In [47]:
df[-30:]

,file_name,title,organisation,page_number,summary,main themes,VC,clusters,skills,AI/data,dual_use/security
44,F33114703.pdf,Strategic Vision Bioeconomy,[International Advisory Council on Global Bioe...,6,"This document, authored by the IACGB European ...","[EU bioeconomy strategy, Biotechnology innovat...",The document highlights persistent risk-capita...,It advocates for the creation and support of b...,The document stresses the importance of compre...,None,The document proposes establishing an EU Life ...
45,F33114714.pdf,Cefic position paper on biotechnology and biom...,[Cefic Bio-based Cluster],7,This document outlines Cefic's recommendations...,[Biotechnology and biomanufacturing definition...,The document highlights the persistent risk of...,It calls for the enhancement of the recently c...,The document proposes developing EU-wide biote...,It advocates for a 'data initiative' to provid...,The document notes the relevance of biomanufac...
46,F33114715.pdf,Additional information,"[Dyrenes Beskyttelse, Animal Protection Denmark]",2,The document discusses the potential of biosol...,"[Biosolutions and sustainability, Cellular agr...",None,None,None,None,None
47,F33114716.pdf,Catalonia.Health Position on the EU Biotech Ac...,[Catalonia.Health],8,This document presents Catalonia.Health's posi...,"[EU Biotech Act advocacy, Decline in European ...",The document highlights that European biotech ...,Catalonia.Health is presented as a successful ...,The document calls for EU-wide training progra...,The document recommends establishing EU clinic...,None
48,F33114718.pdf,Position on Biosecurity Regulation for DNA Dat...,"[DNA Data Storage Alliance (DDSA), SNIA]",5,This document presents the DNA Data Storage Al...,"[Biosecurity regulation for DNA data storage, ...",None,None,None,None,The document discusses biosecurity concerns sp...
49,F33114871.pdf,Gerichtstraße 49 13347 Berlin Germany,"[COGEM, ZKBS]",50,This document is a joint open letter from the ...,[Environmental risk assessment of samRNA and V...,None,None,None,None,The document discusses the challenges posed by...
50,F33114902.pdf,Unlocking Europe’s Bioeconomy: Why Policy supp...,"[Kemira, IFF]",3,The document discusses the importance of suppo...,"[EU bioeconomy policy, Biobased polymers and p...",None,None,None,None,None
51,F33114919.docx,HOUSE OF THE | DUTCH,"[Ministerium für Umwelt, Klima und Energiewirt...",3,The document presents a position paper from th...,"[Biotechnology initiative, Sustainable circula...",None,The document highlights the importance of a tr...,None,None,None
52,F33114933.pdf,Finnish Food and Drink Industries’ input for p...,[Finnish Food and Drink Industries’ Federation],2,The document provides input from the Finnish F...,"[Biotechnology in food industry, Regulatory en...",The document highlights the need for RDI fundi...,None,None,None,None
53,F33114947.pdf,Réponse à la consultation publique sur le règl...,[],2,The document raises critical questions about t...,"[Societal challenges and solutions, Biotechnol...",None,None,None,None,The document highlights the necessity of stren...
54,F33114949.pdf,EFPIA recommendations for Framework Programme 10,[EFPIA],17,The document discusses the current challenges ...,"[Intellectual property reform, Pharmaceutical ...",The document highlights Europe's persistent ga...,The document underscores the significant role ...,The document calls for investment in skills an...,The document proposes operationalising the Eur...,The document references the need for increased...
55,F33114950.pdf,German Social Insurance,"[German Federal Pension Insurance (DRV Bund), ...",5,The document provides feedback from German Soc...,"[Biotech Act and EU regulatory alignment, Bala...",The document highlights the significant financ...,The document advocates for building production...,None,The document stresses that responsible access ...,None
56,F33114951.pdf,Call for Evidence response from Aarhus Univers...,[Aarhus University],2,Aarhus University responds to the European Com...,"[Comprehensive biotechnology regulation, Cross...",The document highlights the need for incentivi...,The document refers to universities as central...,The document emphasises the role of universiti...,The document calls for investment in robust da...,The document addresses biosafety and responsib...
57,F33114960.pdf,ISA’s contribution to the public consultation ...,[International Sweeteners Association (ISA)],1,The International Sweeteners Association (ISA)...,[Inclusion of food in the European Biotech Act...,The document advocates for simplifying access ...,None,None,None,None
58,F33114961.pdf,POSITION PAPER,[Pharma Deutschland e. V.],6,This position paper by Pharma Deutschland outl...,"[Regulatory streamlining and harmonisation, Su...",The document highlights the importance of adeq...,None,The document stresses the necessity of continu...,The document proposes leveraging digital and A...,The document calls for resilience measures to ...
59,F33115064.pdf,Position Paper on EU Biotech Act,[Federchimica Assobiotec],9,This position paper discusses the strategic ro...,"[Biotechnology as enabling technology, Sustain...",The document highlights the need for high-risk...,The document advocates for the creation of tra...,A shortage of specialised skills is identified...,The document recognises the integration of art...,None
60,F33115326.pdf,EUCOPE Recommendations for a World-Leading Eur...,[EUCOPE],9,The document outlines EUCOPE's recommendations...,"[Regulatory simplification for biotech, Suppor...",The document recommends establishing funding a...,It proposes scaling up and inter-connecting ex...,The document calls for financial and administr...,It mentions the digitalisation of ATMP manufac...,None
61,F33115617.pdf,Attachment to Biotech Act Public Consultation,"[Novonesis, Novozymes A/S]",13,This document is a submission to the EU Biotec...,"[Regulatory reform for biosolutions, Accelerat...",The document highlights the need to funnel bot...,None,The document emphasises the necessity of a ski...,The document recommends that the Biotech Act c...,None
62,F33115928 (2).pdf,Annex to consultation document Invest-NL,[Invest-NL],1,This document serves as an annex to a consulta...,"[Fermentation technology, Alternative protein ...",The document highlights persistent risk-capita...,The document refers to the importance of co-lo...,The document discusses the need for deep proce...,"The document addresses the use of AI, includin...",None
63,F33115932.pdf,Tetra Pak’s response to the Public Consultatio...,[Tetra Pak Group],3,This document presents Tetra Pak’s response to...,"[Biotechnology in food production, Regulatory ...",The document highlights that industries seekin...,Tetra Pak partners with Lund University to lau...,The document mentions that enabling the growth...,None,None
64,F33116245.pdf,Bekanntgaben der Herausgeber,"[ZEKO, Bundesministerium für Bildung und Forsc...",44,"The document discusses the legal, ethical, and...","[GDPR and health data processing, AI in medica...",None,None,None,The document discusses the use of artificial i...,None
65,F33116494.pdf,Vaccines Europe (VE) Annex to the Public Quest...,[Vaccines Europe (VE)],6,This document is an annex by Vaccines Europe t...,"[Vaccine innovation and manufacturing, Targete...",The document calls for the EU and its Member S...,The document emphasises the need to strengthen...,It proposes facilitating targeted training and...,The document recommends advancing Europe's dig...,None
66,F33116813.pdf,Association of European Cancer Leagues (ECL),[Association of European Cancer Leagues (ECL)],30,This document discusses the development and im...,"[Academic development of ATMPs, Regulatory cha...",The document highlights the difficulty in secu...,The document recommends increased collaboratio...,The document identifies hurdles related to the...,None,None
67,F33116818.pdf,LSMA Position for the Public Consultation for ...,[Life Science Manufacturers Association (LSMA)],3,This position paper by the Life Science Manufa...,"[Regulatory streamlining and harmonisation, In...",The document recommends establishing a dedicat...,The document supports the development and coor...,The document calls for EU-supported training a...,None,The document emphasises the need for secure da...
68,F33116821.pdf,Sekab BioFuels & Chemicals AB – Response to th...,[Sekab BioFuels & Chemicals AB],3,Sekab BioFuels & Chemicals AB welcomes the Eur...,"[Support for existing and new biotechnologies,...",None,None,None,None,None
69,F33117138.pdf,From Lab to Market: How the Biotech Act Can Ac...,[Fraunhofer Group for Resource Technologies an...,4,This document discusses the importance of the ...,"[Bridging research and industry, De-risking co...",The document highlights that financing for hig...,It proposes the establishment of Europe-wide j...,The document stresses the importance of empowe...,None,None
70,F33117395.pdf,CO2 Value Europe’s response to the Commission’...,[CO2 Value Europe AISBL],6,This document is CO2 Value Europe’s response t...,"[Inclusion of CCU in the Biotech Act, Regulato...",The document highlights the need for clear fun...,None,None,None,None
71,F33117397.pdf,SIOPE Response to EU Biotech Act Consultation ...,[SIOPE],1,The document compiles sources relevant to the ...,"[Paediatric oncology, CAR T-cell therapy, Biot...",None,None,None,None,None
72,F33117687.pdf,TRACELESS MATERIALS | Position Paper. Biotech ...,[traceless],4,This position paper addresses regulatory chall...,"[Regulatory barriers for natural polymers, Pac...",The document highlights that the natural polym...,None,None,None,None
73,F3593805.pdf,European food security through natural ferment...,[Farmless],3,The document outlines Farmless's innovative ap...,"[Natural fermentation for protein production, ...",Farmless has successfully raised €9 million fr...,None,None,None,None

### Treating the Missings

In [36]:
output_folder = Path(folder_path).parent / "results"
xlsx_path = Path(output_folder) / "RAG_all_results.xlsx"
df = pd.read_excel(xlsx_path)

In [38]:
       
doc_name='F3565290-UniSR_European Biotech Act_Extended.pdf'
#doc_name='F3564682-Reco EU biotech EWPA EWPM 10.06.2025.pdf'

completion = client.chat.completions.create(
    model="gpt-4.1",
    messages=[{"role": "user", 
               "content": user_prompt}],
    extra_body={
        "data_sources": [
            {
                "type": "azure_search",
                "parameters": {
                    "endpoint": os.environ["AZURE_AI_SEARCH_ENDPOINT"],
                    "index_name": f"{container_name}_index",
                    "authentication": {
                        "type": "api_key",
                        "key": os.environ["AZURE_AI_SEARCH_API_KEY"],
                    },

                    # Map fields so citations show nice titles/paths (optional but handy)
                    "fields_mapping": {
                        "title_field": "title",
                        "filepath_field": "filepath",
                        "url_field": "url",
                        
                    },

                    # B) If you stored the doc name in a custom field
                    "filter": f"title eq '{odata_escape(doc_name)}'",


                    "in_scope": True,        # keep the answer grounded to retrieved docs
                    # "strictness": 4,       # (optional) tighten relevance
                    # "top_n_documents": 5,  # (optional) fewer chunks for stricter focus
                },
            }
        ],
    },
)

print(completion.choices[0].message.content)

{
  "title": "Contribution to the Consultation on the Future European Biotech Act",
  "organisation": ["Università Vita-Salute San Raffaele"],
  "summary": "The document is a contribution from Università Vita-Salute San Raffaele to the European Commission's consultation on the future European Biotech Act. It welcomes the initiative and provides recommendations to strengthen Europe's position in biotechnology. Key suggestions include enhanced support for academic centres, streamlined regulatory processes, and the creation of a 'Single Biotech Permit' for EU-wide operations. The document also advocates for a dedicated translational track for biotech projects and harmonised tax incentives for private investment. Additionally, it highlights the importance of secure and efficient access to anonymised patient data. The overall aim is to reduce barriers and accelerate innovation in the European biotech sector.",
  "main themes": [
    "Support for academic biotech research",
    "Regulatory streamlining",
    "Single Biotech Permit",
    "Translational track for biotech projects",
    "Tax incentives for biotech investment",
    "Data access and security",
    "Innovation acceleration",
    "EU-wide harmonisation"
  ]
}

In [39]:

extract_pillars(doc_name)

{'VC': 'The document proposes an EU framework for tax relief to incentivise high-risk investment in biotech, including tax credits, capital gains tax deferrals, and favourable treatment of convertible instruments. It argues that harmonising such incentives would create a more predictable and attractive landscape for both European and international investors.',
 'clusters': 'The document recommends dedicated support for academic centres to play a leading role in future biotech clusters and centres of excellence across the EU. It also suggests the creation of themed pan-European biotech accelerators to systematically transform research outputs into companies with access to capital, talent, and infrastructure.',
 'skills': None,
 'AI/data': 'The document highlights the importance of real-world data and AI in accelerating the development of innovative therapies, calling for dedicated support for AI technologies that leverage such data. It emphasises the need for collaboration between biotech companies, academic institutions, and healthcare providers to ensure data quality, interoperability, and robust interpretation.',
 'dual_use/security': None}

In [40]:
main_themes = [
    "Support for academic biotech research",
    "Regulatory streamlining",
    "Single Biotech Permit",
    "Translational track for biotech projects",
    "Tax incentives for biotech investment",
    "Data access and security",
    "Innovation acceleration",
    "EU-wide harmonisation"
  ]

print(main_themes)

['Support for academic biotech research', 'Regulatory streamlining', 'Single Biotech Permit', 'Translational track for biotech projects', 'Tax incentives for biotech investment', 'Data access and security', 'Innovation acceleration', 'EU-wide harmonisation']