In [1]:
from dotenv import load_dotenv
import os
from pathlib import Path
from openai import AzureOpenAI
from embeddings import UserDocumentCollection
import os, json, re
import pandas as pd

import numpy as np
from pypdf import PdfReader
import win32com.client as win32
from time import sleep

In [2]:
load_dotenv()

True

In [3]:
folder_path = os.environ.get("FOLDER_PATH")

## Position papers

In [4]:
docs_path = Path(folder_path) / "position-papers"
output_folder = Path(folder_path).parent / "results"

In [5]:
container_name="sante-docs"
colect = UserDocumentCollection(container_name)


# iterate and upload all files in docs_path
for p in sorted(Path(docs_path).iterdir()):
    if not p.is_file():
        continue
    with p.open("rb") as file_obj:
        colect.add_file_to_blob_container(str(p), file_obj)

colect.create_user_search_index()
colect.create_data_source_connection()
colect.create_user_skillset()
colect.create_user_indexer()
colect.reset_and_run_indexer()

2025-11-03 10:45:52.259 | INFO     | embeddings:get_container:66 - Container 'sante-docs' already exists.
2025-11-03 10:45:52.350 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3552803-Feedback Paper On the European Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:52.363 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3553888-cpme.2025-092.FINAL.Statement.Biotech.Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:52.376 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3554271-Koppert submission for the biotech act consultations.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:52.393 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3559517-EBSA Position Paper - OMNIBUS - 20250416 (1).pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:52.422 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3561326-PhageEU Proposals for Amendments_Pharmaceutical Package_March 2025.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:52.436 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3563493-WACKER Submission Bioeconomy.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:52.452 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3563646-250604_Stellungnahme der Hamilton Bonaduz AG zum geplanten Europäischen Biotech Rechtsakt.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:52.466 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3563652-Biotech input Artemis Def.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:52.480 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3563668-Plant ETP Contribution - Call for evidence Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:52.643 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3563901-EU Biotech Act Position Paper V1.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:52.657 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3563910-Food Fermentation Europe_Biotech Act Call for Evidence, June 2025.docx' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:52.690 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3563929-CFE response to Biotech Act proposal.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:52.708 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564074-GFI-E Call for evidence Biotech act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:52.723 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564102-EBU_BioTech Act_Submission_June 2025 (1).pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:52.739 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564121-BiotechAct_Fraunhofer.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:52.807 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564204-Biotech Act_ Luke.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:52.822 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564210-Amgen_position paper Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:52.837 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564218-CAE Position_Biotech Act_Call for Evidence.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:52.965 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564228-CropLifeEurope_Simplification proposals for GM & Bioppps_.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:52.990 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564247-2025-06-06 A.I.S.E. feedback to the European Commission Call for Evidence on the Biotech Act .pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.005 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564250-BIO Deutschland_ Comments on the EU Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.023 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564253-Postion paper Biocontrol.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.055 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564264-ACDV - Contribution Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.175 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564266-Leading, not lagging - putting mental health at the core of Europe s innovation and competitiveness agenda.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.200 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564268-INRAE Contribution to EU Biotech Act_VF.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.215 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564270-25_EU_11.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.334 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564380-Biotech Act open consultation DSW 2025.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.350 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564435-VK_Akt o biotechnologiích_CZ_.docx' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.389 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564477-MBB Biotech Act Call for Evidence_June 2025.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.409 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564478-20250609_Biotech Act consultation - SPRING.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.427 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564488-MediQuills_Response_to_EU's_Biotech_Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.455 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564504-250410 respuesta MAPA EUSurvey - Survey.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.579 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564682-Reco EU biotech EWPA EWPM 10.06.2025.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.598 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564687-Biotech Act June 2025 _FoodDrinkEurope Feedback.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.615 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564728-ESMO Response - Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.632 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564760-250610_Hollandbio_input_CfE_BiotechAct.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.647 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564769-Written Contribution EFfCI -Biotech Act (1).pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.661 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564784-QbD Group Feedback on EU Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.675 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564813-Reviews and position papers_Annex.docx' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.691 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564816-250610 ANOVE Comentarios Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.798 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564818-FINAL_EuropaBio Position EU Biotech Act_10062025.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.816 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564833-EHA recommendations - Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.834 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564836-20250610 AseBio response Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.850 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564841-20250610 Biovia - Call for evidence - EU Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.866 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564842-EU Biotech  Act_EC Public Consultation_HIPRA.docx' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.881 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564843-ARM Call for Evidence Response Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.896 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564846-2025_06_11_Call for evidence Biotech Act_CNRS.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.910 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564851-2025-023 EPF Response to the Call for Evidence on the European Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.924 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564862-J&J Placing the life science sector at the core of the Competitiveness Compass_FINAL.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.938 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564899-Biotech act_Klaudia Kozusznik_A4BEE.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.952 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564900-June 2025 _ Contribution AFE _ Biotech Act.docx' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.968 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564901-GSK contribution for the Call for Evidence, Biotech Act, 10 June 2025.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.982 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564912-ACRO FINAL Comment - Biotech Act Call for Evidence.docx' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:53.994 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564918-EU Biotech submission.docx' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.011 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564919-Pandemic Action Network response to the EU Biotech Act call for evidence_1006225.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.036 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564930-25.0367.2 - Biotech Act - Euroseeds input to call for evidence.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.073 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564965-RD Moonshot_Contribution to the consultation EU Biotech Act_FINAL.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.089 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564967-Call for Evidence Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.175 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564970-EU BioTech act_VTT messages.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.191 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564976-2025_biotech consultation.docx' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.210 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564981-Submission for EU Biotech Act Call for Evidence_Pour Demain Europe.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.226 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564997-ErVimmune - Réflexions sur le financement des biotech UE ENG 10062025 .pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.243 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564998-EPF’s response to the Call for evidence on the EU Biotect Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.268 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565010-EFPIA Annex_BioTech Act_Call for evidence_Final.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.284 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565025-Joint HNP Position Paper Biotechnology mrt 2024.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.340 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565034-20250611- CNCPI- contribution European Biotech Act .pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.352 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565040-bioMerieux contribution_EU Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.367 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565042-Cepi response to Call for Evidence_Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.388 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565064-EUCOPE_Proposals Biotech Act_final_Jun25.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.403 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565089-Novamont_Biotech Act consultation.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.516 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565090-CORBION_POSITION BIOTECH ACT.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.539 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565110-Biocontrol-Coalition-BiotechAct-final.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.552 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565113-20250611_Helmholtz_BiotechAct_final.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.566 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565115-20250519_LSMA_Biotech Act call for evidence.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.659 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565117-ECL Policy paper The potential for academic development of medicines in Europe.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.913 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565118-EFFCA FEMS Publication on NGTs (2024) & Labelling Solution.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.934 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565143-Biotech Act Call for Evidence, attachment.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:54.979 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565157-Ley Biotecnologia comentarios.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:55.022 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565164-2025-06-04 Stellungnahme Pro Generika EU Biotech Act_Entwurf_final.docx' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:55.036 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565165-MedTech Europe Biotech Act Call for Evidence Draft response June 2025 FINAL.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:55.053 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565166-25-06-11_Biotech-Act_Call_Evidence_SupplLiterature_BfN.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:55.131 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565172-Eurogroup for Animals - Call for evidence on the Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:55.147 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565207-Response to the Call for Evidence on the European Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:55.162 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565208-AnimalhealthEurope_Feedback - Biotech Act (fin).pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:55.177 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565224-Feedback on Biotech Act_Rigshospitalet_Copenhagen University Hospital.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:55.191 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565229-EUBiotechAct_ FIB_final.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:55.206 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565230-Pfizer Response to the EU Biotech Act Call for Evidence.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:55.221 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565232-IFOAMEU_Biotech Act_public consultation_input.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:55.237 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565236-Lif's and SwedensBIO's Biotech act position paper.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:55.255 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565249-Novo Nordisk Foundation - Call for evidence EU Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:55.415 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565251-FIN_DIB_EU BioTech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:55.435 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565252-DanishChamberofCommerce_Callforevidence_BiotechAct.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:55.453 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565256-EU Biotech Act call for evidence_PRI response_Submitted.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:55.471 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565277-Roche feedback EU Biotech Act - Call for Evidence - 11 June 2025.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:55.486 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565281-Position paper WEWIS Biotech Act.pdf' already exists in container 'sante-docs'. Skipping upload.
2025-11-03 10:45:55.501 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565286-20250611 BASF Position_Biotech Act - FINAL.pdf' already exists in container 'sante-docs'. Skipping upload.

In [9]:
colect.reset_and_run_indexer()

2025-11-03 10:10:03.341 | INFO     | embeddings:reset_and_run_indexer:252 - 🧹 Indexer 'sante-docs-indexer' checkpoint reset successfully.
2025-11-03 10:10:03.495 | INFO     | embeddings:reset_and_run_indexer:256 - 🚀 Indexer 'sante-docs-indexer' started successfully.

In [5]:
BRUSSEL_first_PROMPT = (
  """

  Below are concise definitions of three key topics related to biotechnology policy and industry development:

  - ATMP (Advanced Therapy Medicinal Products): Medicinal products based on genes, cells, or engineered tissues offering advanced or personalised therapeutic effects (e.g. gene therapy, CAR-T cell therapy, tissue-engineered grafts). They often overlap with personalised and regenerative medicine, requiring complex regulatory and manufacturing pathways.
      • gene_therapies: Advanced therapy medicinal producsts based on genes
      • cell_therapies: Advanced therapy medicinal products based on cells
      • tissue_engineered_products: Advanced therapy medicinal products based on engineered tissues
      • personalised_medicine: Advanced therapy medicinal products tailored to personalised therapeutic effects
  - Access to Markets: Factors affecting how biotech products reach patients or users, including:
      • access_hurdles — document criticizes the regulatory, reimbursement, validation, or manufacturing obstacles delaying market entry;
      • access_strategies — document promotes, supports, encourages policy or business approaches to address these barriers (e.g. harmonisation, early regulatory dialogue, public procurement, risk-sharing models).

  - VC_Investments_IPO (Venture Capital, Investments, and Stock Exchanges/IPOs): Trends and mechanisms of biotech financing, including venture capital, private equity, institutional investments, and IPOs. This includes availability of capital, exit routes, market maturity, and cross-border funding.

  TASK:
  For each theme and subtheme, check whether the document makes a reference to it.
  If yes, return aLL exact citations and page numbers.
  If not present, set the value to null.

  Output format:
  Return ONE JSON object with EXACTLY these keys; each value is EITHER null OR a list of strings containing exact text excerpts in the format “... (page XX)”:
  {
    "ATMP": <null or ["<exact quote> (page XX)", "<exact quote> (page XX)", ...]>,
    "ATMP_gene_therapies": <null or ["<exact quote> (page XX)", "<exact quote> (page XX)", ...]>,
    "ATMP_cell_therapies": <null or ["<exact quote> (page XX)", "<exact quote> (page XX)", ...]>,
    "ATMP_tissue_engineered_products": <null or ["<exact quote> (page XX)", "<exact quote> (page XX)", ...]>,
    "ATMP_personalised_medicine": <null or ["<exact quote> (page XX)", "<exact quote> (page XX)", ...]>,
    "Access_to_Markets_hurdles": <null or ["<exact quote> (page XX)", "<exact quote> (page XX)", ...]>,
    "Access_to_Markets_strategies": <null or ["<exact quote> (page XX)", "<exact quote> (page XX)", ...]>,
    "VC_Investments_IPO": <null or ["<exact quote> (page XX)", "<exact quote> (page XX)", ...]>
  }

  Rules:
  - Base your answer ONLY on the provided document content.
  - Use **exact quotations** and page numbers where the reference occurs. Do not return extract IDs like [doc1], [doc2], etc.
  - Each citation must be a **full, grammatically complete sentence** exactly as it appears in the document, ending with proper punctuation (e.g. period, semicolon, or question mark) before the page reference.
  - Do not return partial phrases, ellipses (...), or truncated text.
  - Do not return "the document mentions...", instead return the actual citation text.
  - Do NOT invent or infer information; if uncertain or if information is not available, use null.
  - Do not insert arbitrary newline characters in the quotes.
  - Output VALID JSON and NOTHING ELSE (no markdown, no prose, no commentary).
  """
)

In [6]:
client = AzureOpenAI(
    azure_endpoint=os.environ["AZURE_COGNITIVE_SERVICES_ENDPOINT"],
    api_key=os.environ["AZURE_COGNITIVE_API"],
    api_version="2024-10-21",  # 2024-02-01+ supports data_sources
)

In [7]:
def odata_escape(s: str) -> str:
    # OData string literals escape single quotes by doubling them
    return s.replace("'", "''")

In [8]:
def first_information(doc_name):
    completion = client.chat.completions.create(
        model="gpt-model",
        messages=[
            {
                "role": "user",
                "content": f"You already possess the document {doc_name} that contains all necessary information to answer following questions.\n"
                           + BRUSSEL_first_PROMPT
            }
        ],
        response_format={"type": "json_object"},
        extra_body={
            "data_sources": [
                {
                    "type": "azure_search",
                    "parameters": {
                        "endpoint": os.environ["AZURE_AI_SEARCH_ENDPOINT"],
                        "index_name": f"{container_name}_index",
                        "authentication": {
                            "type": "api_key",
                            "key": os.environ["AZURE_AI_SEARCH_API_KEY"],
                        },
                        "fields_mapping": {
                            "title_field": "title",
                            "filepath_field": "filepath",
                            "url_field": "url",
                        },
                        "filter": f"title eq '{odata_escape(doc_name)}'",
                        "in_scope": True,
                    },
                }
            ],
        },
    )

    raw = completion.choices[0].message.content or ""
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        # Fallback schema matching the new prompt keys
        return {
            "ATMP": None,
            "ATMP_gene_therapies": None,
            "ATMP_cell_therapies": None,
            "ATMP_tissue_engineered_products": None,
            "ATMP_personalised_medicine": None,
            "Access_to_Markets_hurdles": None,
            "Access_to_Markets_strategies": None,
            "VC_Investments_IPO": None,
        }

In [46]:
docs = sorted([p.name for p in Path(docs_path).iterdir() if p.is_file()])[11:15]

for doc in docs:
    info = first_information(doc)

    print("=" * 80)
    print(f"📄 Document: {doc}")
    print("-" * 80)
    print(json.dumps(info, indent=2, ensure_ascii=False))
    print("=" * 80 + "\n")

================================================================================
📄 Document: F3563929-CFE response to Biotech Act proposal.pdf
--------------------------------------------------------------------------------
{
  "ATMP": null,
  "ATMP_gene_therapies": null,
  "ATMP_cell_therapies": null,
  "ATMP_tissue_engineered_products": null,
  "ATMP_personalised_medicine": null,
  "Access_to_Markets_hurdles": [
    "The proposal acknowledges that the complex regulatory framework of the EU single market, which may diverge among Member States, is perceived to be slow and burdensome. In a rapidly growing and evolving sector such as biotech, such frameworks can act as a significant barrier to progress. (page 1)",
    "This is particularly pertinent for biotechnologies for non-animal science that, while proving promising in the research and development phase, can face several hurdles when it comes to regulatory uptake, for example slow or lack of validation or low recognition of regulatory utility. (page 1)"
  ],
  "Access_to_Markets_strategies": [
    "As such, the Biotech Act should set a clear pathway for the validation and regulatory acceptance of biotechnologies for non-animal science, including regulatory testing. The Act should be accompanied by guidelines which support effort already underway at organisations such as the OECD and EURL ECVAM. (page 1)",
    "The Biotech Act needs to improve access to funding and funding opportunities, such as public-private funding, for researchers developing biotechnologies for non-animal science, including testing. It should also create innovation hubs or industrialisation centres that will support researchers in taking these technologies from lab-to-factory-to market. (page 1)"
  ],
  "VC_Investments_IPO": null
}
================================================================================

================================================================================
📄 Document: F3564074-GFI-E Call for evidence Biotech act.pdf
--------------------------------------------------------------------------------
{
  "ATMP": null,
  "ATMP_gene_therapies": null,
  "ATMP_cell_therapies": null,
  "ATMP_tissue_engineered_products": null,
  "ATMP_personalised_medicine": null,
  "Access_to_Markets_hurdles": [
    "However, complex and lengthy regulatory approval processes slow down innovation and investment in the alternative protein sector. While other regions advance approvals for new food technologies, European companies face regulatory bottlenecks that undermine industry confidence in the EU path to market, delay market entry and push innovation abroad. (page 2)"
  ],
  "Access_to_Markets_strategies": [
    "A fair and efficient regulatory framework is not about imposing dietary choices but rather expanding them. Consumers should have access to a variety of safe, high-quality food options and be free to decide what best suits their preferences. A well-functioning regulatory system should allow for innovation and predictability for innovators while respecting individual choices. (page 2)",
    "Ensure the pre-market authorisation process under the Novel Food Regulation is as efficient and transparent as possible while maintaining existing high food safety standards. (page 2)",
    "Establish a formal pre-submission consultation process with EFSA to clarify data requirements and prevent delays. To maintain scientific independence, a dedicated ‘front desk’, separate from scientific evaluators, should oversee these consultations. (page 3)",
    "Establish regulatory sandboxes to pilot best practices in novel food regulation and allow for testing in a real-world environment with robust regulatory oversight. (page 3)"
  ],
  "VC_Investments_IPO": [
    "Diversify public financing for biomanufacturing by developing more non-dilutive options, such as grants, loans, and guarantees. Consider leveraging Important Projects of Common European Interest (IPCEIs) to drive investment in biomanufacturing infrastructure. (page 2)",
    "Strengthen the EIB mandate in the bioeconomy and biotechnology by increasing funding for food biotech companies and deepening industry engagement to improve access to financing. (page 2)",
    "Establish public-private partnerships, such as a Joint Undertaking focused on food biotech, to accelerate biomanufacturing, mirroring successful models in other strategic sectors. (page 2)"
  ]
}
================================================================================

================================================================================
📄 Document: F3564102-EBU_BioTech Act_Submission_June 2025 (1).pdf
--------------------------------------------------------------------------------
{
  "ATMP": null,
  "ATMP_gene_therapies": null,
  "ATMP_cell_therapies": null,
  "ATMP_tissue_engineered_products": null,
  "ATMP_personalised_medicine": null,
  "Access_to_Markets_hurdles": [
    "Technologies developed in isolation from real-world needs risk becoming clinically impressive but practically irrelevant. (page 1)",
    "Rare conditions, ultra-orphan diseases, and underserved populations must be eligible for targeted funding, infrastructure access, and regulatory guidance under the Biotech Act. (page 1)",
    "For rare disease communities and other underrepresented populations, innovation is not just a policy issue. It is a question of survival, dignity, and long-term health system resilience. These groups often face fragmented development pipelines, limited investment incentives, and outcome frameworks that fail to reflect lived realities. (page 1)",
    "Structural Gaps in the Current Framing No requirement to involve patients or civil society in early-stage development or regulatory planning No clear pathway for supporting non-lucrative or ultra-rare biotech solutions Lack of alignment with public health needs, real-world outcomes, and equitable access (page 1)"
  ],
  "Access_to_Markets_strategies": [
    "The Biotech Act should explicitly support the integration of patients and civil society into early development processes. This includes co-defining innovation priorities and outcome measures. (page 1)",
    "Early co-creation improves system fit, reduces downstream friction, and builds public trust. (page 1)",
    "Policy must ensure that biotech investment reflects unmet need, not just commercial potential. (page 1)",
    "Developers should be supported to adopt outcomes that reflect societal benefit, such as functional improvement, quality of life, and caregiver burden. These should be aligned with HTA frameworks and health system sustainability goals. (page 1)",
    "Aligning metrics from the outset will accelerate both relevance and uptake. (page 1)",
    "Empowered By Us calls on the European Commission to embed equity, relevance, and co-creation into the design and implementation of the Act. (page 1)"
  ],
  "VC_Investments_IPO": null
}
================================================================================

================================================================================
📄 Document: F3564121-BiotechAct_Fraunhofer.pdf
--------------------------------------------------------------------------------
{
  "ATMP": null,
  "ATMP_gene_therapies": null,
  "ATMP_cell_therapies": null,
  "ATMP_tissue_engineered_products": null,
  "ATMP_personalised_medicine": null,
  "Access_to_Markets_hurdles": [
    "Tapping the full potential of the Act for the competitiveness, resilience, and modernization of the EU’s industry, demands to close the gap in the transfer from research to industry. (page 1)",
    "Additional measures need to address the financing challenges faced by biotech and biomanufacturing start-ups and SMEs. Their early stages are characterized by high capital intensity due to cost-intensive research processes; above-average development times and innovation cycles of bio-based products and materials; securing of renewable feedstock; build-up or use of capital-intensive scaling facilities; plant and infrastructure investments; as well as lengthy time to market. (page 1)"
  ],
  "Access_to_Markets_strategies": [
    "Providing planning security, derisking strategies, and targeted support for the research and development phases of biotech and biomanufacturing start-ups will lead to faster market success, establishment on the market and contribute to long-term climate and resource protection. (page 1)",
    "Funds to support projects at lower TRL stages need to be established in addition to initiatives like ECBF that focus on projects from TRL 6 onwards. (page 1)",
    "Practical tools for businesses and investors should serve the assessment of market potential and sustainability impacts, leading to informed decision-making in product and service development. (page 1)",
    "Create regulatory sandboxes and expand Europe-wide virtual and physical hubs for technological research on the circular bioeconomy for the joint development of systemic and technological solutions along the whole value chain. (page 1)",
    "Guarantee long-term financial support (at least 10 years) for the cooperation of infrastructures, sandboxes, and hubs to test and evaluate creation networks until self-sustained. (page 1)",
    "Outline a roadmap with financial tools and guaranteed support systems for start-ups that take effect per each clearly identified milestone. (page 2)",
    "Create framework conditions to facilitate the market entry and positive economic impact of bioeconomic circular products and processes and reduce subsidies for non-sustainable or barely sustainable products. (page 2)",
    "Increase market pull through regulatory measures, such as blending quotas and material specifications in products. (page 2)"
  ],
  "VC_Investments_IPO": [
    "Additional measures need to address the financing challenges faced by biotech and biomanufacturing start-ups and SMEs. Their early stages are characterized by high capital intensity due to cost-intensive research processes; above-average development times and innovation cycles of bio-based products and materials; securing of renewable feedstock; build-up or use of capital-intensive scaling facilities; plant and infrastructure investments; as well as lengthy time to market. (page 1)",
    "Providing planning security, derisking strategies, and targeted support for the research and development phases of biotech and biomanufacturing start-ups will lead to faster market success, establishment on the market and contribute to long-term climate and resource protection. (page 1)",
    "Funds to support projects at lower TRL stages need to be established in addition to initiatives like ECBF that focus on projects from TRL 6 onwards. (page 1)",
    "Outline a roadmap with financial tools and guaranteed support systems for start-ups that take effect per each clearly identified milestone. (page 2)"
  ]
}
================================================================================

### SECOND PROMPT

In [9]:
BRUSSEL_SECOND_PROMPT = (
  """

  Below are concise definitions of three key topics related to biotechnology policy and industry development:

  - Manufacturing Capabilities: Refers to the existence and advancement of state-of-the-art infrastructure, equipment, and technologies used in biotechnology manufacturing. This includes facilities and processes for bioproduction, bioprocess optimization, automation, and quality systems meeting regulatory (e.g., GMP) standards for scale-up and commercialization.

  - Incubation and Acceleration: Structured programs that support early-stage biotech startups. 
      • Incubation refers to very early-stage support, typically offering laboratory space, mentoring, and assistance in building viable companies.  
      • Acceleration focuses on more mature startups, providing investment readiness, business development, and market access.  
    Identify any references to such programs, initiatives, or national policies supporting biotech incubation or acceleration.

  - Talent Retention: Refers to policies and measures to retain qualified biotech professionals and prevent talent loss. Includes references to career development, research funding, competitive compensation, and efforts to prevent brain drain or migration of expertise.

  - Upskilling / Reskilling: Biomanufacturing requires deep process expertise (e.g., fermentation, molecular methods) alongside cross-cutting skills in data/AI, sustainability, systems thinking, and entrepreneurship. This theme refers to education and training initiatives aimed at improving or renewing workers’ skills to meet evolving biotechnology needs, including continuous learning, professional training, workforce transition, and capacity-building programs.


  TASK:
  For each theme, check whether the document makes a substantive reference to it.
  If present, return ONLY exact quotations from the document with their page numbers.
  Do NOT summarize, paraphrase, or interpret. If not present, set the value to null.

  Output format:
  Return ONE JSON object with EXACTLY these keys; each value is EITHER null OR a list of strings containing exact text excerpts in the format “... (page XX)”:
    {
      "Manufacturing_Capabilities": <null or ["<exact quote> (page XX)", "<exact quote> (page XX)", ...]>,
      "Incubation_and_Acceleration": <null or ["<exact quote> (page XX)", "<exact quote> (page XX)", ...]>,
      "Talent_Retention": <null or ["<exact quote> (page XX)", "<exact quote> (page XX)", ...]>,
      "Upskilling_Reskilling": <null or ["<exact quote> (page XX)", "<exact quote> (page XX)", ...]>
    }

  Rules:
  - Base your answer ONLY on the provided document content.
  - Use **exact citations and page numbers** where the reference occurs. Do not return extract id like [doc1], [doc2], etc.
  - Each citation must be a **full, grammatically complete sentence** exactly as it appears in the document, ending with proper punctuation (e.g. period, semicolon, or question mark) before the page reference.
  - Do not return partial phrases, ellipses (...), or truncated text.
  - Do not return "the document mentions...", instead return the actual citation text.
  - Do not insert arbitrary newline characters in the quotes.
  - If a topic appears on multiple pages, include multiple citation objects.
  - Do NOT invent or infer information; if uncertain or if information is not available, use null.
  - Output VALID JSON and NOTHING ELSE (no markdown, no prose, no commentary).
  """
)

In [10]:
def second_information(doc_name):
    completion = client.chat.completions.create(
        model="gpt-model",
        messages=[
            {
                "role": "user",
                "content": f"You already possess the document {doc_name} that contains all necessary information to answer following questions.\n"
                           + BRUSSEL_SECOND_PROMPT
            }
        ],
        response_format={"type": "json_object"},
        extra_body={
            "data_sources": [
                {
                    "type": "azure_search",
                    "parameters": {
                        "endpoint": os.environ["AZURE_AI_SEARCH_ENDPOINT"],
                        "index_name": f"{container_name}_index",
                        "authentication": {
                            "type": "api_key",
                            "key": os.environ["AZURE_AI_SEARCH_API_KEY"],
                        },
                        "fields_mapping": {
                            "title_field": "title",
                            "filepath_field": "filepath",
                            "url_field": "url",
                        },
                        "filter": f"title eq '{odata_escape(doc_name)}'",
                        "in_scope": True,
                    },
                }
            ],
        },
    )

    raw = completion.choices[0].message.content or ""
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        # Fallback schema matching updated BRUSSEL_SECOND_PROMPT keys
        return {
            "Manufacturing_Capabilities": None,
            "Incubation_and_Acceleration": None,
            "Talent_Retention": None,
            "Upskilling_Reskilling": None,
        }

In [49]:
docs = sorted([p.name for p in Path(docs_path).iterdir() if p.is_file()])[:10]

for doc in docs:
    info = second_information(doc)

    print("=" * 80)
    print(f"📄 Document: {doc}")
    print("-" * 80)
    print(json.dumps(info, indent=2, ensure_ascii=False))
    print("=" * 80 + "\n")

================================================================================
📄 Document: F3552803-Feedback Paper On the European Biotech Act.pdf
--------------------------------------------------------------------------------
{
  "Manufacturing_Capabilities": [
    "While the EU is a leader in biologics manufacturing, it remains vulnerable to geopolitical supply chain risks and foreign investment outflows. Dual-use biotech technologies in health and agriculture further raise security concerns. (page 6)",
    "Launch a Biomanufacturing Sovereignty Fund to support onshore production capacity for APIs, enzymes, and cell-based products. Simplify permitting and create industrial biozones with dedicated infrastructure and environmental oversight.. (page 7)"
  ],
  "Incubation_and_Acceleration": null,
  "Workforce_Development": [
    "A mismatch exists between the labor market and biotech's evolving skills needs. Europe's biotech hubs suffer from a shortage of bioprocess engineers, data scientists, regulatory affairs experts, and translational researchers. (page 5)",
    "Fund EU-wide talent fellowships for bioengineers, data scientists, and regulatory professionals. Embed entrepreneurship curricula within Horizon Europe and Erasmus+ to upskill PhD candidates in innovation management and commercialization. (page 7)"
  ]
}
================================================================================

================================================================================
📄 Document: F3553888-cpme.2025-092.FINAL.Statement.Biotech.Act.pdf
--------------------------------------------------------------------------------
{
  "Manufacturing_Capabilities": null,
  "Incubation_and_Acceleration": null,
  "Workforce_Development": null
}
================================================================================

================================================================================
📄 Document: F3554271-Koppert submission for the biotech act consultations.pdf
--------------------------------------------------------------------------------
{
  "Manufacturing_Capabilities": [
    "More specifically, the EU needs to create EU innovation hubs for biocontrol and biomanufacturing, linking research institutions, startups, and industry. (page 2)"
  ],
  "Incubation_and_Acceleration": [
    "More specifically, the EU needs to create EU innovation hubs for biocontrol and biomanufacturing, linking research institutions, startups, and industry. (page 2)"
  ],
  "Workforce_Development": [
    "Support training and advisory services for farmers and agronomists on the use of biocontrol products. (page 2)"
  ]
}
================================================================================

================================================================================
📄 Document: F3559517-EBSA Position Paper - OMNIBUS - 20250416 (1).pdf
--------------------------------------------------------------------------------
{
  "Manufacturing_Capabilities": null,
  "Incubation_and_Acceleration": null,
  "Workforce_Development": null
}
================================================================================

BadRequestError: Error code: 400 - {'error': {'requestid': '02fe0226-605c-4e47-82e9-cef3583235c9', 'code': 400, 'message': 'An error occurred when calling Azure OpenAI: Server responded with status 429. Error message: {"error":{"code":"429","message": "Rate limit is exceeded. Try again in 7 seconds."}}'}}

### tHIRD PROMPT

In [11]:
BRUSSEL_THIRD_PROMPT = (
  """

  Below are concise definitions of three key topics related to biotechnology policy and industry development:

  - Artificial Intelligence (AI) related Challenges in Biotechnology: Refers to the t'echnical, regulatory or ethical obstacles, limitations and bottlenecks that constrain the responsible use of AI in biotechnology.

  - Artificial Intelligence (AI) Development and Deployment in Biotechnology: Refers to cases where the document promotes, supports, or encourages the practical use, integration, or scaling of AI technologies in biotechnology. This includes references to initiatives, investments, strategies, or policies aimed at developing or deploying AI tools in biotech research, product development, or manufacturing.

  - Global Collaboration: Refers to international partnerships, initiatives, or cooperative frameworks between European biotechnology actors and global counterparts.

  - Biosecurity: Refers to the protection, control, and accountability of biological materials, data, and technologies to prevent their unauthorized access, loss, theft, misuse, diversion, or intentional release.  
      • Nucleic Acid Synthesis Screening — A specific biosecurity measure involving the screening of DNA or RNA synthesis requests to prevent the production of pathogenic or otherwise harmful sequences.

  TASK:
  For each theme, check whether the document makes a substantive reference to it.
  If present, return ONLY exact quotations from the document with their page numbers.
  Do NOT summarize, paraphrase, or interpret. If not present, set the value to null.

  Output format:
  Return ONE JSON object with EXACTLY these keys; each value is EITHER null OR a list of strings containing exact text excerpts in the format “... (page XX)”:
  {
    "AI_Challenges": <null or ["<exact quote> (page XX)", "<exact quote> (page XX)", ...]>,
    "AI_Development_and_Deployment": <null or ["<exact quote> (page XX)", "<exact quote> (page XX)", ...]>,
    "Global_Collaboration": <null or ["<exact quote> (page XX)", "<exact quote> (page XX)", ...]>,
    "Biosecurity": <null or ["<exact quote> (page XX)", "<exact quote> (page XX)", ...]>,
    "Biosecurity_Nucleic_Acid_Screening": <null or ["<exact quote> (page XX)", "<exact quote> (page XX)", ...]>
  }

  Rules:
  - Base your answer ONLY on the provided document content.
  - Use **exact citations and page numbers** where the reference occurs. Do not return extract IDs like [doc1], [doc2], etc.
  - Each citation must be a **full, grammatically complete sentence** exactly as it appears in the document, ending with proper punctuation (e.g. period, semicolon, or question mark) before the page reference.
  - Do not return partial phrases, ellipses (...), or truncated text.
  - Do not return "the document mentions...", instead return the actual citation text.
  - Do not insert arbitrary newline characters in the quotes.
  - If a topic appears on multiple pages, include multiple citation strings.
  - Do NOT invent or infer information; if uncertain or if information is not available, use null.
  - Output VALID JSON and NOTHING ELSE (no markdown, no prose, no commentary).
  """
)

In [12]:
def third_information(doc_name):
    completion = client.chat.completions.create(
        model="gpt-model",
        messages=[
            {
                "role": "user",
                "content": f"You already possess the document {doc_name} that contains all necessary information to answer following questions.\n"
                           + BRUSSEL_THIRD_PROMPT
            }
        ],
        response_format={"type": "json_object"},
        extra_body={
            "data_sources": [
                {
                    "type": "azure_search",
                    "parameters": {
                        "endpoint": os.environ["AZURE_AI_SEARCH_ENDPOINT"],
                        "index_name": f"{container_name}_index",
                        "authentication": {
                            "type": "api_key",
                            "key": os.environ["AZURE_AI_SEARCH_API_KEY"],
                        },
                        "fields_mapping": {
                            "title_field": "title",
                            "filepath_field": "filepath",
                            "url_field": "url",
                        },
                        "filter": f"title eq '{odata_escape(doc_name)}'",
                        "in_scope": True,
                    },
                }
            ],
        },
    )

    raw = completion.choices[0].message.content or ""
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        # Fallback schema matching BRUSSEL_THIRD_PROMPT keys
        return {
            "AI_Challenges": None,
            "AI_Development_and_Deployment": None,
            "Global_Collaboration": None,
            "Biosecurity": None,
            "Biosecurity_Nucleic_Acid_Screening": None,
        }

In [ ]:
docs = sorted([p.name for p in Path(docs_path).iterdir() if p.is_file()])[:10]

for doc in docs:
    info = third_information(doc)

    print("=" * 80)
    print(f"📄 Document: {doc}")
    print("-" * 80)
    print(json.dumps(info, indent=2, ensure_ascii=False))
    print("=" * 80 + "\n")

================================================================================
📄 Document: F3552803-Feedback Paper On the European Biotech Act.pdf
--------------------------------------------------------------------------------
{
  "AI_Challenges": [
    "The biotech revolution depends increasingly on access to real-world data, AI-enhanced simulations, and supercomputing resources. However, many biotech SMEs lack access to the European Health Data Space (EHDS), federated biobanks, or AI testing environments. Academic literature highlights the role of machine learning in expediting drug discovery, protein folding, and metabolic pathway design (Reis et al., 2020). The Biotech Act must integrate the EU AI Strategy and EHDS with dedicated capacity for biotech applications. (page 5)",
    "Ensure biotech-specific access to the EHDS, federated datasets, and AI Factories. Mandate interoperability standards and ethical safeguards. Support the creation of an EU Biotech-AI Alliance to encourage cross-sector R&D. (page 7)"
  ],
  "AI_Development_and_Deployment": [
    "The biotech revolution depends increasingly on access to real-world data, AI-enhanced simulations, and supercomputing resources. However, many biotech SMEs lack access to the European Health Data Space (EHDS), federated biobanks, or AI testing environments. Academic literature highlights the role of machine learning in expediting drug discovery, protein folding, and metabolic pathway design (Reis et al., 2020). The Biotech Act must integrate the EU AI Strategy and EHDS with dedicated capacity for biotech applications. (page 5)",
    "Strengthen Data Infrastructure and AI-Driven Biotech R&D. Ensure biotech-specific access to the EHDS, federated datasets, and AI Factories. Mandate interoperability standards and ethical safeguards. Support the creation of an EU Biotech-AI Alliance to encourage cross-sector R&D. (page 7)"
  ],
  "Global_Collaboration": [
    "Fund EU-wide talent fellowships for bioengineers, data scientists, and regulatory professionals. Embed entrepreneurship curricula within Horizon Europe and Erasmus+ to upskill PhD candidates in innovation management and commercialization. (page 7)",
    "The success of this Act depends on strong coordination across institutions, Member States, academia, industry, and civil society. RareGen Youth Network urges the European Commission to prioritize youth-led innovation, SME equity, and cross-sectoral collaboration in implementation. We stand ready to contribute to the shaping and operationalization of this legislation and call for inclusive dialogue that reflects the interdisciplinary and intergenerational nature of biotechnology. (page 8)"
  ],
  "Biosecurity": [
    "While the EU is a leader in biologics manufacturing, it remains vulnerable to geopolitical supply chain risks and foreign investment outflows. Dual-use biotech technologies in health and agriculture further raise security concerns. The White Paper for European Defence: Readiness 2030 calls for a biotechnology security strategy to address dual-use risks, IP protection, and international standards. The EU must incentivize regional manufacturing, de-risk supply chains, and protect strategic innovation. (page 6)"
  ],
  "Biosecurity_Nucleic_Acid_Screening": null
}
================================================================================

================================================================================
📄 Document: F3553888-cpme.2025-092.FINAL.Statement.Biotech.Act.pdf
--------------------------------------------------------------------------------
{
  "AI_Challenges": null,
  "AI_Development_and_Deployment": null,
  "Global_Collaboration": null,
  "Biosecurity": null,
  "Biosecurity_Nucleic_Acid_Screening": null
}
================================================================================

================================================================================
📄 Document: F3554271-Koppert submission for the biotech act consultations.pdf
--------------------------------------------------------------------------------
{
  "AI_Challenges": null,
  "AI_Development_and_Deployment": [
    "supporting public-private partnerships to co-develop next-generation biocontrol technologies, including AI-driven pest monitoring and precision application tools can boost innovation and unlock the full potential of such technologies. (page 2)"
  ],
  "Global_Collaboration": [
    "Koppert stands ready to collaborate with EU institutions, Member States, and stakeholders to shape a regulatory framework that empowers innovation, accelerates market access, and builds a resilient agrifood system for future generations. (page 3)"
  ],
  "Biosecurity": null,
  "Biosecurity_Nucleic_Acid_Screening": null
}
================================================================================

================================================================================
📄 Document: F3559517-EBSA Position Paper - OMNIBUS - 20250416 (1).pdf
--------------------------------------------------------------------------------
{
  "AI_Challenges": null,
  "AI_Development_and_Deployment": null,
  "Global_Collaboration": [
    "It serves as a platform for professionals across Europe, and beyond, to share knowledge, collaborate, and promote best practices in the field. (page 1)",
    "Founded in 1996, the European Biosafety Association (EBSA) is a professional organization that focuses on biosafety and biosecurity. It serves as a platform for professionals across Europe and beyond to share knowledge, collaborate, and promote best practices in the field. (page 3)"
  ],
  "Biosecurity": [
    "Founded in 1996, the European Biosafety Association (EBSA) is a professional organization that focuses on biosafety and biosecurity. It serves as a platform for professionals across Europe, and beyond, to share knowledge, collaborate, and promote best practices in the field.  EBSA supports the responsible and sustainable development of Europe's life sciences and education sectors through risk-based management of potentially hazardous biological materials. Committed to collaborating with the European Commission, EBSA works to enhance biosafety and biosecurity standard practices while fostering innovation and competitiveness across biotechnology, and human, animal, and plant health sectors.  EBSA welcomes the advancing collaboration with the European Commission to continuously uphold and strengthen biosafety and biosecurity standards, with a focus on the following aspects:   (page 1)",
    "Furthermore, EBSA is dedicated to promoting and disseminating best practices in biosafety and biosecurity among its members and in the greater professional, research and industrial communities. The association actively fosters dialogue on emerging challenges and plays an advisory role in shaping practices to mitigate risks associated with biological agents and materials. (page 3)"
  ],
  "Biosecurity_Nucleic_Acid_Screening": null
}
================================================================================

================================================================================
📄 Document: F3561326-PhageEU Proposals for Amendments_Pharmaceutical Package_March 2025.pdf
--------------------------------------------------------------------------------
{
  "AI_Challenges": null,
  "AI_Development_and_Deployment": null,
  "Global_Collaboration": null,
  "Biosecurity": null,
  "Biosecurity_Nucleic_Acid_Screening": null
}
================================================================================

================================================================================
📄 Document: F3563493-WACKER Submission Bioeconomy.pdf
--------------------------------------------------------------------------------
{
  "AI_Challenges": null,
  "AI_Development_and_Deployment": null,
  "Global_Collaboration": null,
  "Biosecurity": null,
  "Biosecurity_Nucleic_Acid_Screening": null
}
================================================================================

================================================================================
📄 Document: F3563646-250604_Stellungnahme der Hamilton Bonaduz AG zum geplanten Europäischen Biotech Rechtsakt.pdf
--------------------------------------------------------------------------------
{
  "AI_Challenges": [
    "Aus unserer Sicht ist zentral, dass die datenschutzrechtlichen und ethischen Rahmenbedingungen nicht zu übermäßigen Einschränkungen führen. (page 4)"
  ],
  "AI_Development_and_Deployment": [
    "Die im Konsultationspapier betonte Rolle von KI und Big Data für die Biotechnologie ist von strategischer Relevanz. Der Zugang zu hochwertigen, interoperablen Daten – insbesondere im Bereich der Gesundheitsbiotechnologie – ist eine Grundvoraussetzung für neue, datengestützte Innovationsmodelle. Der geplante Europäische Gesundheitsdatenraum (EHDS) und der Aufbau von KI-Testzentren („KI-Fabriken“) bieten hier wertvolle Ansatzpunkte. (page 4)"
  ],
  "Global_Collaboration": [
    "Fördermittel sollten gezielt in Kompetenzzentren, den Ausbau von Daten- und KI-Infrastrukturen sowie in grenzüberschreitende Netzwerke investiert werden, die echten Mehrwert für alle Akteure entlang der Wertschöpfungskette schaffen. (page 4)",
    "Die Hamilton Bonaduz AG befürwortet deshalb Programme zur transnationalen Talentmobilität und gezielte Maßnahmen zur Förderung von unternehmerischem Denken in der Forschung. (page 5)"
  ],
  "Biosecurity": [
    "Insbesondere der in der Konsultation erwähnte Aspekt, dass „spezifische Biotechnologieanwendungen bei der Prüfung möglicher politischer Maßnahmen unter dem Gesichtspunkt der Sicherheit und Verteidigung (z.B. Technologien mit doppeltem Verwendungszweck) betrachtet“ werden sollen, birgt aus unserer Sicht das Potenzial für überbordende regulatorische Detailsteuerung. (page 3)",
    "Dazu gehört bestehende Regulierungen zu vereinfachen, Doppelregulierungen abzubauen und Sicherheitsbedenken klar und verhältnismäßig zu adressieren – ohne die wirtschaftliche Dynamik des Sektors zu untergraben. (page 5)"
  ],
  "Biosecurity_Nucleic_Acid_Screening": null
}
================================================================================

================================================================================
📄 Document: F3563652-Biotech input Artemis Def.pdf
--------------------------------------------------------------------------------
{
  "AI_Challenges": null,
  "AI_Development_and_Deployment": null,
  "Global_Collaboration": null,
  "Biosecurity": null,
  "Biosecurity_Nucleic_Acid_Screening": null
}
================================================================================

================================================================================
📄 Document: F3563668-Plant ETP Contribution - Call for evidence Biotech Act.pdf
--------------------------------------------------------------------------------
{
  "AI_Challenges": null,
  "AI_Development_and_Deployment": null,
  "Global_Collaboration": [
    "Plant ETP brings stakeholders from the plant sector together to consider the challenges and opportunities of agricultural value chains in a holistic way, while developing a vision for future systems spanning food, feed, and biobased raw materials. In this way, Plant ETP provides strategic direction, recommendations of essential research and innovation, and science-based advice for the benefit of policymakers, research funding providers, practitioners, and innovators throughout agricultural value chains.  (page 2)"
  ],
  "Biosecurity": null,
  "Biosecurity_Nucleic_Acid_Screening": null
}
================================================================================

================================================================================
📄 Document: F3563901-EU Biotech Act Position Paper V1.pdf
--------------------------------------------------------------------------------
{
  "AI_Challenges": null,
  "AI_Development_and_Deployment": null,
  "Global_Collaboration": [
    "Biohm supports its attempts to increase co-operation with international partners on biotechnology research, as well as attempts to bring together R&D companies and scaling partnerships, both inside and outside of the EU. (page 04)"
  ],
  "Biosecurity": [
    "We would also like to see the Act help harmonise biosafety-related regulations with the ongoing REACH Revision – it should ensure consistency in the regulatory framework. The Act should support REACH by fast-tracking or incentivising bio-based alternatives that substitute harmful chemicals, through providing means to biotech and biomanufacturing SMEs to participate in REACH’s open, common collection of chemical data, as a means to foster adoption. More specifically, this can be achieved through supporting such entities to help declare and share data concerning their product’s safety and environmental benefits in the database. (page 05)"
  ],
  "Biosecurity_Nucleic_Acid_Screening": null
}
================================================================================

## ALL PROMPTS

In [23]:

from time import sleep, strftime
from openai import APIConnectionError, BadRequestError
import re

def call_once_with_wait(fn, *args, delay=10, label=None, **kwargs):
    who = f"[{label}]" if label else ""
    print(f"{strftime('%H:%M:%S')} {who} waiting {delay}s before call...", flush=True)
    sleep(delay)
    try:
        out = fn(*args, **kwargs)
        print(f"{strftime('%H:%M:%S')} {who} call OK", flush=True)
        return out
    except BadRequestError as e:
        s = str(e)
        if "Rate limit is exceeded" in s:
            m = re.search(r"Try again in\s+(\d+)\s+seconds?", s, re.I)
            wait_s = int(m.group(1)) + 1 if m else max(5, delay)
            print(f"{strftime('%H:%M:%S')} {who} 429 rate limit → waiting {wait_s}s, then retrying once...", flush=True)
            sleep(wait_s)
            out = fn(*args, **kwargs)
            print(f"{strftime('%H:%M:%S')} {who} retry OK", flush=True)
            return out
        print(f"{strftime('%H:%M:%S')} {who} BadRequestError (not rate-limit): {e}", flush=True)
        raise
    except APIConnectionError as e:
        print(f"{strftime('%H:%M:%S')} {who} connection error → waiting 5s, then retrying once... ({e})", flush=True)
        sleep(5)
        out = fn(*args, **kwargs)
        print(f"{strftime('%H:%M:%S')} {who} retry OK", flush=True)
        return out
    except Exception as e:
        print(f"{strftime('%H:%M:%S')} {who} unexpected error: {e}", flush=True)
        raise

In [28]:
from tqdm.auto import tqdm
from pathlib import Path
import json
import pandas as pd
import time

# --- parameters ---
SAVE_EVERY = 10                     # how often to save (every N docs)
OUTPUT_PATH = Path(output_folder) / "brussels_pp_results.json"


docs = sorted([p.name for p in docs_path.iterdir() if p.is_file()])

results, errors = [], []
pbar = tqdm(docs, desc="Processing documents", unit="doc", total=len(docs))

def save_checkpoint():
    """Save current results and errors to disk."""
    try:
        # timestamped checkpoint
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        temp_file = OUTPUT_PATH.with_name(f"{OUTPUT_PATH.stem}_checkpoint_{timestamp}.json")

        with open(temp_file, "w", encoding="utf-8") as f:
            json.dump({"results": results, "errors": errors}, f, ensure_ascii=False, indent=2)
        pbar.write(f"[SAVED] checkpoint with {len(results)} results → {temp_file}")
    except Exception as e:
        pbar.write(f"[WARNING] Failed to save checkpoint: {e}")

for i, doc in enumerate(pbar, start=1):
    pbar.set_postfix_str(doc)
    try:
        first  = call_once_with_wait(first_information, doc, delay=10, label=f"first:{doc}")
        second = call_once_with_wait(second_information, doc, delay=10, label=f"second:{doc}")
        third  = call_once_with_wait(third_information, doc, delay=10, label=f"third:{doc}")
        results.append({**first, **second, **third})
    except Exception as e:
        errors.append((doc, repr(e)))
        pbar.write(f"[ERROR] {doc}: {e}")

    # --- periodic save ---
    if i % SAVE_EVERY == 0:
        save_checkpoint()

# --- final save ---
with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    json.dump({"results": results, "errors": errors}, f, ensure_ascii=False, indent=2)
pbar.write(f"[DONE] All results saved to {OUTPUT_PATH}")

Processing documents:   0%|          | 0/149 [00:00<?, ?doc/s, F3552803-Feedback Paper On the European Biotech Act.pdf]

13:30:44 [first:F3552803-Feedback Paper On the European Biotech Act.pdf] waiting 10s before call...

13:31:00 [first:F3552803-Feedback Paper On the European Biotech Act.pdf] call OK
13:31:00 [second:F3552803-Feedback Paper On the European Biotech Act.pdf] waiting 10s before call...
13:31:14 [second:F3552803-Feedback Paper On the European Biotech Act.pdf] call OK
13:31:14 [third:F3552803-Feedback Paper On the European Biotech Act.pdf] waiting 10s before call...
13:31:31 [third:F3552803-Feedback Paper On the European Biotech Act.pdf] call OK

Processing documents:   1%|          | 1/149 [00:47<1:56:08, 47.08s/doc, F3553888-cpme.2025-092.FINAL.Statement.Biotech.Act.pdf]

13:31:31 [first:F3553888-cpme.2025-092.FINAL.Statement.Biotech.Act.pdf] waiting 10s before call...
13:31:43 [first:F3553888-cpme.2025-092.FINAL.Statement.Biotech.Act.pdf] call OK
13:31:43 [second:F3553888-cpme.2025-092.FINAL.Statement.Biotech.Act.pdf] waiting 10s before call...
13:31:55 [second:F3553888-cpme.2025-092.FINAL.Statement.Biotech.Act.pdf] call OK
13:31:55 [third:F3553888-cpme.2025-092.FINAL.Statement.Biotech.Act.pdf] waiting 10s before call...
13:32:23 [third:F3553888-cpme.2025-092.FINAL.Statement.Biotech.Act.pdf] call OK

Processing documents:   1%|▏         | 2/149 [01:38<2:02:08, 49.85s/doc, F3554271-Koppert submission for the biotech act consultations.pdf]

13:32:23 [first:F3554271-Koppert submission for the biotech act consultations.pdf] waiting 10s before call...
13:32:40 [first:F3554271-Koppert submission for the biotech act consultations.pdf] call OK
13:32:40 [second:F3554271-Koppert submission for the biotech act consultations.pdf] waiting 10s before call...
13:32:53 [second:F3554271-Koppert submission for the biotech act consultations.pdf] call OK
13:32:53 [third:F3554271-Koppert submission for the biotech act consultations.pdf] waiting 10s before call...
13:33:06 [third:F3554271-Koppert submission for the biotech act consultations.pdf] call OK

Processing documents:   2%|▏         | 3/149 [02:21<1:53:39, 46.71s/doc, F3559517-EBSA Position Paper - OMNIBUS - 20250416 (1).pdf]

13:33:06 [first:F3559517-EBSA Position Paper - OMNIBUS - 20250416 (1).pdf] waiting 10s before call...
13:33:22 [first:F3559517-EBSA Position Paper - OMNIBUS - 20250416 (1).pdf] call OK
13:33:22 [second:F3559517-EBSA Position Paper - OMNIBUS - 20250416 (1).pdf] waiting 10s before call...
13:33:36 [second:F3559517-EBSA Position Paper - OMNIBUS - 20250416 (1).pdf] call OK
13:33:36 [third:F3559517-EBSA Position Paper - OMNIBUS - 20250416 (1).pdf] waiting 10s before call...
13:33:51 [third:F3559517-EBSA Position Paper - OMNIBUS - 20250416 (1).pdf] call OK

Processing documents:   3%|▎         | 4/149 [03:07<1:51:24, 46.10s/doc, F3561326-PhageEU Proposals for Amendments_Pharmaceutical Package_March 2025.pdf]

13:33:51 [first:F3561326-PhageEU Proposals for Amendments_Pharmaceutical Package_March 2025.pdf] waiting 10s before call...
13:34:09 [first:F3561326-PhageEU Proposals for Amendments_Pharmaceutical Package_March 2025.pdf] call OK
13:34:09 [second:F3561326-PhageEU Proposals for Amendments_Pharmaceutical Package_March 2025.pdf] waiting 10s before call...
13:34:22 [second:F3561326-PhageEU Proposals for Amendments_Pharmaceutical Package_March 2025.pdf] call OK
13:34:22 [third:F3561326-PhageEU Proposals for Amendments_Pharmaceutical Package_March 2025.pdf] waiting 10s before call...
13:34:36 [third:F3561326-PhageEU Proposals for Amendments_Pharmaceutical Package_March 2025.pdf] call OK

Processing documents:   3%|▎         | 5/149 [03:52<1:49:52, 45.78s/doc, F3563493-WACKER Submission Bioeconomy.pdf]

13:34:36 [first:F3563493-WACKER Submission Bioeconomy.pdf] waiting 10s before call...
13:34:56 [first:F3563493-WACKER Submission Bioeconomy.pdf] call OK
13:34:56 [second:F3563493-WACKER Submission Bioeconomy.pdf] waiting 10s before call...
13:35:10 [second:F3563493-WACKER Submission Bioeconomy.pdf] call OK
13:35:10 [third:F3563493-WACKER Submission Bioeconomy.pdf] waiting 10s before call...
13:35:22 [third:F3563493-WACKER Submission Bioeconomy.pdf] call OK

Processing documents:   4%|▍         | 6/149 [04:37<1:49:01, 45.75s/doc, F3563646-250604_Stellungnahme der Hamilton Bonaduz AG zum geplanten Europäischen Biotech Rechtsakt.pdf]

13:35:22 [first:F3563646-250604_Stellungnahme der Hamilton Bonaduz AG zum geplanten Europäischen Biotech Rechtsakt.pdf] waiting 10s before call...
13:35:36 [first:F3563646-250604_Stellungnahme der Hamilton Bonaduz AG zum geplanten Europäischen Biotech Rechtsakt.pdf] call OK
13:35:36 [second:F3563646-250604_Stellungnahme der Hamilton Bonaduz AG zum geplanten Europäischen Biotech Rechtsakt.pdf] waiting 10s before call...
13:35:49 [second:F3563646-250604_Stellungnahme der Hamilton Bonaduz AG zum geplanten Europäischen Biotech Rechtsakt.pdf] call OK
13:35:49 [third:F3563646-250604_Stellungnahme der Hamilton Bonaduz AG zum geplanten Europäischen Biotech Rechtsakt.pdf] waiting 10s before call...
13:36:04 [third:F3563646-250604_Stellungnahme der Hamilton Bonaduz AG zum geplanten Europäischen Biotech Rechtsakt.pdf] call OK

Processing documents:   5%|▍         | 7/149 [05:20<1:45:42, 44.66s/doc, F3563652-Biotech input Artemis Def.pdf]

13:36:04 [first:F3563652-Biotech input Artemis Def.pdf] waiting 10s before call...
13:36:23 [first:F3563652-Biotech input Artemis Def.pdf] call OK
13:36:23 [second:F3563652-Biotech input Artemis Def.pdf] waiting 10s before call...
13:36:35 [second:F3563652-Biotech input Artemis Def.pdf] call OK
13:36:35 [third:F3563652-Biotech input Artemis Def.pdf] waiting 10s before call...
13:36:47 [third:F3563652-Biotech input Artemis Def.pdf] call OK

Processing documents:   5%|▌         | 8/149 [06:02<1:43:12, 43.92s/doc, F3563668-Plant ETP Contribution - Call for evidence Biotech Act.pdf]

13:36:47 [first:F3563668-Plant ETP Contribution - Call for evidence Biotech Act.pdf] waiting 10s before call...
13:37:00 [first:F3563668-Plant ETP Contribution - Call for evidence Biotech Act.pdf] call OK
13:37:00 [second:F3563668-Plant ETP Contribution - Call for evidence Biotech Act.pdf] waiting 10s before call...
13:37:12 [second:F3563668-Plant ETP Contribution - Call for evidence Biotech Act.pdf] call OK
13:37:12 [third:F3563668-Plant ETP Contribution - Call for evidence Biotech Act.pdf] waiting 10s before call...
13:37:24 [third:F3563668-Plant ETP Contribution - Call for evidence Biotech Act.pdf] call OK

Processing documents:   6%|▌         | 9/149 [06:40<1:37:49, 41.93s/doc, F3563901-EU Biotech Act Position Paper V1.pdf]

13:37:24 [first:F3563901-EU Biotech Act Position Paper V1.pdf] waiting 10s before call...
13:37:40 [first:F3563901-EU Biotech Act Position Paper V1.pdf] call OK
13:37:40 [second:F3563901-EU Biotech Act Position Paper V1.pdf] waiting 10s before call...
13:37:55 [second:F3563901-EU Biotech Act Position Paper V1.pdf] call OK
13:37:55 [third:F3563901-EU Biotech Act Position Paper V1.pdf] waiting 10s before call...
13:38:07 [third:F3563901-EU Biotech Act Position Paper V1.pdf] call OK

Processing documents:   7%|▋         | 10/149 [07:23<1:37:56, 42.27s/doc, F3563910-Food Fermentation Europe_Biotech Act Call for Evidence, June 2025.docx]

[SAVED] checkpoint with 10 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\brussels_pp_results_checkpoint_20251103_133807.json
13:38:07 [first:F3563910-Food Fermentation Europe_Biotech Act Call for Evidence, June 2025.docx] waiting 10s before call...
13:38:21 [first:F3563910-Food Fermentation Europe_Biotech Act Call for Evidence, June 2025.docx] call OK
13:38:21 [second:F3563910-Food Fermentation Europe_Biotech Act Call for Evidence, June 2025.docx] waiting 10s before call...
13:38:36 [second:F3563910-Food Fermentation Europe_Biotech Act Call for Evidence, June 2025.docx] call OK
13:38:36 [third:F3563910-Food Fermentation Europe_Biotech Act Call for Evidence, June 2025.docx] waiting 10s before call...
13:38:48 [third:F3563910-Food Fermentation Europe_Biotech Act Call for Evidence, June 2025.docx] call OK

Processing documents:   7%|▋         | 11/149 [08:04<1:36:12, 41.83s/doc, F3563929-CFE response to Biotech Act proposal.pdf]

13:38:48 [first:F3563929-CFE response to Biotech Act proposal.pdf] waiting 10s before call...
13:39:03 [first:F3563929-CFE response to Biotech Act proposal.pdf] call OK
13:39:03 [second:F3563929-CFE response to Biotech Act proposal.pdf] waiting 10s before call...
13:39:16 [second:F3563929-CFE response to Biotech Act proposal.pdf] call OK
13:39:16 [third:F3563929-CFE response to Biotech Act proposal.pdf] waiting 10s before call...
13:39:29 [third:F3563929-CFE response to Biotech Act proposal.pdf] call OK

Processing documents:   8%|▊         | 12/149 [08:44<1:34:43, 41.49s/doc, F3564074-GFI-E Call for evidence Biotech act.pdf]

13:39:29 [first:F3564074-GFI-E Call for evidence Biotech act.pdf] waiting 10s before call...
13:39:43 [first:F3564074-GFI-E Call for evidence Biotech act.pdf] call OK
13:39:43 [second:F3564074-GFI-E Call for evidence Biotech act.pdf] waiting 10s before call...
13:39:57 [second:F3564074-GFI-E Call for evidence Biotech act.pdf] call OK
13:39:57 [third:F3564074-GFI-E Call for evidence Biotech act.pdf] waiting 10s before call...
13:40:09 [third:F3564074-GFI-E Call for evidence Biotech act.pdf] call OK

Processing documents:   9%|▊         | 13/149 [09:25<1:33:14, 41.13s/doc, F3564102-EBU_BioTech Act_Submission_June 2025 (1).pdf]

13:40:09 [first:F3564102-EBU_BioTech Act_Submission_June 2025 (1).pdf] waiting 10s before call...
13:40:25 [first:F3564102-EBU_BioTech Act_Submission_June 2025 (1).pdf] call OK
13:40:25 [second:F3564102-EBU_BioTech Act_Submission_June 2025 (1).pdf] waiting 10s before call...
13:40:37 [second:F3564102-EBU_BioTech Act_Submission_June 2025 (1).pdf] call OK
13:40:37 [third:F3564102-EBU_BioTech Act_Submission_June 2025 (1).pdf] waiting 10s before call...
13:40:49 [third:F3564102-EBU_BioTech Act_Submission_June 2025 (1).pdf] call OK

Processing documents:   9%|▉         | 14/149 [10:05<1:31:47, 40.79s/doc, F3564121-BiotechAct_Fraunhofer.pdf]

13:40:49 [first:F3564121-BiotechAct_Fraunhofer.pdf] waiting 10s before call...
13:41:07 [first:F3564121-BiotechAct_Fraunhofer.pdf] call OK
13:41:07 [second:F3564121-BiotechAct_Fraunhofer.pdf] waiting 10s before call...
13:41:20 [second:F3564121-BiotechAct_Fraunhofer.pdf] call OK
13:41:20 [third:F3564121-BiotechAct_Fraunhofer.pdf] waiting 10s before call...
13:41:32 [third:F3564121-BiotechAct_Fraunhofer.pdf] call OK

Processing documents:  10%|█         | 15/149 [10:48<1:32:37, 41.47s/doc, F3564204-Biotech Act_ Luke.pdf]

13:41:32 [first:F3564204-Biotech Act_ Luke.pdf] waiting 10s before call...
13:41:51 [first:F3564204-Biotech Act_ Luke.pdf] call OK
13:41:51 [second:F3564204-Biotech Act_ Luke.pdf] waiting 10s before call...
13:42:03 [second:F3564204-Biotech Act_ Luke.pdf] call OK
13:42:03 [third:F3564204-Biotech Act_ Luke.pdf] waiting 10s before call...
13:42:16 [third:F3564204-Biotech Act_ Luke.pdf] call OK

Processing documents:  11%|█         | 16/149 [11:32<1:33:34, 42.21s/doc, F3564210-Amgen_position paper Biotech Act.pdf]

13:42:16 [first:F3564210-Amgen_position paper Biotech Act.pdf] waiting 10s before call...
13:42:33 [first:F3564210-Amgen_position paper Biotech Act.pdf] call OK
13:42:33 [second:F3564210-Amgen_position paper Biotech Act.pdf] waiting 10s before call...
13:42:49 [second:F3564210-Amgen_position paper Biotech Act.pdf] call OK
13:42:49 [third:F3564210-Amgen_position paper Biotech Act.pdf] waiting 10s before call...
13:43:02 [third:F3564210-Amgen_position paper Biotech Act.pdf] call OK

Processing documents:  11%|█▏        | 17/149 [12:18<1:35:18, 43.32s/doc, F3564218-CAE Position_Biotech Act_Call for Evidence.pdf]

13:43:02 [first:F3564218-CAE Position_Biotech Act_Call for Evidence.pdf] waiting 10s before call...
13:43:23 [first:F3564218-CAE Position_Biotech Act_Call for Evidence.pdf] call OK
13:43:23 [second:F3564218-CAE Position_Biotech Act_Call for Evidence.pdf] waiting 10s before call...
13:43:36 [second:F3564218-CAE Position_Biotech Act_Call for Evidence.pdf] call OK
13:43:36 [third:F3564218-CAE Position_Biotech Act_Call for Evidence.pdf] waiting 10s before call...
13:43:49 [third:F3564218-CAE Position_Biotech Act_Call for Evidence.pdf] call OK

Processing documents:  12%|█▏        | 18/149 [13:04<1:36:51, 44.36s/doc, F3564228-CropLifeEurope_Simplification proposals for GM & Bioppps_.pdf]

13:43:49 [first:F3564228-CropLifeEurope_Simplification proposals for GM & Bioppps_.pdf] waiting 10s before call...
13:44:01 [first:F3564228-CropLifeEurope_Simplification proposals for GM & Bioppps_.pdf] call OK
13:44:01 [second:F3564228-CropLifeEurope_Simplification proposals for GM & Bioppps_.pdf] waiting 10s before call...
13:44:12 [second:F3564228-CropLifeEurope_Simplification proposals for GM & Bioppps_.pdf] call OK
13:44:12 [third:F3564228-CropLifeEurope_Simplification proposals for GM & Bioppps_.pdf] waiting 10s before call...
13:44:24 [third:F3564228-CropLifeEurope_Simplification proposals for GM & Bioppps_.pdf] call OK

Processing documents:  13%|█▎        | 19/149 [13:40<1:30:19, 41.69s/doc, F3564247-2025-06-06 A.I.S.E. feedback to the European Commission Call for Evidence on the Biotech Act .pdf]

13:44:24 [first:F3564247-2025-06-06 A.I.S.E. feedback to the European Commission Call for Evidence on the Biotech Act .pdf] waiting 10s before call...
13:44:42 [first:F3564247-2025-06-06 A.I.S.E. feedback to the European Commission Call for Evidence on the Biotech Act .pdf] call OK
13:44:42 [second:F3564247-2025-06-06 A.I.S.E. feedback to the European Commission Call for Evidence on the Biotech Act .pdf] waiting 10s before call...
13:44:54 [second:F3564247-2025-06-06 A.I.S.E. feedback to the European Commission Call for Evidence on the Biotech Act .pdf] call OK
13:44:54 [third:F3564247-2025-06-06 A.I.S.E. feedback to the European Commission Call for Evidence on the Biotech Act .pdf] waiting 10s before call...
13:45:08 [third:F3564247-2025-06-06 A.I.S.E. feedback to the European Commission Call for Evidence on the Biotech Act .pdf] call OK

Processing documents:  13%|█▎        | 20/149 [14:23<1:30:39, 42.17s/doc, F3564250-BIO Deutschland_ Comments on the EU Biotech Act.pdf]

[SAVED] checkpoint with 20 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\brussels_pp_results_checkpoint_20251103_134508.json
13:45:08 [first:F3564250-BIO Deutschland_ Comments on the EU Biotech Act.pdf] waiting 10s before call...
13:45:24 [first:F3564250-BIO Deutschland_ Comments on the EU Biotech Act.pdf] call OK
13:45:24 [second:F3564250-BIO Deutschland_ Comments on the EU Biotech Act.pdf] waiting 10s before call...
13:45:39 [second:F3564250-BIO Deutschland_ Comments on the EU Biotech Act.pdf] call OK
13:45:39 [third:F3564250-BIO Deutschland_ Comments on the EU Biotech Act.pdf] waiting 10s before call...
13:45:51 [third:F3564250-BIO Deutschland_ Comments on the EU Biotech Act.pdf] call OK

Processing documents:  14%|█▍        | 21/149 [15:06<1:30:46, 42.55s/doc, F3564253-Postion paper Biocontrol.pdf]

13:45:51 [first:F3564253-Postion paper Biocontrol.pdf] waiting 10s before call...
13:46:07 [first:F3564253-Postion paper Biocontrol.pdf] call OK
13:46:07 [second:F3564253-Postion paper Biocontrol.pdf] waiting 10s before call...
13:46:20 [second:F3564253-Postion paper Biocontrol.pdf] call OK
13:46:20 [third:F3564253-Postion paper Biocontrol.pdf] waiting 10s before call...
13:46:32 [third:F3564253-Postion paper Biocontrol.pdf] call OK

Processing documents:  15%|█▍        | 22/149 [15:47<1:28:51, 41.98s/doc, F3564264-ACDV - Contribution Biotech Act.pdf]

13:46:32 [first:F3564264-ACDV - Contribution Biotech Act.pdf] waiting 10s before call...
13:46:50 [first:F3564264-ACDV - Contribution Biotech Act.pdf] call OK
13:46:50 [second:F3564264-ACDV - Contribution Biotech Act.pdf] waiting 10s before call...
13:47:04 [second:F3564264-ACDV - Contribution Biotech Act.pdf] call OK
13:47:04 [third:F3564264-ACDV - Contribution Biotech Act.pdf] waiting 10s before call...
13:47:17 [third:F3564264-ACDV - Contribution Biotech Act.pdf] call OK

Processing documents:  15%|█▌        | 23/149 [16:32<1:29:56, 42.83s/doc, F3564266-Leading, not lagging - putting mental health at the core of Europe s innovation and competitiveness agenda.pdf]

13:47:17 [first:F3564266-Leading, not lagging - putting mental health at the core of Europe s innovation and competitiveness agenda.pdf] waiting 10s before call...
13:47:32 [first:F3564266-Leading, not lagging - putting mental health at the core of Europe s innovation and competitiveness agenda.pdf] call OK
13:47:32 [second:F3564266-Leading, not lagging - putting mental health at the core of Europe s innovation and competitiveness agenda.pdf] waiting 10s before call...
13:47:45 [second:F3564266-Leading, not lagging - putting mental health at the core of Europe s innovation and competitiveness agenda.pdf] call OK
13:47:45 [third:F3564266-Leading, not lagging - putting mental health at the core of Europe s innovation and competitiveness agenda.pdf] waiting 10s before call...
13:47:58 [third:F3564266-Leading, not lagging - putting mental health at the core of Europe s innovation and competitiveness agenda.pdf] call OK

Processing documents:  16%|█▌        | 24/149 [17:13<1:28:23, 42.43s/doc, F3564268-INRAE Contribution to EU Biotech Act_VF.pdf]

13:47:58 [first:F3564268-INRAE Contribution to EU Biotech Act_VF.pdf] waiting 10s before call...
13:48:11 [first:F3564268-INRAE Contribution to EU Biotech Act_VF.pdf] call OK
13:48:11 [second:F3564268-INRAE Contribution to EU Biotech Act_VF.pdf] waiting 10s before call...
13:48:27 [second:F3564268-INRAE Contribution to EU Biotech Act_VF.pdf] call OK
13:48:27 [third:F3564268-INRAE Contribution to EU Biotech Act_VF.pdf] waiting 10s before call...
13:48:43 [third:F3564268-INRAE Contribution to EU Biotech Act_VF.pdf] call OK

Processing documents:  17%|█▋        | 25/149 [17:58<1:29:08, 43.14s/doc, F3564270-25_EU_11.pdf]

13:48:43 [first:F3564270-25_EU_11.pdf] waiting 10s before call...
13:48:57 [first:F3564270-25_EU_11.pdf] call OK
13:48:57 [second:F3564270-25_EU_11.pdf] waiting 10s before call...
13:49:10 [second:F3564270-25_EU_11.pdf] call OK
13:49:10 [third:F3564270-25_EU_11.pdf] waiting 10s before call...
13:49:22 [third:F3564270-25_EU_11.pdf] call OK

Processing documents:  17%|█▋        | 26/149 [18:37<1:26:01, 41.96s/doc, F3564380-Biotech Act open consultation DSW 2025.pdf]

13:49:22 [first:F3564380-Biotech Act open consultation DSW 2025.pdf] waiting 10s before call...
13:49:38 [first:F3564380-Biotech Act open consultation DSW 2025.pdf] call OK
13:49:38 [second:F3564380-Biotech Act open consultation DSW 2025.pdf] waiting 10s before call...
13:49:50 [second:F3564380-Biotech Act open consultation DSW 2025.pdf] call OK
13:49:50 [third:F3564380-Biotech Act open consultation DSW 2025.pdf] waiting 10s before call...
13:50:04 [third:F3564380-Biotech Act open consultation DSW 2025.pdf] call OK

Processing documents:  18%|█▊        | 27/149 [19:19<1:25:09, 41.88s/doc, F3564435-VK_Akt o biotechnologiích_CZ_.docx]

13:50:04 [first:F3564435-VK_Akt o biotechnologiích_CZ_.docx] waiting 10s before call...
13:50:16 [first:F3564435-VK_Akt o biotechnologiích_CZ_.docx] call OK
13:50:16 [second:F3564435-VK_Akt o biotechnologiích_CZ_.docx] waiting 10s before call...
13:50:29 [second:F3564435-VK_Akt o biotechnologiích_CZ_.docx] call OK
13:50:29 [third:F3564435-VK_Akt o biotechnologiích_CZ_.docx] waiting 10s before call...
13:50:43 [third:F3564435-VK_Akt o biotechnologiích_CZ_.docx] call OK

Processing documents:  19%|█▉        | 28/149 [19:58<1:22:48, 41.06s/doc, F3564477-MBB Biotech Act Call for Evidence_June 2025.pdf]

13:50:43 [first:F3564477-MBB Biotech Act Call for Evidence_June 2025.pdf] waiting 10s before call...
13:50:55 [first:F3564477-MBB Biotech Act Call for Evidence_June 2025.pdf] call OK
13:50:55 [second:F3564477-MBB Biotech Act Call for Evidence_June 2025.pdf] waiting 10s before call...
13:51:07 [second:F3564477-MBB Biotech Act Call for Evidence_June 2025.pdf] call OK
13:51:07 [third:F3564477-MBB Biotech Act Call for Evidence_June 2025.pdf] waiting 10s before call...
13:51:19 [third:F3564477-MBB Biotech Act Call for Evidence_June 2025.pdf] call OK

Processing documents:  19%|█▉        | 29/149 [20:34<1:19:10, 39.59s/doc, F3564478-20250609_Biotech Act consultation - SPRING.pdf]

13:51:19 [first:F3564478-20250609_Biotech Act consultation - SPRING.pdf] waiting 10s before call...
13:51:34 [first:F3564478-20250609_Biotech Act consultation - SPRING.pdf] call OK
13:51:34 [second:F3564478-20250609_Biotech Act consultation - SPRING.pdf] waiting 10s before call...
13:51:47 [second:F3564478-20250609_Biotech Act consultation - SPRING.pdf] call OK
13:51:47 [third:F3564478-20250609_Biotech Act consultation - SPRING.pdf] waiting 10s before call...
13:51:59 [third:F3564478-20250609_Biotech Act consultation - SPRING.pdf] call OK

Processing documents:  20%|██        | 30/149 [21:15<1:18:49, 39.75s/doc, F3564488-MediQuills_Response_to_EU's_Biotech_Act.pdf]

[SAVED] checkpoint with 30 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\brussels_pp_results_checkpoint_20251103_135159.json
13:51:59 [first:F3564488-MediQuills_Response_to_EU's_Biotech_Act.pdf] waiting 10s before call...
13:52:15 [first:F3564488-MediQuills_Response_to_EU's_Biotech_Act.pdf] call OK
13:52:15 [second:F3564488-MediQuills_Response_to_EU's_Biotech_Act.pdf] waiting 10s before call...
13:52:30 [second:F3564488-MediQuills_Response_to_EU's_Biotech_Act.pdf] call OK
13:52:30 [third:F3564488-MediQuills_Response_to_EU's_Biotech_Act.pdf] waiting 10s before call...
13:52:43 [third:F3564488-MediQuills_Response_to_EU's_Biotech_Act.pdf] call OK

Processing documents:  21%|██        | 31/149 [21:59<1:20:46, 41.07s/doc, F3564504-250410 respuesta MAPA EUSurvey - Survey.pdf]

13:52:43 [first:F3564504-250410 respuesta MAPA EUSurvey - Survey.pdf] waiting 10s before call...
13:53:04 [first:F3564504-250410 respuesta MAPA EUSurvey - Survey.pdf] call OK
13:53:04 [second:F3564504-250410 respuesta MAPA EUSurvey - Survey.pdf] waiting 10s before call...
13:53:16 [second:F3564504-250410 respuesta MAPA EUSurvey - Survey.pdf] call OK
13:53:16 [third:F3564504-250410 respuesta MAPA EUSurvey - Survey.pdf] waiting 10s before call...
13:53:28 [third:F3564504-250410 respuesta MAPA EUSurvey - Survey.pdf] call OK

Processing documents:  21%|██▏       | 32/149 [22:44<1:22:27, 42.29s/doc, F3564682-Reco EU biotech EWPA EWPM 10.06.2025.pdf]

13:53:28 [first:F3564682-Reco EU biotech EWPA EWPM 10.06.2025.pdf] waiting 10s before call...
13:53:43 [first:F3564682-Reco EU biotech EWPA EWPM 10.06.2025.pdf] call OK
13:53:43 [second:F3564682-Reco EU biotech EWPA EWPM 10.06.2025.pdf] waiting 10s before call...
13:53:54 [second:F3564682-Reco EU biotech EWPA EWPM 10.06.2025.pdf] call OK
13:53:54 [third:F3564682-Reco EU biotech EWPA EWPM 10.06.2025.pdf] waiting 10s before call...
13:54:06 [third:F3564682-Reco EU biotech EWPA EWPM 10.06.2025.pdf] call OK

Processing documents:  22%|██▏       | 33/149 [23:22<1:19:11, 40.96s/doc, F3564687-Biotech Act June 2025 _FoodDrinkEurope Feedback.pdf]

13:54:06 [first:F3564687-Biotech Act June 2025 _FoodDrinkEurope Feedback.pdf] waiting 10s before call...
13:54:23 [first:F3564687-Biotech Act June 2025 _FoodDrinkEurope Feedback.pdf] call OK
13:54:23 [second:F3564687-Biotech Act June 2025 _FoodDrinkEurope Feedback.pdf] waiting 10s before call...
13:54:35 [second:F3564687-Biotech Act June 2025 _FoodDrinkEurope Feedback.pdf] call OK
13:54:35 [third:F3564687-Biotech Act June 2025 _FoodDrinkEurope Feedback.pdf] waiting 10s before call...
13:54:47 [third:F3564687-Biotech Act June 2025 _FoodDrinkEurope Feedback.pdf] call OK

Processing documents:  23%|██▎       | 34/149 [24:03<1:18:32, 40.98s/doc, F3564728-ESMO Response - Biotech Act.pdf]

13:54:47 [first:F3564728-ESMO Response - Biotech Act.pdf] waiting 10s before call...
13:55:03 [first:F3564728-ESMO Response - Biotech Act.pdf] call OK
13:55:03 [second:F3564728-ESMO Response - Biotech Act.pdf] waiting 10s before call...
13:55:14 [second:F3564728-ESMO Response - Biotech Act.pdf] call OK
13:55:14 [third:F3564728-ESMO Response - Biotech Act.pdf] waiting 10s before call...
13:55:27 [third:F3564728-ESMO Response - Biotech Act.pdf] call OK

Processing documents:  23%|██▎       | 35/149 [24:42<1:16:52, 40.46s/doc, F3564760-250610_Hollandbio_input_CfE_BiotechAct.pdf]

13:55:27 [first:F3564760-250610_Hollandbio_input_CfE_BiotechAct.pdf] waiting 10s before call...
13:55:43 [first:F3564760-250610_Hollandbio_input_CfE_BiotechAct.pdf] call OK
13:55:43 [second:F3564760-250610_Hollandbio_input_CfE_BiotechAct.pdf] waiting 10s before call...
13:55:56 [second:F3564760-250610_Hollandbio_input_CfE_BiotechAct.pdf] call OK
13:55:56 [third:F3564760-250610_Hollandbio_input_CfE_BiotechAct.pdf] waiting 10s before call...
13:56:10 [third:F3564760-250610_Hollandbio_input_CfE_BiotechAct.pdf] call OK

Processing documents:  24%|██▍       | 36/149 [25:26<1:18:00, 41.42s/doc, F3564769-Written Contribution EFfCI -Biotech Act (1).pdf]

13:56:10 [first:F3564769-Written Contribution EFfCI -Biotech Act (1).pdf] waiting 10s before call...
13:56:27 [first:F3564769-Written Contribution EFfCI -Biotech Act (1).pdf] call OK
13:56:27 [second:F3564769-Written Contribution EFfCI -Biotech Act (1).pdf] waiting 10s before call...
13:56:41 [second:F3564769-Written Contribution EFfCI -Biotech Act (1).pdf] call OK
13:56:41 [third:F3564769-Written Contribution EFfCI -Biotech Act (1).pdf] waiting 10s before call...
13:56:55 [third:F3564769-Written Contribution EFfCI -Biotech Act (1).pdf] call OK

Processing documents:  25%|██▍       | 37/149 [26:10<1:18:57, 42.30s/doc, F3564784-QbD Group Feedback on EU Biotech Act.pdf]

13:56:55 [first:F3564784-QbD Group Feedback on EU Biotech Act.pdf] waiting 10s before call...
13:57:08 [first:F3564784-QbD Group Feedback on EU Biotech Act.pdf] call OK
13:57:08 [second:F3564784-QbD Group Feedback on EU Biotech Act.pdf] waiting 10s before call...
13:57:20 [second:F3564784-QbD Group Feedback on EU Biotech Act.pdf] call OK
13:57:20 [third:F3564784-QbD Group Feedback on EU Biotech Act.pdf] waiting 10s before call...
13:57:33 [third:F3564784-QbD Group Feedback on EU Biotech Act.pdf] call OK

Processing documents:  26%|██▌       | 38/149 [26:48<1:15:54, 41.03s/doc, F3564813-Reviews and position papers_Annex.docx]

13:57:33 [first:F3564813-Reviews and position papers_Annex.docx] waiting 10s before call...
13:57:47 [first:F3564813-Reviews and position papers_Annex.docx] call OK
13:57:47 [second:F3564813-Reviews and position papers_Annex.docx] waiting 10s before call...
13:57:59 [second:F3564813-Reviews and position papers_Annex.docx] call OK
13:57:59 [third:F3564813-Reviews and position papers_Annex.docx] waiting 10s before call...
13:58:10 [third:F3564813-Reviews and position papers_Annex.docx] call OK

Processing documents:  26%|██▌       | 39/149 [27:26<1:13:26, 40.06s/doc, F3564816-250610 ANOVE Comentarios Biotech Act.pdf]

13:58:10 [first:F3564816-250610 ANOVE Comentarios Biotech Act.pdf] waiting 10s before call...
13:58:29 [first:F3564816-250610 ANOVE Comentarios Biotech Act.pdf] call OK
13:58:29 [second:F3564816-250610 ANOVE Comentarios Biotech Act.pdf] waiting 10s before call...
13:58:41 [second:F3564816-250610 ANOVE Comentarios Biotech Act.pdf] call OK
13:58:41 [third:F3564816-250610 ANOVE Comentarios Biotech Act.pdf] waiting 10s before call...
13:58:53 [third:F3564816-250610 ANOVE Comentarios Biotech Act.pdf] call OK

Processing documents:  27%|██▋       | 40/149 [28:09<1:14:13, 40.85s/doc, F3564818-FINAL_EuropaBio Position EU Biotech Act_10062025.pdf]

[SAVED] checkpoint with 40 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\brussels_pp_results_checkpoint_20251103_135853.json
13:58:53 [first:F3564818-FINAL_EuropaBio Position EU Biotech Act_10062025.pdf] waiting 10s before call...
13:59:11 [first:F3564818-FINAL_EuropaBio Position EU Biotech Act_10062025.pdf] call OK
13:59:11 [second:F3564818-FINAL_EuropaBio Position EU Biotech Act_10062025.pdf] waiting 10s before call...
13:59:26 [second:F3564818-FINAL_EuropaBio Position EU Biotech Act_10062025.pdf] call OK
13:59:26 [third:F3564818-FINAL_EuropaBio Position EU Biotech Act_10062025.pdf] waiting 10s before call...
13:59:42 [third:F3564818-FINAL_EuropaBio Position EU Biotech Act_10062025.pdf] call OK

Processing documents:  28%|██▊       | 41/149 [28:57<1:17:44, 43.19s/doc, F3564833-EHA recommendations - Biotech Act.pdf]

13:59:42 [first:F3564833-EHA recommendations - Biotech Act.pdf] waiting 10s before call...
13:59:56 [first:F3564833-EHA recommendations - Biotech Act.pdf] call OK
13:59:56 [second:F3564833-EHA recommendations - Biotech Act.pdf] waiting 10s before call...
14:00:08 [second:F3564833-EHA recommendations - Biotech Act.pdf] call OK
14:00:08 [third:F3564833-EHA recommendations - Biotech Act.pdf] waiting 10s before call...
14:00:20 [third:F3564833-EHA recommendations - Biotech Act.pdf] call OK

Processing documents:  28%|██▊       | 42/149 [29:36<1:14:34, 41.81s/doc, F3564836-20250610 AseBio response Biotech Act.pdf]

14:00:20 [first:F3564836-20250610 AseBio response Biotech Act.pdf] waiting 10s before call...
14:00:38 [first:F3564836-20250610 AseBio response Biotech Act.pdf] call OK
14:00:38 [second:F3564836-20250610 AseBio response Biotech Act.pdf] waiting 10s before call...
14:00:51 [second:F3564836-20250610 AseBio response Biotech Act.pdf] call OK
14:00:51 [third:F3564836-20250610 AseBio response Biotech Act.pdf] waiting 10s before call...
14:01:04 [third:F3564836-20250610 AseBio response Biotech Act.pdf] call OK

Processing documents:  29%|██▉       | 43/149 [30:19<1:14:44, 42.30s/doc, F3564841-20250610 Biovia - Call for evidence - EU Biotech Act.pdf]

14:01:04 [first:F3564841-20250610 Biovia - Call for evidence - EU Biotech Act.pdf] waiting 10s before call...
14:01:22 [first:F3564841-20250610 Biovia - Call for evidence - EU Biotech Act.pdf] call OK
14:01:22 [second:F3564841-20250610 Biovia - Call for evidence - EU Biotech Act.pdf] waiting 10s before call...
14:01:36 [second:F3564841-20250610 Biovia - Call for evidence - EU Biotech Act.pdf] call OK
14:01:36 [third:F3564841-20250610 Biovia - Call for evidence - EU Biotech Act.pdf] waiting 10s before call...
14:01:49 [third:F3564841-20250610 Biovia - Call for evidence - EU Biotech Act.pdf] call OK

Processing documents:  30%|██▉       | 44/149 [31:04<1:15:28, 43.13s/doc, F3564842-EU Biotech  Act_EC Public Consultation_HIPRA.docx]

14:01:49 [first:F3564842-EU Biotech  Act_EC Public Consultation_HIPRA.docx] waiting 10s before call...
14:02:02 [first:F3564842-EU Biotech  Act_EC Public Consultation_HIPRA.docx] call OK
14:02:02 [second:F3564842-EU Biotech  Act_EC Public Consultation_HIPRA.docx] waiting 10s before call...
14:02:15 [second:F3564842-EU Biotech  Act_EC Public Consultation_HIPRA.docx] call OK
14:02:15 [third:F3564842-EU Biotech  Act_EC Public Consultation_HIPRA.docx] waiting 10s before call...
14:02:27 [third:F3564842-EU Biotech  Act_EC Public Consultation_HIPRA.docx] call OK

Processing documents:  30%|███       | 45/149 [31:43<1:12:20, 41.74s/doc, F3564843-ARM Call for Evidence Response Biotech Act.pdf]

14:02:27 [first:F3564843-ARM Call for Evidence Response Biotech Act.pdf] waiting 10s before call...
14:02:44 [first:F3564843-ARM Call for Evidence Response Biotech Act.pdf] call OK
14:02:44 [second:F3564843-ARM Call for Evidence Response Biotech Act.pdf] waiting 10s before call...
14:02:58 [second:F3564843-ARM Call for Evidence Response Biotech Act.pdf] call OK
14:02:58 [third:F3564843-ARM Call for Evidence Response Biotech Act.pdf] waiting 10s before call...
14:03:10 [third:F3564843-ARM Call for Evidence Response Biotech Act.pdf] call OK

Processing documents:  31%|███       | 46/149 [32:26<1:12:11, 42.05s/doc, F3564846-2025_06_11_Call for evidence Biotech Act_CNRS.pdf]

14:03:10 [first:F3564846-2025_06_11_Call for evidence Biotech Act_CNRS.pdf] waiting 10s before call...
14:03:30 [first:F3564846-2025_06_11_Call for evidence Biotech Act_CNRS.pdf] call OK
14:03:30 [second:F3564846-2025_06_11_Call for evidence Biotech Act_CNRS.pdf] waiting 10s before call...
14:03:46 [second:F3564846-2025_06_11_Call for evidence Biotech Act_CNRS.pdf] call OK
14:03:46 [third:F3564846-2025_06_11_Call for evidence Biotech Act_CNRS.pdf] waiting 10s before call...
14:03:58 [third:F3564846-2025_06_11_Call for evidence Biotech Act_CNRS.pdf] call OK

Processing documents:  32%|███▏      | 47/149 [33:13<1:14:27, 43.80s/doc, F3564851-2025-023 EPF Response to the Call for Evidence on the European Biotech Act.pdf]

14:03:58 [first:F3564851-2025-023 EPF Response to the Call for Evidence on the European Biotech Act.pdf] waiting 10s before call...
14:04:13 [first:F3564851-2025-023 EPF Response to the Call for Evidence on the European Biotech Act.pdf] call OK
14:04:13 [second:F3564851-2025-023 EPF Response to the Call for Evidence on the European Biotech Act.pdf] waiting 10s before call...
14:04:26 [second:F3564851-2025-023 EPF Response to the Call for Evidence on the European Biotech Act.pdf] call OK
14:04:26 [third:F3564851-2025-023 EPF Response to the Call for Evidence on the European Biotech Act.pdf] waiting 10s before call...
14:04:38 [third:F3564851-2025-023 EPF Response to the Call for Evidence on the European Biotech Act.pdf] call OK

Processing documents:  32%|███▏      | 48/149 [33:53<1:11:41, 42.59s/doc, F3564862-J&J Placing the life science sector at the core of the Competitiveness Compass_FINAL.pdf]

14:04:38 [first:F3564862-J&J Placing the life science sector at the core of the Competitiveness Compass_FINAL.pdf] waiting 10s before call...
14:04:54 [first:F3564862-J&J Placing the life science sector at the core of the Competitiveness Compass_FINAL.pdf] call OK
14:04:54 [second:F3564862-J&J Placing the life science sector at the core of the Competitiveness Compass_FINAL.pdf] waiting 10s before call...
14:05:08 [second:F3564862-J&J Placing the life science sector at the core of the Competitiveness Compass_FINAL.pdf] call OK
14:05:08 [third:F3564862-J&J Placing the life science sector at the core of the Competitiveness Compass_FINAL.pdf] waiting 10s before call...
14:05:21 [third:F3564862-J&J Placing the life science sector at the core of the Competitiveness Compass_FINAL.pdf] call OK

Processing documents:  33%|███▎      | 49/149 [34:36<1:11:12, 42.72s/doc, F3564899-Biotech act_Klaudia Kozusznik_A4BEE.pdf]

14:05:21 [first:F3564899-Biotech act_Klaudia Kozusznik_A4BEE.pdf] waiting 10s before call...
14:05:35 [first:F3564899-Biotech act_Klaudia Kozusznik_A4BEE.pdf] call OK
14:05:35 [second:F3564899-Biotech act_Klaudia Kozusznik_A4BEE.pdf] waiting 10s before call...
14:05:49 [second:F3564899-Biotech act_Klaudia Kozusznik_A4BEE.pdf] call OK
14:05:49 [third:F3564899-Biotech act_Klaudia Kozusznik_A4BEE.pdf] waiting 10s before call...
14:06:02 [third:F3564899-Biotech act_Klaudia Kozusznik_A4BEE.pdf] call OK

Processing documents:  34%|███▎      | 50/149 [35:18<1:09:51, 42.33s/doc, F3564900-June 2025 _ Contribution AFE _ Biotech Act.docx]

[SAVED] checkpoint with 50 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\brussels_pp_results_checkpoint_20251103_140602.json
14:06:02 [first:F3564900-June 2025 _ Contribution AFE _ Biotech Act.docx] waiting 10s before call...
14:06:18 [first:F3564900-June 2025 _ Contribution AFE _ Biotech Act.docx] call OK
14:06:18 [second:F3564900-June 2025 _ Contribution AFE _ Biotech Act.docx] waiting 10s before call...
14:06:33 [second:F3564900-June 2025 _ Contribution AFE _ Biotech Act.docx] call OK
14:06:33 [third:F3564900-June 2025 _ Contribution AFE _ Biotech Act.docx] waiting 10s before call...
14:06:47 [third:F3564900-June 2025 _ Contribution AFE _ Biotech Act.docx] call OK

Processing documents:  34%|███▍      | 51/149 [36:02<1:10:06, 42.93s/doc, F3564901-GSK contribution for the Call for Evidence, Biotech Act, 10 June 2025.pdf]

14:06:47 [first:F3564901-GSK contribution for the Call for Evidence, Biotech Act, 10 June 2025.pdf] waiting 10s before call...
14:07:03 [first:F3564901-GSK contribution for the Call for Evidence, Biotech Act, 10 June 2025.pdf] call OK
14:07:03 [second:F3564901-GSK contribution for the Call for Evidence, Biotech Act, 10 June 2025.pdf] waiting 10s before call...
14:07:16 [second:F3564901-GSK contribution for the Call for Evidence, Biotech Act, 10 June 2025.pdf] call OK
14:07:16 [third:F3564901-GSK contribution for the Call for Evidence, Biotech Act, 10 June 2025.pdf] waiting 10s before call...
14:07:32 [third:F3564901-GSK contribution for the Call for Evidence, Biotech Act, 10 June 2025.pdf] call OK

Processing documents:  35%|███▍      | 52/149 [36:47<1:10:25, 43.56s/doc, F3564912-ACRO FINAL Comment - Biotech Act Call for Evidence.docx]

14:07:32 [first:F3564912-ACRO FINAL Comment - Biotech Act Call for Evidence.docx] waiting 10s before call...
14:07:51 [first:F3564912-ACRO FINAL Comment - Biotech Act Call for Evidence.docx] call OK
14:07:51 [second:F3564912-ACRO FINAL Comment - Biotech Act Call for Evidence.docx] waiting 10s before call...
14:08:05 [second:F3564912-ACRO FINAL Comment - Biotech Act Call for Evidence.docx] call OK
14:08:05 [third:F3564912-ACRO FINAL Comment - Biotech Act Call for Evidence.docx] waiting 10s before call...
14:08:20 [third:F3564912-ACRO FINAL Comment - Biotech Act Call for Evidence.docx] call OK

Processing documents:  36%|███▌      | 53/149 [37:35<1:11:58, 44.99s/doc, F3564918-EU Biotech submission.docx]

14:08:20 [first:F3564918-EU Biotech submission.docx] waiting 10s before call...
14:08:36 [first:F3564918-EU Biotech submission.docx] call OK
14:08:36 [second:F3564918-EU Biotech submission.docx] waiting 10s before call...
14:08:50 [second:F3564918-EU Biotech submission.docx] call OK
14:08:50 [third:F3564918-EU Biotech submission.docx] waiting 10s before call...
14:09:07 [third:F3564918-EU Biotech submission.docx] call OK

Processing documents:  36%|███▌      | 54/149 [38:22<1:12:01, 45.49s/doc, F3564919-Pandemic Action Network response to the EU Biotech Act call for evidence_1006225.pdf]

14:09:07 [first:F3564919-Pandemic Action Network response to the EU Biotech Act call for evidence_1006225.pdf] waiting 10s before call...
14:09:21 [first:F3564919-Pandemic Action Network response to the EU Biotech Act call for evidence_1006225.pdf] call OK
14:09:21 [second:F3564919-Pandemic Action Network response to the EU Biotech Act call for evidence_1006225.pdf] waiting 10s before call...
14:09:33 [second:F3564919-Pandemic Action Network response to the EU Biotech Act call for evidence_1006225.pdf] call OK
14:09:33 [third:F3564919-Pandemic Action Network response to the EU Biotech Act call for evidence_1006225.pdf] waiting 10s before call...
14:09:50 [third:F3564919-Pandemic Action Network response to the EU Biotech Act call for evidence_1006225.pdf] call OK

Processing documents:  37%|███▋      | 55/149 [39:05<1:10:13, 44.82s/doc, F3564930-25.0367.2 - Biotech Act - Euroseeds input to call for evidence.pdf]

14:09:50 [first:F3564930-25.0367.2 - Biotech Act - Euroseeds input to call for evidence.pdf] waiting 10s before call...
14:10:06 [first:F3564930-25.0367.2 - Biotech Act - Euroseeds input to call for evidence.pdf] call OK
14:10:06 [second:F3564930-25.0367.2 - Biotech Act - Euroseeds input to call for evidence.pdf] waiting 10s before call...
14:10:20 [second:F3564930-25.0367.2 - Biotech Act - Euroseeds input to call for evidence.pdf] call OK
14:10:20 [third:F3564930-25.0367.2 - Biotech Act - Euroseeds input to call for evidence.pdf] waiting 10s before call...
14:10:32 [third:F3564930-25.0367.2 - Biotech Act - Euroseeds input to call for evidence.pdf] call OK

Processing documents:  38%|███▊      | 56/149 [39:47<1:08:09, 43.97s/doc, F3564965-RD Moonshot_Contribution to the consultation EU Biotech Act_FINAL.pdf]

14:10:32 [first:F3564965-RD Moonshot_Contribution to the consultation EU Biotech Act_FINAL.pdf] waiting 10s before call...
14:10:50 [first:F3564965-RD Moonshot_Contribution to the consultation EU Biotech Act_FINAL.pdf] call OK
14:10:50 [second:F3564965-RD Moonshot_Contribution to the consultation EU Biotech Act_FINAL.pdf] waiting 10s before call...
14:11:05 [second:F3564965-RD Moonshot_Contribution to the consultation EU Biotech Act_FINAL.pdf] call OK
14:11:05 [third:F3564965-RD Moonshot_Contribution to the consultation EU Biotech Act_FINAL.pdf] waiting 10s before call...
14:11:18 [third:F3564965-RD Moonshot_Contribution to the consultation EU Biotech Act_FINAL.pdf] call OK

Processing documents:  38%|███▊      | 57/149 [40:33<1:08:13, 44.49s/doc, F3564967-Call for Evidence Biotech Act.pdf]

14:11:18 [first:F3564967-Call for Evidence Biotech Act.pdf] waiting 10s before call...
14:11:43 [first:F3564967-Call for Evidence Biotech Act.pdf] call OK
14:11:43 [second:F3564967-Call for Evidence Biotech Act.pdf] waiting 10s before call...
14:12:01 [second:F3564967-Call for Evidence Biotech Act.pdf] call OK
14:12:01 [third:F3564967-Call for Evidence Biotech Act.pdf] waiting 10s before call...
14:12:17 [third:F3564967-Call for Evidence Biotech Act.pdf] call OK

Processing documents:  39%|███▉      | 58/149 [41:32<1:14:04, 48.84s/doc, F3564970-EU BioTech act_VTT messages.pdf]

14:12:17 [first:F3564970-EU BioTech act_VTT messages.pdf] waiting 10s before call...
14:12:32 [first:F3564970-EU BioTech act_VTT messages.pdf] call OK
14:12:32 [second:F3564970-EU BioTech act_VTT messages.pdf] waiting 10s before call...
14:12:52 [second:F3564970-EU BioTech act_VTT messages.pdf] call OK
14:12:52 [third:F3564970-EU BioTech act_VTT messages.pdf] waiting 10s before call...
14:13:06 [third:F3564970-EU BioTech act_VTT messages.pdf] call OK

Processing documents:  40%|███▉      | 59/149 [42:21<1:13:26, 48.96s/doc, F3564976-2025_biotech consultation.docx]

14:13:06 [first:F3564976-2025_biotech consultation.docx] waiting 10s before call...
14:13:21 [first:F3564976-2025_biotech consultation.docx] call OK
14:13:21 [second:F3564976-2025_biotech consultation.docx] waiting 10s before call...
14:13:34 [second:F3564976-2025_biotech consultation.docx] call OK
14:13:34 [third:F3564976-2025_biotech consultation.docx] waiting 10s before call...
14:13:48 [third:F3564976-2025_biotech consultation.docx] call OK

Processing documents:  40%|████      | 60/149 [43:03<1:09:36, 46.92s/doc, F3564981-Submission for EU Biotech Act Call for Evidence_Pour Demain Europe.pdf]

[SAVED] checkpoint with 60 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\brussels_pp_results_checkpoint_20251103_141348.json
14:13:48 [first:F3564981-Submission for EU Biotech Act Call for Evidence_Pour Demain Europe.pdf] waiting 10s before call...
14:14:01 [first:F3564981-Submission for EU Biotech Act Call for Evidence_Pour Demain Europe.pdf] call OK
14:14:01 [second:F3564981-Submission for EU Biotech Act Call for Evidence_Pour Demain Europe.pdf] waiting 10s before call...
14:14:14 [second:F3564981-Submission for EU Biotech Act Call for Evidence_Pour Demain Europe.pdf] call OK
14:14:14 [third:F3564981-Submission for EU Biotech Act Call for Evidence_Pour Demain Europe.pdf] waiting 10s before call...
14:14:33 [third:F3564981-Submission for EU Biotech Act Call for Evidence_Pour Demain Europe.pdf] call OK

Processing documents:  41%|████      | 61/149 [43:48<1:07:59, 46.36s/doc, F3564997-ErVimmune - Réflexions sur le financement des biotech UE ENG 10062025 .pdf]

14:14:33 [first:F3564997-ErVimmune - Réflexions sur le financement des biotech UE ENG 10062025 .pdf] waiting 10s before call...
14:14:52 [first:F3564997-ErVimmune - Réflexions sur le financement des biotech UE ENG 10062025 .pdf] call OK
14:14:52 [second:F3564997-ErVimmune - Réflexions sur le financement des biotech UE ENG 10062025 .pdf] waiting 10s before call...
14:15:06 [second:F3564997-ErVimmune - Réflexions sur le financement des biotech UE ENG 10062025 .pdf] call OK
14:15:06 [third:F3564997-ErVimmune - Réflexions sur le financement des biotech UE ENG 10062025 .pdf] waiting 10s before call...
14:15:18 [third:F3564997-ErVimmune - Réflexions sur le financement des biotech UE ENG 10062025 .pdf] call OK

Processing documents:  42%|████▏     | 62/149 [44:33<1:06:39, 45.97s/doc, F3564998-EPF’s response to the Call for evidence on the EU Biotect Act.pdf]

14:15:18 [first:F3564998-EPF’s response to the Call for evidence on the EU Biotect Act.pdf] waiting 10s before call...
14:15:31 [first:F3564998-EPF’s response to the Call for evidence on the EU Biotect Act.pdf] call OK
14:15:31 [second:F3564998-EPF’s response to the Call for evidence on the EU Biotect Act.pdf] waiting 10s before call...
14:15:43 [second:F3564998-EPF’s response to the Call for evidence on the EU Biotect Act.pdf] call OK
14:15:43 [third:F3564998-EPF’s response to the Call for evidence on the EU Biotect Act.pdf] waiting 10s before call...
14:15:55 [third:F3564998-EPF’s response to the Call for evidence on the EU Biotect Act.pdf] call OK

Processing documents:  42%|████▏     | 63/149 [45:10<1:01:52, 43.16s/doc, F3565010-EFPIA Annex_BioTech Act_Call for evidence_Final.pdf]

14:15:55 [first:F3565010-EFPIA Annex_BioTech Act_Call for evidence_Final.pdf] waiting 10s before call...
14:16:09 [first:F3565010-EFPIA Annex_BioTech Act_Call for evidence_Final.pdf] call OK
14:16:09 [second:F3565010-EFPIA Annex_BioTech Act_Call for evidence_Final.pdf] waiting 10s before call...
14:16:23 [second:F3565010-EFPIA Annex_BioTech Act_Call for evidence_Final.pdf] call OK
14:16:23 [third:F3565010-EFPIA Annex_BioTech Act_Call for evidence_Final.pdf] waiting 10s before call...
14:16:37 [third:F3565010-EFPIA Annex_BioTech Act_Call for evidence_Final.pdf] call OK

Processing documents:  43%|████▎     | 64/149 [45:52<1:00:35, 42.77s/doc, F3565025-Joint HNP Position Paper Biotechnology mrt 2024.pdf]

14:16:37 [first:F3565025-Joint HNP Position Paper Biotechnology mrt 2024.pdf] waiting 10s before call...
14:16:50 [first:F3565025-Joint HNP Position Paper Biotechnology mrt 2024.pdf] call OK
14:16:50 [second:F3565025-Joint HNP Position Paper Biotechnology mrt 2024.pdf] waiting 10s before call...
14:17:02 [second:F3565025-Joint HNP Position Paper Biotechnology mrt 2024.pdf] call OK
14:17:02 [third:F3565025-Joint HNP Position Paper Biotechnology mrt 2024.pdf] waiting 10s before call...
14:17:14 [third:F3565025-Joint HNP Position Paper Biotechnology mrt 2024.pdf] call OK

Processing documents:  44%|████▎     | 65/149 [46:29<57:40, 41.19s/doc, F3565034-20250611- CNCPI- contribution European Biotech Act .pdf]

14:17:14 [first:F3565034-20250611- CNCPI- contribution European Biotech Act .pdf] waiting 10s before call...
14:17:31 [first:F3565034-20250611- CNCPI- contribution European Biotech Act .pdf] call OK
14:17:31 [second:F3565034-20250611- CNCPI- contribution European Biotech Act .pdf] waiting 10s before call...
14:17:45 [second:F3565034-20250611- CNCPI- contribution European Biotech Act .pdf] call OK
14:17:45 [third:F3565034-20250611- CNCPI- contribution European Biotech Act .pdf] waiting 10s before call...
14:17:57 [third:F3565034-20250611- CNCPI- contribution European Biotech Act .pdf] call OK

Processing documents:  44%|████▍     | 66/149 [47:12<57:32, 41.59s/doc, F3565040-bioMerieux contribution_EU Biotech Act.pdf]

14:17:57 [first:F3565040-bioMerieux contribution_EU Biotech Act.pdf] waiting 10s before call...
14:18:10 [first:F3565040-bioMerieux contribution_EU Biotech Act.pdf] call OK
14:18:10 [second:F3565040-bioMerieux contribution_EU Biotech Act.pdf] waiting 10s before call...
14:18:24 [second:F3565040-bioMerieux contribution_EU Biotech Act.pdf] call OK
14:18:24 [third:F3565040-bioMerieux contribution_EU Biotech Act.pdf] waiting 10s before call...
14:18:37 [third:F3565040-bioMerieux contribution_EU Biotech Act.pdf] call OK

Processing documents:  45%|████▍     | 67/149 [47:52<56:10, 41.11s/doc, F3565042-Cepi response to Call for Evidence_Biotech Act.pdf]

14:18:37 [first:F3565042-Cepi response to Call for Evidence_Biotech Act.pdf] waiting 10s before call...
14:18:50 [first:F3565042-Cepi response to Call for Evidence_Biotech Act.pdf] call OK
14:18:50 [second:F3565042-Cepi response to Call for Evidence_Biotech Act.pdf] waiting 10s before call...
14:19:04 [second:F3565042-Cepi response to Call for Evidence_Biotech Act.pdf] call OK
14:19:04 [third:F3565042-Cepi response to Call for Evidence_Biotech Act.pdf] waiting 10s before call...
14:19:16 [third:F3565042-Cepi response to Call for Evidence_Biotech Act.pdf] call OK

Processing documents:  46%|████▌     | 68/149 [48:31<54:40, 40.51s/doc, F3565064-EUCOPE_Proposals Biotech Act_final_Jun25.pdf]

14:19:16 [first:F3565064-EUCOPE_Proposals Biotech Act_final_Jun25.pdf] waiting 10s before call...
14:19:34 [first:F3565064-EUCOPE_Proposals Biotech Act_final_Jun25.pdf] call OK
14:19:34 [second:F3565064-EUCOPE_Proposals Biotech Act_final_Jun25.pdf] waiting 10s before call...
14:19:54 [second:F3565064-EUCOPE_Proposals Biotech Act_final_Jun25.pdf] call OK
14:19:54 [third:F3565064-EUCOPE_Proposals Biotech Act_final_Jun25.pdf] waiting 10s before call...
14:20:08 [third:F3565064-EUCOPE_Proposals Biotech Act_final_Jun25.pdf] call OK

Processing documents:  46%|████▋     | 69/149 [49:24<58:56, 44.21s/doc, F3565089-Novamont_Biotech Act consultation.pdf]

14:20:08 [first:F3565089-Novamont_Biotech Act consultation.pdf] waiting 10s before call...
14:20:23 [first:F3565089-Novamont_Biotech Act consultation.pdf] call OK
14:20:23 [second:F3565089-Novamont_Biotech Act consultation.pdf] waiting 10s before call...
14:20:36 [second:F3565089-Novamont_Biotech Act consultation.pdf] call OK
14:20:36 [third:F3565089-Novamont_Biotech Act consultation.pdf] waiting 10s before call...
14:20:48 [third:F3565089-Novamont_Biotech Act consultation.pdf] call OK

Processing documents:  47%|████▋     | 70/149 [50:03<56:23, 42.83s/doc, F3565090-CORBION_POSITION BIOTECH ACT.pdf]

[SAVED] checkpoint with 70 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\brussels_pp_results_checkpoint_20251103_142048.json
14:20:48 [first:F3565090-CORBION_POSITION BIOTECH ACT.pdf] waiting 10s before call...
14:21:02 [first:F3565090-CORBION_POSITION BIOTECH ACT.pdf] call OK
14:21:02 [second:F3565090-CORBION_POSITION BIOTECH ACT.pdf] waiting 10s before call...
14:21:14 [second:F3565090-CORBION_POSITION BIOTECH ACT.pdf] call OK
14:21:14 [third:F3565090-CORBION_POSITION BIOTECH ACT.pdf] waiting 10s before call...
14:21:27 [third:F3565090-CORBION_POSITION BIOTECH ACT.pdf] call OK

Processing documents:  48%|████▊     | 71/149 [50:42<54:02, 41.57s/doc, F3565110-Biocontrol-Coalition-BiotechAct-final.pdf]

14:21:27 [first:F3565110-Biocontrol-Coalition-BiotechAct-final.pdf] waiting 10s before call...
14:21:45 [first:F3565110-Biocontrol-Coalition-BiotechAct-final.pdf] call OK
14:21:45 [second:F3565110-Biocontrol-Coalition-BiotechAct-final.pdf] waiting 10s before call...
14:21:58 [second:F3565110-Biocontrol-Coalition-BiotechAct-final.pdf] call OK
14:21:58 [third:F3565110-Biocontrol-Coalition-BiotechAct-final.pdf] waiting 10s before call...
14:22:10 [third:F3565110-Biocontrol-Coalition-BiotechAct-final.pdf] call OK

Processing documents:  48%|████▊     | 72/149 [51:26<54:07, 42.17s/doc, F3565113-20250611_Helmholtz_BiotechAct_final.pdf]

14:22:10 [first:F3565113-20250611_Helmholtz_BiotechAct_final.pdf] waiting 10s before call...
14:22:22 [first:F3565113-20250611_Helmholtz_BiotechAct_final.pdf] call OK
14:22:22 [second:F3565113-20250611_Helmholtz_BiotechAct_final.pdf] waiting 10s before call...
14:22:36 [second:F3565113-20250611_Helmholtz_BiotechAct_final.pdf] call OK
14:22:36 [third:F3565113-20250611_Helmholtz_BiotechAct_final.pdf] waiting 10s before call...
14:22:49 [third:F3565113-20250611_Helmholtz_BiotechAct_final.pdf] call OK

Processing documents:  49%|████▉     | 73/149 [52:04<51:57, 41.02s/doc, F3565115-20250519_LSMA_Biotech Act call for evidence.pdf]

14:22:49 [first:F3565115-20250519_LSMA_Biotech Act call for evidence.pdf] waiting 10s before call...
14:23:03 [first:F3565115-20250519_LSMA_Biotech Act call for evidence.pdf] call OK
14:23:03 [second:F3565115-20250519_LSMA_Biotech Act call for evidence.pdf] waiting 10s before call...
14:23:16 [second:F3565115-20250519_LSMA_Biotech Act call for evidence.pdf] call OK
14:23:16 [third:F3565115-20250519_LSMA_Biotech Act call for evidence.pdf] waiting 10s before call...
14:23:31 [third:F3565115-20250519_LSMA_Biotech Act call for evidence.pdf] call OK

Processing documents:  50%|████▉     | 74/149 [52:46<51:40, 41.34s/doc, F3565117-ECL Policy paper The potential for academic development of medicines in Europe.pdf]

14:23:31 [first:F3565117-ECL Policy paper The potential for academic development of medicines in Europe.pdf] waiting 10s before call...
14:23:50 [first:F3565117-ECL Policy paper The potential for academic development of medicines in Europe.pdf] call OK
14:23:50 [second:F3565117-ECL Policy paper The potential for academic development of medicines in Europe.pdf] waiting 10s before call...
14:24:05 [second:F3565117-ECL Policy paper The potential for academic development of medicines in Europe.pdf] call OK
14:24:05 [third:F3565117-ECL Policy paper The potential for academic development of medicines in Europe.pdf] waiting 10s before call...
14:24:18 [third:F3565117-ECL Policy paper The potential for academic development of medicines in Europe.pdf] call OK

Processing documents:  50%|█████     | 75/149 [53:33<53:11, 43.13s/doc, F3565118-EFFCA FEMS Publication on NGTs (2024) & Labelling Solution.pdf]

14:24:18 [first:F3565118-EFFCA FEMS Publication on NGTs (2024) & Labelling Solution.pdf] waiting 10s before call...
14:24:34 [first:F3565118-EFFCA FEMS Publication on NGTs (2024) & Labelling Solution.pdf] call OK
14:24:34 [second:F3565118-EFFCA FEMS Publication on NGTs (2024) & Labelling Solution.pdf] waiting 10s before call...
14:24:47 [second:F3565118-EFFCA FEMS Publication on NGTs (2024) & Labelling Solution.pdf] call OK
14:24:47 [third:F3565118-EFFCA FEMS Publication on NGTs (2024) & Labelling Solution.pdf] waiting 10s before call...
14:24:59 [third:F3565118-EFFCA FEMS Publication on NGTs (2024) & Labelling Solution.pdf] call OK

Processing documents:  51%|█████     | 76/149 [54:15<51:49, 42.59s/doc, F3565143-Biotech Act Call for Evidence, attachment.pdf]

14:24:59 [first:F3565143-Biotech Act Call for Evidence, attachment.pdf] waiting 10s before call...
14:25:18 [first:F3565143-Biotech Act Call for Evidence, attachment.pdf] call OK
14:25:18 [second:F3565143-Biotech Act Call for Evidence, attachment.pdf] waiting 10s before call...
14:25:30 [second:F3565143-Biotech Act Call for Evidence, attachment.pdf] call OK
14:25:30 [third:F3565143-Biotech Act Call for Evidence, attachment.pdf] waiting 10s before call...
14:25:43 [third:F3565143-Biotech Act Call for Evidence, attachment.pdf] call OK

Processing documents:  52%|█████▏    | 77/149 [54:59<51:35, 42.99s/doc, F3565157-Ley Biotecnologia comentarios.pdf]

14:25:43 [first:F3565157-Ley Biotecnologia comentarios.pdf] waiting 10s before call...
14:25:58 [first:F3565157-Ley Biotecnologia comentarios.pdf] call OK
14:25:58 [second:F3565157-Ley Biotecnologia comentarios.pdf] waiting 10s before call...
14:26:10 [second:F3565157-Ley Biotecnologia comentarios.pdf] call OK
14:26:10 [third:F3565157-Ley Biotecnologia comentarios.pdf] waiting 10s before call...
14:26:22 [third:F3565157-Ley Biotecnologia comentarios.pdf] call OK

Processing documents:  52%|█████▏    | 78/149 [55:38<49:30, 41.84s/doc, F3565164-2025-06-04 Stellungnahme Pro Generika EU Biotech Act_Entwurf_final.docx]

14:26:22 [first:F3565164-2025-06-04 Stellungnahme Pro Generika EU Biotech Act_Entwurf_final.docx] waiting 10s before call...
14:26:41 [first:F3565164-2025-06-04 Stellungnahme Pro Generika EU Biotech Act_Entwurf_final.docx] call OK
14:26:41 [second:F3565164-2025-06-04 Stellungnahme Pro Generika EU Biotech Act_Entwurf_final.docx] waiting 10s before call...
14:26:55 [second:F3565164-2025-06-04 Stellungnahme Pro Generika EU Biotech Act_Entwurf_final.docx] call OK
14:26:55 [third:F3565164-2025-06-04 Stellungnahme Pro Generika EU Biotech Act_Entwurf_final.docx] waiting 10s before call...
14:27:09 [third:F3565164-2025-06-04 Stellungnahme Pro Generika EU Biotech Act_Entwurf_final.docx] call OK

Processing documents:  53%|█████▎    | 79/149 [56:24<50:26, 43.23s/doc, F3565165-MedTech Europe Biotech Act Call for Evidence Draft response June 2025 FINAL.pdf]

14:27:09 [first:F3565165-MedTech Europe Biotech Act Call for Evidence Draft response June 2025 FINAL.pdf] waiting 10s before call...
14:27:22 [first:F3565165-MedTech Europe Biotech Act Call for Evidence Draft response June 2025 FINAL.pdf] call OK
14:27:22 [second:F3565165-MedTech Europe Biotech Act Call for Evidence Draft response June 2025 FINAL.pdf] waiting 10s before call...
14:27:35 [second:F3565165-MedTech Europe Biotech Act Call for Evidence Draft response June 2025 FINAL.pdf] call OK
14:27:35 [third:F3565165-MedTech Europe Biotech Act Call for Evidence Draft response June 2025 FINAL.pdf] waiting 10s before call...
14:27:47 [third:F3565165-MedTech Europe Biotech Act Call for Evidence Draft response June 2025 FINAL.pdf] call OK

Processing documents:  54%|█████▎    | 80/149 [57:03<48:05, 41.82s/doc, F3565166-25-06-11_Biotech-Act_Call_Evidence_SupplLiterature_BfN.pdf]

[SAVED] checkpoint with 80 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\brussels_pp_results_checkpoint_20251103_142747.json
14:27:47 [first:F3565166-25-06-11_Biotech-Act_Call_Evidence_SupplLiterature_BfN.pdf] waiting 10s before call...
14:28:01 [first:F3565166-25-06-11_Biotech-Act_Call_Evidence_SupplLiterature_BfN.pdf] call OK
14:28:01 [second:F3565166-25-06-11_Biotech-Act_Call_Evidence_SupplLiterature_BfN.pdf] waiting 10s before call...
14:28:13 [second:F3565166-25-06-11_Biotech-Act_Call_Evidence_SupplLiterature_BfN.pdf] call OK
14:28:13 [third:F3565166-25-06-11_Biotech-Act_Call_Evidence_SupplLiterature_BfN.pdf] waiting 10s before call...
14:28:26 [third:F3565166-25-06-11_Biotech-Act_Call_Evidence_SupplLiterature_BfN.pdf] call OK

Processing documents:  54%|█████▍    | 81/149 [57:42<46:21, 40.90s/doc, F3565172-Eurogroup for Animals - Call for evidence on the Biotech Act.pdf]

14:28:26 [first:F3565172-Eurogroup for Animals - Call for evidence on the Biotech Act.pdf] waiting 10s before call...
14:28:41 [first:F3565172-Eurogroup for Animals - Call for evidence on the Biotech Act.pdf] call OK
14:28:41 [second:F3565172-Eurogroup for Animals - Call for evidence on the Biotech Act.pdf] waiting 10s before call...
14:28:54 [second:F3565172-Eurogroup for Animals - Call for evidence on the Biotech Act.pdf] call OK
14:28:54 [third:F3565172-Eurogroup for Animals - Call for evidence on the Biotech Act.pdf] waiting 10s before call...
14:29:09 [third:F3565172-Eurogroup for Animals - Call for evidence on the Biotech Act.pdf] call OK

Processing documents:  55%|█████▌    | 82/149 [58:25<46:22, 41.53s/doc, F3565207-Response to the Call for Evidence on the European Biotech Act.pdf]

14:29:09 [first:F3565207-Response to the Call for Evidence on the European Biotech Act.pdf] waiting 10s before call...
14:29:25 [first:F3565207-Response to the Call for Evidence on the European Biotech Act.pdf] call OK
14:29:25 [second:F3565207-Response to the Call for Evidence on the European Biotech Act.pdf] waiting 10s before call...
14:29:39 [second:F3565207-Response to the Call for Evidence on the European Biotech Act.pdf] call OK
14:29:39 [third:F3565207-Response to the Call for Evidence on the European Biotech Act.pdf] waiting 10s before call...
14:29:51 [third:F3565207-Response to the Call for Evidence on the European Biotech Act.pdf] call OK

Processing documents:  56%|█████▌    | 83/149 [59:07<45:51, 41.69s/doc, F3565208-AnimalhealthEurope_Feedback - Biotech Act (fin).pdf]

14:29:51 [first:F3565208-AnimalhealthEurope_Feedback - Biotech Act (fin).pdf] waiting 10s before call...
14:30:34 [first:F3565208-AnimalhealthEurope_Feedback - Biotech Act (fin).pdf] call OK
14:30:34 [second:F3565208-AnimalhealthEurope_Feedback - Biotech Act (fin).pdf] waiting 10s before call...
14:30:51 [second:F3565208-AnimalhealthEurope_Feedback - Biotech Act (fin).pdf] call OK
14:30:51 [third:F3565208-AnimalhealthEurope_Feedback - Biotech Act (fin).pdf] waiting 10s before call...
14:31:05 [third:F3565208-AnimalhealthEurope_Feedback - Biotech Act (fin).pdf] call OK

Processing documents:  56%|█████▋    | 84/149 [1:00:21<55:41, 51.40s/doc, F3565224-Feedback on Biotech Act_Rigshospitalet_Copenhagen University Hospital.pdf]

14:31:05 [first:F3565224-Feedback on Biotech Act_Rigshospitalet_Copenhagen University Hospital.pdf] waiting 10s before call...
14:31:20 [first:F3565224-Feedback on Biotech Act_Rigshospitalet_Copenhagen University Hospital.pdf] call OK
14:31:20 [second:F3565224-Feedback on Biotech Act_Rigshospitalet_Copenhagen University Hospital.pdf] waiting 10s before call...
14:31:35 [second:F3565224-Feedback on Biotech Act_Rigshospitalet_Copenhagen University Hospital.pdf] call OK
14:31:35 [third:F3565224-Feedback on Biotech Act_Rigshospitalet_Copenhagen University Hospital.pdf] waiting 10s before call...
14:31:48 [third:F3565224-Feedback on Biotech Act_Rigshospitalet_Copenhagen University Hospital.pdf] call OK

Processing documents:  57%|█████▋    | 85/149 [1:01:04<52:08, 48.89s/doc, F3565229-EUBiotechAct_ FIB_final.pdf]

14:31:48 [first:F3565229-EUBiotechAct_ FIB_final.pdf] waiting 10s before call...
14:32:04 [first:F3565229-EUBiotechAct_ FIB_final.pdf] call OK
14:32:04 [second:F3565229-EUBiotechAct_ FIB_final.pdf] waiting 10s before call...
14:32:17 [second:F3565229-EUBiotechAct_ FIB_final.pdf] call OK
14:32:17 [third:F3565229-EUBiotechAct_ FIB_final.pdf] waiting 10s before call...
14:32:30 [third:F3565229-EUBiotechAct_ FIB_final.pdf] call OK

Processing documents:  58%|█████▊    | 86/149 [1:01:45<48:56, 46.61s/doc, F3565230-Pfizer Response to the EU Biotech Act Call for Evidence.pdf]

14:32:30 [first:F3565230-Pfizer Response to the EU Biotech Act Call for Evidence.pdf] waiting 10s before call...
14:32:45 [first:F3565230-Pfizer Response to the EU Biotech Act Call for Evidence.pdf] call OK
14:32:45 [second:F3565230-Pfizer Response to the EU Biotech Act Call for Evidence.pdf] waiting 10s before call...
14:32:59 [second:F3565230-Pfizer Response to the EU Biotech Act Call for Evidence.pdf] call OK
14:32:59 [third:F3565230-Pfizer Response to the EU Biotech Act Call for Evidence.pdf] waiting 10s before call...
14:33:11 [third:F3565230-Pfizer Response to the EU Biotech Act Call for Evidence.pdf] call OK

Processing documents:  58%|█████▊    | 87/149 [1:02:26<46:31, 45.02s/doc, F3565232-IFOAMEU_Biotech Act_public consultation_input.pdf]

14:33:11 [first:F3565232-IFOAMEU_Biotech Act_public consultation_input.pdf] waiting 10s before call...
14:33:25 [first:F3565232-IFOAMEU_Biotech Act_public consultation_input.pdf] call OK
14:33:25 [second:F3565232-IFOAMEU_Biotech Act_public consultation_input.pdf] waiting 10s before call...
14:33:37 [second:F3565232-IFOAMEU_Biotech Act_public consultation_input.pdf] call OK
14:33:37 [third:F3565232-IFOAMEU_Biotech Act_public consultation_input.pdf] waiting 10s before call...
14:33:49 [third:F3565232-IFOAMEU_Biotech Act_public consultation_input.pdf] call OK

Processing documents:  59%|█████▉    | 88/149 [1:03:04<43:37, 42.90s/doc, F3565236-Lif's and SwedensBIO's Biotech act position paper.pdf]

14:33:49 [first:F3565236-Lif's and SwedensBIO's Biotech act position paper.pdf] waiting 10s before call...
14:34:10 [first:F3565236-Lif's and SwedensBIO's Biotech act position paper.pdf] call OK
14:34:10 [second:F3565236-Lif's and SwedensBIO's Biotech act position paper.pdf] waiting 10s before call...
14:34:25 [second:F3565236-Lif's and SwedensBIO's Biotech act position paper.pdf] call OK
14:34:25 [third:F3565236-Lif's and SwedensBIO's Biotech act position paper.pdf] waiting 10s before call...
14:34:40 [third:F3565236-Lif's and SwedensBIO's Biotech act position paper.pdf] call OK

Processing documents:  60%|█████▉    | 89/149 [1:03:56<45:29, 45.49s/doc, F3565249-Novo Nordisk Foundation - Call for evidence EU Biotech Act.pdf]

14:34:40 [first:F3565249-Novo Nordisk Foundation - Call for evidence EU Biotech Act.pdf] waiting 10s before call...
14:35:00 [first:F3565249-Novo Nordisk Foundation - Call for evidence EU Biotech Act.pdf] call OK
14:35:00 [second:F3565249-Novo Nordisk Foundation - Call for evidence EU Biotech Act.pdf] waiting 10s before call...
14:35:16 [second:F3565249-Novo Nordisk Foundation - Call for evidence EU Biotech Act.pdf] call OK
14:35:16 [third:F3565249-Novo Nordisk Foundation - Call for evidence EU Biotech Act.pdf] waiting 10s before call...
14:35:32 [third:F3565249-Novo Nordisk Foundation - Call for evidence EU Biotech Act.pdf] call OK

Processing documents:  60%|██████    | 90/149 [1:04:48<46:37, 47.41s/doc, F3565251-FIN_DIB_EU BioTech Act.pdf]

[SAVED] checkpoint with 90 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\brussels_pp_results_checkpoint_20251103_143532.json
14:35:32 [first:F3565251-FIN_DIB_EU BioTech Act.pdf] waiting 10s before call...
14:35:53 [first:F3565251-FIN_DIB_EU BioTech Act.pdf] call OK
14:35:53 [second:F3565251-FIN_DIB_EU BioTech Act.pdf] waiting 10s before call...
14:36:08 [second:F3565251-FIN_DIB_EU BioTech Act.pdf] call OK
14:36:08 [third:F3565251-FIN_DIB_EU BioTech Act.pdf] waiting 10s before call...
14:36:22 [third:F3565251-FIN_DIB_EU BioTech Act.pdf] call OK

Processing documents:  61%|██████    | 91/149 [1:05:37<46:26, 48.05s/doc, F3565252-DanishChamberofCommerce_Callforevidence_BiotechAct.pdf]

14:36:22 [first:F3565252-DanishChamberofCommerce_Callforevidence_BiotechAct.pdf] waiting 10s before call...
14:36:37 [first:F3565252-DanishChamberofCommerce_Callforevidence_BiotechAct.pdf] call OK
14:36:37 [second:F3565252-DanishChamberofCommerce_Callforevidence_BiotechAct.pdf] waiting 10s before call...
14:36:54 [second:F3565252-DanishChamberofCommerce_Callforevidence_BiotechAct.pdf] call OK
14:36:54 [third:F3565252-DanishChamberofCommerce_Callforevidence_BiotechAct.pdf] waiting 10s before call...
14:37:08 [third:F3565252-DanishChamberofCommerce_Callforevidence_BiotechAct.pdf] call OK

Processing documents:  62%|██████▏   | 92/149 [1:06:24<45:10, 47.54s/doc, F3565256-EU Biotech Act call for evidence_PRI response_Submitted.pdf]

14:37:08 [first:F3565256-EU Biotech Act call for evidence_PRI response_Submitted.pdf] waiting 10s before call...
14:37:27 [first:F3565256-EU Biotech Act call for evidence_PRI response_Submitted.pdf] call OK
14:37:27 [second:F3565256-EU Biotech Act call for evidence_PRI response_Submitted.pdf] waiting 10s before call...
14:37:40 [second:F3565256-EU Biotech Act call for evidence_PRI response_Submitted.pdf] call OK
14:37:40 [third:F3565256-EU Biotech Act call for evidence_PRI response_Submitted.pdf] waiting 10s before call...
14:37:52 [third:F3565256-EU Biotech Act call for evidence_PRI response_Submitted.pdf] call OK

Processing documents:  62%|██████▏   | 93/149 [1:07:08<43:23, 46.49s/doc, F3565277-Roche feedback EU Biotech Act - Call for Evidence - 11 June 2025.pdf]

14:37:52 [first:F3565277-Roche feedback EU Biotech Act - Call for Evidence - 11 June 2025.pdf] waiting 10s before call...
14:38:08 [first:F3565277-Roche feedback EU Biotech Act - Call for Evidence - 11 June 2025.pdf] call OK
14:38:08 [second:F3565277-Roche feedback EU Biotech Act - Call for Evidence - 11 June 2025.pdf] waiting 10s before call...
14:38:21 [second:F3565277-Roche feedback EU Biotech Act - Call for Evidence - 11 June 2025.pdf] call OK
14:38:21 [third:F3565277-Roche feedback EU Biotech Act - Call for Evidence - 11 June 2025.pdf] waiting 10s before call...
14:38:35 [third:F3565277-Roche feedback EU Biotech Act - Call for Evidence - 11 June 2025.pdf] call OK

Processing documents:  63%|██████▎   | 94/149 [1:07:51<41:39, 45.44s/doc, F3565281-Position paper WEWIS Biotech Act.pdf]

14:38:35 [first:F3565281-Position paper WEWIS Biotech Act.pdf] waiting 10s before call...
14:38:51 [first:F3565281-Position paper WEWIS Biotech Act.pdf] call OK
14:38:51 [second:F3565281-Position paper WEWIS Biotech Act.pdf] waiting 10s before call...
14:39:04 [second:F3565281-Position paper WEWIS Biotech Act.pdf] call OK
14:39:04 [third:F3565281-Position paper WEWIS Biotech Act.pdf] waiting 10s before call...
14:39:18 [third:F3565281-Position paper WEWIS Biotech Act.pdf] call OK

Processing documents:  64%|██████▍   | 95/149 [1:08:33<40:10, 44.64s/doc, F3565286-20250611 BASF Position_Biotech Act - FINAL.pdf]

14:39:18 [first:F3565286-20250611 BASF Position_Biotech Act - FINAL.pdf] waiting 10s before call...
14:39:35 [first:F3565286-20250611 BASF Position_Biotech Act - FINAL.pdf] call OK
14:39:35 [second:F3565286-20250611 BASF Position_Biotech Act - FINAL.pdf] waiting 10s before call...
14:39:48 [second:F3565286-20250611 BASF Position_Biotech Act - FINAL.pdf] call OK
14:39:48 [third:F3565286-20250611 BASF Position_Biotech Act - FINAL.pdf] waiting 10s before call...
14:40:01 [third:F3565286-20250611 BASF Position_Biotech Act - FINAL.pdf] call OK

Processing documents:  64%|██████▍   | 96/149 [1:09:16<38:54, 44.05s/doc, F3565287-AMFEP Response to the Call for Evidence on the Biotech Act - 11 June.pdf]

14:40:01 [first:F3565287-AMFEP Response to the Call for Evidence on the Biotech Act - 11 June.pdf] waiting 10s before call...
14:40:15 [first:F3565287-AMFEP Response to the Call for Evidence on the Biotech Act - 11 June.pdf] call OK
14:40:15 [second:F3565287-AMFEP Response to the Call for Evidence on the Biotech Act - 11 June.pdf] waiting 10s before call...
14:40:28 [second:F3565287-AMFEP Response to the Call for Evidence on the Biotech Act - 11 June.pdf] call OK
14:40:28 [third:F3565287-AMFEP Response to the Call for Evidence on the Biotech Act - 11 June.pdf] waiting 10s before call...
14:40:41 [third:F3565287-AMFEP Response to the Call for Evidence on the Biotech Act - 11 June.pdf] call OK

Processing documents:  65%|██████▌   | 97/149 [1:09:56<37:04, 42.77s/doc, F3565290-UniSR_European Biotech Act_Extended.pdf]

14:40:41 [first:F3565290-UniSR_European Biotech Act_Extended.pdf] waiting 10s before call...
14:40:59 [first:F3565290-UniSR_European Biotech Act_Extended.pdf] call OK
14:40:59 [second:F3565290-UniSR_European Biotech Act_Extended.pdf] waiting 10s before call...
14:41:13 [second:F3565290-UniSR_European Biotech Act_Extended.pdf] call OK
14:41:13 [third:F3565290-UniSR_European Biotech Act_Extended.pdf] waiting 10s before call...
14:41:26 [third:F3565290-UniSR_European Biotech Act_Extended.pdf] call OK

Processing documents:  66%|██████▌   | 98/149 [1:10:41<36:57, 43.48s/doc, F3565295-2025-06-10 Biotech Call for Evidence.pdf]

14:41:26 [first:F3565295-2025-06-10 Biotech Call for Evidence.pdf] waiting 10s before call...
14:41:42 [first:F3565295-2025-06-10 Biotech Call for Evidence.pdf] call OK
14:41:42 [second:F3565295-2025-06-10 Biotech Call for Evidence.pdf] waiting 10s before call...
14:41:57 [second:F3565295-2025-06-10 Biotech Call for Evidence.pdf] call OK
14:41:57 [third:F3565295-2025-06-10 Biotech Call for Evidence.pdf] waiting 10s before call...
14:42:10 [third:F3565295-2025-06-10 Biotech Call for Evidence.pdf] call OK

Processing documents:  66%|██████▋   | 99/149 [1:11:26<36:32, 43.85s/doc, F3565302-EAHP relevant position papers.pdf]

14:42:10 [first:F3565302-EAHP relevant position papers.pdf] waiting 10s before call...
14:42:27 [first:F3565302-EAHP relevant position papers.pdf] call OK
14:42:27 [second:F3565302-EAHP relevant position papers.pdf] waiting 10s before call...
14:42:40 [second:F3565302-EAHP relevant position papers.pdf] call OK
14:42:40 [third:F3565302-EAHP relevant position papers.pdf] waiting 10s before call...
14:42:52 [third:F3565302-EAHP relevant position papers.pdf] call OK

Processing documents:  67%|██████▋   | 100/149 [1:12:08<35:23, 43.33s/doc, F3565307-Call for Evidence_BiotechAct11062025FINAL.pdf]

[SAVED] checkpoint with 100 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\brussels_pp_results_checkpoint_20251103_144252.json
14:42:52 [first:F3565307-Call for Evidence_BiotechAct11062025FINAL.pdf] waiting 10s before call...
14:43:08 [first:F3565307-Call for Evidence_BiotechAct11062025FINAL.pdf] call OK
14:43:08 [second:F3565307-Call for Evidence_BiotechAct11062025FINAL.pdf] waiting 10s before call...
14:43:21 [second:F3565307-Call for Evidence_BiotechAct11062025FINAL.pdf] call OK
14:43:21 [third:F3565307-Call for Evidence_BiotechAct11062025FINAL.pdf] waiting 10s before call...
14:43:33 [third:F3565307-Call for Evidence_BiotechAct11062025FINAL.pdf] call OK

Processing documents:  68%|██████▊   | 101/149 [1:12:49<34:06, 42.64s/doc, F3565312-European Biosolutions Coalition_Call for Evidens_Biotech Act_EBC.pdf]

14:43:33 [first:F3565312-European Biosolutions Coalition_Call for Evidens_Biotech Act_EBC.pdf] waiting 10s before call...
14:43:49 [first:F3565312-European Biosolutions Coalition_Call for Evidens_Biotech Act_EBC.pdf] call OK
14:43:49 [second:F3565312-European Biosolutions Coalition_Call for Evidens_Biotech Act_EBC.pdf] waiting 10s before call...
14:44:03 [second:F3565312-European Biosolutions Coalition_Call for Evidens_Biotech Act_EBC.pdf] call OK
14:44:03 [third:F3565312-European Biosolutions Coalition_Call for Evidens_Biotech Act_EBC.pdf] waiting 10s before call...
14:44:17 [third:F3565312-European Biosolutions Coalition_Call for Evidens_Biotech Act_EBC.pdf] call OK

Processing documents:  68%|██████▊   | 102/149 [1:13:32<33:33, 42.84s/doc, F3565317-BiotechAct_Impact_GASB.pdf]

14:44:17 [first:F3565317-BiotechAct_Impact_GASB.pdf] waiting 10s before call...
14:44:31 [first:F3565317-BiotechAct_Impact_GASB.pdf] call OK
14:44:31 [second:F3565317-BiotechAct_Impact_GASB.pdf] waiting 10s before call...
14:44:46 [second:F3565317-BiotechAct_Impact_GASB.pdf] call OK
14:44:46 [third:F3565317-BiotechAct_Impact_GASB.pdf] waiting 10s before call...
14:44:59 [third:F3565317-BiotechAct_Impact_GASB.pdf] call OK

Processing documents:  69%|██████▉   | 103/149 [1:14:14<32:37, 42.55s/doc, F3565319-Attractiveness-of-the-Vaccines-Industry_June2023.pdf]

14:44:59 [first:F3565319-Attractiveness-of-the-Vaccines-Industry_June2023.pdf] waiting 10s before call...
14:45:16 [first:F3565319-Attractiveness-of-the-Vaccines-Industry_June2023.pdf] call OK
14:45:16 [second:F3565319-Attractiveness-of-the-Vaccines-Industry_June2023.pdf] waiting 10s before call...
14:45:32 [second:F3565319-Attractiveness-of-the-Vaccines-Industry_June2023.pdf] call OK
14:45:32 [third:F3565319-Attractiveness-of-the-Vaccines-Industry_June2023.pdf] waiting 10s before call...
14:45:45 [third:F3565319-Attractiveness-of-the-Vaccines-Industry_June2023.pdf] call OK

Processing documents:  70%|██████▉   | 104/149 [1:15:00<32:43, 43.64s/doc, F3565323-Johns Hopkins Center for Health Security Call for Evidence Response on EU Biotech Act.pdf]

14:45:45 [first:F3565323-Johns Hopkins Center for Health Security Call for Evidence Response on EU Biotech Act.pdf] waiting 10s before call...
14:45:57 [first:F3565323-Johns Hopkins Center for Health Security Call for Evidence Response on EU Biotech Act.pdf] call OK
14:45:57 [second:F3565323-Johns Hopkins Center for Health Security Call for Evidence Response on EU Biotech Act.pdf] waiting 10s before call...
14:46:10 [second:F3565323-Johns Hopkins Center for Health Security Call for Evidence Response on EU Biotech Act.pdf] call OK
14:46:10 [third:F3565323-Johns Hopkins Center for Health Security Call for Evidence Response on EU Biotech Act.pdf] waiting 10s before call...
14:46:22 [third:F3565323-Johns Hopkins Center for Health Security Call for Evidence Response on EU Biotech Act.pdf] call OK

Processing documents:  70%|███████   | 105/149 [1:15:37<30:33, 41.67s/doc, F3565339-AstraZeeca_BiotechAct_submission.pdf]

14:46:22 [first:F3565339-AstraZeeca_BiotechAct_submission.pdf] waiting 10s before call...
14:46:44 [first:F3565339-AstraZeeca_BiotechAct_submission.pdf] call OK
14:46:44 [second:F3565339-AstraZeeca_BiotechAct_submission.pdf] waiting 10s before call...
14:46:58 [second:F3565339-AstraZeeca_BiotechAct_submission.pdf] call OK
14:46:58 [third:F3565339-AstraZeeca_BiotechAct_submission.pdf] waiting 10s before call...
14:47:10 [third:F3565339-AstraZeeca_BiotechAct_submission.pdf] call OK

Processing documents:  71%|███████   | 106/149 [1:16:26<31:19, 43.71s/doc, F3565340-2025 06 11_IBBIS Submission_EU Biotech Act.pdf]

14:47:10 [first:F3565340-2025 06 11_IBBIS Submission_EU Biotech Act.pdf] waiting 10s before call...
14:47:24 [first:F3565340-2025 06 11_IBBIS Submission_EU Biotech Act.pdf] call OK
14:47:24 [second:F3565340-2025 06 11_IBBIS Submission_EU Biotech Act.pdf] waiting 10s before call...
14:47:36 [second:F3565340-2025 06 11_IBBIS Submission_EU Biotech Act.pdf] call OK
14:47:36 [third:F3565340-2025 06 11_IBBIS Submission_EU Biotech Act.pdf] waiting 10s before call...
14:47:55 [third:F3565340-2025 06 11_IBBIS Submission_EU Biotech Act.pdf] call OK

Processing documents:  72%|███████▏  | 107/149 [1:17:10<30:46, 43.97s/doc, F3565342-Humane World Animals_EU Biotech Act.pdf]

14:47:55 [first:F3565342-Humane World Animals_EU Biotech Act.pdf] waiting 10s before call...
14:48:11 [first:F3565342-Humane World Animals_EU Biotech Act.pdf] call OK
14:48:11 [second:F3565342-Humane World Animals_EU Biotech Act.pdf] waiting 10s before call...
14:48:25 [second:F3565342-Humane World Animals_EU Biotech Act.pdf] call OK
14:48:25 [third:F3565342-Humane World Animals_EU Biotech Act.pdf] waiting 10s before call...
14:48:40 [third:F3565342-Humane World Animals_EU Biotech Act.pdf] call OK

Processing documents:  72%|███████▏  | 108/149 [1:17:56<30:18, 44.35s/doc, F3565344-2025-06-11 IBMA input to Biotech Act call for evidence.pdf]

14:48:40 [first:F3565344-2025-06-11 IBMA input to Biotech Act call for evidence.pdf] waiting 10s before call...
14:48:59 [first:F3565344-2025-06-11 IBMA input to Biotech Act call for evidence.pdf] call OK
14:48:59 [second:F3565344-2025-06-11 IBMA input to Biotech Act call for evidence.pdf] waiting 10s before call...
14:49:12 [second:F3565344-2025-06-11 IBMA input to Biotech Act call for evidence.pdf] call OK
14:49:12 [third:F3565344-2025-06-11 IBMA input to Biotech Act call for evidence.pdf] waiting 10s before call...
14:49:24 [third:F3565344-2025-06-11 IBMA input to Biotech Act call for evidence.pdf] call OK

Processing documents:  73%|███████▎  | 109/149 [1:18:39<29:24, 44.12s/doc, F3565349-Biotech Act call for evidence - Cefic reply_20250611.pdf]

14:49:24 [first:F3565349-Biotech Act call for evidence - Cefic reply_20250611.pdf] waiting 10s before call...
14:49:38 [first:F3565349-Biotech Act call for evidence - Cefic reply_20250611.pdf] call OK
14:49:38 [second:F3565349-Biotech Act call for evidence - Cefic reply_20250611.pdf] waiting 10s before call...
14:49:52 [second:F3565349-Biotech Act call for evidence - Cefic reply_20250611.pdf] call OK
14:49:52 [third:F3565349-Biotech Act call for evidence - Cefic reply_20250611.pdf] waiting 10s before call...
14:50:04 [third:F3565349-Biotech Act call for evidence - Cefic reply_20250611.pdf] call OK

Processing documents:  74%|███████▍  | 110/149 [1:19:19<27:51, 42.87s/doc, F3565354-Lif's and SwedensBIO's Biotech act position paper.pdf]

[SAVED] checkpoint with 110 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\brussels_pp_results_checkpoint_20251103_145004.json
14:50:04 [first:F3565354-Lif's and SwedensBIO's Biotech act position paper.pdf] waiting 10s before call...
14:50:23 [first:F3565354-Lif's and SwedensBIO's Biotech act position paper.pdf] call OK
14:50:23 [second:F3565354-Lif's and SwedensBIO's Biotech act position paper.pdf] waiting 10s before call...
14:50:39 [second:F3565354-Lif's and SwedensBIO's Biotech act position paper.pdf] call OK
14:50:39 [third:F3565354-Lif's and SwedensBIO's Biotech act position paper.pdf] waiting 10s before call...
14:50:54 [third:F3565354-Lif's and SwedensBIO's Biotech act position paper.pdf] call OK

Processing documents:  74%|███████▍  | 111/149 [1:20:09<28:28, 44.95s/doc, F3565358-EU CONSULTATION BIOTECH ACT - submitted 06112025.pdf]

14:50:54 [first:F3565358-EU CONSULTATION BIOTECH ACT - submitted 06112025.pdf] waiting 10s before call...
14:51:08 [first:F3565358-EU CONSULTATION BIOTECH ACT - submitted 06112025.pdf] call OK
14:51:08 [second:F3565358-EU CONSULTATION BIOTECH ACT - submitted 06112025.pdf] waiting 10s before call...
14:51:20 [second:F3565358-EU CONSULTATION BIOTECH ACT - submitted 06112025.pdf] call OK
14:51:20 [third:F3565358-EU CONSULTATION BIOTECH ACT - submitted 06112025.pdf] waiting 10s before call...
14:51:32 [third:F3565358-EU CONSULTATION BIOTECH ACT - submitted 06112025.pdf] call OK

Processing documents:  75%|███████▌  | 112/149 [1:20:48<26:36, 43.15s/doc, F3565359-Biotech Act Consultation response from the Triangle AU_INRAE_WUR _June 2025.pdf]

14:51:32 [first:F3565359-Biotech Act Consultation response from the Triangle AU_INRAE_WUR _June 2025.pdf] waiting 10s before call...
14:51:47 [first:F3565359-Biotech Act Consultation response from the Triangle AU_INRAE_WUR _June 2025.pdf] call OK
14:51:47 [second:F3565359-Biotech Act Consultation response from the Triangle AU_INRAE_WUR _June 2025.pdf] waiting 10s before call...
14:52:08 [second:F3565359-Biotech Act Consultation response from the Triangle AU_INRAE_WUR _June 2025.pdf] call OK
14:52:08 [third:F3565359-Biotech Act Consultation response from the Triangle AU_INRAE_WUR _June 2025.pdf] waiting 10s before call...
14:52:22 [third:F3565359-Biotech Act Consultation response from the Triangle AU_INRAE_WUR _June 2025.pdf] call OK

Processing documents:  76%|███████▌  | 113/149 [1:21:38<27:06, 45.18s/doc, F3565361-EIT Food_Response_to Call for Evidence IA Biotech Act_FINAL.pdf]

14:52:22 [first:F3565361-EIT Food_Response_to Call for Evidence IA Biotech Act_FINAL.pdf] waiting 10s before call...
14:52:43 [first:F3565361-EIT Food_Response_to Call for Evidence IA Biotech Act_FINAL.pdf] call OK
14:52:43 [second:F3565361-EIT Food_Response_to Call for Evidence IA Biotech Act_FINAL.pdf] waiting 10s before call...
14:53:01 [second:F3565361-EIT Food_Response_to Call for Evidence IA Biotech Act_FINAL.pdf] call OK
14:53:01 [third:F3565361-EIT Food_Response_to Call for Evidence IA Biotech Act_FINAL.pdf] waiting 10s before call...
14:53:15 [third:F3565361-EIT Food_Response_to Call for Evidence IA Biotech Act_FINAL.pdf] call OK

Processing documents:  77%|███████▋  | 114/149 [1:22:30<27:34, 47.26s/doc, F3565366-Description Microbs 2025.pdf]

14:53:15 [first:F3565366-Description Microbs 2025.pdf] waiting 10s before call...
14:53:30 [first:F3565366-Description Microbs 2025.pdf] call OK
14:53:30 [second:F3565366-Description Microbs 2025.pdf] waiting 10s before call...
14:53:52 [second:F3565366-Description Microbs 2025.pdf] call OK
14:53:52 [third:F3565366-Description Microbs 2025.pdf] waiting 10s before call...
14:54:06 [third:F3565366-Description Microbs 2025.pdf] call OK

Processing documents:  77%|███████▋  | 115/149 [1:23:22<27:31, 48.58s/doc, F3565367-CEPI Submission to the EU Biotech Act Call for Evidence_Attachment.docx]

14:54:06 [first:F3565367-CEPI Submission to the EU Biotech Act Call for Evidence_Attachment.docx] waiting 10s before call...
14:54:23 [first:F3565367-CEPI Submission to the EU Biotech Act Call for Evidence_Attachment.docx] call OK
14:54:23 [second:F3565367-CEPI Submission to the EU Biotech Act Call for Evidence_Attachment.docx] waiting 10s before call...
14:54:36 [second:F3565367-CEPI Submission to the EU Biotech Act Call for Evidence_Attachment.docx] call OK
14:54:36 [third:F3565367-CEPI Submission to the EU Biotech Act Call for Evidence_Attachment.docx] waiting 10s before call...
14:54:51 [third:F3565367-CEPI Submission to the EU Biotech Act Call for Evidence_Attachment.docx] call OK

Processing documents:  78%|███████▊  | 116/149 [1:24:07<26:09, 47.57s/doc, F3565369-Synpa_contribution_biotechact_11062025.pdf]

14:54:51 [first:F3565369-Synpa_contribution_biotechact_11062025.pdf] waiting 10s before call...
14:55:13 [first:F3565369-Synpa_contribution_biotechact_11062025.pdf] call OK
14:55:13 [second:F3565369-Synpa_contribution_biotechact_11062025.pdf] waiting 10s before call...
14:55:28 [second:F3565369-Synpa_contribution_biotechact_11062025.pdf] call OK
14:55:28 [third:F3565369-Synpa_contribution_biotechact_11062025.pdf] waiting 10s before call...
14:55:43 [third:F3565369-Synpa_contribution_biotechact_11062025.pdf] call OK

Processing documents:  79%|███████▊  | 117/149 [1:24:58<25:57, 48.67s/doc, F3565371-EU Biotech Act - EBC Contribution.pdf]

14:55:43 [first:F3565371-EU Biotech Act - EBC Contribution.pdf] waiting 10s before call...
14:55:58 [first:F3565371-EU Biotech Act - EBC Contribution.pdf] call OK
14:55:58 [second:F3565371-EU Biotech Act - EBC Contribution.pdf] waiting 10s before call...
14:56:13 [second:F3565371-EU Biotech Act - EBC Contribution.pdf] call OK
14:56:13 [third:F3565371-EU Biotech Act - EBC Contribution.pdf] waiting 10s before call...
14:56:28 [third:F3565371-EU Biotech Act - EBC Contribution.pdf] call OK

Processing documents:  79%|███████▉  | 118/149 [1:25:44<24:40, 47.77s/doc, F3565376-ESIP-Feedback_Call-for-Evidence_for-an-Impact-Assessment_European-Biotech-Act_11-06-2025.pdf]

14:56:28 [first:F3565376-ESIP-Feedback_Call-for-Evidence_for-an-Impact-Assessment_European-Biotech-Act_11-06-2025.pdf] waiting 10s before call...
14:56:43 [first:F3565376-ESIP-Feedback_Call-for-Evidence_for-an-Impact-Assessment_European-Biotech-Act_11-06-2025.pdf] call OK
14:56:43 [second:F3565376-ESIP-Feedback_Call-for-Evidence_for-an-Impact-Assessment_European-Biotech-Act_11-06-2025.pdf] waiting 10s before call...
14:56:55 [second:F3565376-ESIP-Feedback_Call-for-Evidence_for-an-Impact-Assessment_European-Biotech-Act_11-06-2025.pdf] call OK
14:56:55 [third:F3565376-ESIP-Feedback_Call-for-Evidence_for-an-Impact-Assessment_European-Biotech-Act_11-06-2025.pdf] waiting 10s before call...
14:57:08 [third:F3565376-ESIP-Feedback_Call-for-Evidence_for-an-Impact-Assessment_European-Biotech-Act_11-06-2025.pdf] call OK

Processing documents:  80%|███████▉  | 119/149 [1:26:23<22:36, 45.23s/doc, F3565383-New Harvest NL EUBiotechAct.pdf]

14:57:08 [first:F3565383-New Harvest NL EUBiotechAct.pdf] waiting 10s before call...
14:57:22 [first:F3565383-New Harvest NL EUBiotechAct.pdf] call OK
14:57:22 [second:F3565383-New Harvest NL EUBiotechAct.pdf] waiting 10s before call...
14:57:38 [second:F3565383-New Harvest NL EUBiotechAct.pdf] call OK
14:57:38 [third:F3565383-New Harvest NL EUBiotechAct.pdf] waiting 10s before call...
14:57:53 [third:F3565383-New Harvest NL EUBiotechAct.pdf] call OK

Processing documents:  81%|████████  | 120/149 [1:27:08<21:49, 45.16s/doc, F3565386-20250611-EBIC-BiotechAct-Submission.pdf]

[SAVED] checkpoint with 120 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\brussels_pp_results_checkpoint_20251103_145753.json
14:57:53 [first:F3565386-20250611-EBIC-BiotechAct-Submission.pdf] waiting 10s before call...
14:58:07 [first:F3565386-20250611-EBIC-BiotechAct-Submission.pdf] call OK
14:58:07 [second:F3565386-20250611-EBIC-BiotechAct-Submission.pdf] waiting 10s before call...
14:58:20 [second:F3565386-20250611-EBIC-BiotechAct-Submission.pdf] call OK
14:58:20 [third:F3565386-20250611-EBIC-BiotechAct-Submission.pdf] waiting 10s before call...
14:58:32 [third:F3565386-20250611-EBIC-BiotechAct-Submission.pdf] call OK

Processing documents:  81%|████████  | 121/149 [1:27:47<20:17, 43.47s/doc, F3565387-BIC contribution to Biotech Act call for evidence FV 1.pdf]

14:58:32 [first:F3565387-BIC contribution to Biotech Act call for evidence FV 1.pdf] waiting 10s before call...
14:58:47 [first:F3565387-BIC contribution to Biotech Act call for evidence FV 1.pdf] call OK
14:58:47 [second:F3565387-BIC contribution to Biotech Act call for evidence FV 1.pdf] waiting 10s before call...
14:59:00 [second:F3565387-BIC contribution to Biotech Act call for evidence FV 1.pdf] call OK
14:59:00 [third:F3565387-BIC contribution to Biotech Act call for evidence FV 1.pdf] waiting 10s before call...
14:59:13 [third:F3565387-BIC contribution to Biotech Act call for evidence FV 1.pdf] call OK

Processing documents:  82%|████████▏ | 122/149 [1:28:28<19:09, 42.58s/doc, F3565388-2025 Biotech Act Call for evidence - IFF contribution FINAL - CASE STUDIES.pdf]

14:59:13 [first:F3565388-2025 Biotech Act Call for evidence - IFF contribution FINAL - CASE STUDIES.pdf] waiting 10s before call...
14:59:33 [first:F3565388-2025 Biotech Act Call for evidence - IFF contribution FINAL - CASE STUDIES.pdf] call OK
14:59:33 [second:F3565388-2025 Biotech Act Call for evidence - IFF contribution FINAL - CASE STUDIES.pdf] waiting 10s before call...
14:59:47 [second:F3565388-2025 Biotech Act Call for evidence - IFF contribution FINAL - CASE STUDIES.pdf] call OK
14:59:47 [third:F3565388-2025 Biotech Act Call for evidence - IFF contribution FINAL - CASE STUDIES.pdf] waiting 10s before call...
15:00:00 [third:F3565388-2025 Biotech Act Call for evidence - IFF contribution FINAL - CASE STUDIES.pdf] call OK

Processing documents:  83%|████████▎ | 123/149 [1:29:15<19:00, 43.88s/doc, F3565395-Lallemand Call for evidence EU Biotech Act.pdf]

15:00:00 [first:F3565395-Lallemand Call for evidence EU Biotech Act.pdf] waiting 10s before call...
15:00:17 [first:F3565395-Lallemand Call for evidence EU Biotech Act.pdf] call OK
15:00:17 [second:F3565395-Lallemand Call for evidence EU Biotech Act.pdf] waiting 10s before call...
15:00:31 [second:F3565395-Lallemand Call for evidence EU Biotech Act.pdf] call OK
15:00:31 [third:F3565395-Lallemand Call for evidence EU Biotech Act.pdf] waiting 10s before call...
15:00:44 [third:F3565395-Lallemand Call for evidence EU Biotech Act.pdf] call OK

Processing documents:  83%|████████▎ | 124/149 [1:29:59<18:21, 44.05s/doc, F3565399-Response.pdf.pdf]

15:00:44 [first:F3565399-Response.pdf.pdf] waiting 10s before call...
15:01:06 [first:F3565399-Response.pdf.pdf] call OK
15:01:06 [second:F3565399-Response.pdf.pdf] waiting 10s before call...
15:01:21 [second:F3565399-Response.pdf.pdf] call OK
15:01:21 [third:F3565399-Response.pdf.pdf] waiting 10s before call...
15:01:34 [third:F3565399-Response.pdf.pdf] call OK

Processing documents:  84%|████████▍ | 125/149 [1:30:49<18:19, 45.81s/doc, F3565405-20250611_Pharma Deutschland_Call for Evidence_Biotech Act.pdf]

15:01:34 [first:F3565405-20250611_Pharma Deutschland_Call for Evidence_Biotech Act.pdf] waiting 10s before call...
15:01:51 [first:F3565405-20250611_Pharma Deutschland_Call for Evidence_Biotech Act.pdf] call OK
15:01:51 [second:F3565405-20250611_Pharma Deutschland_Call for Evidence_Biotech Act.pdf] waiting 10s before call...
15:02:03 [second:F3565405-20250611_Pharma Deutschland_Call for Evidence_Biotech Act.pdf] call OK
15:02:03 [third:F3565405-20250611_Pharma Deutschland_Call for Evidence_Biotech Act.pdf] waiting 10s before call...
15:02:16 [third:F3565405-20250611_Pharma Deutschland_Call for Evidence_Biotech Act.pdf] call OK

Processing documents:  85%|████████▍ | 126/149 [1:31:31<17:07, 44.67s/doc, F3565413-20250611IPAEUROPE Biotech Act Call for Evidence.pdf]

15:02:16 [first:F3565413-20250611IPAEUROPE Biotech Act Call for Evidence.pdf] waiting 10s before call...
15:02:30 [first:F3565413-20250611IPAEUROPE Biotech Act Call for Evidence.pdf] call OK
15:02:30 [second:F3565413-20250611IPAEUROPE Biotech Act Call for Evidence.pdf] waiting 10s before call...
15:02:43 [second:F3565413-20250611IPAEUROPE Biotech Act Call for Evidence.pdf] call OK
15:02:43 [third:F3565413-20250611IPAEUROPE Biotech Act Call for Evidence.pdf] waiting 10s before call...
15:02:56 [third:F3565413-20250611IPAEUROPE Biotech Act Call for Evidence.pdf] call OK

Processing documents:  85%|████████▌ | 127/149 [1:32:11<15:50, 43.21s/doc, F3565422-EU Biotech Act_CSL Response.pdf]

15:02:56 [first:F3565422-EU Biotech Act_CSL Response.pdf] waiting 10s before call...
15:03:15 [first:F3565422-EU Biotech Act_CSL Response.pdf] call OK
15:03:15 [second:F3565422-EU Biotech Act_CSL Response.pdf] waiting 10s before call...
15:03:30 [second:F3565422-EU Biotech Act_CSL Response.pdf] call OK
15:03:30 [third:F3565422-EU Biotech Act_CSL Response.pdf] waiting 10s before call...
15:03:45 [third:F3565422-EU Biotech Act_CSL Response.pdf] call OK

Processing documents:  86%|████████▌ | 128/149 [1:33:01<15:48, 45.18s/doc, F3565426-AmchamEU_aeu_call_for_evidence_response_on_biotech_act.pdf]

15:03:45 [first:F3565426-AmchamEU_aeu_call_for_evidence_response_on_biotech_act.pdf] waiting 10s before call...
15:04:00 [first:F3565426-AmchamEU_aeu_call_for_evidence_response_on_biotech_act.pdf] call OK
15:04:00 [second:F3565426-AmchamEU_aeu_call_for_evidence_response_on_biotech_act.pdf] waiting 10s before call...
15:04:14 [second:F3565426-AmchamEU_aeu_call_for_evidence_response_on_biotech_act.pdf] call OK
15:04:14 [third:F3565426-AmchamEU_aeu_call_for_evidence_response_on_biotech_act.pdf] waiting 10s before call...
15:04:28 [third:F3565426-AmchamEU_aeu_call_for_evidence_response_on_biotech_act.pdf] call OK

Processing documents:  87%|████████▋ | 129/149 [1:33:43<14:44, 44.23s/doc, F3565431-Utrecht Region_Consultation European Commission Biotech Act.pdf]

15:04:28 [first:F3565431-Utrecht Region_Consultation European Commission Biotech Act.pdf] waiting 10s before call...
15:04:45 [first:F3565431-Utrecht Region_Consultation European Commission Biotech Act.pdf] call OK
15:04:45 [second:F3565431-Utrecht Region_Consultation European Commission Biotech Act.pdf] waiting 10s before call...
15:05:02 [second:F3565431-Utrecht Region_Consultation European Commission Biotech Act.pdf] call OK
15:05:02 [third:F3565431-Utrecht Region_Consultation European Commission Biotech Act.pdf] waiting 10s before call...
15:05:17 [third:F3565431-Utrecht Region_Consultation European Commission Biotech Act.pdf] call OK

Processing documents:  87%|████████▋ | 130/149 [1:34:32<14:30, 45.83s/doc, F3565435-Ecolab Position Paper on Supply Chain Resilience for Medicines and Boosting Biotechnology and Biomanufacturing in Europe.pdf]

[SAVED] checkpoint with 130 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\brussels_pp_results_checkpoint_20251103_150517.json
15:05:17 [first:F3565435-Ecolab Position Paper on Supply Chain Resilience for Medicines and Boosting Biotechnology and Biomanufacturing in Europe.pdf] waiting 10s before call...
15:05:35 [first:F3565435-Ecolab Position Paper on Supply Chain Resilience for Medicines and Boosting Biotechnology and Biomanufacturing in Europe.pdf] call OK
15:05:35 [second:F3565435-Ecolab Position Paper on Supply Chain Resilience for Medicines and Boosting Biotechnology and Biomanufacturing in Europe.pdf] waiting 10s before call...
15:05:51 [second:F3565435-Ecolab Position Paper on Supply Chain Resilience for Medicines and Boosting Biotechnology and Biomanufacturing in Europe.pdf] call OK
15:05:51 [third:F3565435-Ecolab Position Paper on Supply Chain Resilience for Medicines and Boosting Biotechnology and Biomanufacturing in Europe.pdf] waiting 10s before call...
15:06:04 [third:F3565435-Ecolab Position Paper on Supply Chain Resilience for Medicines and Boosting Biotechnology and Biomanufacturing in Europe.pdf] call OK

Processing documents:  88%|████████▊ | 131/149 [1:35:20<13:52, 46.26s/doc, F3565438-EIT Health response to the call for evidence on the Biotech Act.pdf]

15:06:04 [first:F3565438-EIT Health response to the call for evidence on the Biotech Act.pdf] waiting 10s before call...
15:06:21 [first:F3565438-EIT Health response to the call for evidence on the Biotech Act.pdf] call OK
15:06:21 [second:F3565438-EIT Health response to the call for evidence on the Biotech Act.pdf] waiting 10s before call...
15:06:37 [second:F3565438-EIT Health response to the call for evidence on the Biotech Act.pdf] call OK
15:06:37 [third:F3565438-EIT Health response to the call for evidence on the Biotech Act.pdf] waiting 10s before call...
15:06:51 [third:F3565438-EIT Health response to the call for evidence on the Biotech Act.pdf] call OK

Processing documents:  89%|████████▊ | 132/149 [1:36:07<13:09, 46.45s/doc, F3565441-Biotech Act - Call for evidence - FAMHP.pdf]

15:06:51 [first:F3565441-Biotech Act - Call for evidence - FAMHP.pdf] waiting 10s before call...
15:07:09 [first:F3565441-Biotech Act - Call for evidence - FAMHP.pdf] call OK
15:07:09 [second:F3565441-Biotech Act - Call for evidence - FAMHP.pdf] waiting 10s before call...
15:07:21 [second:F3565441-Biotech Act - Call for evidence - FAMHP.pdf] call OK
15:07:21 [third:F3565441-Biotech Act - Call for evidence - FAMHP.pdf] waiting 10s before call...
15:07:35 [third:F3565441-Biotech Act - Call for evidence - FAMHP.pdf] call OK

Processing documents:  89%|████████▉ | 133/149 [1:36:51<12:11, 45.70s/doc, F3565444-2025-06 EU Biotech Position_FINAL (3).pdf]

15:07:35 [first:F3565444-2025-06 EU Biotech Position_FINAL (3).pdf] waiting 10s before call...
15:07:54 [first:F3565444-2025-06 EU Biotech Position_FINAL (3).pdf] call OK
15:07:54 [second:F3565444-2025-06 EU Biotech Position_FINAL (3).pdf] waiting 10s before call...
15:08:08 [second:F3565444-2025-06 EU Biotech Position_FINAL (3).pdf] call OK
15:08:08 [third:F3565444-2025-06 EU Biotech Position_FINAL (3).pdf] waiting 10s before call...
15:08:21 [third:F3565444-2025-06 EU Biotech Position_FINAL (3).pdf] call OK

Processing documents:  90%|████████▉ | 134/149 [1:37:36<11:23, 45.60s/doc, F3565463-M-Bios White paper - Biotech Act proposal - key points 20250611-FINAL.pdf]

15:08:21 [first:F3565463-M-Bios White paper - Biotech Act proposal - key points 20250611-FINAL.pdf] waiting 10s before call...
15:08:39 [first:F3565463-M-Bios White paper - Biotech Act proposal - key points 20250611-FINAL.pdf] call OK
15:08:39 [second:F3565463-M-Bios White paper - Biotech Act proposal - key points 20250611-FINAL.pdf] waiting 10s before call...
15:08:59 [second:F3565463-M-Bios White paper - Biotech Act proposal - key points 20250611-FINAL.pdf] call OK
15:08:59 [third:F3565463-M-Bios White paper - Biotech Act proposal - key points 20250611-FINAL.pdf] waiting 10s before call...
15:09:12 [third:F3565463-M-Bios White paper - Biotech Act proposal - key points 20250611-FINAL.pdf] call OK

Processing documents:  91%|█████████ | 135/149 [1:38:27<11:01, 47.24s/doc, F3565466-Submission_Biotech_dsm-firmenich_11-6-2025.pdf]

15:09:12 [first:F3565466-Submission_Biotech_dsm-firmenich_11-6-2025.pdf] waiting 10s before call...
15:09:26 [first:F3565466-Submission_Biotech_dsm-firmenich_11-6-2025.pdf] call OK
15:09:26 [second:F3565466-Submission_Biotech_dsm-firmenich_11-6-2025.pdf] waiting 10s before call...
15:09:39 [second:F3565466-Submission_Biotech_dsm-firmenich_11-6-2025.pdf] call OK
15:09:39 [third:F3565466-Submission_Biotech_dsm-firmenich_11-6-2025.pdf] waiting 10s before call...
15:09:51 [third:F3565466-Submission_Biotech_dsm-firmenich_11-6-2025.pdf] call OK

Processing documents:  91%|█████████▏| 136/149 [1:39:07<09:44, 44.96s/doc, F3565477-CLTR_EUBiotechAct_Submission.pdf]

15:09:51 [first:F3565477-CLTR_EUBiotechAct_Submission.pdf] waiting 10s before call...
15:10:08 [first:F3565477-CLTR_EUBiotechAct_Submission.pdf] call OK
15:10:08 [second:F3565477-CLTR_EUBiotechAct_Submission.pdf] waiting 10s before call...
15:10:23 [second:F3565477-CLTR_EUBiotechAct_Submission.pdf] call OK
15:10:23 [third:F3565477-CLTR_EUBiotechAct_Submission.pdf] waiting 10s before call...
15:10:41 [third:F3565477-CLTR_EUBiotechAct_Submission.pdf] call OK

Processing documents:  92%|█████████▏| 137/149 [1:39:56<09:15, 46.29s/doc, F3565481-EURORDIS Response Biotech Act CfE.pdf]

15:10:41 [first:F3565481-EURORDIS Response Biotech Act CfE.pdf] waiting 10s before call...
15:10:59 [first:F3565481-EURORDIS Response Biotech Act CfE.pdf] call OK
15:10:59 [second:F3565481-EURORDIS Response Biotech Act CfE.pdf] waiting 10s before call...
15:11:14 [second:F3565481-EURORDIS Response Biotech Act CfE.pdf] call OK
15:11:14 [third:F3565481-EURORDIS Response Biotech Act CfE.pdf] waiting 10s before call...
15:11:29 [third:F3565481-EURORDIS Response Biotech Act CfE.pdf] call OK

Processing documents:  93%|█████████▎| 138/149 [1:40:44<08:35, 46.88s/doc, F3565484-Preparation input EU Biotech Act - Call for evidence - 11062025.docx]

15:11:29 [first:F3565484-Preparation input EU Biotech Act - Call for evidence - 11062025.docx] waiting 10s before call...
15:11:50 [first:F3565484-Preparation input EU Biotech Act - Call for evidence - 11062025.docx] call OK
15:11:50 [second:F3565484-Preparation input EU Biotech Act - Call for evidence - 11062025.docx] waiting 10s before call...
15:12:04 [second:F3565484-Preparation input EU Biotech Act - Call for evidence - 11062025.docx] call OK
15:12:04 [third:F3565484-Preparation input EU Biotech Act - Call for evidence - 11062025.docx] waiting 10s before call...
15:12:16 [third:F3565484-Preparation input EU Biotech Act - Call for evidence - 11062025.docx] call OK

Processing documents:  93%|█████████▎| 139/149 [1:41:32<07:50, 47.03s/doc, F3565496-2025 06 11 Stockholm Trio_input_Biotech Act_FINAL.pdf]

15:12:16 [first:F3565496-2025 06 11 Stockholm Trio_input_Biotech Act_FINAL.pdf] waiting 10s before call...
15:12:32 [first:F3565496-2025 06 11 Stockholm Trio_input_Biotech Act_FINAL.pdf] call OK
15:12:32 [second:F3565496-2025 06 11 Stockholm Trio_input_Biotech Act_FINAL.pdf] waiting 10s before call...
15:12:46 [second:F3565496-2025 06 11 Stockholm Trio_input_Biotech Act_FINAL.pdf] call OK
15:12:46 [third:F3565496-2025 06 11 Stockholm Trio_input_Biotech Act_FINAL.pdf] waiting 10s before call...
15:13:00 [third:F3565496-2025 06 11 Stockholm Trio_input_Biotech Act_FINAL.pdf] call OK

Processing documents:  94%|█████████▍| 140/149 [1:42:16<06:55, 46.20s/doc, F3565499-SecureDNA Evidence for EU Biotech Act 06.11.2025.pdf]

[SAVED] checkpoint with 140 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\brussels_pp_results_checkpoint_20251103_151300.json
15:13:01 [first:F3565499-SecureDNA Evidence for EU Biotech Act 06.11.2025.pdf] waiting 10s before call...
15:13:13 [first:F3565499-SecureDNA Evidence for EU Biotech Act 06.11.2025.pdf] call OK
15:13:13 [second:F3565499-SecureDNA Evidence for EU Biotech Act 06.11.2025.pdf] waiting 10s before call...
15:13:26 [second:F3565499-SecureDNA Evidence for EU Biotech Act 06.11.2025.pdf] call OK
15:13:26 [third:F3565499-SecureDNA Evidence for EU Biotech Act 06.11.2025.pdf] waiting 10s before call...
15:13:43 [third:F3565499-SecureDNA Evidence for EU Biotech Act 06.11.2025.pdf] call OK

Processing documents:  95%|█████████▍| 141/149 [1:42:58<06:00, 45.10s/doc, F3565503-New Genomic Techniques applied to food cultures a po w erful contribution to inno v a ti v e, safe, and sustainable food products.pdf]

15:13:43 [first:F3565503-New Genomic Techniques applied to food cultures a po w erful contribution to inno v a ti v e, safe, and sustainable food products.pdf] waiting 10s before call...
15:14:00 [first:F3565503-New Genomic Techniques applied to food cultures a po w erful contribution to inno v a ti v e, safe, and sustainable food products.pdf] call OK
15:14:00 [second:F3565503-New Genomic Techniques applied to food cultures a po w erful contribution to inno v a ti v e, safe, and sustainable food products.pdf] waiting 10s before call...
15:14:13 [second:F3565503-New Genomic Techniques applied to food cultures a po w erful contribution to inno v a ti v e, safe, and sustainable food products.pdf] call OK
15:14:13 [third:F3565503-New Genomic Techniques applied to food cultures a po w erful contribution to inno v a ti v e, safe, and sustainable food products.pdf] waiting 10s before call...
15:14:25 [third:F3565503-New Genomic Techniques applied to food cultures a po w erful contribution to inno v a ti v e, safe, and sustainable food products.pdf] call OK

Processing documents:  95%|█████████▌| 142/149 [1:43:41<05:09, 44.22s/doc, F3565509-DK feedback to Call for Evidence for Biotech Act.pdf]

15:14:25 [first:F3565509-DK feedback to Call for Evidence for Biotech Act.pdf] waiting 10s before call...
15:14:45 [first:F3565509-DK feedback to Call for Evidence for Biotech Act.pdf] call OK
15:14:45 [second:F3565509-DK feedback to Call for Evidence for Biotech Act.pdf] waiting 10s before call...
15:15:00 [second:F3565509-DK feedback to Call for Evidence for Biotech Act.pdf] call OK
15:15:00 [third:F3565509-DK feedback to Call for Evidence for Biotech Act.pdf] waiting 10s before call...
15:15:13 [third:F3565509-DK feedback to Call for Evidence for Biotech Act.pdf] call OK

Processing documents:  96%|█████████▌| 143/149 [1:44:29<04:32, 45.41s/doc, F3565510-Have your Say Plantum.pdf]

15:15:13 [first:F3565510-Have your Say Plantum.pdf] waiting 10s before call...
15:15:27 [first:F3565510-Have your Say Plantum.pdf] call OK
15:15:27 [second:F3565510-Have your Say Plantum.pdf] waiting 10s before call...
15:15:41 [second:F3565510-Have your Say Plantum.pdf] call OK
15:15:41 [third:F3565510-Have your Say Plantum.pdf] waiting 10s before call...
15:15:53 [third:F3565510-Have your Say Plantum.pdf] call OK

Processing documents:  97%|█████████▋| 144/149 [1:45:08<03:38, 43.66s/doc, F3565520-201809-ST0918EN-tyfa (1).pdf]

15:15:53 [first:F3565520-201809-ST0918EN-tyfa (1).pdf] waiting 10s before call...
15:16:06 [first:F3565520-201809-ST0918EN-tyfa (1).pdf] call OK
15:16:06 [second:F3565520-201809-ST0918EN-tyfa (1).pdf] waiting 10s before call...
15:16:19 [second:F3565520-201809-ST0918EN-tyfa (1).pdf] call OK
15:16:19 [third:F3565520-201809-ST0918EN-tyfa (1).pdf] waiting 10s before call...
15:16:31 [third:F3565520-201809-ST0918EN-tyfa (1).pdf] call OK

Processing documents:  97%|█████████▋| 145/149 [1:45:47<02:48, 42.03s/doc, F3565521-06112025_GLBS_Biotech_Act_Consultation_Contribution.pdf]

15:16:31 [first:F3565521-06112025_GLBS_Biotech_Act_Consultation_Contribution.pdf] waiting 10s before call...
15:16:55 [first:F3565521-06112025_GLBS_Biotech_Act_Consultation_Contribution.pdf] call OK
15:16:55 [second:F3565521-06112025_GLBS_Biotech_Act_Consultation_Contribution.pdf] waiting 10s before call...
15:17:09 [second:F3565521-06112025_GLBS_Biotech_Act_Consultation_Contribution.pdf] call OK
15:17:09 [third:F3565521-06112025_GLBS_Biotech_Act_Consultation_Contribution.pdf] waiting 10s before call...
15:17:21 [third:F3565521-06112025_GLBS_Biotech_Act_Consultation_Contribution.pdf] call OK

Processing documents:  98%|█████████▊| 146/149 [1:46:36<02:13, 44.37s/doc, F3565526-BBEPP statement_BiotechAct_June2025.pdf]

15:17:21 [first:F3565526-BBEPP statement_BiotechAct_June2025.pdf] waiting 10s before call...
15:17:39 [first:F3565526-BBEPP statement_BiotechAct_June2025.pdf] call OK
15:17:39 [second:F3565526-BBEPP statement_BiotechAct_June2025.pdf] waiting 10s before call...
15:17:55 [second:F3565526-BBEPP statement_BiotechAct_June2025.pdf] call OK
15:17:55 [third:F3565526-BBEPP statement_BiotechAct_June2025.pdf] waiting 10s before call...
15:18:07 [third:F3565526-BBEPP statement_BiotechAct_June2025.pdf] call OK

Processing documents:  99%|█████████▊| 147/149 [1:47:23<01:29, 44.93s/doc, F3565532-BiotechAct_VPHi.pdf]

15:18:07 [first:F3565532-BiotechAct_VPHi.pdf] waiting 10s before call...
15:18:20 [first:F3565532-BiotechAct_VPHi.pdf] call OK
15:18:20 [second:F3565532-BiotechAct_VPHi.pdf] waiting 10s before call...
15:18:33 [second:F3565532-BiotechAct_VPHi.pdf] call OK
15:18:33 [third:F3565532-BiotechAct_VPHi.pdf] waiting 10s before call...
15:18:46 [third:F3565532-BiotechAct_VPHi.pdf] call OK

Processing documents:  99%|█████████▉| 148/149 [1:48:02<00:43, 43.18s/doc, F3582124-Q12_cfe_biotech_act_Fondazione Telethon.docx]

15:18:46 [first:F3582124-Q12_cfe_biotech_act_Fondazione Telethon.docx] waiting 10s before call...
15:19:05 [first:F3582124-Q12_cfe_biotech_act_Fondazione Telethon.docx] call OK
15:19:05 [second:F3582124-Q12_cfe_biotech_act_Fondazione Telethon.docx] waiting 10s before call...
15:19:19 [second:F3582124-Q12_cfe_biotech_act_Fondazione Telethon.docx] call OK
15:19:19 [third:F3582124-Q12_cfe_biotech_act_Fondazione Telethon.docx] waiting 10s before call...
15:19:31 [third:F3582124-Q12_cfe_biotech_act_Fondazione Telethon.docx] call OK

Processing documents: 100%|██████████| 149/149 [1:48:47<00:00, 43.81s/doc, F3582124-Q12_cfe_biotech_act_Fondazione Telethon.docx]

[DONE] All results saved to C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\brussels_pp_results.json

In [29]:
results[:5]

[{'ATMP': ['Biotech firms report difficulty navigating EU regulatory environments, particularly for clinical trials, GMOs, and advanced therapies. (page 4)',
   'The European Biotech Act was introduced in response to these challenges and is expected to form the legislative backbone of a broader European life sciences strategy. It seeks to simplify complex regulatory pathways, streamline product development pipelines, and harmonize fragmented biotech policies across Member States. (page 4)'],
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': ['Biotech firms report difficulty navigating EU regulatory environments, particularly for clinical trials, GMOs, and advanced therapies. Regulatory divergence across Member States results in unnecessary costs, slow time-to-market, and underutilized research findings. (page 4)',
   'The EU biotech investment landscape is dominated by small, fragmented funding mechanisms, with only 5% of global venture capital compared to 52% in the U.S. (page 4)',
   'Public-private partnerships are underdeveloped, and late-stage capital remains scarce. High-impact firms often exit to U.S. markets where capital access, listing incentives, and regulatory clarity are more favorable. (page 4)'],
  'Access_to_Markets_strategies': ['A streamlined and science-responsive risk assessment framework is essential to boost EU attractiveness for biotech R&D. (page 4)',
   'The European Biotech Act must resolve these bottlenecks through investment matching schemes, incentive-linked grants, and EU stock market harmonization. (page 4)',
   'Introduce a biotech-specific fast-track authorization system modeled after the EMA PRIME scheme. Create a “Biotech Passport” that ensures mutual recognition of assessments across Member States, reducing delays in multi-country trials and product deployment. (page 6)'],
  'VC_Investments_IPO': ['The EU biotech investment landscape is dominated by small, fragmented funding mechanisms, with only 5% of global venture capital compared to 52% in the U.S. (page 4)',
   'Public-private partnerships are underdeveloped, and late-stage capital remains scarce. High-impact firms often exit to U.S. markets where capital access, listing incentives, and regulatory clarity are more favorable. (page 4)',
   'Establish an EU Biotech Investment Facility with blended finance instruments, equity guarantees, and scale-up funding. Partner with European stock exchanges to facilitate IPO pathways for biotech firms and reduce reliance on U.S. listings. (page 6)'],
  'Manufacturing_Capabilities': ['While the EU is a leader in biologics manufacturing, it remains vulnerable to geopolitical supply chain risks and foreign investment outflows. Dual-use biotech technologies in health and agriculture further raise security concerns. (page 6)',
   'Launch a Biomanufacturing Sovereignty Fund to support onshore production capacity for APIs, enzymes, and cell-based products. Simplify permitting and create industrial biozones with dedicated infrastructure and environmental oversight.. (page 7)'],
  'Incubation_and_Acceleration': None,
  'Talent_Retention': ['Fund EU-wide talent fellowships for bioengineers, data scientists, and regulatory professionals. Embed entrepreneurship curricula within Horizon Europe and Erasmus+ to upskill PhD candidates in innovation management and commercialization. (page 7)'],
  'Upskilling_Reskilling': ['Embed entrepreneurship curricula within Horizon Europe and Erasmus+ to upskill PhD candidates in innovation management and commercialization. (page 7)',
   'Programs focused on mentoring, mobility, and commercial training must be integral to the Act. (page 5)'],
  'AI_Challenges': ['However, many biotech SMEs lack access to the European Health Data Space (EHDS), federated biobanks, or AI testing environments. (page 5)',
   'Ensure biotech-specific access to the EHDS, federated datasets, and AI Factories. Mandate interoperability standards and ethical safeguards. (page 7)'],
  'AI_Development_and_Deployment': ['The biotech revolution depends increasingly on access to real-world data, AI-enhanced simulations, and supercomputing resources. (page 5)',
   'Academic literature highlights the role of machine learning in expediting drug discovery, protein folding, and metabolic pathway design (Reis et al., 2020). (page 5)',
   'The Biotech Act must integrate the EU AI Strategy and EHDS with dedicated capacity for biotech applications. (page 5)',
   'Strengthen Data Infrastructure and AI-Driven Biotech R&D (page 6)',
   'Ensure biotech-specific access to the EHDS, federated datasets, and AI Factories. Mandate interoperability standards and ethical safeguards. Support the creation of an EU Biotech-AI Alliance to encourage cross-sector R&D. (page 7)'],
  'Global_Collaboration': ['Fund EU-wide talent fellowships for bioengineers, data scientists, and regulatory professionals. Embed entrepreneurship curricula within Horizon Europe and Erasmus+ to upskill PhD candidates in innovation management and commercialization. (page 7)',
   'The success of this Act depends on strong coordination across institutions, Member States, academia, industry, and civil society. RareGen Youth Network urges the European Commission to prioritize youth-led innovation, SME equity, and cross-sectoral collaboration in implementation. (page 8)'],
  'Biosecurity': ['While the EU is a leader in biologics manufacturing, it remains vulnerable to geopolitical supply chain risks and foreign investment outflows. Dual-use biotech technologies in health and agriculture further raise security concerns. (page 6)',
   'The White Paper for European Defence: Readiness 2030 calls for a biotechnology security strategy to address dual-use risks, IP protection, and international standards. The EU must incentivize regional manufacturing, de-risk supply chains, and protect strategic innovation. (page 6)'],
  'Biosecurity_Nucleic_Acid_Screening': None},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': ['Despite its proven benefits, biocontrol remains underutilized in the EU due to regulatory bottlenecks, fragmented market access, and limited public awareness. An unnecessarily lengthy and complex authorization process for biocontrol products leads to time to market constraints and competitive disadvantages. Regulation (EU) 1107/2009 on the placing on the market of EU Plant Protection Products (PPPs) has been designed for chemical pesticides and is not well adapted to biological PPPs, leading to unnecessary delays in their evaluations (up to 10 years from submission to market, compared to 2-3 years in other global jurisdictions) The Biotech Act must address these barriers to unlock the full potential of biocontrol as a pillar of sustainable biotechnology. (page 2)',
   'The current regulatory framework for biocontrol products is often modeled after chemical pesticide legislation, which is ill-suited to the nature and risk profile of biological solutions. This misalignment results in: Long and costly approval processes (often exceeding 7 years); Inconsistent implementation across Member States; Limited incentives for firms to innovate. (page 2)'],
  'Access_to_Markets_strategies': ['Immediate simplification measures should be introduced in any upcoming legislative initiative from the European Commission to make biocontrol solutions available to farmers now, including a harmonized EU wide legal definition of biocontrol PPPs accompanied with measures to amend the treatment of this defined group of PPPs within Regulation (EU) 1107/2009 outlined below. Specifically, we call for: Re-instatement of provisional authorization (art 30) for PPPs containing only active biocontrol substances. Removal of re-registration process for biocontrol Facilitate label expansion for biocontrol PPPs expansion of biocontrol PPPs can increase their availability in arable crops. (page 2)',
   "A system of mutual recognition 'automatically' applied to all Member States could ensure a single market for biocontrol within the EU. Establishing a priority lane for biocontrol solutions will also allow Member States to deliver these alternatives to the market faster. (page 3)",
   "Post 2035, biocontrol is expected to be the dominant type of pest control. In this situation, a future-proof new regulatory framework adapted to biocontrol is needed to maintain the competitiveness and resilience of the agricultural and crop protection markets in Europe. In doing so, the Commission shall assess the need to establish a dedicated Single Agency for biocontrol active substances and products; as well as other key features such as (i) moving away from the current zonal system established under 1107/2009 so that there would be instead one single zone for biocontrol products ('one market, one assessment') and (ii) developing a risk assessment procedure fully adapted for all types of biocontrol products. (page 3)"],
  'VC_Investments_IPO': ['At this point we deem important for the EU to find ways to promote an ecosystem for the entrepreneurial economy, including creating a supportive environment to raise private finance for EU companies at a competitive scale. Biotech clusters need to be significant and meaningful on a continental scale to compete globally. (page 3)'],
  'Manufacturing_Capabilities': ['More specifically, the EU needs to create EU innovation hubs for biocontrol and biomanufacturing, linking research institutions, startups, and industry. (page 2)'],
  'Incubation_and_Acceleration': ['More specifically, the EU needs to create EU innovation hubs for biocontrol and biomanufacturing, linking research institutions, startups, and industry. (page 2)'],
  'Talent_Retention': None,
  'Upskilling_Reskilling': ['Support training and advisory services for farmers and agronomists on the use of biocontrol products. (page 2)'],
  'AI_Challenges': None,
  'AI_Development_and_Deployment': ['Moreover, supporting public-private partnerships to co-develop next-generation biocontrol technologies, including AI-driven pest monitoring and precision application tools can boost innovation and unlock the full potential of such technologies. (page 2)'],
  'Global_Collaboration': ['Biotech clusters need to be significant and meaningful on a continental scale to compete globally. (page 2)'],
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': ['Examples include misaligned provisions in the legislation concerning Contained Use of Genetically Modified Microorganisms, Workers’ Protection or Animal By-products. This paper aims to outline these challenges for EU biotechnology and pharmaceutical companies, labs, startups and academics in terms of regulatory complexity, which translates into increased costs, delays and loss of competitiveness. (page 4)',
   'The GMO legislation regulates genome-edited organisms in which genetic alterations (mutations) have been introduced that exist in nature or can arise through conventional breeding. This leads to a situation where organisms with the same mutation – one made through genome editing and the other made using conventional methods – are treated differently. (page 4)',
   'For plants, new NGT (New Genomic Techniques, also referred to as Genome-edited or GE) legislation is being negotiated that should be better fit for purpose, but for GE micro-organisms no alternative legislation has been proposed yet. (page 4)'],
  'Access_to_Markets_strategies': ['With the upcoming Biotech Act, the European Union has the opportunity to create a streamlined and predictable product-based legislative environment taking into account the specifics of either classically genetically modified or genome-edited organisms. Specifically for genome-edited (GE) micro-organisms, a separate regulatory framework that treats these micro-organisms in the same way as wild-type micro-organisms should be created, thereby removing them from the scope of the GMO legislation (both the contained use and deliberate release legislation). (page 4)',
   'It could also be considered to harmonize various GMO definitions in light of the 2018 CJEU ruling (6) and the long-existing definition of Living Modified Organism (LMO) as described in the Cartagena Protocol on Biosafety (7). (page 4)',
   'With science-based and predictable legislative frameworks for GMO’s and GE organisms, Europe can maintain its position in the front of the biotechnology race, whether it is for medicines, food and industrial processes. For both NGT plants and GE micro-organisms this would allow for reduced administrative effort while still maintaining the high product safety enshrined in Europe’s core values. (page 4)'],
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': ['Founded in 1996, the European Biosafety Association (EBSA) is a professional organization that focuses on biosafety and biosecurity. It serves as a platform for professionals across Europe, and beyond, to share knowledge, collaborate, and promote best practices in the field. (page 1)',
   'Founded in 1996, the European Biosafety Association (EBSA) is a professional organization that focuses on biosafety and biosecurity. It serves as a platform for professionals across Europe and beyond to share knowledge, collaborate, and promote best practices in the field. (page 3)'],
  'Biosecurity': ["Founded in 1996, the European Biosafety Association (EBSA) is a professional organization that focuses on biosafety and biosecurity. It serves as a platform for professionals across Europe, and beyond, to share knowledge, collaborate, and promote best practices in the field.  EBSA supports the responsible and sustainable development of Europe's life sciences and education sectors through risk-based management of potentially hazardous biological materials. Committed to collaborating with the European Commission, EBSA works to enhance biosafety and biosecurity standard practices while fostering innovation and competitiveness across biotechnology, and human, animal, and plant health sectors.  EBSA welcomes the advancing collaboration with the European Commission to continuously uphold and strengthen biosafety and biosecurity standards, with a focus on the following aspects:   (page 1)",
   'Furthermore, EBSA is dedicated to promoting and disseminating best practices in biosafety and biosecurity among its members and in the greater professional, research and industrial communities. The association actively fosters dialogue on emerging challenges and plays an advisory role in shaping practices to mitigate risks associated with biological agents and materials. (page 3)'],
  'Biosecurity_Nucleic_Acid_Screening': None},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': ['This is crucial because, under current frameworks, each phage might otherwise require separate approval, posing a business disincentive. (page 2)',
   'Currently, adding a new phage could be treated as a new product, since each phage is an active substance requiring review. That is a “major regulatory issue” and would severely slow down improvements to phage therapies. (page 5)'],
  'Access_to_Markets_strategies': ['The amendment thus aligns with the broader EU strategy to fix “market failures, especially in the development of priority antimicrobials” by broadening the eligible modalities to include phage-based medicines. (page 2)',
   'The sandbox plan shall detail how requirements are adapted (e.g., bespoke manufacturing validations, alternative trial endpoints) and how safety is ensured for such phage therapies. (page 4)',
   'Furthermore, the sandbox may facilitate the establishment of certified phage banks, where pre-characterized phages undergo regulatory validation for rapid deployment in clinical settings, including compassionate use frameworks. (page 4)',
   'The sandbox can provide “targeted derogations” from standard rules, such as allowing adaptive trial protocols or n-of-1 trials with pooled data, while still under authority supervision. (page 4)',
   'By tailoring variation rules to phage cocktails, we maintain regulatory rigor (each change reviewed by authorities) but avoid unnecessary duplication of full dossiers. (page 5)'],
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': ['In particular, medicinal products based on bacteriophages may be considered for a sandbox when their personalization or novel manufacturing methods make standard development pathways challenging. (page 2)',
   'The sandbox plan shall detail how requirements are adapted (e.g., bespoke manufacturing validations, alternative trial endpoints) and how safety is ensured for such phage therapies. (page 3)',
   'This approach has precedent: Belgium has effectively created a phage therapy framework by treating personalized phages as magistral (compounded) preparations. In Belgium, phages are prepared per prescription in a pharmacy with quality oversight, bypassing full pharmaceutical marketing authorization. This “magistral phage” model – allowed under national law – provides production and handling flexibility (e.g. not forcing strict GMP) for personalized phages. (page 3)'],
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None}]

In [30]:
FINAL_JSON_PATH = Path(output_folder) / "brussels_final_results.json"

try:
    # dump your list of dictionaries (results) as a single JSON array
    with open(FINAL_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    print(f"[DONE] Final merged results saved to {FINAL_JSON_PATH}")
except Exception as e:
    print(f"[ERROR] Failed to save final JSON: {e}")

[DONE] Final merged results saved to C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\brussels_final_results.json

In [31]:
import pandas as pd
from pathlib import Path

def _tolist(x):
    if isinstance(x, list):
        return x
    return [x] if x else []

# Align results to docs (safe even if lengths differ)
rows = []
for doc_name, r in zip(docs, results):
    title = Path(doc_name).stem  # filename without extension

    rows.append({
        "title": title,  # <-- first column from docs
        # --- First group (BRUSSEL_FIRST_PROMPT) ---
        "ATMP": _tolist(r.get("ATMP")),
        "ATMP_gene_therapies": _tolist(r.get("ATMP_gene_therapies")),
        "ATMP_cell_therapies": _tolist(r.get("ATMP_cell_therapies")),
        "ATMP_tissue_engineered_products": _tolist(r.get("ATMP_tissue_engineered_products")),
        "ATMP_personalised_medicine": _tolist(r.get("ATMP_personalised_medicine")),
        "Access_to_Markets_hurdles": _tolist(r.get("Access_to_Markets_hurdles")),
        "Access_to_Markets_strategies": _tolist(r.get("Access_to_Markets_strategies")),
        "VC_Investments_IPO": _tolist(r.get("VC_Investments_IPO")),

        # --- Second group (BRUSSEL_SECOND_PROMPT) ---
        "Manufacturing_Capabilities": _tolist(r.get("Manufacturing_Capabilities")),
        "Incubation_and_Acceleration": _tolist(r.get("Incubation_and_Acceleration")),
        "Workforce_Development": _tolist(r.get("Workforce_Development")),

        # --- Third group (BRUSSEL_THIRD_PROMPT) ---
        "AI_Challenges": _tolist(r.get("AI_Challenges")),
        "AI_Development_and_Deployment": _tolist(r.get("AI_Development_and_Deployment")),
        "Global_Collaboration": _tolist(r.get("Global_Collaboration")),
        "Biosecurity": _tolist(r.get("Biosecurity")),
        "Biosecurity_Nucleic_Acid_Screening": _tolist(r.get("Biosecurity_Nucleic_Acid_Screening")),
    })

df = pd.DataFrame(
    rows,
    columns=[
        "title",  # first column
        "ATMP", "ATMP_gene_therapies", "ATMP_cell_therapies",
        "ATMP_tissue_engineered_products", "ATMP_personalised_medicine",
        "Access_to_Markets_hurdles", "Access_to_Markets_strategies", "VC_Investments_IPO",
        "Manufacturing_Capabilities", "Incubation_and_Acceleration", "Workforce_Development",
        "AI_Challenges", "AI_Development_and_Deployment", "Global_Collaboration",
        "Biosecurity", "Biosecurity_Nucleic_Acid_Screening"
    ]
)

In [32]:
# Split the existing 'title' column into two new columns: 'reference' and 'title'
df[["reference", "title"]] = df["title"].str.split("-", n=1, expand=True)

# Strip whitespace
df["reference"] = df["reference"].str.strip()
df["title"] = df["title"].str.strip()

# Move 'reference' to be the first column
cols = ["reference"] + [c for c in df.columns if c != "reference"]
df = df[cols]
df.head()

,reference,title,ATMP,ATMP_gene_therapies,ATMP_cell_therapies,ATMP_tissue_engineered_products,ATMP_personalised_medicine,Access_to_Markets_hurdles,Access_to_Markets_strategies,VC_Investments_IPO,Manufacturing_Capabilities,Incubation_and_Acceleration,Workforce_Development,AI_Challenges,AI_Development_and_Deployment,Global_Collaboration,Biosecurity,Biosecurity_Nucleic_Acid_Screening
0,F3552803,Feedback Paper On the European Biotech Act,[Biotech firms report difficulty navigating EU...,[],[],[],[],[Biotech firms report difficulty navigating EU...,[A streamlined and science-responsive risk ass...,[The EU biotech investment landscape is domina...,[While the EU is a leader in biologics manufac...,[],[],"[However, many biotech SMEs lack access to the...",[The biotech revolution depends increasingly o...,[Fund EU-wide talent fellowships for bioengine...,[While the EU is a leader in biologics manufac...,[]
1,F3553888,cpme.2025-092.FINAL.Statement.Biotech.Act,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]
2,F3554271,Koppert submission for the biotech act consult...,[],[],[],[],[],"[Despite its proven benefits, biocontrol remai...",[Immediate simplification measures should be i...,[At this point we deem important for the EU to...,"[More specifically, the EU needs to create EU ...","[More specifically, the EU needs to create EU ...",[],[],"[Moreover, supporting public-private partnersh...",[Biotech clusters need to be significant and m...,[],[]
3,F3559517,EBSA Position Paper - OMNIBUS - 20250416 (1),[],[],[],[],[],[Examples include misaligned provisions in the...,"[With the upcoming Biotech Act, the European U...",[],[],[],[],[],[],"[Founded in 1996, the European Biosafety Assoc...","[Founded in 1996, the European Biosafety Assoc...",[]
4,F3561326,PhageEU Proposals for Amendments_Pharmaceutica...,[],[],[],[],[],"[This is crucial because, under current framew...",[The amendment thus aligns with the broader EU...,[],"[In particular, medicinal products based on ba...",[],[],[],[],[],[],[]

In [40]:
# assuming `results` and `df` have the same order and length
for i, r in enumerate(results):
    if i < len(df):
        r["reference"] = df.loc[i, "reference"]
        r["title"] = df.loc[i, "title"]

In [41]:
len(results)

149

In [42]:
results[:5]

[{'ATMP': ['Biotech firms report difficulty navigating EU regulatory environments, particularly for clinical trials, GMOs, and advanced therapies. (page 4)',
   'The European Biotech Act was introduced in response to these challenges and is expected to form the legislative backbone of a broader European life sciences strategy. It seeks to simplify complex regulatory pathways, streamline product development pipelines, and harmonize fragmented biotech policies across Member States. (page 4)'],
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': ['Biotech firms report difficulty navigating EU regulatory environments, particularly for clinical trials, GMOs, and advanced therapies. Regulatory divergence across Member States results in unnecessary costs, slow time-to-market, and underutilized research findings. (page 4)',
   'The EU biotech investment landscape is dominated by small, fragmented funding mechanisms, with only 5% of global venture capital compared to 52% in the U.S. (page 4)',
   'Public-private partnerships are underdeveloped, and late-stage capital remains scarce. High-impact firms often exit to U.S. markets where capital access, listing incentives, and regulatory clarity are more favorable. (page 4)'],
  'Access_to_Markets_strategies': ['A streamlined and science-responsive risk assessment framework is essential to boost EU attractiveness for biotech R&D. (page 4)',
   'The European Biotech Act must resolve these bottlenecks through investment matching schemes, incentive-linked grants, and EU stock market harmonization. (page 4)',
   'Introduce a biotech-specific fast-track authorization system modeled after the EMA PRIME scheme. Create a “Biotech Passport” that ensures mutual recognition of assessments across Member States, reducing delays in multi-country trials and product deployment. (page 6)'],
  'VC_Investments_IPO': ['The EU biotech investment landscape is dominated by small, fragmented funding mechanisms, with only 5% of global venture capital compared to 52% in the U.S. (page 4)',
   'Public-private partnerships are underdeveloped, and late-stage capital remains scarce. High-impact firms often exit to U.S. markets where capital access, listing incentives, and regulatory clarity are more favorable. (page 4)',
   'Establish an EU Biotech Investment Facility with blended finance instruments, equity guarantees, and scale-up funding. Partner with European stock exchanges to facilitate IPO pathways for biotech firms and reduce reliance on U.S. listings. (page 6)'],
  'Manufacturing_Capabilities': ['While the EU is a leader in biologics manufacturing, it remains vulnerable to geopolitical supply chain risks and foreign investment outflows. Dual-use biotech technologies in health and agriculture further raise security concerns. (page 6)',
   'Launch a Biomanufacturing Sovereignty Fund to support onshore production capacity for APIs, enzymes, and cell-based products. Simplify permitting and create industrial biozones with dedicated infrastructure and environmental oversight.. (page 7)'],
  'Incubation_and_Acceleration': None,
  'Talent_Retention': ['Fund EU-wide talent fellowships for bioengineers, data scientists, and regulatory professionals. Embed entrepreneurship curricula within Horizon Europe and Erasmus+ to upskill PhD candidates in innovation management and commercialization. (page 7)'],
  'Upskilling_Reskilling': ['Embed entrepreneurship curricula within Horizon Europe and Erasmus+ to upskill PhD candidates in innovation management and commercialization. (page 7)',
   'Programs focused on mentoring, mobility, and commercial training must be integral to the Act. (page 5)'],
  'AI_Challenges': ['However, many biotech SMEs lack access to the European Health Data Space (EHDS), federated biobanks, or AI testing environments. (page 5)',
   'Ensure biotech-specific access to the EHDS, federated datasets, and AI Factories. Mandate interoperability standards and ethical safeguards. (page 7)'],
  'AI_Development_and_Deployment': ['The biotech revolution depends increasingly on access to real-world data, AI-enhanced simulations, and supercomputing resources. (page 5)',
   'Academic literature highlights the role of machine learning in expediting drug discovery, protein folding, and metabolic pathway design (Reis et al., 2020). (page 5)',
   'The Biotech Act must integrate the EU AI Strategy and EHDS with dedicated capacity for biotech applications. (page 5)',
   'Strengthen Data Infrastructure and AI-Driven Biotech R&D (page 6)',
   'Ensure biotech-specific access to the EHDS, federated datasets, and AI Factories. Mandate interoperability standards and ethical safeguards. Support the creation of an EU Biotech-AI Alliance to encourage cross-sector R&D. (page 7)'],
  'Global_Collaboration': ['Fund EU-wide talent fellowships for bioengineers, data scientists, and regulatory professionals. Embed entrepreneurship curricula within Horizon Europe and Erasmus+ to upskill PhD candidates in innovation management and commercialization. (page 7)',
   'The success of this Act depends on strong coordination across institutions, Member States, academia, industry, and civil society. RareGen Youth Network urges the European Commission to prioritize youth-led innovation, SME equity, and cross-sectoral collaboration in implementation. (page 8)'],
  'Biosecurity': ['While the EU is a leader in biologics manufacturing, it remains vulnerable to geopolitical supply chain risks and foreign investment outflows. Dual-use biotech technologies in health and agriculture further raise security concerns. (page 6)',
   'The White Paper for European Defence: Readiness 2030 calls for a biotechnology security strategy to address dual-use risks, IP protection, and international standards. The EU must incentivize regional manufacturing, de-risk supply chains, and protect strategic innovation. (page 6)'],
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3552803',
  'title': 'Feedback Paper On the European Biotech Act'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3553888',
  'title': 'cpme.2025-092.FINAL.Statement.Biotech.Act'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': ['Despite its proven benefits, biocontrol remains underutilized in the EU due to regulatory bottlenecks, fragmented market access, and limited public awareness. An unnecessarily lengthy and complex authorization process for biocontrol products leads to time to market constraints and competitive disadvantages. Regulation (EU) 1107/2009 on the placing on the market of EU Plant Protection Products (PPPs) has been designed for chemical pesticides and is not well adapted to biological PPPs, leading to unnecessary delays in their evaluations (up to 10 years from submission to market, compared to 2-3 years in other global jurisdictions) The Biotech Act must address these barriers to unlock the full potential of biocontrol as a pillar of sustainable biotechnology. (page 2)',
   'The current regulatory framework for biocontrol products is often modeled after chemical pesticide legislation, which is ill-suited to the nature and risk profile of biological solutions. This misalignment results in: Long and costly approval processes (often exceeding 7 years); Inconsistent implementation across Member States; Limited incentives for firms to innovate. (page 2)'],
  'Access_to_Markets_strategies': ['Immediate simplification measures should be introduced in any upcoming legislative initiative from the European Commission to make biocontrol solutions available to farmers now, including a harmonized EU wide legal definition of biocontrol PPPs accompanied with measures to amend the treatment of this defined group of PPPs within Regulation (EU) 1107/2009 outlined below. Specifically, we call for: Re-instatement of provisional authorization (art 30) for PPPs containing only active biocontrol substances. Removal of re-registration process for biocontrol Facilitate label expansion for biocontrol PPPs expansion of biocontrol PPPs can increase their availability in arable crops. (page 2)',
   "A system of mutual recognition 'automatically' applied to all Member States could ensure a single market for biocontrol within the EU. Establishing a priority lane for biocontrol solutions will also allow Member States to deliver these alternatives to the market faster. (page 3)",
   "Post 2035, biocontrol is expected to be the dominant type of pest control. In this situation, a future-proof new regulatory framework adapted to biocontrol is needed to maintain the competitiveness and resilience of the agricultural and crop protection markets in Europe. In doing so, the Commission shall assess the need to establish a dedicated Single Agency for biocontrol active substances and products; as well as other key features such as (i) moving away from the current zonal system established under 1107/2009 so that there would be instead one single zone for biocontrol products ('one market, one assessment') and (ii) developing a risk assessment procedure fully adapted for all types of biocontrol products. (page 3)"],
  'VC_Investments_IPO': ['At this point we deem important for the EU to find ways to promote an ecosystem for the entrepreneurial economy, including creating a supportive environment to raise private finance for EU companies at a competitive scale. Biotech clusters need to be significant and meaningful on a continental scale to compete globally. (page 3)'],
  'Manufacturing_Capabilities': ['More specifically, the EU needs to create EU innovation hubs for biocontrol and biomanufacturing, linking research institutions, startups, and industry. (page 2)'],
  'Incubation_and_Acceleration': ['More specifically, the EU needs to create EU innovation hubs for biocontrol and biomanufacturing, linking research institutions, startups, and industry. (page 2)'],
  'Talent_Retention': None,
  'Upskilling_Reskilling': ['Support training and advisory services for farmers and agronomists on the use of biocontrol products. (page 2)'],
  'AI_Challenges': None,
  'AI_Development_and_Deployment': ['Moreover, supporting public-private partnerships to co-develop next-generation biocontrol technologies, including AI-driven pest monitoring and precision application tools can boost innovation and unlock the full potential of such technologies. (page 2)'],
  'Global_Collaboration': ['Biotech clusters need to be significant and meaningful on a continental scale to compete globally. (page 2)'],
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3554271',
  'title': 'Koppert submission for the biotech act consultations'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': ['Examples include misaligned provisions in the legislation concerning Contained Use of Genetically Modified Microorganisms, Workers’ Protection or Animal By-products. This paper aims to outline these challenges for EU biotechnology and pharmaceutical companies, labs, startups and academics in terms of regulatory complexity, which translates into increased costs, delays and loss of competitiveness. (page 4)',
   'The GMO legislation regulates genome-edited organisms in which genetic alterations (mutations) have been introduced that exist in nature or can arise through conventional breeding. This leads to a situation where organisms with the same mutation – one made through genome editing and the other made using conventional methods – are treated differently. (page 4)',
   'For plants, new NGT (New Genomic Techniques, also referred to as Genome-edited or GE) legislation is being negotiated that should be better fit for purpose, but for GE micro-organisms no alternative legislation has been proposed yet. (page 4)'],
  'Access_to_Markets_strategies': ['With the upcoming Biotech Act, the European Union has the opportunity to create a streamlined and predictable product-based legislative environment taking into account the specifics of either classically genetically modified or genome-edited organisms. Specifically for genome-edited (GE) micro-organisms, a separate regulatory framework that treats these micro-organisms in the same way as wild-type micro-organisms should be created, thereby removing them from the scope of the GMO legislation (both the contained use and deliberate release legislation). (page 4)',
   'It could also be considered to harmonize various GMO definitions in light of the 2018 CJEU ruling (6) and the long-existing definition of Living Modified Organism (LMO) as described in the Cartagena Protocol on Biosafety (7). (page 4)',
   'With science-based and predictable legislative frameworks for GMO’s and GE organisms, Europe can maintain its position in the front of the biotechnology race, whether it is for medicines, food and industrial processes. For both NGT plants and GE micro-organisms this would allow for reduced administrative effort while still maintaining the high product safety enshrined in Europe’s core values. (page 4)'],
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': ['Founded in 1996, the European Biosafety Association (EBSA) is a professional organization that focuses on biosafety and biosecurity. It serves as a platform for professionals across Europe, and beyond, to share knowledge, collaborate, and promote best practices in the field. (page 1)',
   'Founded in 1996, the European Biosafety Association (EBSA) is a professional organization that focuses on biosafety and biosecurity. It serves as a platform for professionals across Europe and beyond to share knowledge, collaborate, and promote best practices in the field. (page 3)'],
  'Biosecurity': ["Founded in 1996, the European Biosafety Association (EBSA) is a professional organization that focuses on biosafety and biosecurity. It serves as a platform for professionals across Europe, and beyond, to share knowledge, collaborate, and promote best practices in the field.  EBSA supports the responsible and sustainable development of Europe's life sciences and education sectors through risk-based management of potentially hazardous biological materials. Committed to collaborating with the European Commission, EBSA works to enhance biosafety and biosecurity standard practices while fostering innovation and competitiveness across biotechnology, and human, animal, and plant health sectors.  EBSA welcomes the advancing collaboration with the European Commission to continuously uphold and strengthen biosafety and biosecurity standards, with a focus on the following aspects:   (page 1)",
   'Furthermore, EBSA is dedicated to promoting and disseminating best practices in biosafety and biosecurity among its members and in the greater professional, research and industrial communities. The association actively fosters dialogue on emerging challenges and plays an advisory role in shaping practices to mitigate risks associated with biological agents and materials. (page 3)'],
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3559517',
  'title': 'EBSA Position Paper - OMNIBUS - 20250416 (1)'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': ['This is crucial because, under current frameworks, each phage might otherwise require separate approval, posing a business disincentive. (page 2)',
   'Currently, adding a new phage could be treated as a new product, since each phage is an active substance requiring review. That is a “major regulatory issue” and would severely slow down improvements to phage therapies. (page 5)'],
  'Access_to_Markets_strategies': ['The amendment thus aligns with the broader EU strategy to fix “market failures, especially in the development of priority antimicrobials” by broadening the eligible modalities to include phage-based medicines. (page 2)',
   'The sandbox plan shall detail how requirements are adapted (e.g., bespoke manufacturing validations, alternative trial endpoints) and how safety is ensured for such phage therapies. (page 4)',
   'Furthermore, the sandbox may facilitate the establishment of certified phage banks, where pre-characterized phages undergo regulatory validation for rapid deployment in clinical settings, including compassionate use frameworks. (page 4)',
   'The sandbox can provide “targeted derogations” from standard rules, such as allowing adaptive trial protocols or n-of-1 trials with pooled data, while still under authority supervision. (page 4)',
   'By tailoring variation rules to phage cocktails, we maintain regulatory rigor (each change reviewed by authorities) but avoid unnecessary duplication of full dossiers. (page 5)'],
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': ['In particular, medicinal products based on bacteriophages may be considered for a sandbox when their personalization or novel manufacturing methods make standard development pathways challenging. (page 2)',
   'The sandbox plan shall detail how requirements are adapted (e.g., bespoke manufacturing validations, alternative trial endpoints) and how safety is ensured for such phage therapies. (page 3)',
   'This approach has precedent: Belgium has effectively created a phage therapy framework by treating personalized phages as magistral (compounded) preparations. In Belgium, phages are prepared per prescription in a pharmacy with quality oversight, bypassing full pharmaceutical marketing authorization. This “magistral phage” model – allowed under national law – provides production and handling flexibility (e.g. not forcing strict GMP) for personalized phages. (page 3)'],
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3561326',
  'title': 'PhageEU Proposals for Amendments_Pharmaceutical Package_March 2025'}]

In [43]:
FINAL_JSON_PATH = Path(output_folder) / "brussels_final_results_with_ref_title.json"

try:
    # dump your list of dictionaries (results) as a single JSON array
    with open(FINAL_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    print(f"[DONE] Final merged results saved to {FINAL_JSON_PATH}")
except Exception as e:
    print(f"[ERROR] Failed to save final JSON: {e}")

[DONE] Final merged results saved to C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\brussels_final_results_with_ref_title.json

In [33]:
output_folder = Path(folder_path).parent / "results"
xlsx_path = Path(output_folder) / "RAG_pp_results_table.xlsx"

df.to_excel(xlsx_path, index=False)

## Feedbacks

In [68]:
# Load the Excel sheet, skip first 3 rows, treat the 4th as header
fb = pd.read_excel(
    os.path.join(folder_path, "Working file-biotech act call for evidence telethon_VP Check.xlsx"),
    sheet_name="Sector analysis",
    skiprows=3
)
fb.head()

,Reference publication,Feedback reference,Ares reference,Date feedback,User type,Tr _ number,Organization,Sector - from EC,Scope,Governance level,...,title,organisation,page_number,summary,main themes,VC,clusters,skills,AI/data,dual_use/security
0,Ares(2025)3876590,F3551675,Ares(2025)3913571,2025/05/15 10:17:58,Business Association,NaN,COMPAG,Medical/pharma,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ares(2025)3876590,F3551693,Ares(2025)3918507,2025/05/15 13:44:22,EU Citizen,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ares(2025)3876590,F3551766,Ares(2025)3957144,2025/05/16 12:02:14,EU Citizen,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ares(2025)3876590,F3551820,Ares(2025)3978576,2025/05/17 04:02:15,EU Citizen,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ares(2025)3876590,F3551923,Ares(2025)3990974,2025/05/18 16:26:28,NGO (Non-governmental organisation),629482044225-60,OGM dangers,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Send texts to the blob container

In [45]:
from azure.storage.blob import BlobServiceClient
import os

# --- Connect to Azure Blob Storage ---
blob_service = BlobServiceClient.from_connection_string(os.environ["AZURE_BLOB_CONNECTION_STRING"])
container_client = blob_service.get_container_client("sante-docs")

# --- Loop through rows of fb and upload each feedback ---
for _, row in fb.iterrows():
    reference = str(row["Feedback reference"]).strip()
    text = str(row["Feedback   in   original   language"]).strip()

    # Skip rows with missing values
    if not reference or not text or reference.lower() == "nan":
        continue

    # Construct blob name using the reference
    blob_name = f"{reference}.txt"

    # Upload the feedback as a separate text file
    blob_client = container_client.get_blob_client(blob_name)
    blob_client.upload_blob(text.encode("utf-8"), overwrite=True)

    print(f"✅ Uploaded: {blob_name}")

✅ Uploaded: F3552803.txt
✅ Uploaded: F3553888.txt
✅ Uploaded: F3554271.txt
✅ Uploaded: F3559517.txt
✅ Uploaded: F3561326.txt
✅ Uploaded: F3563493.txt
✅ Uploaded: F3563646.txt
✅ Uploaded: F3563652.txt
✅ Uploaded: F3563668.txt
✅ Uploaded: F3563901.txt
✅ Uploaded: F3563910.txt
✅ Uploaded: F3563929.txt
✅ Uploaded: F3564074.txt
✅ Uploaded: F3564102.txt
✅ Uploaded: F3564121.txt
✅ Uploaded: F3564204.txt
✅ Uploaded: F3564210.txt
✅ Uploaded: F3564218.txt
✅ Uploaded: F3564247.txt
✅ Uploaded: F3564250.txt
✅ Uploaded: F3564253.txt
✅ Uploaded: F3564264.txt
✅ Uploaded: F3564266.txt
✅ Uploaded: F3564268.txt
✅ Uploaded: F3564270.txt
✅ Uploaded: F3564380.txt
✅ Uploaded: F3564435.txt
✅ Uploaded: F3564477.txt
✅ Uploaded: F3564478.txt
✅ Uploaded: F3564488.txt
✅ Uploaded: F3564504.txt
✅ Uploaded: F3564682.txt
✅ Uploaded: F3564687.txt
✅ Uploaded: F3564728.txt
✅ Uploaded: F3564760.txt
✅ Uploaded: F3564769.txt
✅ Uploaded: F3564784.txt
✅ Uploaded: F3564813.txt
✅ Uploaded: F3564816.txt
✅ Uploaded: F3564818.txt
✅ Uploaded: F3564833.txt
✅ Uploaded: F3564836.txt
✅ Uploaded: F3564841.txt
✅ Uploaded: F3564842.txt
✅ Uploaded: F3564843.txt
✅ Uploaded: F3564846.txt
✅ Uploaded: F3564851.txt
✅ Uploaded: F3564862.txt
✅ Uploaded: F3564899.txt
✅ Uploaded: F3564900.txt
✅ Uploaded: F3564901.txt
✅ Uploaded: F3564912.txt
✅ Uploaded: F3564918.txt
✅ Uploaded: F3564919.txt
✅ Uploaded: F3564930.txt
✅ Uploaded: F3564965.txt
✅ Uploaded: F3564967.txt
✅ Uploaded: F3564970.txt
✅ Uploaded: F3564976.txt
✅ Uploaded: F3564981.txt
✅ Uploaded: F3564997.txt
✅ Uploaded: F3564998.txt
✅ Uploaded: F3565010.txt
✅ Uploaded: F3565025.txt
✅ Uploaded: F3565034.txt
✅ Uploaded: F3565040.txt
✅ Uploaded: F3565042.txt
✅ Uploaded: F3565064.txt
✅ Uploaded: F3565089.txt
✅ Uploaded: F3565090.txt
✅ Uploaded: F3565110.txt
✅ Uploaded: F3565113.txt
✅ Uploaded: F3565115.txt
✅ Uploaded: F3565117.txt
✅ Uploaded: F3565118.txt
✅ Uploaded: F3565136.txt
✅ Uploaded: F3565143.txt
✅ Uploaded: F3565157.txt
✅ Uploaded: F3565164.txt
✅ Uploaded: F3565165.txt
✅ Uploaded: F3565166.txt
✅ Uploaded: F3565207.txt
✅ Uploaded: F3565208.txt
✅ Uploaded: F3565224.txt
✅ Uploaded: F3565229.txt
✅ Uploaded: F3565230.txt
✅ Uploaded: F3565232.txt
✅ Uploaded: F3565236.txt
✅ Uploaded: F3565249.txt
✅ Uploaded: F3565251.txt
✅ Uploaded: F3565252.txt
✅ Uploaded: F3565256.txt
✅ Uploaded: F3565277.txt
✅ Uploaded: F3565281.txt
✅ Uploaded: F3565286.txt
✅ Uploaded: F3565287.txt
✅ Uploaded: F3565290.txt
✅ Uploaded: F3565295.txt
✅ Uploaded: F3565302.txt
✅ Uploaded: F3565307.txt
✅ Uploaded: F3565312.txt
✅ Uploaded: F3565317.txt
✅ Uploaded: F3565319.txt
✅ Uploaded: F3565323.txt
✅ Uploaded: F3565339.txt
✅ Uploaded: F3565340.txt
✅ Uploaded: F3565342.txt
✅ Uploaded: F3565344.txt
✅ Uploaded: F3565349.txt
✅ Uploaded: F3565354.txt
✅ Uploaded: F3565358.txt
✅ Uploaded: F3565359.txt
✅ Uploaded: F3565361.txt
✅ Uploaded: F3565366.txt
✅ Uploaded: F3565367.txt
✅ Uploaded: F3565369.txt
✅ Uploaded: F3565371.txt
✅ Uploaded: F3565376.txt
✅ Uploaded: F3565383.txt
✅ Uploaded: F3565386.txt
✅ Uploaded: F3565387.txt
✅ Uploaded: F3565388.txt
✅ Uploaded: F3565395.txt
✅ Uploaded: F3565399.txt
✅ Uploaded: F3565405.txt
✅ Uploaded: F3565413.txt
✅ Uploaded: F3565422.txt
✅ Uploaded: F3565426.txt
✅ Uploaded: F3565431.txt
✅ Uploaded: F3565435.txt
✅ Uploaded: F3565438.txt
✅ Uploaded: F3565441.txt
✅ Uploaded: F3565444.txt
✅ Uploaded: F3565463.txt
✅ Uploaded: F3565466.txt
✅ Uploaded: F3565477.txt
✅ Uploaded: F3565481.txt
✅ Uploaded: F3565484.txt
✅ Uploaded: F3565496.txt
✅ Uploaded: F3565499.txt
✅ Uploaded: F3565503.txt
✅ Uploaded: F3565509.txt
✅ Uploaded: F3565510.txt
✅ Uploaded: F3565520.txt
✅ Uploaded: F3565521.txt
✅ Uploaded: F3565526.txt
✅ Uploaded: F3565532.txt
✅ Uploaded: F3582124.txt
✅ Uploaded: F3563345.txt
✅ Uploaded: F3555138.txt
✅ Uploaded: F3564826.txt
✅ Uploaded: F3565407.txt
✅ Uploaded: F3557206.txt
✅ Uploaded: F3565219.txt
✅ Uploaded: F3564228.txt
✅ Uploaded: F3562778.txt
✅ Uploaded: F3565234.txt
✅ Uploaded: F3564641.txt
✅ Uploaded: F3565356.txt
✅ Uploaded: F3564205.txt
✅ Uploaded: F3563451.txt
✅ Uploaded: F3564738.txt
✅ Uploaded: F3551675.txt
✅ Uploaded: F3564781.txt
✅ Uploaded: F3565061.txt
✅ Uploaded: F3565446.txt
✅ Uploaded: F3565491.txt
✅ Uploaded: F3564964.txt
✅ Uploaded: F3565420.txt
✅ Uploaded: F3564722.txt
✅ Uploaded: F3565495.txt
✅ Uploaded: F3565451.txt
✅ Uploaded: F3554076.txt
✅ Uploaded: F3563581.txt
✅ Uploaded: F3564695.txt
✅ Uploaded: F3564990.txt
✅ Uploaded: F3564907.txt
✅ Uploaded: F3565421.txt
✅ Uploaded: F3565315.txt
✅ Uploaded: F3565250.txt
✅ Uploaded: F3565493.txt
✅ Uploaded: F3565296.txt
✅ Uploaded: F3565239.txt
✅ Uploaded: F3565284.txt
✅ Uploaded: F3565273.txt
✅ Uploaded: F3564289.txt
✅ Uploaded: F3562563.txt
✅ Uploaded: F3565261.txt
✅ Uploaded: F3553780.txt
✅ Uploaded: F3562128.txt
✅ Uploaded: F3564280.txt
✅ Uploaded: F3551693.txt
✅ Uploaded: F3551766.txt
✅ Uploaded: F3551820.txt
✅ Uploaded: F3552807.txt
✅ Uploaded: F3553267.txt
✅ Uploaded: F3563368.txt
✅ Uploaded: F3564290.txt
✅ Uploaded: F3565172.txt
✅ Uploaded: F3565417.txt
✅ Uploaded: F3565390.txt
✅ Uploaded: F3553253.txt
✅ Uploaded: F3564221.txt
✅ Uploaded: F3564736.txt
✅ Uploaded: F3564982.txt
✅ Uploaded: F3565052.txt
✅ Uploaded: F3565059.txt
✅ Uploaded: F3565418.txt
✅ Uploaded: F3551923.txt
✅ Uploaded: F3565321.txt
✅ Uploaded: F3563249.txt
✅ Uploaded: F3564213.txt
✅ Uploaded: F3564359.txt
✅ Uploaded: F3564909.txt
✅ Uploaded: F3565455.txt
✅ Uploaded: F3564942.txt
✅ Uploaded: F3565196.txt
✅ Uploaded: F3565258.txt
✅ Uploaded: F3564863.txt
✅ Uploaded: F3565357.txt
✅ Uploaded: F3564832.txt
✅ Uploaded: F3565442.txt

In [46]:
len(fb)

222

In [47]:
container_name="sante-docs"
colect = UserDocumentCollection(container_name)

colect.reset_and_run_indexer()

2025-11-03 15:32:23.825 | INFO     | embeddings:get_container:66 - Container 'sante-docs' already exists.
2025-11-03 15:32:26.311 | INFO     | embeddings:reset_and_run_indexer:252 - 🧹 Indexer 'sante-docs-indexer' checkpoint reset successfully.
2025-11-03 15:32:26.543 | INFO     | embeddings:reset_and_run_indexer:256 - 🚀 Indexer 'sante-docs-indexer' started successfully.

In [48]:
from tqdm.auto import tqdm
import os, json, time

# --- Parameters ---
SAVE_EVERY = 10
OUTPUT_PATH = Path(output_folder)/"feedback_results.json"

# --- Get only uploaded .txt feedback files ---
docs = sorted([blob.name for blob in container_client.list_blobs() if blob.name.endswith(".txt")])

results, errors = [], []
pbar = tqdm(docs, desc="Processing feedback documents from blob", unit="doc", total=len(docs))

def save_checkpoint():
    """Save current progress to disk."""
    try:
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        temp_file = f"{os.path.splitext(OUTPUT_PATH)[0]}_checkpoint_{timestamp}.json"
        with open(temp_file, "w", encoding="utf-8") as f:
            json.dump({"results": results, "errors": errors}, f, ensure_ascii=False, indent=2)
        pbar.write(f"[SAVED] checkpoint with {len(results)} results → {temp_file}")
    except Exception as e:
        pbar.write(f"[WARNING] Failed to save checkpoint: {e}")

for i, doc in enumerate(pbar, start=1):
    pbar.set_postfix_str(doc)
    try:
        first  = call_once_with_wait(first_information,  doc, delay=10, label=f"first:{doc}")
        second = call_once_with_wait(second_information, doc, delay=10, label=f"second:{doc}")
        third  = call_once_with_wait(third_information,  doc, delay=10, label=f"third:{doc}")
        results.append({**first, **second, **third})
    except Exception as e:
        errors.append((doc, repr(e)))
        pbar.write(f"[ERROR] {doc}: {e}")

    # periodic checkpoint
    if i % SAVE_EVERY == 0:
        save_checkpoint()

# --- Final save ---
with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    json.dump({"results": results, "errors": errors}, f, ensure_ascii=False, indent=2)
pbar.write(f"[DONE] All results saved to {OUTPUT_PATH}")

Processing feedback documents from blob:   0%|          | 0/222 [00:00<?, ?doc/s, F3551675.txt]

15:34:57 [first:F3551675.txt] waiting 10s before call...
15:35:09 [first:F3551675.txt] call OK
15:35:09 [second:F3551675.txt] waiting 10s before call...
15:35:21 [second:F3551675.txt] call OK
15:35:21 [third:F3551675.txt] waiting 10s before call...
15:35:34 [third:F3551675.txt] call OK

Processing feedback documents from blob:   0%|          | 1/222 [00:37<2:17:40, 37.38s/doc, F3551693.txt]

15:35:34 [first:F3551693.txt] waiting 10s before call...
15:35:46 [first:F3551693.txt] call OK
15:35:46 [second:F3551693.txt] waiting 10s before call...
15:35:59 [second:F3551693.txt] call OK
15:35:59 [third:F3551693.txt] waiting 10s before call...
15:36:11 [third:F3551693.txt] call OK

Processing feedback documents from blob:   1%|          | 2/222 [01:14<2:17:09, 37.40s/doc, F3551766.txt]

15:36:11 [first:F3551766.txt] waiting 10s before call...
15:36:24 [first:F3551766.txt] call OK
15:36:24 [second:F3551766.txt] waiting 10s before call...
15:36:36 [second:F3551766.txt] call OK
15:36:36 [third:F3551766.txt] waiting 10s before call...
15:36:48 [third:F3551766.txt] call OK

Processing feedback documents from blob:   1%|▏         | 3/222 [01:51<2:14:53, 36.96s/doc, F3551820.txt]

15:36:48 [first:F3551820.txt] waiting 10s before call...
15:37:01 [first:F3551820.txt] call OK
15:37:01 [second:F3551820.txt] waiting 10s before call...
15:37:14 [second:F3551820.txt] call OK
15:37:14 [third:F3551820.txt] waiting 10s before call...
15:37:26 [third:F3551820.txt] call OK

Processing feedback documents from blob:   2%|▏         | 4/222 [02:29<2:15:40, 37.34s/doc, F3551923.txt]

15:37:26 [first:F3551923.txt] waiting 10s before call...
15:37:38 [first:F3551923.txt] call OK
15:37:38 [second:F3551923.txt] waiting 10s before call...
15:37:50 [second:F3551923.txt] call OK
15:37:50 [third:F3551923.txt] waiting 10s before call...
15:38:05 [third:F3551923.txt] call OK

Processing feedback documents from blob:   2%|▏         | 5/222 [03:08<2:17:56, 38.14s/doc, F3552803.txt]

15:38:05 [first:F3552803.txt] waiting 10s before call...
15:38:21 [first:F3552803.txt] call OK
15:38:21 [second:F3552803.txt] waiting 10s before call...
15:38:35 [second:F3552803.txt] call OK
15:38:35 [third:F3552803.txt] waiting 10s before call...
15:38:50 [third:F3552803.txt] call OK

Processing feedback documents from blob:   3%|▎         | 6/222 [03:53<2:24:51, 40.24s/doc, F3552807.txt]

15:38:50 [first:F3552807.txt] waiting 10s before call...
15:39:07 [first:F3552807.txt] call OK
15:39:07 [second:F3552807.txt] waiting 10s before call...
15:39:19 [second:F3552807.txt] call OK
15:39:19 [third:F3552807.txt] waiting 10s before call...
15:39:32 [third:F3552807.txt] call OK

Processing feedback documents from blob:   3%|▎         | 7/222 [04:35<2:26:40, 40.93s/doc, F3553253.txt]

15:39:32 [first:F3553253.txt] waiting 10s before call...
15:39:47 [first:F3553253.txt] call OK
15:39:47 [second:F3553253.txt] waiting 10s before call...
15:40:00 [second:F3553253.txt] call OK
15:40:00 [third:F3553253.txt] waiting 10s before call...
15:40:13 [third:F3553253.txt] call OK

Processing feedback documents from blob:   4%|▎         | 8/222 [05:16<2:26:17, 41.02s/doc, F3553267.txt]

15:40:13 [first:F3553267.txt] waiting 10s before call...
15:40:26 [first:F3553267.txt] call OK
15:40:26 [second:F3553267.txt] waiting 10s before call...
15:40:38 [second:F3553267.txt] call OK
15:40:38 [third:F3553267.txt] waiting 10s before call...
15:40:50 [third:F3553267.txt] call OK

Processing feedback documents from blob:   4%|▍         | 9/222 [05:53<2:20:47, 39.66s/doc, F3553780.txt]

15:40:50 [first:F3553780.txt] waiting 10s before call...
15:41:03 [first:F3553780.txt] call OK
15:41:03 [second:F3553780.txt] waiting 10s before call...
15:41:15 [second:F3553780.txt] call OK
15:41:15 [third:F3553780.txt] waiting 10s before call...
15:41:26 [third:F3553780.txt] call OK

Processing feedback documents from blob:   5%|▍         | 10/222 [06:29<2:16:46, 38.71s/doc, F3553888.txt]

[SAVED] checkpoint with 10 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_154126.json
15:41:26 [first:F3553888.txt] waiting 10s before call...
15:41:39 [first:F3553888.txt] call OK
15:41:39 [second:F3553888.txt] waiting 10s before call...
15:41:51 [second:F3553888.txt] call OK
15:41:51 [third:F3553888.txt] waiting 10s before call...
15:42:04 [third:F3553888.txt] call OK

Processing feedback documents from blob:   5%|▍         | 11/222 [07:06<2:14:24, 38.22s/doc, F3554076.txt]

15:42:04 [first:F3554076.txt] waiting 10s before call...
15:42:19 [first:F3554076.txt] call OK
15:42:19 [second:F3554076.txt] waiting 10s before call...
15:42:31 [second:F3554076.txt] call OK
15:42:31 [third:F3554076.txt] waiting 10s before call...
15:42:45 [third:F3554076.txt] call OK

Processing feedback documents from blob:   5%|▌         | 12/222 [07:48<2:16:51, 39.10s/doc, F3554271.txt]

15:42:45 [first:F3554271.txt] waiting 10s before call...
15:42:58 [first:F3554271.txt] call OK
15:42:58 [second:F3554271.txt] waiting 10s before call...
15:43:10 [second:F3554271.txt] call OK
15:43:10 [third:F3554271.txt] waiting 10s before call...
15:43:22 [third:F3554271.txt] call OK

Processing feedback documents from blob:   6%|▌         | 13/222 [08:25<2:14:42, 38.67s/doc, F3555138.txt]

15:43:22 [first:F3555138.txt] waiting 10s before call...
15:43:36 [first:F3555138.txt] call OK
15:43:36 [second:F3555138.txt] waiting 10s before call...
15:43:48 [second:F3555138.txt] call OK
15:43:48 [third:F3555138.txt] waiting 10s before call...
15:44:01 [third:F3555138.txt] call OK

Processing feedback documents from blob:   6%|▋         | 14/222 [09:04<2:14:05, 38.68s/doc, F3557206.txt]

15:44:01 [first:F3557206.txt] waiting 10s before call...
15:44:14 [first:F3557206.txt] call OK
15:44:14 [second:F3557206.txt] waiting 10s before call...
15:44:27 [second:F3557206.txt] call OK
15:44:27 [third:F3557206.txt] waiting 10s before call...
15:44:39 [third:F3557206.txt] call OK

Processing feedback documents from blob:   7%|▋         | 15/222 [09:42<2:13:06, 38.58s/doc, F3559517.txt]

15:44:39 [first:F3559517.txt] waiting 10s before call...
15:44:53 [first:F3559517.txt] call OK
15:44:53 [second:F3559517.txt] waiting 10s before call...
15:45:05 [second:F3559517.txt] call OK
15:45:05 [third:F3559517.txt] waiting 10s before call...
15:45:19 [third:F3559517.txt] call OK

Processing feedback documents from blob:   7%|▋         | 16/222 [10:21<2:13:00, 38.74s/doc, F3561326.txt]

15:45:19 [first:F3561326.txt] waiting 10s before call...
15:45:33 [first:F3561326.txt] call OK
15:45:33 [second:F3561326.txt] waiting 10s before call...
15:45:46 [second:F3561326.txt] call OK
15:45:46 [third:F3561326.txt] waiting 10s before call...
15:45:58 [third:F3561326.txt] call OK

Processing feedback documents from blob:   8%|▊         | 17/222 [11:01<2:12:57, 38.92s/doc, F3562128.txt]

15:45:58 [first:F3562128.txt] waiting 10s before call...
15:46:15 [first:F3562128.txt] call OK
15:46:15 [second:F3562128.txt] waiting 10s before call...
15:46:30 [second:F3562128.txt] call OK
15:46:30 [third:F3562128.txt] waiting 10s before call...
15:46:42 [third:F3562128.txt] call OK

Processing feedback documents from blob:   8%|▊         | 18/222 [11:45<2:18:10, 40.64s/doc, F3562563.txt]

15:46:42 [first:F3562563.txt] waiting 10s before call...
15:46:56 [first:F3562563.txt] call OK
15:46:56 [second:F3562563.txt] waiting 10s before call...
15:47:12 [second:F3562563.txt] call OK
15:47:12 [third:F3562563.txt] waiting 10s before call...
15:47:24 [third:F3562563.txt] call OK

Processing feedback documents from blob:   9%|▊         | 19/222 [12:27<2:18:36, 40.97s/doc, F3562778.txt]

15:47:24 [first:F3562778.txt] waiting 10s before call...
15:47:36 [first:F3562778.txt] call OK
15:47:36 [second:F3562778.txt] waiting 10s before call...
15:47:48 [second:F3562778.txt] call OK
15:47:48 [third:F3562778.txt] waiting 10s before call...
15:48:00 [third:F3562778.txt] call OK

Processing feedback documents from blob:   9%|▉         | 20/222 [13:03<2:12:21, 39.32s/doc, F3563249.txt]

[SAVED] checkpoint with 20 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_154800.json
15:48:00 [first:F3563249.txt] waiting 10s before call...
15:48:12 [first:F3563249.txt] call OK
15:48:12 [second:F3563249.txt] waiting 10s before call...
15:48:24 [second:F3563249.txt] call OK
15:48:24 [third:F3563249.txt] waiting 10s before call...
15:48:36 [third:F3563249.txt] call OK

Processing feedback documents from blob:   9%|▉         | 21/222 [13:38<2:08:11, 38.27s/doc, F3563345.txt]

15:48:36 [first:F3563345.txt] waiting 10s before call...
15:48:48 [first:F3563345.txt] call OK
15:48:48 [second:F3563345.txt] waiting 10s before call...
15:49:01 [second:F3563345.txt] call OK
15:49:01 [third:F3563345.txt] waiting 10s before call...
15:49:13 [third:F3563345.txt] call OK

Processing feedback documents from blob:  10%|▉         | 22/222 [14:16<2:06:22, 37.91s/doc, F3563368.txt]

15:49:13 [first:F3563368.txt] waiting 10s before call...
15:49:25 [first:F3563368.txt] call OK
15:49:25 [second:F3563368.txt] waiting 10s before call...
15:49:36 [second:F3563368.txt] call OK
15:49:36 [third:F3563368.txt] waiting 10s before call...
15:49:49 [third:F3563368.txt] call OK

Processing feedback documents from blob:  10%|█         | 23/222 [14:52<2:03:50, 37.34s/doc, F3563451.txt]

15:49:49 [first:F3563451.txt] waiting 10s before call...
15:50:01 [first:F3563451.txt] call OK
15:50:01 [second:F3563451.txt] waiting 10s before call...
15:50:12 [second:F3563451.txt] call OK
15:50:12 [third:F3563451.txt] waiting 10s before call...
15:50:25 [third:F3563451.txt] call OK

Processing feedback documents from blob:  11%|█         | 24/222 [15:28<2:02:09, 37.02s/doc, F3563493.txt]

15:50:25 [first:F3563493.txt] waiting 10s before call...
15:50:38 [first:F3563493.txt] call OK
15:50:38 [second:F3563493.txt] waiting 10s before call...
15:50:51 [second:F3563493.txt] call OK
15:50:51 [third:F3563493.txt] waiting 10s before call...
15:51:03 [third:F3563493.txt] call OK

Processing feedback documents from blob:  11%|█▏        | 25/222 [16:05<2:02:13, 37.23s/doc, F3563581.txt]

15:51:03 [first:F3563581.txt] waiting 10s before call...
15:51:19 [first:F3563581.txt] call OK
15:51:19 [second:F3563581.txt] waiting 10s before call...
15:51:31 [second:F3563581.txt] call OK
15:51:31 [third:F3563581.txt] waiting 10s before call...
15:51:43 [third:F3563581.txt] call OK

Processing feedback documents from blob:  12%|█▏        | 26/222 [16:46<2:04:21, 38.07s/doc, F3563646.txt]

15:51:43 [first:F3563646.txt] waiting 10s before call...
15:51:55 [first:F3563646.txt] call OK
15:51:55 [second:F3563646.txt] waiting 10s before call...
15:52:07 [second:F3563646.txt] call OK
15:52:07 [third:F3563646.txt] waiting 10s before call...
15:52:19 [third:F3563646.txt] call OK

Processing feedback documents from blob:  12%|█▏        | 27/222 [17:22<2:01:56, 37.52s/doc, F3563652.txt]

15:52:19 [first:F3563652.txt] waiting 10s before call...
15:52:32 [first:F3563652.txt] call OK
15:52:32 [second:F3563652.txt] waiting 10s before call...
15:52:44 [second:F3563652.txt] call OK
15:52:44 [third:F3563652.txt] waiting 10s before call...
15:52:56 [third:F3563652.txt] call OK

Processing feedback documents from blob:  13%|█▎        | 28/222 [17:59<2:01:23, 37.54s/doc, F3563668.txt]

15:52:56 [first:F3563668.txt] waiting 10s before call...
15:53:10 [first:F3563668.txt] call OK
15:53:10 [second:F3563668.txt] waiting 10s before call...
15:53:22 [second:F3563668.txt] call OK
15:53:22 [third:F3563668.txt] waiting 10s before call...
15:53:34 [third:F3563668.txt] call OK

Processing feedback documents from blob:  13%|█▎        | 29/222 [18:37<2:00:57, 37.60s/doc, F3563901.txt]

15:53:34 [first:F3563901.txt] waiting 10s before call...
15:53:49 [first:F3563901.txt] call OK
15:53:49 [second:F3563901.txt] waiting 10s before call...
15:54:02 [second:F3563901.txt] call OK
15:54:02 [third:F3563901.txt] waiting 10s before call...
15:54:15 [third:F3563901.txt] call OK

Processing feedback documents from blob:  14%|█▎        | 30/222 [19:17<2:02:58, 38.43s/doc, F3563910.txt]

[SAVED] checkpoint with 30 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_155415.json
15:54:15 [first:F3563910.txt] waiting 10s before call...
15:54:29 [first:F3563910.txt] call OK
15:54:29 [second:F3563910.txt] waiting 10s before call...
15:54:43 [second:F3563910.txt] call OK
15:54:43 [third:F3563910.txt] waiting 10s before call...
15:54:55 [third:F3563910.txt] call OK

Processing feedback documents from blob:  14%|█▍        | 31/222 [19:58<2:04:04, 38.98s/doc, F3563929.txt]

15:54:55 [first:F3563929.txt] waiting 10s before call...
15:55:10 [first:F3563929.txt] call OK
15:55:10 [second:F3563929.txt] waiting 10s before call...
15:55:23 [second:F3563929.txt] call OK
15:55:23 [third:F3563929.txt] waiting 10s before call...
15:55:36 [third:F3563929.txt] call OK

Processing feedback documents from blob:  14%|█▍        | 32/222 [20:39<2:05:17, 39.57s/doc, F3564074.txt]

15:55:36 [first:F3564074.txt] waiting 10s before call...
15:55:49 [first:F3564074.txt] call OK
15:55:49 [second:F3564074.txt] waiting 10s before call...
15:56:02 [second:F3564074.txt] call OK
15:56:02 [third:F3564074.txt] waiting 10s before call...
15:56:14 [third:F3564074.txt] call OK

Processing feedback documents from blob:  15%|█▍        | 33/222 [21:17<2:03:27, 39.20s/doc, F3564102.txt]

15:56:14 [first:F3564102.txt] waiting 10s before call...
15:56:28 [first:F3564102.txt] call OK
15:56:28 [second:F3564102.txt] waiting 10s before call...
15:56:40 [second:F3564102.txt] call OK
15:56:40 [third:F3564102.txt] waiting 10s before call...
15:56:52 [third:F3564102.txt] call OK

Processing feedback documents from blob:  15%|█▌        | 34/222 [21:55<2:01:59, 38.93s/doc, F3564121.txt]

15:56:52 [first:F3564121.txt] waiting 10s before call...
15:57:09 [first:F3564121.txt] call OK
15:57:09 [second:F3564121.txt] waiting 10s before call...
15:57:23 [second:F3564121.txt] call OK
15:57:23 [third:F3564121.txt] waiting 10s before call...
15:57:35 [third:F3564121.txt] call OK

Processing feedback documents from blob:  16%|█▌        | 35/222 [22:38<2:04:33, 39.97s/doc, F3564204.txt]

15:57:35 [first:F3564204.txt] waiting 10s before call...
15:57:51 [first:F3564204.txt] call OK
15:57:51 [second:F3564204.txt] waiting 10s before call...
15:58:04 [second:F3564204.txt] call OK
15:58:04 [third:F3564204.txt] waiting 10s before call...
15:58:16 [third:F3564204.txt] call OK

Processing feedback documents from blob:  16%|█▌        | 36/222 [23:19<2:05:24, 40.46s/doc, F3564205.txt]

15:58:16 [first:F3564205.txt] waiting 10s before call...
15:58:34 [first:F3564205.txt] call OK
15:58:34 [second:F3564205.txt] waiting 10s before call...
15:58:47 [second:F3564205.txt] call OK
15:58:47 [third:F3564205.txt] waiting 10s before call...
15:59:00 [third:F3564205.txt] call OK

Processing feedback documents from blob:  17%|█▋        | 37/222 [24:03<2:07:39, 41.40s/doc, F3564210.txt]

15:59:00 [first:F3564210.txt] waiting 10s before call...
15:59:14 [first:F3564210.txt] call OK
15:59:14 [second:F3564210.txt] waiting 10s before call...
15:59:27 [second:F3564210.txt] call OK
15:59:27 [third:F3564210.txt] waiting 10s before call...
15:59:40 [third:F3564210.txt] call OK

Processing feedback documents from blob:  17%|█▋        | 38/222 [24:43<2:05:49, 41.03s/doc, F3564213.txt]

15:59:40 [first:F3564213.txt] waiting 10s before call...
15:59:53 [first:F3564213.txt] call OK
15:59:53 [second:F3564213.txt] waiting 10s before call...
16:00:05 [second:F3564213.txt] call OK
16:00:05 [third:F3564213.txt] waiting 10s before call...
16:00:18 [third:F3564213.txt] call OK

Processing feedback documents from blob:  18%|█▊        | 39/222 [25:21<2:02:11, 40.06s/doc, F3564218.txt]

16:00:18 [first:F3564218.txt] waiting 10s before call...
16:00:30 [first:F3564218.txt] call OK
16:00:30 [second:F3564218.txt] waiting 10s before call...
16:00:43 [second:F3564218.txt] call OK
16:00:43 [third:F3564218.txt] waiting 10s before call...
16:00:55 [third:F3564218.txt] call OK

Processing feedback documents from blob:  18%|█▊        | 40/222 [25:58<1:58:28, 39.06s/doc, F3564221.txt]

[SAVED] checkpoint with 40 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_160055.json
16:00:55 [first:F3564221.txt] waiting 10s before call...
16:01:11 [first:F3564221.txt] call OK
16:01:11 [second:F3564221.txt] waiting 10s before call...
16:01:24 [second:F3564221.txt] call OK
16:01:24 [third:F3564221.txt] waiting 10s before call...
16:01:36 [third:F3564221.txt] call OK

Processing feedback documents from blob:  18%|█▊        | 41/222 [26:39<1:59:43, 39.69s/doc, F3564228.txt]

16:01:36 [first:F3564228.txt] waiting 10s before call...
16:01:51 [first:F3564228.txt] call OK
16:01:51 [second:F3564228.txt] waiting 10s before call...
16:02:03 [second:F3564228.txt] call OK
16:02:03 [third:F3564228.txt] waiting 10s before call...
16:02:15 [third:F3564228.txt] call OK

Processing feedback documents from blob:  19%|█▉        | 42/222 [27:18<1:59:03, 39.68s/doc, F3564247.txt]

16:02:15 [first:F3564247.txt] waiting 10s before call...
16:02:28 [first:F3564247.txt] call OK
16:02:28 [second:F3564247.txt] waiting 10s before call...
16:02:40 [second:F3564247.txt] call OK
16:02:40 [third:F3564247.txt] waiting 10s before call...
16:02:52 [third:F3564247.txt] call OK

Processing feedback documents from blob:  19%|█▉        | 43/222 [27:55<1:55:54, 38.85s/doc, F3564250.txt]

16:02:52 [first:F3564250.txt] waiting 10s before call...
16:03:05 [first:F3564250.txt] call OK
16:03:05 [second:F3564250.txt] waiting 10s before call...
16:03:17 [second:F3564250.txt] call OK
16:03:17 [third:F3564250.txt] waiting 10s before call...
16:03:29 [third:F3564250.txt] call OK

Processing feedback documents from blob:  20%|█▉        | 44/222 [28:32<1:53:31, 38.27s/doc, F3564253.txt]

16:03:29 [first:F3564253.txt] waiting 10s before call...
16:03:42 [first:F3564253.txt] call OK
16:03:42 [second:F3564253.txt] waiting 10s before call...
16:03:54 [second:F3564253.txt] call OK
16:03:54 [third:F3564253.txt] waiting 10s before call...
16:04:06 [third:F3564253.txt] call OK

Processing feedback documents from blob:  20%|██        | 45/222 [29:09<1:51:48, 37.90s/doc, F3564264.txt]

16:04:06 [first:F3564264.txt] waiting 10s before call...
16:04:24 [first:F3564264.txt] call OK
16:04:24 [second:F3564264.txt] waiting 10s before call...
16:04:38 [second:F3564264.txt] call OK
16:04:38 [third:F3564264.txt] waiting 10s before call...
16:04:50 [third:F3564264.txt] call OK

Processing feedback documents from blob:  21%|██        | 46/222 [29:53<1:56:07, 39.59s/doc, F3564266.txt]

16:04:50 [first:F3564266.txt] waiting 10s before call...
16:05:04 [first:F3564266.txt] call OK
16:05:04 [second:F3564266.txt] waiting 10s before call...
16:05:17 [second:F3564266.txt] call OK
16:05:17 [third:F3564266.txt] waiting 10s before call...
16:05:29 [third:F3564266.txt] call OK

Processing feedback documents from blob:  21%|██        | 47/222 [30:32<1:55:03, 39.45s/doc, F3564268.txt]

16:05:29 [first:F3564268.txt] waiting 10s before call...
16:05:43 [first:F3564268.txt] call OK
16:05:43 [second:F3564268.txt] waiting 10s before call...
16:05:56 [second:F3564268.txt] call OK
16:05:56 [third:F3564268.txt] waiting 10s before call...
16:06:09 [third:F3564268.txt] call OK

Processing feedback documents from blob:  22%|██▏       | 48/222 [31:12<1:54:39, 39.54s/doc, F3564270.txt]

16:06:09 [first:F3564270.txt] waiting 10s before call...
16:06:23 [first:F3564270.txt] call OK
16:06:23 [second:F3564270.txt] waiting 10s before call...
16:06:41 [second:F3564270.txt] call OK
16:06:41 [third:F3564270.txt] waiting 10s before call...
16:06:54 [third:F3564270.txt] call OK

Processing feedback documents from blob:  22%|██▏       | 49/222 [31:57<1:58:40, 41.16s/doc, F3564280.txt]

16:06:54 [first:F3564280.txt] waiting 10s before call...
16:07:11 [first:F3564280.txt] call OK
16:07:11 [second:F3564280.txt] waiting 10s before call...
16:07:23 [second:F3564280.txt] call OK
16:07:23 [third:F3564280.txt] waiting 10s before call...
16:07:35 [third:F3564280.txt] call OK

Processing feedback documents from blob:  23%|██▎       | 50/222 [32:38<1:58:33, 41.36s/doc, F3564289.txt]

[SAVED] checkpoint with 50 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_160735.json
16:07:36 [first:F3564289.txt] waiting 10s before call...
16:07:48 [first:F3564289.txt] call OK
16:07:48 [second:F3564289.txt] waiting 10s before call...
16:08:00 [second:F3564289.txt] call OK
16:08:00 [third:F3564289.txt] waiting 10s before call...
16:08:12 [third:F3564289.txt] call OK

Processing feedback documents from blob:  23%|██▎       | 51/222 [33:15<1:54:05, 40.03s/doc, F3564290.txt]

16:08:12 [first:F3564290.txt] waiting 10s before call...
16:08:25 [first:F3564290.txt] call OK
16:08:25 [second:F3564290.txt] waiting 10s before call...
16:08:37 [second:F3564290.txt] call OK
16:08:37 [third:F3564290.txt] waiting 10s before call...
16:08:50 [third:F3564290.txt] call OK

Processing feedback documents from blob:  23%|██▎       | 52/222 [33:53<1:50:58, 39.17s/doc, F3564359.txt]

16:08:50 [first:F3564359.txt] waiting 10s before call...
16:09:08 [first:F3564359.txt] call OK
16:09:08 [second:F3564359.txt] waiting 10s before call...
16:09:21 [second:F3564359.txt] call OK
16:09:21 [third:F3564359.txt] waiting 10s before call...
16:09:33 [third:F3564359.txt] call OK

Processing feedback documents from blob:  24%|██▍       | 53/222 [34:36<1:54:07, 40.52s/doc, F3564380.txt]

16:09:33 [first:F3564380.txt] waiting 10s before call...
16:09:48 [first:F3564380.txt] call OK
16:09:48 [second:F3564380.txt] waiting 10s before call...
16:10:07 [second:F3564380.txt] call OK
16:10:07 [third:F3564380.txt] waiting 10s before call...
16:10:20 [third:F3564380.txt] call OK

Processing feedback documents from blob:  24%|██▍       | 54/222 [35:23<1:58:54, 42.47s/doc, F3564435.txt]

16:10:20 [first:F3564435.txt] waiting 10s before call...
16:10:33 [first:F3564435.txt] call OK
16:10:33 [second:F3564435.txt] waiting 10s before call...
16:10:44 [second:F3564435.txt] call OK
16:10:44 [third:F3564435.txt] waiting 10s before call...
16:10:56 [third:F3564435.txt] call OK

Processing feedback documents from blob:  25%|██▍       | 55/222 [35:59<1:52:34, 40.45s/doc, F3564477.txt]

16:10:56 [first:F3564477.txt] waiting 10s before call...
16:11:10 [first:F3564477.txt] call OK
16:11:10 [second:F3564477.txt] waiting 10s before call...
16:11:21 [second:F3564477.txt] call OK
16:11:21 [third:F3564477.txt] waiting 10s before call...
16:11:33 [third:F3564477.txt] call OK

Processing feedback documents from blob:  25%|██▌       | 56/222 [36:36<1:49:06, 39.43s/doc, F3564478.txt]

16:11:33 [first:F3564478.txt] waiting 10s before call...
16:11:46 [first:F3564478.txt] call OK
16:11:46 [second:F3564478.txt] waiting 10s before call...
16:11:58 [second:F3564478.txt] call OK
16:11:58 [third:F3564478.txt] waiting 10s before call...
16:12:11 [third:F3564478.txt] call OK

Processing feedback documents from blob:  26%|██▌       | 57/222 [37:14<1:47:08, 38.96s/doc, F3564488.txt]

16:12:11 [first:F3564488.txt] waiting 10s before call...
16:12:25 [first:F3564488.txt] call OK
16:12:25 [second:F3564488.txt] waiting 10s before call...
16:12:38 [second:F3564488.txt] call OK
16:12:38 [third:F3564488.txt] waiting 10s before call...
16:12:51 [third:F3564488.txt] call OK

Processing feedback documents from blob:  26%|██▌       | 58/222 [37:54<1:47:44, 39.42s/doc, F3564504.txt]

16:12:51 [first:F3564504.txt] waiting 10s before call...
16:13:05 [first:F3564504.txt] call OK
16:13:05 [second:F3564504.txt] waiting 10s before call...
16:13:17 [second:F3564504.txt] call OK
16:13:17 [third:F3564504.txt] waiting 10s before call...
16:13:29 [third:F3564504.txt] call OK

Processing feedback documents from blob:  27%|██▋       | 59/222 [38:32<1:45:55, 38.99s/doc, F3564641.txt]

16:13:29 [first:F3564641.txt] waiting 10s before call...
16:13:42 [first:F3564641.txt] call OK
16:13:42 [second:F3564641.txt] waiting 10s before call...
16:13:53 [second:F3564641.txt] call OK
16:13:53 [third:F3564641.txt] waiting 10s before call...
16:14:05 [third:F3564641.txt] call OK

Processing feedback documents from blob:  27%|██▋       | 60/222 [39:08<1:42:42, 38.04s/doc, F3564682.txt]

[SAVED] checkpoint with 60 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_161405.json
16:14:05 [first:F3564682.txt] waiting 10s before call...
16:14:21 [first:F3564682.txt] call OK
16:14:21 [second:F3564682.txt] waiting 10s before call...
16:14:33 [second:F3564682.txt] call OK
16:14:33 [third:F3564682.txt] waiting 10s before call...
16:14:46 [third:F3564682.txt] call OK

Processing feedback documents from blob:  27%|██▋       | 61/222 [39:49<1:44:07, 38.80s/doc, F3564687.txt]

16:14:46 [first:F3564687.txt] waiting 10s before call...
16:15:01 [first:F3564687.txt] call OK
16:15:01 [second:F3564687.txt] waiting 10s before call...
16:15:14 [second:F3564687.txt] call OK
16:15:14 [third:F3564687.txt] waiting 10s before call...
16:15:27 [third:F3564687.txt] call OK

Processing feedback documents from blob:  28%|██▊       | 62/222 [40:30<1:45:33, 39.58s/doc, F3564695.txt]

16:15:27 [first:F3564695.txt] waiting 10s before call...
16:15:41 [first:F3564695.txt] call OK
16:15:41 [second:F3564695.txt] waiting 10s before call...
16:15:54 [second:F3564695.txt] call OK
16:15:54 [third:F3564695.txt] waiting 10s before call...
16:16:06 [third:F3564695.txt] call OK

Processing feedback documents from blob:  28%|██▊       | 63/222 [41:09<1:44:16, 39.35s/doc, F3564722.txt]

16:16:06 [first:F3564722.txt] waiting 10s before call...
16:16:20 [first:F3564722.txt] call OK
16:16:20 [second:F3564722.txt] waiting 10s before call...
16:16:34 [second:F3564722.txt] call OK
16:16:34 [third:F3564722.txt] waiting 10s before call...
16:16:46 [third:F3564722.txt] call OK

Processing feedback documents from blob:  29%|██▉       | 64/222 [41:49<1:44:16, 39.60s/doc, F3564728.txt]

16:16:46 [first:F3564728.txt] waiting 10s before call...
16:16:59 [first:F3564728.txt] call OK
16:16:59 [second:F3564728.txt] waiting 10s before call...
16:17:11 [second:F3564728.txt] call OK
16:17:11 [third:F3564728.txt] waiting 10s before call...
16:17:24 [third:F3564728.txt] call OK

Processing feedback documents from blob:  29%|██▉       | 65/222 [42:27<1:41:59, 38.98s/doc, F3564736.txt]

16:17:24 [first:F3564736.txt] waiting 10s before call...
16:17:38 [first:F3564736.txt] call OK
16:17:38 [second:F3564736.txt] waiting 10s before call...
16:17:50 [second:F3564736.txt] call OK
16:17:50 [third:F3564736.txt] waiting 10s before call...
16:18:03 [third:F3564736.txt] call OK

Processing feedback documents from blob:  30%|██▉       | 66/222 [43:06<1:41:51, 39.17s/doc, F3564738.txt]

16:18:03 [first:F3564738.txt] waiting 10s before call...
16:18:17 [first:F3564738.txt] call OK
16:18:17 [second:F3564738.txt] waiting 10s before call...
16:18:30 [second:F3564738.txt] call OK
16:18:30 [third:F3564738.txt] waiting 10s before call...
16:18:43 [third:F3564738.txt] call OK

Processing feedback documents from blob:  30%|███       | 67/222 [43:45<1:41:11, 39.17s/doc, F3564760.txt]

16:18:43 [first:F3564760.txt] waiting 10s before call...
16:18:56 [first:F3564760.txt] call OK
16:18:56 [second:F3564760.txt] waiting 10s before call...
16:19:09 [second:F3564760.txt] call OK
16:19:09 [third:F3564760.txt] waiting 10s before call...
16:19:21 [third:F3564760.txt] call OK

Processing feedback documents from blob:  31%|███       | 68/222 [44:24<1:40:08, 39.02s/doc, F3564769.txt]

16:19:21 [first:F3564769.txt] waiting 10s before call...
16:19:34 [first:F3564769.txt] call OK
16:19:34 [second:F3564769.txt] waiting 10s before call...
16:19:45 [second:F3564769.txt] call OK
16:19:45 [third:F3564769.txt] waiting 10s before call...
16:19:57 [third:F3564769.txt] call OK

Processing feedback documents from blob:  31%|███       | 69/222 [45:00<1:37:23, 38.19s/doc, F3564781.txt]

16:19:57 [first:F3564781.txt] waiting 10s before call...
16:20:15 [first:F3564781.txt] call OK
16:20:15 [second:F3564781.txt] waiting 10s before call...
16:20:29 [second:F3564781.txt] call OK
16:20:29 [third:F3564781.txt] waiting 10s before call...
16:20:41 [third:F3564781.txt] call OK

Processing feedback documents from blob:  32%|███▏      | 70/222 [45:44<1:40:47, 39.79s/doc, F3564784.txt]

[SAVED] checkpoint with 70 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_162041.json
16:20:41 [first:F3564784.txt] waiting 10s before call...
16:20:54 [first:F3564784.txt] call OK
16:20:54 [second:F3564784.txt] waiting 10s before call...
16:21:06 [second:F3564784.txt] call OK
16:21:06 [third:F3564784.txt] waiting 10s before call...
16:21:18 [third:F3564784.txt] call OK

Processing feedback documents from blob:  32%|███▏      | 71/222 [46:21<1:38:23, 39.10s/doc, F3564813.txt]

16:21:18 [first:F3564813.txt] waiting 10s before call...
16:21:35 [first:F3564813.txt] call OK
16:21:35 [second:F3564813.txt] waiting 10s before call...
16:21:50 [second:F3564813.txt] call OK
16:21:50 [third:F3564813.txt] waiting 10s before call...
16:22:03 [third:F3564813.txt] call OK

Processing feedback documents from blob:  32%|███▏      | 72/222 [47:05<1:41:29, 40.60s/doc, F3564816.txt]

16:22:03 [first:F3564816.txt] waiting 10s before call...
16:22:15 [first:F3564816.txt] call OK
16:22:15 [second:F3564816.txt] waiting 10s before call...
16:22:26 [second:F3564816.txt] call OK
16:22:26 [third:F3564816.txt] waiting 10s before call...
16:22:38 [third:F3564816.txt] call OK

Processing feedback documents from blob:  33%|███▎      | 73/222 [47:41<1:36:54, 39.02s/doc, F3564818.txt]

16:22:38 [first:F3564818.txt] waiting 10s before call...
16:22:50 [first:F3564818.txt] call OK
16:22:50 [second:F3564818.txt] waiting 10s before call...
16:23:02 [second:F3564818.txt] call OK
16:23:02 [third:F3564818.txt] waiting 10s before call...
16:23:15 [third:F3564818.txt] call OK

Processing feedback documents from blob:  33%|███▎      | 74/222 [48:18<1:34:34, 38.34s/doc, F3564826.txt]

16:23:15 [first:F3564826.txt] waiting 10s before call...
16:23:35 [first:F3564826.txt] call OK
16:23:35 [second:F3564826.txt] waiting 10s before call...
16:23:48 [second:F3564826.txt] call OK
16:23:48 [third:F3564826.txt] waiting 10s before call...
16:24:00 [third:F3564826.txt] call OK

Processing feedback documents from blob:  34%|███▍      | 75/222 [49:03<1:39:06, 40.46s/doc, F3564832.txt]

16:24:00 [first:F3564832.txt] waiting 10s before call...
16:24:14 [first:F3564832.txt] call OK
16:24:14 [second:F3564832.txt] waiting 10s before call...
16:24:27 [second:F3564832.txt] call OK
16:24:27 [third:F3564832.txt] waiting 10s before call...
16:24:40 [third:F3564832.txt] call OK

Processing feedback documents from blob:  34%|███▍      | 76/222 [49:43<1:38:01, 40.28s/doc, F3564833.txt]

16:24:40 [first:F3564833.txt] waiting 10s before call...
16:24:58 [first:F3564833.txt] call OK
16:24:58 [second:F3564833.txt] waiting 10s before call...
16:25:11 [second:F3564833.txt] call OK
16:25:11 [third:F3564833.txt] waiting 10s before call...
16:25:24 [third:F3564833.txt] call OK

Processing feedback documents from blob:  35%|███▍      | 77/222 [50:27<1:40:10, 41.45s/doc, F3564836.txt]

16:25:24 [first:F3564836.txt] waiting 10s before call...
16:25:38 [first:F3564836.txt] call OK
16:25:38 [second:F3564836.txt] waiting 10s before call...
16:25:50 [second:F3564836.txt] call OK
16:25:50 [third:F3564836.txt] waiting 10s before call...
16:26:02 [third:F3564836.txt] call OK

Processing feedback documents from blob:  35%|███▌      | 78/222 [51:05<1:37:13, 40.51s/doc, F3564841.txt]

16:26:02 [first:F3564841.txt] waiting 10s before call...
16:26:19 [first:F3564841.txt] call OK
16:26:19 [second:F3564841.txt] waiting 10s before call...
16:26:31 [second:F3564841.txt] call OK
16:26:31 [third:F3564841.txt] waiting 10s before call...
16:26:44 [third:F3564841.txt] call OK

Processing feedback documents from blob:  36%|███▌      | 79/222 [51:47<1:37:24, 40.87s/doc, F3564842.txt]

16:26:44 [first:F3564842.txt] waiting 10s before call...
16:26:57 [first:F3564842.txt] call OK
16:26:57 [second:F3564842.txt] waiting 10s before call...
16:27:09 [second:F3564842.txt] call OK
16:27:09 [third:F3564842.txt] waiting 10s before call...
16:27:21 [third:F3564842.txt] call OK

Processing feedback documents from blob:  36%|███▌      | 80/222 [52:24<1:34:08, 39.78s/doc, F3564843.txt]

[SAVED] checkpoint with 80 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_162721.json
16:27:21 [first:F3564843.txt] waiting 10s before call...
16:27:39 [first:F3564843.txt] call OK
16:27:39 [second:F3564843.txt] waiting 10s before call...
16:27:54 [second:F3564843.txt] call OK
16:27:54 [third:F3564843.txt] waiting 10s before call...
16:28:07 [third:F3564843.txt] call OK

Processing feedback documents from blob:  36%|███▋      | 81/222 [53:10<1:37:29, 41.49s/doc, F3564846.txt]

16:28:07 [first:F3564846.txt] waiting 10s before call...
16:28:20 [first:F3564846.txt] call OK
16:28:20 [second:F3564846.txt] waiting 10s before call...
16:28:32 [second:F3564846.txt] call OK
16:28:32 [third:F3564846.txt] waiting 10s before call...
16:28:44 [third:F3564846.txt] call OK

Processing feedback documents from blob:  37%|███▋      | 82/222 [53:47<1:34:04, 40.32s/doc, F3564851.txt]

16:28:44 [first:F3564851.txt] waiting 10s before call...
16:28:57 [first:F3564851.txt] call OK
16:28:57 [second:F3564851.txt] waiting 10s before call...
16:29:09 [second:F3564851.txt] call OK
16:29:09 [third:F3564851.txt] waiting 10s before call...
16:29:21 [third:F3564851.txt] call OK

Processing feedback documents from blob:  37%|███▋      | 83/222 [54:24<1:30:55, 39.25s/doc, F3564862.txt]

16:29:21 [first:F3564862.txt] waiting 10s before call...
16:29:36 [first:F3564862.txt] call OK
16:29:36 [second:F3564862.txt] waiting 10s before call...
16:29:49 [second:F3564862.txt] call OK
16:29:49 [third:F3564862.txt] waiting 10s before call...
16:30:02 [third:F3564862.txt] call OK

Processing feedback documents from blob:  38%|███▊      | 84/222 [55:05<1:31:38, 39.84s/doc, F3564863.txt]

16:30:02 [first:F3564863.txt] waiting 10s before call...
16:30:18 [first:F3564863.txt] call OK
16:30:18 [second:F3564863.txt] waiting 10s before call...
16:30:30 [second:F3564863.txt] call OK
16:30:30 [third:F3564863.txt] waiting 10s before call...
16:30:43 [third:F3564863.txt] call OK

Processing feedback documents from blob:  38%|███▊      | 85/222 [55:46<1:31:17, 39.98s/doc, F3564899.txt]

16:30:43 [first:F3564899.txt] waiting 10s before call...
16:30:57 [first:F3564899.txt] call OK
16:30:57 [second:F3564899.txt] waiting 10s before call...
16:31:11 [second:F3564899.txt] call OK
16:31:11 [third:F3564899.txt] waiting 10s before call...
16:31:24 [third:F3564899.txt] call OK

Processing feedback documents from blob:  39%|███▊      | 86/222 [56:27<1:31:50, 40.52s/doc, F3564900.txt]

16:31:24 [first:F3564900.txt] waiting 10s before call...
16:31:37 [first:F3564900.txt] call OK
16:31:37 [second:F3564900.txt] waiting 10s before call...
16:31:49 [second:F3564900.txt] call OK
16:31:49 [third:F3564900.txt] waiting 10s before call...
16:32:01 [third:F3564900.txt] call OK

Processing feedback documents from blob:  39%|███▉      | 87/222 [57:04<1:28:39, 39.40s/doc, F3564901.txt]

16:32:01 [first:F3564901.txt] waiting 10s before call...
16:32:24 [first:F3564901.txt] call OK
16:32:24 [second:F3564901.txt] waiting 10s before call...
16:32:36 [second:F3564901.txt] call OK
16:32:36 [third:F3564901.txt] waiting 10s before call...
16:32:50 [third:F3564901.txt] call OK

Processing feedback documents from blob:  40%|███▉      | 88/222 [57:53<1:34:32, 42.33s/doc, F3564907.txt]

16:32:50 [first:F3564907.txt] waiting 10s before call...
16:33:05 [first:F3564907.txt] call OK
16:33:05 [second:F3564907.txt] waiting 10s before call...
16:33:18 [second:F3564907.txt] call OK
16:33:18 [third:F3564907.txt] waiting 10s before call...
16:33:30 [third:F3564907.txt] call OK

Processing feedback documents from blob:  40%|████      | 89/222 [58:33<1:31:52, 41.44s/doc, F3564909.txt]

16:33:30 [first:F3564909.txt] waiting 10s before call...
16:33:43 [first:F3564909.txt] call OK
16:33:43 [second:F3564909.txt] waiting 10s before call...
16:33:57 [second:F3564909.txt] call OK
16:33:57 [third:F3564909.txt] waiting 10s before call...
16:34:10 [third:F3564909.txt] call OK

Processing feedback documents from blob:  41%|████      | 90/222 [59:13<1:30:19, 41.06s/doc, F3564912.txt]

[SAVED] checkpoint with 90 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_163410.json
16:34:10 [first:F3564912.txt] waiting 10s before call...
16:34:24 [first:F3564912.txt] call OK
16:34:24 [second:F3564912.txt] waiting 10s before call...
16:34:36 [second:F3564912.txt] call OK
16:34:36 [third:F3564912.txt] waiting 10s before call...
16:34:48 [third:F3564912.txt] call OK

Processing feedback documents from blob:  41%|████      | 91/222 [59:51<1:27:45, 40.19s/doc, F3564918.txt]

16:34:48 [first:F3564918.txt] waiting 10s before call...
16:35:01 [first:F3564918.txt] call OK
16:35:01 [second:F3564918.txt] waiting 10s before call...
16:35:13 [second:F3564918.txt] call OK
16:35:13 [third:F3564918.txt] waiting 10s before call...
16:35:26 [third:F3564918.txt] call OK

Processing feedback documents from blob:  41%|████▏     | 92/222 [1:00:29<1:25:37, 39.52s/doc, F3564919.txt]

16:35:26 [first:F3564919.txt] waiting 10s before call...
16:35:39 [first:F3564919.txt] call OK
16:35:39 [second:F3564919.txt] waiting 10s before call...
16:35:51 [second:F3564919.txt] call OK
16:35:51 [third:F3564919.txt] waiting 10s before call...
16:36:05 [third:F3564919.txt] call OK

Processing feedback documents from blob:  42%|████▏     | 93/222 [1:01:07<1:24:17, 39.21s/doc, F3564930.txt]

16:36:05 [first:F3564930.txt] waiting 10s before call...
16:36:20 [first:F3564930.txt] call OK
16:36:20 [second:F3564930.txt] waiting 10s before call...
16:36:33 [second:F3564930.txt] call OK
16:36:33 [third:F3564930.txt] waiting 10s before call...
16:36:47 [third:F3564930.txt] call OK

Processing feedback documents from blob:  42%|████▏     | 94/222 [1:01:49<1:25:25, 40.04s/doc, F3564942.txt]

16:36:47 [first:F3564942.txt] waiting 10s before call...
16:36:59 [first:F3564942.txt] call OK
16:36:59 [second:F3564942.txt] waiting 10s before call...
16:37:14 [second:F3564942.txt] call OK
16:37:14 [third:F3564942.txt] waiting 10s before call...
16:37:26 [third:F3564942.txt] call OK

Processing feedback documents from blob:  43%|████▎     | 95/222 [1:02:29<1:24:30, 39.93s/doc, F3564964.txt]

16:37:26 [first:F3564964.txt] waiting 10s before call...
16:37:42 [first:F3564964.txt] call OK
16:37:42 [second:F3564964.txt] waiting 10s before call...
16:37:54 [second:F3564964.txt] call OK
16:37:54 [third:F3564964.txt] waiting 10s before call...
16:38:07 [third:F3564964.txt] call OK

Processing feedback documents from blob:  43%|████▎     | 96/222 [1:03:10<1:24:10, 40.08s/doc, F3564965.txt]

16:38:07 [first:F3564965.txt] waiting 10s before call...
16:38:26 [first:F3564965.txt] call OK
16:38:26 [second:F3564965.txt] waiting 10s before call...
16:38:39 [second:F3564965.txt] call OK
16:38:39 [third:F3564965.txt] waiting 10s before call...
16:38:51 [third:F3564965.txt] call OK

Processing feedback documents from blob:  44%|████▎     | 97/222 [1:03:54<1:26:24, 41.48s/doc, F3564967.txt]

16:38:51 [first:F3564967.txt] waiting 10s before call...
16:39:04 [first:F3564967.txt] call OK
16:39:04 [second:F3564967.txt] waiting 10s before call...
16:39:15 [second:F3564967.txt] call OK
16:39:15 [third:F3564967.txt] waiting 10s before call...
16:39:27 [third:F3564967.txt] call OK

Processing feedback documents from blob:  44%|████▍     | 98/222 [1:04:30<1:22:03, 39.70s/doc, F3564970.txt]

16:39:27 [first:F3564970.txt] waiting 10s before call...
16:39:42 [first:F3564970.txt] call OK
16:39:42 [second:F3564970.txt] waiting 10s before call...
16:39:55 [second:F3564970.txt] call OK
16:39:55 [third:F3564970.txt] waiting 10s before call...
16:40:08 [third:F3564970.txt] call OK

Processing feedback documents from blob:  45%|████▍     | 99/222 [1:05:11<1:22:03, 40.03s/doc, F3564976.txt]

16:40:08 [first:F3564976.txt] waiting 10s before call...
16:40:23 [first:F3564976.txt] call OK
16:40:23 [second:F3564976.txt] waiting 10s before call...
16:40:37 [second:F3564976.txt] call OK
16:40:37 [third:F3564976.txt] waiting 10s before call...
16:40:51 [third:F3564976.txt] call OK

Processing feedback documents from blob:  45%|████▌     | 100/222 [1:05:54<1:23:22, 41.00s/doc, F3564981.txt]

[SAVED] checkpoint with 100 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_164051.json
16:40:51 [first:F3564981.txt] waiting 10s before call...
16:41:05 [first:F3564981.txt] call OK
16:41:05 [second:F3564981.txt] waiting 10s before call...
16:41:17 [second:F3564981.txt] call OK
16:41:17 [third:F3564981.txt] waiting 10s before call...
16:41:31 [third:F3564981.txt] call OK

Processing feedback documents from blob:  45%|████▌     | 101/222 [1:06:33<1:21:46, 40.55s/doc, F3564982.txt]

16:41:31 [first:F3564982.txt] waiting 10s before call...
16:41:47 [first:F3564982.txt] call OK
16:41:47 [second:F3564982.txt] waiting 10s before call...
16:41:59 [second:F3564982.txt] call OK
16:41:59 [third:F3564982.txt] waiting 10s before call...
16:42:12 [third:F3564982.txt] call OK

Processing feedback documents from blob:  46%|████▌     | 102/222 [1:07:15<1:21:53, 40.95s/doc, F3564990.txt]

16:42:12 [first:F3564990.txt] waiting 10s before call...
16:42:26 [first:F3564990.txt] call OK
16:42:26 [second:F3564990.txt] waiting 10s before call...
16:42:38 [second:F3564990.txt] call OK
16:42:38 [third:F3564990.txt] waiting 10s before call...
16:42:53 [third:F3564990.txt] call OK

Processing feedback documents from blob:  46%|████▋     | 103/222 [1:07:56<1:20:54, 40.79s/doc, F3564997.txt]

16:42:53 [first:F3564997.txt] waiting 10s before call...
16:43:08 [first:F3564997.txt] call OK
16:43:08 [second:F3564997.txt] waiting 10s before call...
16:43:19 [second:F3564997.txt] call OK
16:43:19 [third:F3564997.txt] waiting 10s before call...
16:43:32 [third:F3564997.txt] call OK

Processing feedback documents from blob:  47%|████▋     | 104/222 [1:08:35<1:19:24, 40.37s/doc, F3564998.txt]

16:43:32 [first:F3564998.txt] waiting 10s before call...
16:43:46 [first:F3564998.txt] call OK
16:43:46 [second:F3564998.txt] waiting 10s before call...
16:43:58 [second:F3564998.txt] call OK
16:43:58 [third:F3564998.txt] waiting 10s before call...
16:44:10 [third:F3564998.txt] call OK

Processing feedback documents from blob:  47%|████▋     | 105/222 [1:09:13<1:17:04, 39.53s/doc, F3565010.txt]

16:44:10 [first:F3565010.txt] waiting 10s before call...
16:44:29 [first:F3565010.txt] call OK
16:44:29 [second:F3565010.txt] waiting 10s before call...
16:44:43 [second:F3565010.txt] call OK
16:44:43 [third:F3565010.txt] waiting 10s before call...
16:44:57 [third:F3565010.txt] call OK

Processing feedback documents from blob:  48%|████▊     | 106/222 [1:10:00<1:21:01, 41.91s/doc, F3565025.txt]

16:44:57 [first:F3565025.txt] waiting 10s before call...
16:45:11 [first:F3565025.txt] call OK
16:45:11 [second:F3565025.txt] waiting 10s before call...
16:45:23 [second:F3565025.txt] call OK
16:45:23 [third:F3565025.txt] waiting 10s before call...
16:45:36 [third:F3565025.txt] call OK

Processing feedback documents from blob:  48%|████▊     | 107/222 [1:10:39<1:18:31, 40.97s/doc, F3565034.txt]

16:45:36 [first:F3565034.txt] waiting 10s before call...
16:45:49 [first:F3565034.txt] call OK
16:45:50 [second:F3565034.txt] waiting 10s before call...
16:46:01 [second:F3565034.txt] call OK
16:46:01 [third:F3565034.txt] waiting 10s before call...
16:46:14 [third:F3565034.txt] call OK

Processing feedback documents from blob:  49%|████▊     | 108/222 [1:11:17<1:16:06, 40.06s/doc, F3565040.txt]

16:46:14 [first:F3565040.txt] waiting 10s before call...
16:46:29 [first:F3565040.txt] call OK
16:46:29 [second:F3565040.txt] waiting 10s before call...
16:46:43 [second:F3565040.txt] call OK
16:46:43 [third:F3565040.txt] waiting 10s before call...
16:46:55 [third:F3565040.txt] call OK

Processing feedback documents from blob:  49%|████▉     | 109/222 [1:11:58<1:16:14, 40.48s/doc, F3565042.txt]

16:46:55 [first:F3565042.txt] waiting 10s before call...
16:47:08 [first:F3565042.txt] call OK
16:47:08 [second:F3565042.txt] waiting 10s before call...
16:47:20 [second:F3565042.txt] call OK
16:47:20 [third:F3565042.txt] waiting 10s before call...
16:47:34 [third:F3565042.txt] call OK

Processing feedback documents from blob:  50%|████▉     | 110/222 [1:12:36<1:14:13, 39.76s/doc, F3565052.txt]

[SAVED] checkpoint with 110 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_164734.json
16:47:34 [first:F3565052.txt] waiting 10s before call...
16:47:51 [first:F3565052.txt] call OK
16:47:51 [second:F3565052.txt] waiting 10s before call...
16:48:04 [second:F3565052.txt] call OK
16:48:04 [third:F3565052.txt] waiting 10s before call...
16:48:20 [third:F3565052.txt] call OK

Processing feedback documents from blob:  50%|█████     | 111/222 [1:13:23<1:17:29, 41.89s/doc, F3565059.txt]

16:48:20 [first:F3565059.txt] waiting 10s before call...
16:48:33 [first:F3565059.txt] call OK
16:48:33 [second:F3565059.txt] waiting 10s before call...
16:48:46 [second:F3565059.txt] call OK
16:48:46 [third:F3565059.txt] waiting 10s before call...
16:49:01 [third:F3565059.txt] call OK

Processing feedback documents from blob:  50%|█████     | 112/222 [1:14:03<1:15:51, 41.38s/doc, F3565061.txt]

16:49:01 [first:F3565061.txt] waiting 10s before call...
16:49:18 [first:F3565061.txt] call OK
16:49:18 [second:F3565061.txt] waiting 10s before call...
16:49:32 [second:F3565061.txt] call OK
16:49:32 [third:F3565061.txt] waiting 10s before call...
16:49:44 [third:F3565061.txt] call OK

Processing feedback documents from blob:  51%|█████     | 113/222 [1:14:47<1:16:27, 42.09s/doc, F3565064.txt]

16:49:44 [first:F3565064.txt] waiting 10s before call...
16:50:00 [first:F3565064.txt] call OK
16:50:00 [second:F3565064.txt] waiting 10s before call...
16:50:12 [second:F3565064.txt] call OK
16:50:12 [third:F3565064.txt] waiting 10s before call...
16:50:25 [third:F3565064.txt] call OK

Processing feedback documents from blob:  51%|█████▏    | 114/222 [1:15:27<1:14:46, 41.54s/doc, F3565089.txt]

16:50:25 [first:F3565089.txt] waiting 10s before call...
16:50:37 [first:F3565089.txt] call OK
16:50:37 [second:F3565089.txt] waiting 10s before call...
16:50:49 [second:F3565089.txt] call OK
16:50:49 [third:F3565089.txt] waiting 10s before call...
16:51:02 [third:F3565089.txt] call OK

Processing feedback documents from blob:  52%|█████▏    | 115/222 [1:16:05<1:11:44, 40.23s/doc, F3565090.txt]

16:51:02 [first:F3565090.txt] waiting 10s before call...
16:51:15 [first:F3565090.txt] call OK
16:51:15 [second:F3565090.txt] waiting 10s before call...
16:51:28 [second:F3565090.txt] call OK
16:51:28 [third:F3565090.txt] waiting 10s before call...
16:51:40 [third:F3565090.txt] call OK

Processing feedback documents from blob:  52%|█████▏    | 116/222 [1:16:43<1:10:00, 39.63s/doc, F3565110.txt]

16:51:40 [first:F3565110.txt] waiting 10s before call...
16:51:55 [first:F3565110.txt] call OK
16:51:55 [second:F3565110.txt] waiting 10s before call...
16:52:07 [second:F3565110.txt] call OK
16:52:07 [third:F3565110.txt] waiting 10s before call...
16:52:20 [third:F3565110.txt] call OK

Processing feedback documents from blob:  53%|█████▎    | 117/222 [1:17:23<1:09:38, 39.80s/doc, F3565113.txt]

16:52:20 [first:F3565113.txt] waiting 10s before call...
16:52:33 [first:F3565113.txt] call OK
16:52:33 [second:F3565113.txt] waiting 10s before call...
16:52:47 [second:F3565113.txt] call OK
16:52:47 [third:F3565113.txt] waiting 10s before call...
16:52:59 [third:F3565113.txt] call OK

Processing feedback documents from blob:  53%|█████▎    | 118/222 [1:18:02<1:08:33, 39.55s/doc, F3565115.txt]

16:52:59 [first:F3565115.txt] waiting 10s before call...
16:53:13 [first:F3565115.txt] call OK
16:53:13 [second:F3565115.txt] waiting 10s before call...
16:53:28 [second:F3565115.txt] call OK
16:53:28 [third:F3565115.txt] waiting 10s before call...
16:53:41 [third:F3565115.txt] call OK

Processing feedback documents from blob:  54%|█████▎    | 119/222 [1:18:44<1:09:19, 40.39s/doc, F3565117.txt]

16:53:41 [first:F3565117.txt] waiting 10s before call...
16:54:00 [first:F3565117.txt] call OK
16:54:00 [second:F3565117.txt] waiting 10s before call...
16:54:13 [second:F3565117.txt] call OK
16:54:13 [third:F3565117.txt] waiting 10s before call...
16:54:25 [third:F3565117.txt] call OK

Processing feedback documents from blob:  54%|█████▍    | 120/222 [1:19:28<1:10:20, 41.38s/doc, F3565118.txt]

[SAVED] checkpoint with 120 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_165425.json
16:54:25 [first:F3565118.txt] waiting 10s before call...
16:54:42 [first:F3565118.txt] call OK
16:54:42 [second:F3565118.txt] waiting 10s before call...
16:54:54 [second:F3565118.txt] call OK
16:54:54 [third:F3565118.txt] waiting 10s before call...
16:55:06 [third:F3565118.txt] call OK

Processing feedback documents from blob:  55%|█████▍    | 121/222 [1:20:09<1:09:35, 41.34s/doc, F3565136.txt]

16:55:06 [first:F3565136.txt] waiting 10s before call...
16:55:19 [first:F3565136.txt] call OK
16:55:19 [second:F3565136.txt] waiting 10s before call...
16:55:32 [second:F3565136.txt] call OK
16:55:32 [third:F3565136.txt] waiting 10s before call...
16:55:46 [third:F3565136.txt] call OK

Processing feedback documents from blob:  55%|█████▍    | 122/222 [1:20:49<1:07:49, 40.69s/doc, F3565143.txt]

16:55:46 [first:F3565143.txt] waiting 10s before call...
16:56:00 [first:F3565143.txt] call OK
16:56:00 [second:F3565143.txt] waiting 10s before call...
16:56:13 [second:F3565143.txt] call OK
16:56:13 [third:F3565143.txt] waiting 10s before call...
16:56:27 [third:F3565143.txt] call OK

Processing feedback documents from blob:  55%|█████▌    | 123/222 [1:21:30<1:07:25, 40.86s/doc, F3565157.txt]

16:56:27 [first:F3565157.txt] waiting 10s before call...
16:56:41 [first:F3565157.txt] call OK
16:56:41 [second:F3565157.txt] waiting 10s before call...
16:56:53 [second:F3565157.txt] call OK
16:56:53 [third:F3565157.txt] waiting 10s before call...
16:57:05 [third:F3565157.txt] call OK

Processing feedback documents from blob:  56%|█████▌    | 124/222 [1:22:08<1:05:34, 40.15s/doc, F3565164.txt]

16:57:05 [first:F3565164.txt] waiting 10s before call...
16:57:19 [first:F3565164.txt] call OK
16:57:19 [second:F3565164.txt] waiting 10s before call...
16:57:32 [second:F3565164.txt] call OK
16:57:32 [third:F3565164.txt] waiting 10s before call...
16:57:44 [third:F3565164.txt] call OK

Processing feedback documents from blob:  56%|█████▋    | 125/222 [1:22:47<1:04:24, 39.84s/doc, F3565165.txt]

16:57:44 [first:F3565165.txt] waiting 10s before call...
16:57:58 [first:F3565165.txt] call OK
16:57:58 [second:F3565165.txt] waiting 10s before call...
16:58:11 [second:F3565165.txt] call OK
16:58:11 [third:F3565165.txt] waiting 10s before call...
16:58:24 [third:F3565165.txt] call OK

Processing feedback documents from blob:  57%|█████▋    | 126/222 [1:23:27<1:03:35, 39.74s/doc, F3565166.txt]

16:58:24 [first:F3565166.txt] waiting 10s before call...
16:58:37 [first:F3565166.txt] call OK
16:58:37 [second:F3565166.txt] waiting 10s before call...
16:58:49 [second:F3565166.txt] call OK
16:58:49 [third:F3565166.txt] waiting 10s before call...
16:59:02 [third:F3565166.txt] call OK

Processing feedback documents from blob:  57%|█████▋    | 127/222 [1:24:05<1:02:10, 39.27s/doc, F3565172.txt]

16:59:02 [first:F3565172.txt] waiting 10s before call...
16:59:16 [first:F3565172.txt] call OK
16:59:16 [second:F3565172.txt] waiting 10s before call...
16:59:28 [second:F3565172.txt] call OK
16:59:28 [third:F3565172.txt] waiting 10s before call...
16:59:40 [third:F3565172.txt] call OK

Processing feedback documents from blob:  58%|█████▊    | 128/222 [1:24:43<1:00:49, 38.82s/doc, F3565196.txt]

16:59:40 [first:F3565196.txt] waiting 10s before call...
16:59:52 [first:F3565196.txt] call OK
16:59:52 [second:F3565196.txt] waiting 10s before call...
17:00:04 [second:F3565196.txt] call OK
17:00:04 [third:F3565196.txt] waiting 10s before call...
17:00:17 [third:F3565196.txt] call OK

Processing feedback documents from blob:  58%|█████▊    | 129/222 [1:25:20<59:11, 38.19s/doc, F3565207.txt]

17:00:17 [first:F3565207.txt] waiting 10s before call...
17:00:29 [first:F3565207.txt] call OK
17:00:29 [second:F3565207.txt] waiting 10s before call...
17:00:41 [second:F3565207.txt] call OK
17:00:41 [third:F3565207.txt] waiting 10s before call...
17:00:53 [third:F3565207.txt] call OK

Processing feedback documents from blob:  59%|█████▊    | 130/222 [1:25:56<57:36, 37.57s/doc, F3565208.txt]

[SAVED] checkpoint with 130 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_170053.json
17:00:53 [first:F3565208.txt] waiting 10s before call...
17:01:05 [first:F3565208.txt] call OK
17:01:05 [second:F3565208.txt] waiting 10s before call...
17:01:16 [second:F3565208.txt] call OK
17:01:16 [third:F3565208.txt] waiting 10s before call...
17:01:28 [third:F3565208.txt] call OK

Processing feedback documents from blob:  59%|█████▉    | 131/222 [1:26:31<56:07, 37.01s/doc, F3565219.txt]

17:01:28 [first:F3565219.txt] waiting 10s before call...
17:01:42 [first:F3565219.txt] call OK
17:01:42 [second:F3565219.txt] waiting 10s before call...
17:01:54 [second:F3565219.txt] call OK
17:01:54 [third:F3565219.txt] waiting 10s before call...
17:02:06 [third:F3565219.txt] call OK

Processing feedback documents from blob:  59%|█████▉    | 132/222 [1:27:09<55:58, 37.32s/doc, F3565224.txt]

17:02:06 [first:F3565224.txt] waiting 10s before call...
17:02:22 [first:F3565224.txt] call OK
17:02:22 [second:F3565224.txt] waiting 10s before call...
17:02:35 [second:F3565224.txt] call OK
17:02:35 [third:F3565224.txt] waiting 10s before call...
17:02:49 [third:F3565224.txt] call OK

Processing feedback documents from blob:  60%|█████▉    | 133/222 [1:27:52<57:51, 39.01s/doc, F3565229.txt]

17:02:49 [first:F3565229.txt] waiting 10s before call...
17:03:02 [first:F3565229.txt] call OK
17:03:02 [second:F3565229.txt] waiting 10s before call...
17:03:14 [second:F3565229.txt] call OK
17:03:14 [third:F3565229.txt] waiting 10s before call...
17:03:26 [third:F3565229.txt] call OK

Processing feedback documents from blob:  60%|██████    | 134/222 [1:28:29<56:11, 38.31s/doc, F3565230.txt]

17:03:26 [first:F3565230.txt] waiting 10s before call...
17:03:41 [first:F3565230.txt] call OK
17:03:41 [second:F3565230.txt] waiting 10s before call...
17:03:54 [second:F3565230.txt] call OK
17:03:54 [third:F3565230.txt] waiting 10s before call...
17:04:07 [third:F3565230.txt] call OK

Processing feedback documents from blob:  61%|██████    | 135/222 [1:29:09<56:28, 38.95s/doc, F3565232.txt]

17:04:07 [first:F3565232.txt] waiting 10s before call...
17:04:20 [first:F3565232.txt] call OK
17:04:20 [second:F3565232.txt] waiting 10s before call...
17:04:31 [second:F3565232.txt] call OK
17:04:31 [third:F3565232.txt] waiting 10s before call...
17:04:44 [third:F3565232.txt] call OK

Processing feedback documents from blob:  61%|██████▏   | 136/222 [1:29:46<54:58, 38.35s/doc, F3565234.txt]

17:04:44 [first:F3565234.txt] waiting 10s before call...
17:04:59 [first:F3565234.txt] call OK
17:04:59 [second:F3565234.txt] waiting 10s before call...
17:05:11 [second:F3565234.txt] call OK
17:05:11 [third:F3565234.txt] waiting 10s before call...
17:05:23 [third:F3565234.txt] call OK

Processing feedback documents from blob:  62%|██████▏   | 137/222 [1:30:26<54:44, 38.64s/doc, F3565236.txt]

17:05:23 [first:F3565236.txt] waiting 10s before call...
17:05:36 [first:F3565236.txt] call OK
17:05:36 [second:F3565236.txt] waiting 10s before call...
17:05:48 [second:F3565236.txt] call OK
17:05:48 [third:F3565236.txt] waiting 10s before call...
17:06:01 [third:F3565236.txt] call OK

Processing feedback documents from blob:  62%|██████▏   | 138/222 [1:31:04<53:49, 38.45s/doc, F3565239.txt]

17:06:01 [first:F3565239.txt] waiting 10s before call...
17:06:16 [first:F3565239.txt] call OK
17:06:16 [second:F3565239.txt] waiting 10s before call...
17:06:27 [second:F3565239.txt] call OK
17:06:27 [third:F3565239.txt] waiting 10s before call...
17:06:40 [third:F3565239.txt] call OK

Processing feedback documents from blob:  63%|██████▎   | 139/222 [1:31:43<53:26, 38.64s/doc, F3565249.txt]

17:06:40 [first:F3565249.txt] waiting 10s before call...
17:06:52 [first:F3565249.txt] call OK
17:06:52 [second:F3565249.txt] waiting 10s before call...
17:07:04 [second:F3565249.txt] call OK
17:07:04 [third:F3565249.txt] waiting 10s before call...
17:07:17 [third:F3565249.txt] call OK

Processing feedback documents from blob:  63%|██████▎   | 140/222 [1:32:20<52:10, 38.18s/doc, F3565250.txt]

[SAVED] checkpoint with 140 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_170717.json
17:07:17 [first:F3565250.txt] waiting 10s before call...
17:07:31 [first:F3565250.txt] call OK
17:07:31 [second:F3565250.txt] waiting 10s before call...
17:07:44 [second:F3565250.txt] call OK
17:07:44 [third:F3565250.txt] waiting 10s before call...
17:07:56 [third:F3565250.txt] call OK

Processing feedback documents from blob:  64%|██████▎   | 141/222 [1:32:59<51:56, 38.47s/doc, F3565251.txt]

17:07:56 [first:F3565251.txt] waiting 10s before call...
17:08:10 [first:F3565251.txt] call OK
17:08:10 [second:F3565251.txt] waiting 10s before call...
17:08:22 [second:F3565251.txt] call OK
17:08:22 [third:F3565251.txt] waiting 10s before call...
17:08:34 [third:F3565251.txt] call OK

Processing feedback documents from blob:  64%|██████▍   | 142/222 [1:33:37<51:07, 38.34s/doc, F3565252.txt]

17:08:34 [first:F3565252.txt] waiting 10s before call...
17:08:47 [first:F3565252.txt] call OK
17:08:47 [second:F3565252.txt] waiting 10s before call...
17:08:59 [second:F3565252.txt] call OK
17:08:59 [third:F3565252.txt] waiting 10s before call...
17:09:11 [third:F3565252.txt] call OK

Processing feedback documents from blob:  64%|██████▍   | 143/222 [1:34:14<49:53, 37.89s/doc, F3565256.txt]

17:09:11 [first:F3565256.txt] waiting 10s before call...
17:09:26 [first:F3565256.txt] call OK
17:09:26 [second:F3565256.txt] waiting 10s before call...
17:09:38 [second:F3565256.txt] call OK
17:09:38 [third:F3565256.txt] waiting 10s before call...
17:09:50 [third:F3565256.txt] call OK

Processing feedback documents from blob:  65%|██████▍   | 144/222 [1:34:53<49:41, 38.23s/doc, F3565258.txt]

17:09:50 [first:F3565258.txt] waiting 10s before call...
17:10:04 [first:F3565258.txt] call OK
17:10:04 [second:F3565258.txt] waiting 10s before call...
17:10:16 [second:F3565258.txt] call OK
17:10:16 [third:F3565258.txt] waiting 10s before call...
17:10:29 [third:F3565258.txt] call OK

Processing feedback documents from blob:  65%|██████▌   | 145/222 [1:35:31<49:08, 38.30s/doc, F3565261.txt]

17:10:29 [first:F3565261.txt] waiting 10s before call...
17:10:42 [first:F3565261.txt] call OK
17:10:42 [second:F3565261.txt] waiting 10s before call...
17:10:55 [second:F3565261.txt] call OK
17:10:55 [third:F3565261.txt] waiting 10s before call...
17:11:07 [third:F3565261.txt] call OK

Processing feedback documents from blob:  66%|██████▌   | 146/222 [1:36:10<48:40, 38.43s/doc, F3565273.txt]

17:11:07 [first:F3565273.txt] waiting 10s before call...
17:11:20 [first:F3565273.txt] call OK
17:11:20 [second:F3565273.txt] waiting 10s before call...
17:11:33 [second:F3565273.txt] call OK
17:11:33 [third:F3565273.txt] waiting 10s before call...
17:11:45 [third:F3565273.txt] call OK

Processing feedback documents from blob:  66%|██████▌   | 147/222 [1:36:48<47:58, 38.38s/doc, F3565277.txt]

17:11:46 [first:F3565277.txt] waiting 10s before call...
17:12:01 [first:F3565277.txt] call OK
17:12:01 [second:F3565277.txt] waiting 10s before call...
17:12:13 [second:F3565277.txt] call OK
17:12:13 [third:F3565277.txt] waiting 10s before call...
17:12:26 [third:F3565277.txt] call OK

Processing feedback documents from blob:  67%|██████▋   | 148/222 [1:37:29<48:15, 39.12s/doc, F3565281.txt]

17:12:26 [first:F3565281.txt] waiting 10s before call...
17:12:42 [first:F3565281.txt] call OK
17:12:42 [second:F3565281.txt] waiting 10s before call...
17:12:54 [second:F3565281.txt] call OK
17:12:54 [third:F3565281.txt] waiting 10s before call...
17:13:07 [third:F3565281.txt] call OK

Processing feedback documents from blob:  67%|██████▋   | 149/222 [1:38:10<48:08, 39.58s/doc, F3565284.txt]

17:13:07 [first:F3565284.txt] waiting 10s before call...
17:13:21 [first:F3565284.txt] call OK
17:13:21 [second:F3565284.txt] waiting 10s before call...
17:13:34 [second:F3565284.txt] call OK
17:13:34 [third:F3565284.txt] waiting 10s before call...
17:13:47 [third:F3565284.txt] call OK

Processing feedback documents from blob:  68%|██████▊   | 150/222 [1:38:50<47:41, 39.75s/doc, F3565286.txt]

[SAVED] checkpoint with 150 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_171347.json
17:13:47 [first:F3565286.txt] waiting 10s before call...
17:14:02 [first:F3565286.txt] call OK
17:14:02 [second:F3565286.txt] waiting 10s before call...
17:14:14 [second:F3565286.txt] call OK
17:14:14 [third:F3565286.txt] waiting 10s before call...
17:14:26 [third:F3565286.txt] call OK

Processing feedback documents from blob:  68%|██████▊   | 151/222 [1:39:29<46:48, 39.56s/doc, F3565287.txt]

17:14:26 [first:F3565287.txt] waiting 10s before call...
17:14:40 [first:F3565287.txt] call OK
17:14:40 [second:F3565287.txt] waiting 10s before call...
17:14:53 [second:F3565287.txt] call OK
17:14:53 [third:F3565287.txt] waiting 10s before call...
17:15:05 [third:F3565287.txt] call OK

Processing feedback documents from blob:  68%|██████▊   | 152/222 [1:40:08<45:43, 39.19s/doc, F3565290.txt]

17:15:05 [first:F3565290.txt] waiting 10s before call...
17:15:18 [first:F3565290.txt] call OK
17:15:18 [second:F3565290.txt] waiting 10s before call...
17:15:30 [second:F3565290.txt] call OK
17:15:30 [third:F3565290.txt] waiting 10s before call...
17:15:42 [third:F3565290.txt] call OK

Processing feedback documents from blob:  69%|██████▉   | 153/222 [1:40:45<44:36, 38.79s/doc, F3565295.txt]

17:15:42 [first:F3565295.txt] waiting 10s before call...
17:15:56 [first:F3565295.txt] call OK
17:15:56 [second:F3565295.txt] waiting 10s before call...
17:16:08 [second:F3565295.txt] call OK
17:16:08 [third:F3565295.txt] waiting 10s before call...
17:16:21 [third:F3565295.txt] call OK

Processing feedback documents from blob:  69%|██████▉   | 154/222 [1:41:23<43:43, 38.58s/doc, F3565296.txt]

17:16:21 [first:F3565296.txt] waiting 10s before call...
17:16:38 [first:F3565296.txt] call OK
17:16:38 [second:F3565296.txt] waiting 10s before call...
17:16:50 [second:F3565296.txt] call OK
17:16:50 [third:F3565296.txt] waiting 10s before call...
17:17:02 [third:F3565296.txt] call OK

Processing feedback documents from blob:  70%|██████▉   | 155/222 [1:42:05<44:02, 39.44s/doc, F3565302.txt]

17:17:02 [first:F3565302.txt] waiting 10s before call...
17:17:16 [first:F3565302.txt] call OK
17:17:16 [second:F3565302.txt] waiting 10s before call...
17:17:28 [second:F3565302.txt] call OK
17:17:28 [third:F3565302.txt] waiting 10s before call...
17:17:40 [third:F3565302.txt] call OK

Processing feedback documents from blob:  70%|███████   | 156/222 [1:42:43<42:57, 39.06s/doc, F3565307.txt]

17:17:40 [first:F3565307.txt] waiting 10s before call...
17:17:53 [first:F3565307.txt] call OK
17:17:53 [second:F3565307.txt] waiting 10s before call...
17:18:05 [second:F3565307.txt] call OK
17:18:05 [third:F3565307.txt] waiting 10s before call...
17:18:16 [third:F3565307.txt] call OK

Processing feedback documents from blob:  71%|███████   | 157/222 [1:43:19<41:22, 38.19s/doc, F3565312.txt]

17:18:16 [first:F3565312.txt] waiting 10s before call...
17:18:30 [first:F3565312.txt] call OK
17:18:30 [second:F3565312.txt] waiting 10s before call...
17:18:43 [second:F3565312.txt] call OK
17:18:43 [third:F3565312.txt] waiting 10s before call...
17:18:55 [third:F3565312.txt] call OK

Processing feedback documents from blob:  71%|███████   | 158/222 [1:43:58<41:03, 38.49s/doc, F3565315.txt]

17:18:56 [first:F3565315.txt] waiting 10s before call...
17:19:11 [first:F3565315.txt] call OK
17:19:11 [second:F3565315.txt] waiting 10s before call...
17:19:23 [second:F3565315.txt] call OK
17:19:23 [third:F3565315.txt] waiting 10s before call...
17:19:35 [third:F3565315.txt] call OK

Processing feedback documents from blob:  72%|███████▏  | 159/222 [1:44:38<40:44, 38.81s/doc, F3565317.txt]

17:19:35 [first:F3565317.txt] waiting 10s before call...
17:19:48 [first:F3565317.txt] call OK
17:19:48 [second:F3565317.txt] waiting 10s before call...
17:20:00 [second:F3565317.txt] call OK
17:20:00 [third:F3565317.txt] waiting 10s before call...
17:20:12 [third:F3565317.txt] call OK

Processing feedback documents from blob:  72%|███████▏  | 160/222 [1:45:15<39:40, 38.39s/doc, F3565319.txt]

[SAVED] checkpoint with 160 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_172012.json
17:20:12 [first:F3565319.txt] waiting 10s before call...
17:20:28 [first:F3565319.txt] call OK
17:20:28 [second:F3565319.txt] waiting 10s before call...
17:20:41 [second:F3565319.txt] call OK
17:20:41 [third:F3565319.txt] waiting 10s before call...
17:20:53 [third:F3565319.txt] call OK

Processing feedback documents from blob:  73%|███████▎  | 161/222 [1:45:56<39:37, 38.97s/doc, F3565321.txt]

17:20:53 [first:F3565321.txt] waiting 10s before call...
17:21:07 [first:F3565321.txt] call OK
17:21:07 [second:F3565321.txt] waiting 10s before call...
17:21:20 [second:F3565321.txt] call OK
17:21:20 [third:F3565321.txt] waiting 10s before call...
17:21:33 [third:F3565321.txt] call OK

Processing feedback documents from blob:  73%|███████▎  | 162/222 [1:46:36<39:14, 39.24s/doc, F3565323.txt]

17:21:33 [first:F3565323.txt] waiting 10s before call...
17:21:45 [first:F3565323.txt] call OK
17:21:45 [second:F3565323.txt] waiting 10s before call...
17:21:57 [second:F3565323.txt] call OK
17:21:57 [third:F3565323.txt] waiting 10s before call...
17:22:09 [third:F3565323.txt] call OK

Processing feedback documents from blob:  73%|███████▎  | 163/222 [1:47:12<37:42, 38.36s/doc, F3565339.txt]

17:22:09 [first:F3565339.txt] waiting 10s before call...
17:22:25 [first:F3565339.txt] call OK
17:22:25 [second:F3565339.txt] waiting 10s before call...
17:22:37 [second:F3565339.txt] call OK
17:22:37 [third:F3565339.txt] waiting 10s before call...
17:22:49 [third:F3565339.txt] call OK

Processing feedback documents from blob:  74%|███████▍  | 164/222 [1:47:52<37:42, 39.01s/doc, F3565340.txt]

17:22:50 [first:F3565340.txt] waiting 10s before call...
17:23:02 [first:F3565340.txt] call OK
17:23:02 [second:F3565340.txt] waiting 10s before call...
17:23:14 [second:F3565340.txt] call OK
17:23:14 [third:F3565340.txt] waiting 10s before call...
17:23:26 [third:F3565340.txt] call OK

Processing feedback documents from blob:  74%|███████▍  | 165/222 [1:48:29<36:28, 38.39s/doc, F3565342.txt]

17:23:26 [first:F3565342.txt] waiting 10s before call...
17:23:40 [first:F3565342.txt] call OK
17:23:40 [second:F3565342.txt] waiting 10s before call...
17:23:52 [second:F3565342.txt] call OK
17:23:52 [third:F3565342.txt] waiting 10s before call...
17:24:05 [third:F3565342.txt] call OK

Processing feedback documents from blob:  75%|███████▍  | 166/222 [1:49:08<35:46, 38.33s/doc, F3565344.txt]

17:24:05 [first:F3565344.txt] waiting 10s before call...
17:24:17 [first:F3565344.txt] call OK
17:24:17 [second:F3565344.txt] waiting 10s before call...
17:24:29 [second:F3565344.txt] call OK
17:24:29 [third:F3565344.txt] waiting 10s before call...
17:24:41 [third:F3565344.txt] call OK

Processing feedback documents from blob:  75%|███████▌  | 167/222 [1:49:44<34:35, 37.75s/doc, F3565349.txt]

17:24:41 [first:F3565349.txt] waiting 10s before call...
17:24:55 [first:F3565349.txt] call OK
17:24:55 [second:F3565349.txt] waiting 10s before call...
17:25:06 [second:F3565349.txt] call OK
17:25:06 [third:F3565349.txt] waiting 10s before call...
17:25:18 [third:F3565349.txt] call OK

Processing feedback documents from blob:  76%|███████▌  | 168/222 [1:50:21<33:53, 37.65s/doc, F3565354.txt]

17:25:18 [first:F3565354.txt] waiting 10s before call...
17:25:32 [first:F3565354.txt] call OK
17:25:32 [second:F3565354.txt] waiting 10s before call...
17:25:44 [second:F3565354.txt] call OK
17:25:44 [third:F3565354.txt] waiting 10s before call...
17:25:57 [third:F3565354.txt] call OK

Processing feedback documents from blob:  76%|███████▌  | 169/222 [1:51:00<33:25, 37.84s/doc, F3565356.txt]

17:25:57 [first:F3565356.txt] waiting 10s before call...
17:26:10 [first:F3565356.txt] call OK
17:26:10 [second:F3565356.txt] waiting 10s before call...
17:26:23 [second:F3565356.txt] call OK
17:26:23 [third:F3565356.txt] waiting 10s before call...
17:26:35 [third:F3565356.txt] call OK

Processing feedback documents from blob:  77%|███████▋  | 170/222 [1:51:38<33:00, 38.08s/doc, F3565357.txt]

[SAVED] checkpoint with 170 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_172635.json
17:26:35 [first:F3565357.txt] waiting 10s before call...
17:26:51 [first:F3565357.txt] call OK
17:26:51 [second:F3565357.txt] waiting 10s before call...
17:27:03 [second:F3565357.txt] call OK
17:27:03 [third:F3565357.txt] waiting 10s before call...
17:27:16 [third:F3565357.txt] call OK

Processing feedback documents from blob:  77%|███████▋  | 171/222 [1:52:19<33:00, 38.84s/doc, F3565358.txt]

17:27:16 [first:F3565358.txt] waiting 10s before call...
17:27:31 [first:F3565358.txt] call OK
17:27:31 [second:F3565358.txt] waiting 10s before call...
17:27:43 [second:F3565358.txt] call OK
17:27:43 [third:F3565358.txt] waiting 10s before call...
17:27:55 [third:F3565358.txt] call OK

Processing feedback documents from blob:  77%|███████▋  | 172/222 [1:52:58<32:24, 38.90s/doc, F3565359.txt]

17:27:55 [first:F3565359.txt] waiting 10s before call...
17:28:09 [first:F3565359.txt] call OK
17:28:09 [second:F3565359.txt] waiting 10s before call...
17:28:21 [second:F3565359.txt] call OK
17:28:21 [third:F3565359.txt] waiting 10s before call...
17:28:34 [third:F3565359.txt] call OK

Processing feedback documents from blob:  78%|███████▊  | 173/222 [1:53:37<31:49, 38.98s/doc, F3565361.txt]

17:28:34 [first:F3565361.txt] waiting 10s before call...
17:28:47 [first:F3565361.txt] call OK
17:28:47 [second:F3565361.txt] waiting 10s before call...
17:28:59 [second:F3565361.txt] call OK
17:28:59 [third:F3565361.txt] waiting 10s before call...
17:29:12 [third:F3565361.txt] call OK

Processing feedback documents from blob:  78%|███████▊  | 174/222 [1:54:15<30:56, 38.67s/doc, F3565366.txt]

17:29:12 [first:F3565366.txt] waiting 10s before call...
17:29:27 [first:F3565366.txt] call OK
17:29:27 [second:F3565366.txt] waiting 10s before call...
17:29:40 [second:F3565366.txt] call OK
17:29:40 [third:F3565366.txt] waiting 10s before call...
17:29:52 [third:F3565366.txt] call OK

Processing feedback documents from blob:  79%|███████▉  | 175/222 [1:54:55<30:32, 38.99s/doc, F3565367.txt]

17:29:52 [first:F3565367.txt] waiting 10s before call...
17:30:07 [first:F3565367.txt] call OK
17:30:07 [second:F3565367.txt] waiting 10s before call...
17:30:19 [second:F3565367.txt] call OK
17:30:19 [third:F3565367.txt] waiting 10s before call...
17:30:33 [third:F3565367.txt] call OK

Processing feedback documents from blob:  79%|███████▉  | 176/222 [1:55:36<30:20, 39.59s/doc, F3565369.txt]

17:30:33 [first:F3565369.txt] waiting 10s before call...
17:30:45 [first:F3565369.txt] call OK
17:30:45 [second:F3565369.txt] waiting 10s before call...
17:30:57 [second:F3565369.txt] call OK
17:30:57 [third:F3565369.txt] waiting 10s before call...
17:31:09 [third:F3565369.txt] call OK

Processing feedback documents from blob:  80%|███████▉  | 177/222 [1:56:11<28:49, 38.42s/doc, F3565371.txt]

17:31:09 [first:F3565371.txt] waiting 10s before call...
17:31:21 [first:F3565371.txt] call OK
17:31:21 [second:F3565371.txt] waiting 10s before call...
17:31:33 [second:F3565371.txt] call OK
17:31:33 [third:F3565371.txt] waiting 10s before call...
17:31:45 [third:F3565371.txt] call OK

Processing feedback documents from blob:  80%|████████  | 178/222 [1:56:48<27:39, 37.71s/doc, F3565376.txt]

17:31:45 [first:F3565376.txt] waiting 10s before call...
17:31:59 [first:F3565376.txt] call OK
17:31:59 [second:F3565376.txt] waiting 10s before call...
17:32:11 [second:F3565376.txt] call OK
17:32:11 [third:F3565376.txt] waiting 10s before call...
17:32:23 [third:F3565376.txt] call OK

Processing feedback documents from blob:  81%|████████  | 179/222 [1:57:26<27:09, 37.90s/doc, F3565383.txt]

17:32:23 [first:F3565383.txt] waiting 10s before call...
17:32:36 [first:F3565383.txt] call OK
17:32:36 [second:F3565383.txt] waiting 10s before call...
17:32:48 [second:F3565383.txt] call OK
17:32:48 [third:F3565383.txt] waiting 10s before call...
17:33:00 [third:F3565383.txt] call OK

Processing feedback documents from blob:  81%|████████  | 180/222 [1:58:03<26:18, 37.58s/doc, F3565386.txt]

[SAVED] checkpoint with 180 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_173300.json
17:33:00 [first:F3565386.txt] waiting 10s before call...
17:33:13 [first:F3565386.txt] call OK
17:33:13 [second:F3565386.txt] waiting 10s before call...
17:33:25 [second:F3565386.txt] call OK
17:33:25 [third:F3565386.txt] waiting 10s before call...
17:33:38 [third:F3565386.txt] call OK

Processing feedback documents from blob:  82%|████████▏ | 181/222 [1:58:41<25:45, 37.70s/doc, F3565387.txt]

17:33:38 [first:F3565387.txt] waiting 10s before call...
17:33:55 [first:F3565387.txt] call OK
17:33:55 [second:F3565387.txt] waiting 10s before call...
17:34:09 [second:F3565387.txt] call OK
17:34:09 [third:F3565387.txt] waiting 10s before call...
17:34:22 [third:F3565387.txt] call OK

Processing feedback documents from blob:  82%|████████▏ | 182/222 [1:59:25<26:24, 39.62s/doc, F3565388.txt]

17:34:22 [first:F3565388.txt] waiting 10s before call...
17:34:37 [first:F3565388.txt] call OK
17:34:37 [second:F3565388.txt] waiting 10s before call...
17:34:50 [second:F3565388.txt] call OK
17:34:50 [third:F3565388.txt] waiting 10s before call...
17:35:02 [third:F3565388.txt] call OK

Processing feedback documents from blob:  82%|████████▏ | 183/222 [2:00:05<25:52, 39.81s/doc, F3565390.txt]

17:35:02 [first:F3565390.txt] waiting 10s before call...
17:35:18 [first:F3565390.txt] call OK
17:35:18 [second:F3565390.txt] waiting 10s before call...
17:35:31 [second:F3565390.txt] call OK
17:35:31 [third:F3565390.txt] waiting 10s before call...
17:35:45 [third:F3565390.txt] call OK

Processing feedback documents from blob:  83%|████████▎ | 184/222 [2:00:47<25:42, 40.59s/doc, F3565395.txt]

17:35:45 [first:F3565395.txt] waiting 10s before call...
17:35:57 [first:F3565395.txt] call OK
17:35:57 [second:F3565395.txt] waiting 10s before call...
17:36:10 [second:F3565395.txt] call OK
17:36:10 [third:F3565395.txt] waiting 10s before call...
17:36:22 [third:F3565395.txt] call OK

Processing feedback documents from blob:  83%|████████▎ | 185/222 [2:01:25<24:26, 39.64s/doc, F3565399.txt]

17:36:22 [first:F3565399.txt] waiting 10s before call...
17:36:38 [first:F3565399.txt] call OK
17:36:38 [second:F3565399.txt] waiting 10s before call...
17:36:50 [second:F3565399.txt] call OK
17:36:50 [third:F3565399.txt] waiting 10s before call...
17:37:02 [third:F3565399.txt] call OK

Processing feedback documents from blob:  84%|████████▍ | 186/222 [2:02:05<23:52, 39.79s/doc, F3565405.txt]

17:37:02 [first:F3565405.txt] waiting 10s before call...
17:37:16 [first:F3565405.txt] call OK
17:37:16 [second:F3565405.txt] waiting 10s before call...
17:37:28 [second:F3565405.txt] call OK
17:37:28 [third:F3565405.txt] waiting 10s before call...
17:37:40 [third:F3565405.txt] call OK

Processing feedback documents from blob:  84%|████████▍ | 187/222 [2:02:43<22:57, 39.36s/doc, F3565407.txt]

17:37:40 [first:F3565407.txt] waiting 10s before call...
17:37:54 [first:F3565407.txt] call OK
17:37:54 [second:F3565407.txt] waiting 10s before call...
17:38:08 [second:F3565407.txt] call OK
17:38:08 [third:F3565407.txt] waiting 10s before call...
17:38:22 [third:F3565407.txt] call OK

Processing feedback documents from blob:  85%|████████▍ | 188/222 [2:03:25<22:41, 40.03s/doc, F3565413.txt]

17:38:22 [first:F3565413.txt] waiting 10s before call...
17:38:36 [first:F3565413.txt] call OK
17:38:36 [second:F3565413.txt] waiting 10s before call...
17:38:48 [second:F3565413.txt] call OK
17:38:48 [third:F3565413.txt] waiting 10s before call...
17:39:00 [third:F3565413.txt] call OK

Processing feedback documents from blob:  85%|████████▌ | 189/222 [2:04:03<21:37, 39.33s/doc, F3565417.txt]

17:39:00 [first:F3565417.txt] waiting 10s before call...
17:39:13 [first:F3565417.txt] call OK
17:39:13 [second:F3565417.txt] waiting 10s before call...
17:39:25 [second:F3565417.txt] call OK
17:39:25 [third:F3565417.txt] waiting 10s before call...
17:39:37 [third:F3565417.txt] call OK

Processing feedback documents from blob:  86%|████████▌ | 190/222 [2:04:40<20:43, 38.86s/doc, F3565418.txt]

[SAVED] checkpoint with 190 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_173937.json
17:39:37 [first:F3565418.txt] waiting 10s before call...
17:39:51 [first:F3565418.txt] call OK
17:39:51 [second:F3565418.txt] waiting 10s before call...
17:40:03 [second:F3565418.txt] call OK
17:40:03 [third:F3565418.txt] waiting 10s before call...
17:40:15 [third:F3565418.txt] call OK

Processing feedback documents from blob:  86%|████████▌ | 191/222 [2:05:18<19:52, 38.46s/doc, F3565420.txt]

17:40:15 [first:F3565420.txt] waiting 10s before call...
17:40:31 [first:F3565420.txt] call OK
17:40:31 [second:F3565420.txt] waiting 10s before call...
17:40:45 [second:F3565420.txt] call OK
17:40:45 [third:F3565420.txt] waiting 10s before call...
17:40:57 [third:F3565420.txt] call OK

Processing feedback documents from blob:  86%|████████▋ | 192/222 [2:06:00<19:48, 39.62s/doc, F3565421.txt]

17:40:57 [first:F3565421.txt] waiting 10s before call...
17:41:15 [first:F3565421.txt] call OK
17:41:15 [second:F3565421.txt] waiting 10s before call...
17:41:29 [second:F3565421.txt] call OK
17:41:29 [third:F3565421.txt] waiting 10s before call...
17:41:41 [third:F3565421.txt] call OK

Processing feedback documents from blob:  87%|████████▋ | 193/222 [2:06:44<19:45, 40.87s/doc, F3565422.txt]

17:41:41 [first:F3565422.txt] waiting 10s before call...
17:41:54 [first:F3565422.txt] call OK
17:41:54 [second:F3565422.txt] waiting 10s before call...
17:42:07 [second:F3565422.txt] call OK
17:42:07 [third:F3565422.txt] waiting 10s before call...
17:42:20 [third:F3565422.txt] call OK

Processing feedback documents from blob:  87%|████████▋ | 194/222 [2:07:23<18:45, 40.19s/doc, F3565426.txt]

17:42:20 [first:F3565426.txt] waiting 10s before call...
17:42:36 [first:F3565426.txt] call OK
17:42:36 [second:F3565426.txt] waiting 10s before call...
17:42:50 [second:F3565426.txt] call OK
17:42:50 [third:F3565426.txt] waiting 10s before call...
17:43:03 [third:F3565426.txt] call OK

Processing feedback documents from blob:  88%|████████▊ | 195/222 [2:08:06<18:28, 41.05s/doc, F3565431.txt]

17:43:03 [first:F3565431.txt] waiting 10s before call...
17:43:16 [first:F3565431.txt] call OK
17:43:16 [second:F3565431.txt] waiting 10s before call...
17:43:28 [second:F3565431.txt] call OK
17:43:28 [third:F3565431.txt] waiting 10s before call...
17:43:40 [third:F3565431.txt] call OK

Processing feedback documents from blob:  88%|████████▊ | 196/222 [2:08:43<17:16, 39.87s/doc, F3565435.txt]

17:43:40 [first:F3565435.txt] waiting 10s before call...
17:43:54 [first:F3565435.txt] call OK
17:43:54 [second:F3565435.txt] waiting 10s before call...
17:44:08 [second:F3565435.txt] call OK
17:44:08 [third:F3565435.txt] waiting 10s before call...
17:44:21 [third:F3565435.txt] call OK

Processing feedback documents from blob:  89%|████████▊ | 197/222 [2:09:24<16:48, 40.36s/doc, F3565438.txt]

17:44:21 [first:F3565438.txt] waiting 10s before call...
17:44:35 [first:F3565438.txt] call OK
17:44:35 [second:F3565438.txt] waiting 10s before call...
17:44:47 [second:F3565438.txt] call OK
17:44:47 [third:F3565438.txt] waiting 10s before call...
17:44:59 [third:F3565438.txt] call OK

Processing feedback documents from blob:  89%|████████▉ | 198/222 [2:10:02<15:46, 39.45s/doc, F3565441.txt]

17:44:59 [first:F3565441.txt] waiting 10s before call...
17:45:12 [first:F3565441.txt] call OK
17:45:12 [second:F3565441.txt] waiting 10s before call...
17:45:24 [second:F3565441.txt] call OK
17:45:24 [third:F3565441.txt] waiting 10s before call...
17:45:37 [third:F3565441.txt] call OK

Processing feedback documents from blob:  90%|████████▉ | 199/222 [2:10:40<15:01, 39.19s/doc, F3565442.txt]

17:45:37 [first:F3565442.txt] waiting 10s before call...
17:45:53 [first:F3565442.txt] call OK
17:45:53 [second:F3565442.txt] waiting 10s before call...
17:46:05 [second:F3565442.txt] call OK
17:46:05 [third:F3565442.txt] waiting 10s before call...
17:46:18 [third:F3565442.txt] call OK

Processing feedback documents from blob:  90%|█████████ | 200/222 [2:11:21<14:31, 39.60s/doc, F3565444.txt]

[SAVED] checkpoint with 200 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_174618.json
17:46:18 [first:F3565444.txt] waiting 10s before call...
17:46:31 [first:F3565444.txt] call OK
17:46:31 [second:F3565444.txt] waiting 10s before call...
17:46:44 [second:F3565444.txt] call OK
17:46:44 [third:F3565444.txt] waiting 10s before call...
17:46:56 [third:F3565444.txt] call OK

Processing feedback documents from blob:  91%|█████████ | 201/222 [2:11:59<13:42, 39.16s/doc, F3565446.txt]

17:46:56 [first:F3565446.txt] waiting 10s before call...
17:47:12 [first:F3565446.txt] call OK
17:47:12 [second:F3565446.txt] waiting 10s before call...
17:47:23 [second:F3565446.txt] call OK
17:47:23 [third:F3565446.txt] waiting 10s before call...
17:47:36 [third:F3565446.txt] call OK

Processing feedback documents from blob:  91%|█████████ | 202/222 [2:12:39<13:08, 39.42s/doc, F3565451.txt]

17:47:36 [first:F3565451.txt] waiting 10s before call...
17:47:50 [first:F3565451.txt] call OK
17:47:50 [second:F3565451.txt] waiting 10s before call...
17:48:03 [second:F3565451.txt] call OK
17:48:03 [third:F3565451.txt] waiting 10s before call...
17:48:16 [third:F3565451.txt] call OK

Processing feedback documents from blob:  91%|█████████▏| 203/222 [2:13:19<12:31, 39.57s/doc, F3565455.txt]

17:48:16 [first:F3565455.txt] waiting 10s before call...
17:48:29 [first:F3565455.txt] call OK
17:48:29 [second:F3565455.txt] waiting 10s before call...
17:48:41 [second:F3565455.txt] call OK
17:48:41 [third:F3565455.txt] waiting 10s before call...
17:48:53 [third:F3565455.txt] call OK

Processing feedback documents from blob:  92%|█████████▏| 204/222 [2:13:56<11:37, 38.78s/doc, F3565463.txt]

17:48:53 [first:F3565463.txt] waiting 10s before call...
17:49:06 [first:F3565463.txt] call OK
17:49:06 [second:F3565463.txt] waiting 10s before call...
17:49:18 [second:F3565463.txt] call OK
17:49:18 [third:F3565463.txt] waiting 10s before call...
17:49:30 [third:F3565463.txt] call OK

Processing feedback documents from blob:  92%|█████████▏| 205/222 [2:14:33<10:49, 38.23s/doc, F3565466.txt]

17:49:30 [first:F3565466.txt] waiting 10s before call...
17:49:43 [first:F3565466.txt] call OK
17:49:43 [second:F3565466.txt] waiting 10s before call...
17:49:55 [second:F3565466.txt] call OK
17:49:55 [third:F3565466.txt] waiting 10s before call...
17:50:07 [third:F3565466.txt] call OK

Processing feedback documents from blob:  93%|█████████▎| 206/222 [2:15:10<10:08, 38.03s/doc, F3565477.txt]

17:50:07 [first:F3565477.txt] waiting 10s before call...
17:50:20 [first:F3565477.txt] call OK
17:50:20 [second:F3565477.txt] waiting 10s before call...
17:50:32 [second:F3565477.txt] call OK
17:50:32 [third:F3565477.txt] waiting 10s before call...
17:50:46 [third:F3565477.txt] call OK

Processing feedback documents from blob:  93%|█████████▎| 207/222 [2:15:49<09:35, 38.35s/doc, F3565481.txt]

17:50:46 [first:F3565481.txt] waiting 10s before call...
17:51:03 [first:F3565481.txt] call OK
17:51:03 [second:F3565481.txt] waiting 10s before call...
17:51:16 [second:F3565481.txt] call OK
17:51:16 [third:F3565481.txt] waiting 10s before call...
17:51:29 [third:F3565481.txt] call OK

Processing feedback documents from blob:  94%|█████████▎| 208/222 [2:16:32<09:13, 39.56s/doc, F3565484.txt]

17:51:29 [first:F3565484.txt] waiting 10s before call...
17:51:44 [first:F3565484.txt] call OK
17:51:44 [second:F3565484.txt] waiting 10s before call...
17:51:58 [second:F3565484.txt] call OK
17:51:58 [third:F3565484.txt] waiting 10s before call...
17:52:10 [third:F3565484.txt] call OK

Processing feedback documents from blob:  94%|█████████▍| 209/222 [2:17:13<08:41, 40.10s/doc, F3565491.txt]

17:52:10 [first:F3565491.txt] waiting 10s before call...
17:52:27 [first:F3565491.txt] call OK
17:52:27 [second:F3565491.txt] waiting 10s before call...
17:52:41 [second:F3565491.txt] call OK
17:52:41 [third:F3565491.txt] waiting 10s before call...
17:52:55 [third:F3565491.txt] call OK

Processing feedback documents from blob:  95%|█████████▍| 210/222 [2:17:58<08:16, 41.39s/doc, F3565493.txt]

[SAVED] checkpoint with 210 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_175255.json
17:52:55 [first:F3565493.txt] waiting 10s before call...
17:53:07 [first:F3565493.txt] call OK
17:53:07 [second:F3565493.txt] waiting 10s before call...
17:53:20 [second:F3565493.txt] call OK
17:53:20 [third:F3565493.txt] waiting 10s before call...
17:53:33 [third:F3565493.txt] call OK

Processing feedback documents from blob:  95%|█████████▌| 211/222 [2:18:36<07:26, 40.56s/doc, F3565495.txt]

17:53:33 [first:F3565495.txt] waiting 10s before call...
17:53:45 [first:F3565495.txt] call OK
17:53:46 [second:F3565495.txt] waiting 10s before call...
17:53:58 [second:F3565495.txt] call OK
17:53:58 [third:F3565495.txt] waiting 10s before call...
17:54:10 [third:F3565495.txt] call OK

Processing feedback documents from blob:  95%|█████████▌| 212/222 [2:19:13<06:34, 39.42s/doc, F3565496.txt]

17:54:10 [first:F3565496.txt] waiting 10s before call...
17:54:23 [first:F3565496.txt] call OK
17:54:23 [second:F3565496.txt] waiting 10s before call...
17:54:35 [second:F3565496.txt] call OK
17:54:35 [third:F3565496.txt] waiting 10s before call...
17:54:47 [third:F3565496.txt] call OK

Processing feedback documents from blob:  96%|█████████▌| 213/222 [2:19:50<05:48, 38.74s/doc, F3565499.txt]

17:54:47 [first:F3565499.txt] waiting 10s before call...
17:55:02 [first:F3565499.txt] call OK
17:55:02 [second:F3565499.txt] waiting 10s before call...
17:55:14 [second:F3565499.txt] call OK
17:55:14 [third:F3565499.txt] waiting 10s before call...
17:55:31 [third:F3565499.txt] call OK

Processing feedback documents from blob:  96%|█████████▋| 214/222 [2:20:34<05:21, 40.23s/doc, F3565503.txt]

17:55:31 [first:F3565503.txt] waiting 10s before call...
17:55:46 [first:F3565503.txt] call OK
17:55:46 [second:F3565503.txt] waiting 10s before call...
17:55:58 [second:F3565503.txt] call OK
17:55:58 [third:F3565503.txt] waiting 10s before call...
17:56:10 [third:F3565503.txt] call OK

Processing feedback documents from blob:  97%|█████████▋| 215/222 [2:21:13<04:40, 40.03s/doc, F3565509.txt]

17:56:10 [first:F3565509.txt] waiting 10s before call...
17:56:24 [first:F3565509.txt] call OK
17:56:24 [second:F3565509.txt] waiting 10s before call...
17:56:37 [second:F3565509.txt] call OK
17:56:37 [third:F3565509.txt] waiting 10s before call...
17:56:49 [third:F3565509.txt] call OK

Processing feedback documents from blob:  97%|█████████▋| 216/222 [2:21:52<03:57, 39.52s/doc, F3565510.txt]

17:56:49 [first:F3565510.txt] waiting 10s before call...
17:57:03 [first:F3565510.txt] call OK
17:57:03 [second:F3565510.txt] waiting 10s before call...
17:57:15 [second:F3565510.txt] call OK
17:57:15 [third:F3565510.txt] waiting 10s before call...
17:57:27 [third:F3565510.txt] call OK

Processing feedback documents from blob:  98%|█████████▊| 217/222 [2:22:30<03:15, 39.12s/doc, F3565520.txt]

17:57:27 [first:F3565520.txt] waiting 10s before call...
17:57:42 [first:F3565520.txt] call OK
17:57:42 [second:F3565520.txt] waiting 10s before call...
17:57:54 [second:F3565520.txt] call OK
17:57:54 [third:F3565520.txt] waiting 10s before call...
17:58:06 [third:F3565520.txt] call OK

Processing feedback documents from blob:  98%|█████████▊| 218/222 [2:23:09<02:36, 39.23s/doc, F3565521.txt]

17:58:06 [first:F3565521.txt] waiting 10s before call...
17:58:19 [first:F3565521.txt] call OK
17:58:19 [second:F3565521.txt] waiting 10s before call...
17:58:31 [second:F3565521.txt] call OK
17:58:31 [third:F3565521.txt] waiting 10s before call...
17:58:43 [third:F3565521.txt] call OK

Processing feedback documents from blob:  99%|█████████▊| 219/222 [2:23:46<01:55, 38.39s/doc, F3565526.txt]

17:58:43 [first:F3565526.txt] waiting 10s before call...
17:58:57 [first:F3565526.txt] call OK
17:58:57 [second:F3565526.txt] waiting 10s before call...
17:59:11 [second:F3565526.txt] call OK
17:59:11 [third:F3565526.txt] waiting 10s before call...
17:59:24 [third:F3565526.txt] call OK

Processing feedback documents from blob:  99%|█████████▉| 220/222 [2:24:27<01:18, 39.16s/doc, F3565532.txt]

[SAVED] checkpoint with 220 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results_checkpoint_20251103_175924.json
17:59:24 [first:F3565532.txt] waiting 10s before call...
17:59:38 [first:F3565532.txt] call OK
17:59:38 [second:F3565532.txt] waiting 10s before call...
17:59:52 [second:F3565532.txt] call OK
17:59:52 [third:F3565532.txt] waiting 10s before call...
18:00:05 [third:F3565532.txt] call OK

Processing feedback documents from blob: 100%|█████████▉| 221/222 [2:25:08<00:39, 39.84s/doc, F3582124.txt]

18:00:05 [first:F3582124.txt] waiting 10s before call...
18:00:23 [first:F3582124.txt] call OK
18:00:23 [second:F3582124.txt] waiting 10s before call...
18:00:37 [second:F3582124.txt] call OK
18:00:37 [third:F3582124.txt] waiting 10s before call...
18:00:50 [third:F3582124.txt] call OK

Processing feedback documents from blob: 100%|██████████| 222/222 [2:25:53<00:00, 39.43s/doc, F3582124.txt]

[DONE] All results saved to C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_results.json

In [59]:
results

[{'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': ["Non si può trascurare che va ad interessare dei punti di criticità da un punto di vista etico e della sicurezza della salute dei cittadini e pertanto necessita di un'attenta valutazione. (page 1)"],
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3552803'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3553888'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3554271'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3559517'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': ['Il en est de même de l\'"IA" mal nommée. Elle n\'est pas une intelligence, mais juste un calcul. Elle servira surtout à justifier le dépôt de brevet sur des séquences génétiques sans avoir à demander le droit d\'utilisation aux population du Sud qui ont accepté de donner leur connaissance. (page 1)'],
  'AI_Development_and_Deployment': ['Il en est de même de l\'"IA" mal nommée. Elle n\'est pas une intelligence, mais juste un calcul. Elle servira surtout à justifier le dépôt de brevet sur des séquences génétiques sans avoir à demander le droit d\'utilisation aux population du Sud qui ont accepté de donner leur connaissance. (page 1)'],
  'Global_Collaboration': ['Ils donnent leurs connaissances et nos entreprises (avec le soutien de la COm) contribue à les piller pour augmenter la concentration capitalistique en Europe. (page 1)'],
  'Biosecurity': ['Enfin j\'apprends que "Le règlement sur la biotechnologie prévoira une série de mesures visant à créer un environnement permettant daccélérer la transition des produits biotechnologiques du laboratoire à lusine et au marché, tout en maintenant les normes de sécurité les plus élevées pour la protection de la population et de lenvironnement.". (page 1)'],
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3561326'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': ['The initiative responds to well-documented barriers: fragmented regulatory frameworks, slow time-to-market for new products, limited access to risk-tolerant capital, a shortage of skilled biotech professionals, and inadequate integration of AI and big data into biotech development. (page 1)',
   'These challenges disproportionately affect small and medium-sized enterprises (SMEs), spin-offs, and start-upsthe very drivers of innovation in this sector. (page 1)'],
  'Access_to_Markets_strategies': ['This paper identifies five strategic areas of intervention and proposes actionable recommendations to (1) accelerate regulatory alignment and market entry; (2) scale investment pathways; (3) build a cross-border biotech talent pipeline; (4) modernize Europes digital and AI infrastructure for life sciences; and (5) position the EU as a leader in secure, resilient biomanufacturing. (page 1)',
   'If enacted ambitiously, the European Biotech Act can serve as a cornerstone for global competitiveness, environmental resilience, and health innovation in the decades ahead. (page 1)'],
  'VC_Investments_IPO': ['The initiative responds to well-documented barriers: fragmented regulatory frameworks, slow time-to-market for new products, limited access to risk-tolerant capital, a shortage of skilled biotech professionals, and inadequate integration of AI and big data into biotech development. (page 1)',
   'This paper identifies five strategic areas of intervention and proposes actionable recommendations to (1) accelerate regulatory alignment and market entry; (2) scale investment pathways; (3) build a cross-border biotech talent pipeline; (4) modernize Europes digital and AI infrastructure for life sciences; and (5) position the EU as a leader in secure, resilient biomanufacturing. (page 1)'],
  'Manufacturing_Capabilities': ['This paper identifies five strategic areas of intervention and proposes actionable recommendations to (1) accelerate regulatory alignment and market entry; (2) scale investment pathways; (3) build a cross-border biotech talent pipeline; (4) modernize Europes digital and AI infrastructure for life sciences; and (5) position the EU as a leader in secure, resilient biomanufacturing. (page 1)'],
  'Incubation_and_Acceleration': ['These challenges disproportionately affect small and medium-sized enterprises (SMEs), spin-offs, and start-upsthe very drivers of innovation in this sector. (page 1)'],
  'Talent_Retention': ['Yet, despite Europes strength in foundational research, the region continues to underperform in commercializing innovation, scaling production, and securing global leadership in biotech. (page 1)',
   'The initiative responds to well-documented barriers: fragmented regulatory frameworks, slow time-to-market for new products, limited access to risk-tolerant capital, a shortage of skilled biotech professionals, and inadequate integration of AI and big data into biotech development. (page 1)',
   'build a cross-border biotech talent pipeline; (page 1)'],
  'Upskilling_Reskilling': ['The initiative responds to well-documented barriers: fragmented regulatory frameworks, slow time-to-market for new products, limited access to risk-tolerant capital, a shortage of skilled biotech professionals, and inadequate integration of AI and big data into biotech development. (page 1)',
   'modernize Europes digital and AI infrastructure for life sciences; (page 1)'],
  'AI_Challenges': ['The initiative responds to well-documented barriers: fragmented regulatory frameworks, slow time-to-market for new products, limited access to risk-tolerant capital, a shortage of skilled biotech professionals, and inadequate integration of AI and big data into biotech development. (page 1)'],
  'AI_Development_and_Deployment': ['This paper identifies five strategic areas of intervention and proposes actionable recommendations to (1) accelerate regulatory alignment and market entry; (2) scale investment pathways; (3) build a cross-border biotech talent pipeline; (4) modernize Europes digital and AI infrastructure for life sciences; and (5) position the EU as a leader in secure, resilient biomanufacturing. (page 1)'],
  'Global_Collaboration': None,
  'Biosecurity': ['This paper identifies five strategic areas of intervention and proposes actionable recommendations to (1) accelerate regulatory alignment and market entry; (2) scale investment pathways; (3) build a cross-border biotech talent pipeline; (4) modernize Europes digital and AI infrastructure for life sciences; and (5) position the EU as a leader in secure, resilient biomanufacturing. (page 1)'],
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3563493'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3563646'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': ['De biotech sector in de EU zou heel sterk kunnen zijn, maar de barrières zijn enorm. Risicokapitaal is er één van, maar de allerbelangrijkste zijn de regulatoire hordes. De regulators (of competente autoriteiten) gedragen zich als kampbewakers en niet als competente wetenschappers. Elke innovatie wordt geëvalueerd als een potentiële bedreiging, niet als een potentiële opportuniteit. Daarbij stelt de regulator niet tot doel om implementatie van biotechinnovaties te faciliteren, maar om het proces zo groot, zo lang en zo zwaar mogelijk te maken. Op die manier wordt enkel nog het proces relevant en niet meer het doel waardoor innovatiedoelen niet gehaald worden. Rationeel denken en het afwegen van risico ontbreekt dus. In onze eigen ervaring werd een innovatief product dat afgeleid is van een bestaande, veilige klinische interventie geherclassificeerd tot de zwaarst mogelijke categorie. Daarbij werd geen wetenschappelijke onderbouwing gegeven, maar eerder een vage algemene omschrijving van een oude wet. Dat is voor de regulator de makkelijkste positie, want niet verantwoordelijk voor zelfs maar het kleinste risico. De regulatoren zouden zich moeten inwerken in een dossier teneinde het risico voor de bevolking te kunnen inschatten. Dat doen ze niet. In de plaats daarvan wordt maximalistisch ingezet op hun eigen defensie zodat ze zelf zijn ingedekt. Dat is een attitude die innovators wegjaagt naar derde landen waar er feeling en motivatie is voor innovatie. Ook wij overwegen met onze innovaties naar derde landen te gaan waar de wetenschappelijk overweging nog gemaakt wordt en niet de defensieve. Als de EU dit opgelost krijgt (wat betwijfeld kan worden) dan bestaat de kans dat biotech innovaties nog in de EU worden gehouden. (page 1)'],
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': ['Risicokapitaal is er één van, maar de allerbelangrijkste zijn de regulatoire hordes. (page 1)'],
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': ['Dat is een attitude die innovators wegjaagt naar derde landen waar er feeling en motivatie is voor innovatie. Ook wij overwegen met onze innovaties naar derde landen te gaan waar de wetenschappelijk overweging nog gemaakt wordt en niet de defensieve. (page 1)'],
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': ['Dat is een attitude die innovators wegjaagt naar derde landen waar er feeling en motivatie is voor innovatie. Ook wij overwegen met onze innovaties naar derde landen te gaan waar de wetenschappelijk overweging nog gemaakt wordt en niet de defensieve. (page 1)'],
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3563652'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3563668'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3563901'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3563910'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': ['A strong data privacy culture and fragmented healthcare data infrastructure often slow data aggregation for AI training, particularly in healthcare. (page 1)',
   'A "personalist and humanist approach" to copyright creates complexities regarding ownership and protection of AI-generated content, impacting IP strategies. (page 1)',
   'A "lack of information and knowledge" among companies regarding AI implementation and compliance, especially in biomedicine, highlights the need for greater awareness, training, and clear guidance. (page 1)'],
  'Access_to_Markets_strategies': ['A harmonized, future-proof regulatory structure is critical: Legislative Form: A Regulation is preferred to ensure uniform implementation across Member States, preventing fragmentation. (page 1)',
   'Comprehensive Scope: Cover all biotech sectors (medical, agri-food) to maximize cross-sector synergies and address divergent national policies. (page 1)',
   'Integration with Existing Laws: Clarify overlaps between the Biotech Act, AI Act, Data Act, GDPR, and sector-specific rules (e.g., MDR, IVDR) to avoid duplication. (page 1)',
   'Adaptability: Incorporate technology-neutral principles and periodic reviews to accommodate rapid AI advancements. (page 1)',
   'Collaborative Governance: Strengthen coordination between agencies (EMA, EFSA) and the proposed HealthData@EU infrastructure for cross-border data access. (page 1)',
   'To enhance competitiveness, the Act must address systemic gaps: Risk Capital Access: Establish EU-funded venture mechanisms and tax incentives for biotech startups and scale-ups. (page 1)',
   'Biomanufacturing Infrastructure: Invest in AI-driven production facilities and high-performance computing resources (e.g., EuroHPC). (page 1)',
   'Skills Development: Launch EU-wide training programs for AI-biotech interdisciplinary roles, bridging academia and industry. (page 1)',
   'SME Support: Simplify administrative burdens and provide grants for SMEs navigating AI compliance. (page 1)',
   'Data Accessibility: Utilize EHDS and HealthData@EU to provide researchers with anonymized health datasets, fostering AI innovation in drug development. (page 1)'],
  'VC_Investments_IPO': ['To enhance competitiveness, the Act must address systemic gaps: Risk Capital Access: Establish EU-funded venture mechanisms and tax incentives for biotech startups and scale-ups. (page 1)'],
  'Manufacturing_Capabilities': ['Invest in AI-driven production facilities and high-performance computing resources (e.g., EuroHPC). (page 1)'],
  'Incubation_and_Acceleration': ['Establish EU-funded venture mechanisms and tax incentives for biotech startups and scale-ups. (page 1)',
   'Simplify administrative burdens and provide grants for SMEs navigating AI compliance. (page 1)'],
  'Talent_Retention': None,
  'Upskilling_Reskilling': ['Launch EU-wide training programs for AI-biotech interdisciplinary roles, bridging academia and industry. (page 1)'],
  'AI_Challenges': ['Bias mitigation, as per AI Act Article 10, necessitates dataset diversity assessments and corrective measures. (page 1)',
   'A strong data privacy culture and fragmented healthcare data infrastructure often slow data aggregation for AI training, particularly in healthcare. (page 1)',
   'A "personalist and humanist approach" to copyright creates complexities regarding ownership and protection of AI-generated content, impacting IP strategies. (page 1)',
   'A "lack of information and knowledge" among companies regarding AI implementation and compliance, especially in biomedicine, highlights the need for greater awareness, training, and clear guidance. (page 1)'],
  'AI_Development_and_Deployment': ['The Act must balance robust risk mitigation with innovation, especially in AI-driven medical/pharma and agronomy. (page 1)',
   'Invest in AI-driven production facilities and high-performance computing resources (e.g., EuroHPC). (page 1)',
   'Launch EU-wide training programs for AI-biotech interdisciplinary roles, bridging academia and industry. (page 1)',
   'Utilize EHDS and HealthData@EU to provide researchers with anonymized health datasets, fostering AI innovation in drug development. (page 1)'],
  'Global_Collaboration': ['Strengthen coordination between agencies (EMA, EFSA) and the proposed HealthData@EU infrastructure for cross-border data access. (page 1)'],
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3563929'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': ['However, to fully realize this potential, the upcoming Act must explicitly include biocontrol technologies and create an enabling policy and regulatory environment that accelerates their development and deployment while maintaining the highest safety standards for people and the environment. (page 1)',
   'Furthermore, proactive support and work towards a change in paradigm is needed by all sides hence the new act needs to lay the ground for that. (page 1)'],
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,

In [53]:
fb

,Reference publication,Feedback reference,Ares reference,Date feedback,User type,Tr _ number,Organization,Sector - from EC,Scope,Governance level,...,title,organisation,page_number,summary,main themes,VC,clusters,skills,AI/data,dual_use/security
0,Ares(2025)3876590,F3552803,Ares(2025)4046089,2025/05/18 22:52:52,NGO (Non-governmental organisation),NaN,RareGen Youth Network,General,NaN,NaN,...,Feedback on the European Biotech Act,RareGen Youth Network,12.0,This document provides feedback on the Europea...,"['Regulatory fragmentation and bottlenecks', '...",The document highlights persistent gaps in ris...,The document discusses the importance of biote...,A shortage of skilled biotech professionals is...,The document stresses the growing importance o...,The document raises concerns about dual-use ri...
1,Ares(2025)3876590,F3553888,Ares(2025)4046970,2025/05/20 11:30:18,NGO (Non-governmental organisation),9276943405-41,Standing Committee of European Doctors (CPME),Medical/pharma,NaN,NaN,...,Statement on the European Commission call for ...,Standing Committee of European Doctors (CPME),1.0,The document is a statement from the Standing ...,"['Biotech Act consultation', 'Transparency in ...",The document urges the European Commission to ...,NaN,NaN,NaN,NaN
2,Ares(2025)3876590,F3554271,Ares(2025)4099470,2025/05/21 09:59:36,Company/business,852199818450-61,Koppert B.V.,Agri,NaN,NaN,...,Koppert’s Contribution to the EU Biotech Act C...,Koppert B.V.,2.0,Koppert's submission to the EU Biotech Act con...,"['Biocontrol inclusion in EU Biotech Act', 'Re...",The document highlights the need for the EU to...,It advocates for the creation of EU innovation...,NaN,The document proposes supporting public–privat...,NaN
3,Ares(2025)3876590,F3559517,Ares(2025)4262845,2025/05/27 10:28:48,Other,194518991651-02,EBSA ivzw,Biosecurity,NaN,NaN,...,Maturing Biological Risk Management for EU com...,EBSA ivzw,12.0,This position paper by the European Biosafety ...,"['Regulatory simplification in life sciences',...",NaN,NaN,NaN,NaN,The document highlights the need for a unified...
4,Ares(2025)3876590,F3561326,Ares(2025)4354009,2025/05/28 16:07:11,NGO (Non-governmental organisation),174779050296-36,PhageEU,Medical/pharma,NaN,NaN,...,PhageEU proposals for amendments to Pharmaceut...,PhageEU,7.0,This document proposes amendments to the EU Ph...,['Integration of phage therapies into EU pharm...,The document highlights that explicit inclusio...,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Ares(2025)3876590,F3565258,Ares(2025)4656034,2025/06/11 14:59:28,Public authority,NaN,Danish National Center for Ethics,General,International,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218,Ares(2025)3876590,F3564863,Ares(2025)4633359,2025/06/10 18:46:47,Public authority,560693115075-38,AGES,Medical/pharma,National,Agency,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,Ares(2025)3876590,F3565357,Ares(2025)4660574,2025/06/11 17:19:09,Public authority,NaN,Secrétariat général des Affaires européennes,"Industrial, food and feed, medical/pharma",National,Authority,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
220,Ares(2025)3876590,F3564832,Ares(2025)4629830,2025/06/10 16:56:32,Public authority,NaN,National Institute for Public Health and the E...,NaN,National,Agency,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
221,Ares(2025)3876590,F3565442,Ares(2025)4666326,2025/06/11 19:45:30,Trade Union,25571625843-29,ASSOCIATION GENERALE DE L'INDUSTRIE DU MEDICAM...,Medical/pharma,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
len(results)

222

In [55]:
fb.columns

Index(['Reference publication', 'Feedback reference', 'Ares reference',
       'Date feedback', 'User type', 'Tr _ number', 'Organization',
       'Sector - from EC', 'Scope', 'Governance level', 'Company size',
       'Country', 'First name', 'Surname', 'Email', 'Publication status',
       'Feedback language', 'Feedback   in   original   language',
       'Feedback   english   translation', 'Attachment', 'Status', 'Reviewed',
       'Login', 'First report date', 'Has to be reviewed',
       'papers to publish anonymised', 'file_name', 'Doc title _raw',
       'to anonymize', 'Stakeholder group', 'Country.1', 'title',
       'organisation', 'page_number', 'summary', 'main themes', 'VC',
       'clusters', 'skills', 'AI/data', 'dual_use/security'],
      dtype='object')

In [77]:
sorted_refs = fb["Feedback reference"].sort_values().tolist()

# Step 2: Assign these sorted references to your results
for i, r in enumerate(results):
    if i < len(sorted_refs):
        r["reference"] = sorted_refs[i]

In [78]:
results[:5]

[{'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': ["Non si può trascurare che va ad interessare dei punti di criticità da un punto di vista etico e della sicurezza della salute dei cittadini e pertanto necessita di un'attenta valutazione. (page 1)"],
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3551675'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3551693'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3551766'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3551820'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': ['Il en est de même de l\'"IA" mal nommée. Elle n\'est pas une intelligence, mais juste un calcul. Elle servira surtout à justifier le dépôt de brevet sur des séquences génétiques sans avoir à demander le droit d\'utilisation aux population du Sud qui ont accepté de donner leur connaissance. (page 1)'],
  'AI_Development_and_Deployment': ['Il en est de même de l\'"IA" mal nommée. Elle n\'est pas une intelligence, mais juste un calcul. Elle servira surtout à justifier le dépôt de brevet sur des séquences génétiques sans avoir à demander le droit d\'utilisation aux population du Sud qui ont accepté de donner leur connaissance. (page 1)'],
  'Global_Collaboration': ['Ils donnent leurs connaissances et nos entreprises (avec le soutien de la COm) contribue à les piller pour augmenter la concentration capitalistique en Europe. (page 1)'],
  'Biosecurity': ['Enfin j\'apprends que "Le règlement sur la biotechnologie prévoira une série de mesures visant à créer un environnement permettant daccélérer la transition des produits biotechnologiques du laboratoire à lusine et au marché, tout en maintenant les normes de sécurité les plus élevées pour la protection de la population et de lenvironnement.". (page 1)'],
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3551923'}]

In [79]:
# Let's assume 'results' is your updated list of dictionaries
with open('brussels_fb_results.json', 'w', encoding='utf-8') as f:
    json.dump(results, f, ensure_ascii=False, indent=2)

### Replace pages with feedback

In [83]:
import re

def replace_page_with_feedback(lst):
    if isinstance(lst, list):
        return [
            re.sub(r"\(page\s*\d+\)", "(feedback)", s) if isinstance(s, str) else s
            for s in lst
        ]
    return lst

for d in results:
    for k, v in d.items():
        if isinstance(v, list):
            d[k] = replace_page_with_feedback(v)

In [84]:
results[:5]

[{'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': ["Non si può trascurare che va ad interessare dei punti di criticità da un punto di vista etico e della sicurezza della salute dei cittadini e pertanto necessita di un'attenta valutazione. (feedback)"],
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3551675'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3551693'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3551766'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3551820'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': ['Il en est de même de l\'"IA" mal nommée. Elle n\'est pas une intelligence, mais juste un calcul. Elle servira surtout à justifier le dépôt de brevet sur des séquences génétiques sans avoir à demander le droit d\'utilisation aux population du Sud qui ont accepté de donner leur connaissance. (feedback)'],
  'AI_Development_and_Deployment': ['Il en est de même de l\'"IA" mal nommée. Elle n\'est pas une intelligence, mais juste un calcul. Elle servira surtout à justifier le dépôt de brevet sur des séquences génétiques sans avoir à demander le droit d\'utilisation aux population du Sud qui ont accepté de donner leur connaissance. (feedback)'],
  'Global_Collaboration': ['Ils donnent leurs connaissances et nos entreprises (avec le soutien de la COm) contribue à les piller pour augmenter la concentration capitalistique en Europe. (feedback)'],
  'Biosecurity': ['Enfin j\'apprends que "Le règlement sur la biotechnologie prévoira une série de mesures visant à créer un environnement permettant daccélérer la transition des produits biotechnologiques du laboratoire à lusine et au marché, tout en maintenant les normes de sécurité les plus élevées pour la protection de la population et de lenvironnement.". (feedback)'],
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3551923'}]

In [85]:
# Let's assume 'results' is your updated list of dictionaries
with open(Path(output_folder) /'brussels_feedback_replaced_results.json', 'w', encoding='utf-8') as f:
    json.dump(results, f, ensure_ascii=False, indent=2)

## MERGE PP AND FB

In [94]:
import json
from pathlib import Path



with (output_folder / 'brussels_final_results_with_ref_title.json').open(encoding='utf-8') as f:
    pp = json.load(f)

with (output_folder / 'brussels_feedback_replaced_results.json').open(encoding='utf-8') as f:
    fb = json.load(f)

# Build a lookup for pp by reference
pp_refs = {d['reference']: d for d in pp if 'reference' in d}

for fb_dict in fb:
    ref = fb_dict.get('reference')
    if ref in pp_refs:
        pp_dict = pp_refs[ref]
        for k, v in fb_dict.items():
            if k == "reference":
                continue
            # Merge lists, else set/overwrite
            if v is not None:
                if k in pp_dict and isinstance(pp_dict[k], list) and isinstance(v, list):
                    pp_dict[k].extend(v)
                else:
                    pp_dict[k] = v
    else:
        pp.append(fb_dict)

# Save merged result
with (output_folder / 'brussels_merged_results.json').open('w', encoding='utf-8') as f:
    json.dump(pp, f, ensure_ascii=False, indent=2)

In [97]:
import pandas as pd

# Convert list of dicts to DataFrame
df = pd.DataFrame(pp)

# Make sure both 'reference' and 'title' are present
columns = df.columns.tolist()
first_cols = [col for col in ['reference', 'title'] if col in columns]
other_cols = [col for col in columns if col not in first_cols]
ordered_cols = first_cols + other_cols

# Reorder
df = df[ordered_cols]


# Save to Excel
df.to_excel(Path(output_folder) / 'brussels_final_merged_results.xlsx', index=False)

## NON ENG FEEDBACK TRANSLATE

In [17]:
# Load the Excel sheet, skip first 3 rows, treat the 4th as header
fb = pd.read_excel(
    os.path.join(folder_path, "Working file-biotech act call for evidence telethon_VP Check.xlsx"),
    sheet_name="Sector analysis",
    skiprows=3
)
fb.head()

,Reference publication,Feedback reference,Ares reference,Date feedback,User type,Tr _ number,Organization,Sector - from EC,Scope,Governance level,...,title,organisation,page_number,summary,main themes,VC,clusters,skills,AI/data,dual_use/security
0,Ares(2025)3876590,F3551675,Ares(2025)3913571,2025/05/15 10:17:58,Business Association,NaN,COMPAG,Medical/pharma,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ares(2025)3876590,F3551693,Ares(2025)3918507,2025/05/15 13:44:22,EU Citizen,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ares(2025)3876590,F3551766,Ares(2025)3957144,2025/05/16 12:02:14,EU Citizen,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ares(2025)3876590,F3551820,Ares(2025)3978576,2025/05/17 04:02:15,EU Citizen,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ares(2025)3876590,F3551923,Ares(2025)3990974,2025/05/18 16:26:28,NGO (Non-governmental organisation),629482044225-60,OGM dangers,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
fb.columns

Index(['Reference publication', 'Feedback reference', 'Ares reference',
       'Date feedback', 'User type', 'Tr _ number', 'Organization',
       'Sector - from EC', 'Scope', 'Governance level', 'Company size',
       'Country', 'First name', 'Surname', 'Email', 'Publication status',
       'Feedback language', 'Feedback   in   original   language',
       'Feedback   english   translation', 'Attachment', 'Status', 'Reviewed',
       'Login', 'First report date', 'Has to be reviewed',
       'papers to publish anonymised', 'file_name', 'Doc title _raw',
       'to anonymize', 'Stakeholder group', 'Country.1', 'title',
       'organisation', 'page_number', 'summary', 'main themes', 'VC',
       'clusters', 'skills', 'AI/data', 'dual_use/security'],
      dtype='object')

In [19]:
# --- Filter rows with a value in "Feedback   english   translation" ---
mask = fb["Feedback   english   translation"].notnull() & (fb["Feedback   english   translation"].astype(str).str.strip() != "")
filtered_fb = fb[mask]


# Print the number of rows with a translation
print(len(filtered_fb))

34

In [20]:
from azure.storage.blob import BlobServiceClient
import os

# --- Connect to Azure Blob Storage ---
blob_service = BlobServiceClient.from_connection_string(os.environ["AZURE_BLOB_CONNECTION_STRING"])
container_client = blob_service.get_container_client("sante-docs")


# --- Upload each translation as a separate text file ---
for _, row in filtered_fb.iterrows():
    reference = str(row["Feedback reference"]).strip()
    text = str(row["Feedback   english   translation"]).strip()

    # Construct blob name
    blob_name = f"{reference}_en.txt"

    # Upload
    blob_client = container_client.get_blob_client(blob_name)
    blob_client.upload_blob(text.encode("utf-8"), overwrite=True)

    print(f"✅ Uploaded: {blob_name}")

✅ Uploaded: F3551675_en.txt
✅ Uploaded: F3551693_en.txt
✅ Uploaded: F3551766_en.txt
✅ Uploaded: F3551820_en.txt
✅ Uploaded: F3551923_en.txt
✅ Uploaded: F3553253_en.txt
✅ Uploaded: F3553267_en.txt
✅ Uploaded: F3553780_en.txt
✅ Uploaded: F3562778_en.txt
✅ Uploaded: F3563249_en.txt
✅ Uploaded: F3563345_en.txt
✅ Uploaded: F3563368_en.txt
✅ Uploaded: F3563451_en.txt
✅ Uploaded: F3563646_en.txt
✅ Uploaded: F3564253_en.txt
✅ Uploaded: F3564264_en.txt
✅ Uploaded: F3564435_en.txt
✅ Uploaded: F3564641_en.txt
✅ Uploaded: F3564816_en.txt
✅ Uploaded: F3564900_en.txt
✅ Uploaded: F3564967_en.txt
✅ Uploaded: F3565034_en.txt
✅ Uploaded: F3565059_en.txt
✅ Uploaded: F3565157_en.txt
✅ Uploaded: F3565164_en.txt
✅ Uploaded: F3565196_en.txt
✅ Uploaded: F3565357_en.txt
✅ Uploaded: F3565369_en.txt
✅ Uploaded: F3565421_en.txt
✅ Uploaded: F3565446_en.txt
✅ Uploaded: F3565491_en.txt
✅ Uploaded: F3565493_en.txt
✅ Uploaded: F3565495_en.txt
✅ Uploaded: F3565520_en.txt

In [21]:
container_name="sante-docs"
colect = UserDocumentCollection(container_name)

colect.reset_and_run_indexer()

2025-11-04 11:13:13.432 | INFO     | embeddings:get_container:66 - Container 'sante-docs' already exists.
2025-11-04 11:13:24.996 | INFO     | embeddings:reset_and_run_indexer:252 - 🧹 Indexer 'sante-docs-indexer' checkpoint reset successfully.
2025-11-04 11:13:25.237 | INFO     | embeddings:reset_and_run_indexer:256 - 🚀 Indexer 'sante-docs-indexer' started successfully.

In [24]:
from tqdm.auto import tqdm
import os, json, time

# --- Parameters ---
SAVE_EVERY = 10
OUTPUT_PATH = Path(output_folder)/"feedback_translation_results.json"

# --- Get only uploaded .txt feedback files ---
docs = sorted([blob.name for blob in container_client.list_blobs() if blob.name.endswith(".txt")])

results, errors = [], []
pbar = tqdm(docs, desc="Processing feedback documents from blob", unit="doc", total=len(docs))

def save_checkpoint():
    """Save current progress to disk."""
    try:
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        temp_file = f"{os.path.splitext(OUTPUT_PATH)[0]}_checkpoint_{timestamp}.json"
        with open(temp_file, "w", encoding="utf-8") as f:
            json.dump({"results": results, "errors": errors}, f, ensure_ascii=False, indent=2)
        pbar.write(f"[SAVED] checkpoint with {len(results)} results → {temp_file}")
    except Exception as e:
        pbar.write(f"[WARNING] Failed to save checkpoint: {e}")

for i, doc in enumerate(pbar, start=1):
    pbar.set_postfix_str(doc)
    try:
        first  = call_once_with_wait(first_information,  doc, delay=10, label=f"first:{doc}")
        second = call_once_with_wait(second_information, doc, delay=10, label=f"second:{doc}")
        third  = call_once_with_wait(third_information,  doc, delay=10, label=f"third:{doc}")
        results.append({**first, **second, **third})
    except Exception as e:
        errors.append((doc, repr(e)))
        pbar.write(f"[ERROR] {doc}: {e}")

    # periodic checkpoint
    if i % SAVE_EVERY == 0:
        save_checkpoint()

# --- Final save ---
with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    json.dump({"results": results, "errors": errors}, f, ensure_ascii=False, indent=2)
pbar.write(f"[DONE] All results saved to {OUTPUT_PATH}")

Processing feedback documents from blob:   0%|          | 0/34 [00:00<?, ?doc/s, F3551675_en.txt]

11:14:51 [first:F3551675_en.txt] waiting 10s before call...
11:15:06 [first:F3551675_en.txt] call OK
11:15:06 [second:F3551675_en.txt] waiting 10s before call...
11:15:20 [second:F3551675_en.txt] call OK
11:15:20 [third:F3551675_en.txt] waiting 10s before call...
11:15:32 [third:F3551675_en.txt] call OK

Processing feedback documents from blob:   3%|▎         | 1/34 [00:41<22:47, 41.45s/doc, F3551693_en.txt]

11:15:32 [first:F3551693_en.txt] waiting 10s before call...
11:15:46 [first:F3551693_en.txt] call OK
11:15:46 [second:F3551693_en.txt] waiting 10s before call...
11:15:59 [second:F3551693_en.txt] call OK
11:15:59 [third:F3551693_en.txt] waiting 10s before call...
11:16:11 [third:F3551693_en.txt] call OK

Processing feedback documents from blob:   6%|▌         | 2/34 [01:20<21:22, 40.07s/doc, F3551766_en.txt]

11:16:11 [first:F3551766_en.txt] waiting 10s before call...
11:16:25 [first:F3551766_en.txt] call OK
11:16:25 [second:F3551766_en.txt] waiting 10s before call...
11:16:38 [second:F3551766_en.txt] call OK
11:16:38 [third:F3551766_en.txt] waiting 10s before call...
11:16:50 [third:F3551766_en.txt] call OK

Processing feedback documents from blob:   9%|▉         | 3/34 [01:59<20:25, 39.53s/doc, F3551820_en.txt]

11:16:50 [first:F3551820_en.txt] waiting 10s before call...
11:17:03 [first:F3551820_en.txt] call OK
11:17:03 [second:F3551820_en.txt] waiting 10s before call...
11:17:15 [second:F3551820_en.txt] call OK
11:17:15 [third:F3551820_en.txt] waiting 10s before call...
11:17:28 [third:F3551820_en.txt] call OK

Processing feedback documents from blob:  12%|█▏        | 4/34 [02:37<19:25, 38.85s/doc, F3551923_en.txt]

11:17:28 [first:F3551923_en.txt] waiting 10s before call...
11:17:42 [first:F3551923_en.txt] call OK
11:17:42 [second:F3551923_en.txt] waiting 10s before call...
11:17:55 [second:F3551923_en.txt] call OK
11:17:55 [third:F3551923_en.txt] waiting 10s before call...
11:18:09 [third:F3551923_en.txt] call OK

Processing feedback documents from blob:  15%|█▍        | 5/34 [03:18<19:09, 39.63s/doc, F3553253_en.txt]

11:18:09 [first:F3553253_en.txt] waiting 10s before call...
11:18:24 [first:F3553253_en.txt] call OK
11:18:24 [second:F3553253_en.txt] waiting 10s before call...
11:18:37 [second:F3553253_en.txt] call OK
11:18:37 [third:F3553253_en.txt] waiting 10s before call...
11:18:50 [third:F3553253_en.txt] call OK

Processing feedback documents from blob:  18%|█▊        | 6/34 [03:59<18:41, 40.06s/doc, F3553267_en.txt]

11:18:50 [first:F3553267_en.txt] waiting 10s before call...
11:19:03 [first:F3553267_en.txt] call OK
11:19:03 [second:F3553267_en.txt] waiting 10s before call...
11:19:16 [second:F3553267_en.txt] call OK
11:19:16 [third:F3553267_en.txt] waiting 10s before call...
11:19:29 [third:F3553267_en.txt] call OK

Processing feedback documents from blob:  21%|██        | 7/34 [04:38<17:50, 39.66s/doc, F3553780_en.txt]

11:19:29 [first:F3553780_en.txt] waiting 10s before call...
11:19:43 [first:F3553780_en.txt] call OK
11:19:43 [second:F3553780_en.txt] waiting 10s before call...
11:19:55 [second:F3553780_en.txt] call OK
11:19:55 [third:F3553780_en.txt] waiting 10s before call...
11:20:08 [third:F3553780_en.txt] call OK

Processing feedback documents from blob:  24%|██▎       | 8/34 [05:16<17:03, 39.36s/doc, F3562778_en.txt]

11:20:08 [first:F3562778_en.txt] waiting 10s before call...
11:20:22 [first:F3562778_en.txt] call OK
11:20:22 [second:F3562778_en.txt] waiting 10s before call...
11:20:34 [second:F3562778_en.txt] call OK
11:20:34 [third:F3562778_en.txt] waiting 10s before call...
11:20:46 [third:F3562778_en.txt] call OK

Processing feedback documents from blob:  26%|██▋       | 9/34 [05:55<16:19, 39.19s/doc, F3563249_en.txt]

11:20:46 [first:F3563249_en.txt] waiting 10s before call...
11:21:04 [first:F3563249_en.txt] call OK
11:21:04 [second:F3563249_en.txt] waiting 10s before call...
11:21:17 [second:F3563249_en.txt] call OK
11:21:17 [third:F3563249_en.txt] waiting 10s before call...
11:21:30 [third:F3563249_en.txt] call OK

Processing feedback documents from blob:  29%|██▉       | 10/34 [06:39<16:14, 40.60s/doc, F3563345_en.txt]

[SAVED] checkpoint with 10 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_translation_results_checkpoint_20251104_112130.json
11:21:30 [first:F3563345_en.txt] waiting 10s before call...
11:21:43 [first:F3563345_en.txt] call OK
11:21:43 [second:F3563345_en.txt] waiting 10s before call...
11:21:56 [second:F3563345_en.txt] call OK
11:21:56 [third:F3563345_en.txt] waiting 10s before call...
11:22:08 [third:F3563345_en.txt] call OK

Processing feedback documents from blob:  32%|███▏      | 11/34 [07:17<15:14, 39.78s/doc, F3563368_en.txt]

11:22:08 [first:F3563368_en.txt] waiting 10s before call...
11:22:21 [first:F3563368_en.txt] call OK
11:22:21 [second:F3563368_en.txt] waiting 10s before call...
11:22:33 [second:F3563368_en.txt] call OK
11:22:33 [third:F3563368_en.txt] waiting 10s before call...
11:22:46 [third:F3563368_en.txt] call OK

Processing feedback documents from blob:  35%|███▌      | 12/34 [07:54<14:21, 39.15s/doc, F3563451_en.txt]

11:22:46 [first:F3563451_en.txt] waiting 10s before call...
11:23:01 [first:F3563451_en.txt] call OK
11:23:01 [second:F3563451_en.txt] waiting 10s before call...
11:23:15 [second:F3563451_en.txt] call OK
11:23:15 [third:F3563451_en.txt] waiting 10s before call...
11:23:27 [third:F3563451_en.txt] call OK

Processing feedback documents from blob:  38%|███▊      | 13/34 [08:35<13:54, 39.74s/doc, F3563646_en.txt]

11:23:27 [first:F3563646_en.txt] waiting 10s before call...
11:23:40 [first:F3563646_en.txt] call OK
11:23:40 [second:F3563646_en.txt] waiting 10s before call...
11:23:52 [second:F3563646_en.txt] call OK
11:23:52 [third:F3563646_en.txt] waiting 10s before call...
11:24:05 [third:F3563646_en.txt] call OK

Processing feedback documents from blob:  41%|████      | 14/34 [09:13<13:02, 39.13s/doc, F3564253_en.txt]

11:24:05 [first:F3564253_en.txt] waiting 10s before call...
11:24:17 [first:F3564253_en.txt] call OK
11:24:17 [second:F3564253_en.txt] waiting 10s before call...
11:24:30 [second:F3564253_en.txt] call OK
11:24:30 [third:F3564253_en.txt] waiting 10s before call...
11:24:43 [third:F3564253_en.txt] call OK

Processing feedback documents from blob:  44%|████▍     | 15/34 [09:52<12:18, 38.88s/doc, F3564264_en.txt]

11:24:43 [first:F3564264_en.txt] waiting 10s before call...
11:24:59 [first:F3564264_en.txt] call OK
11:24:59 [second:F3564264_en.txt] waiting 10s before call...
11:25:12 [second:F3564264_en.txt] call OK
11:25:12 [third:F3564264_en.txt] waiting 10s before call...
11:25:25 [third:F3564264_en.txt] call OK

Processing feedback documents from blob:  47%|████▋     | 16/34 [10:33<11:55, 39.75s/doc, F3564435_en.txt]

11:25:25 [first:F3564435_en.txt] waiting 10s before call...
11:25:37 [first:F3564435_en.txt] call OK
11:25:37 [second:F3564435_en.txt] waiting 10s before call...
11:25:49 [second:F3564435_en.txt] call OK
11:25:49 [third:F3564435_en.txt] waiting 10s before call...
11:26:12 [third:F3564435_en.txt] call OK

Processing feedback documents from blob:  50%|█████     | 17/34 [11:21<11:56, 42.16s/doc, F3564641_en.txt]

11:26:12 [first:F3564641_en.txt] waiting 10s before call...
11:26:27 [first:F3564641_en.txt] call OK
11:26:27 [second:F3564641_en.txt] waiting 10s before call...
11:26:40 [second:F3564641_en.txt] call OK
11:26:40 [third:F3564641_en.txt] waiting 10s before call...
11:26:53 [third:F3564641_en.txt] call OK

Processing feedback documents from blob:  53%|█████▎    | 18/34 [12:02<11:07, 41.74s/doc, F3564816_en.txt]

11:26:53 [first:F3564816_en.txt] waiting 10s before call...
11:27:07 [first:F3564816_en.txt] call OK
11:27:07 [second:F3564816_en.txt] waiting 10s before call...
11:27:19 [second:F3564816_en.txt] call OK
11:27:19 [third:F3564816_en.txt] waiting 10s before call...
11:27:31 [third:F3564816_en.txt] call OK

Processing feedback documents from blob:  56%|█████▌    | 19/34 [12:40<10:09, 40.63s/doc, F3564900_en.txt]

11:27:31 [first:F3564900_en.txt] waiting 10s before call...
11:27:44 [first:F3564900_en.txt] call OK
11:27:44 [second:F3564900_en.txt] waiting 10s before call...
11:27:57 [second:F3564900_en.txt] call OK
11:27:57 [third:F3564900_en.txt] waiting 10s before call...
11:28:09 [third:F3564900_en.txt] call OK

Processing feedback documents from blob:  59%|█████▉    | 20/34 [13:18<09:16, 39.77s/doc, F3564967_en.txt]

[SAVED] checkpoint with 20 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_translation_results_checkpoint_20251104_112809.json
11:28:09 [first:F3564967_en.txt] waiting 10s before call...
11:28:22 [first:F3564967_en.txt] call OK
11:28:22 [second:F3564967_en.txt] waiting 10s before call...
11:28:35 [second:F3564967_en.txt] call OK
11:28:35 [third:F3564967_en.txt] waiting 10s before call...
11:28:48 [third:F3564967_en.txt] call OK

Processing feedback documents from blob:  62%|██████▏   | 21/34 [13:57<08:34, 39.57s/doc, F3565034_en.txt]

11:28:48 [first:F3565034_en.txt] waiting 10s before call...
11:29:01 [first:F3565034_en.txt] call OK
11:29:01 [second:F3565034_en.txt] waiting 10s before call...
11:29:13 [second:F3565034_en.txt] call OK
11:29:13 [third:F3565034_en.txt] waiting 10s before call...
11:29:26 [third:F3565034_en.txt] call OK

Processing feedback documents from blob:  65%|██████▍   | 22/34 [14:35<07:48, 39.06s/doc, F3565059_en.txt]

11:29:26 [first:F3565059_en.txt] waiting 10s before call...
11:29:42 [first:F3565059_en.txt] call OK
11:29:43 [second:F3565059_en.txt] waiting 10s before call...
11:29:55 [second:F3565059_en.txt] call OK
11:29:55 [third:F3565059_en.txt] waiting 10s before call...
11:30:09 [third:F3565059_en.txt] call OK

Processing feedback documents from blob:  68%|██████▊   | 23/34 [15:17<07:21, 40.17s/doc, F3565157_en.txt]

11:30:09 [first:F3565157_en.txt] waiting 10s before call...
11:30:26 [first:F3565157_en.txt] call OK
11:30:26 [second:F3565157_en.txt] waiting 10s before call...
11:30:39 [second:F3565157_en.txt] call OK
11:30:39 [third:F3565157_en.txt] waiting 10s before call...
11:30:52 [third:F3565157_en.txt] call OK

Processing feedback documents from blob:  71%|███████   | 24/34 [16:01<06:50, 41.08s/doc, F3565164_en.txt]

11:30:52 [first:F3565164_en.txt] waiting 10s before call...
11:31:08 [first:F3565164_en.txt] call OK
11:31:08 [second:F3565164_en.txt] waiting 10s before call...
11:31:20 [second:F3565164_en.txt] call OK
11:31:20 [third:F3565164_en.txt] waiting 10s before call...
11:31:32 [third:F3565164_en.txt] call OK

Processing feedback documents from blob:  74%|███████▎  | 25/34 [16:41<06:07, 40.87s/doc, F3565196_en.txt]

11:31:32 [first:F3565196_en.txt] waiting 10s before call...
11:31:51 [first:F3565196_en.txt] call OK
11:31:51 [second:F3565196_en.txt] waiting 10s before call...
11:32:05 [second:F3565196_en.txt] call OK
11:32:05 [third:F3565196_en.txt] waiting 10s before call...
11:32:17 [third:F3565196_en.txt] call OK

Processing feedback documents from blob:  76%|███████▋  | 26/34 [17:26<05:35, 41.98s/doc, F3565357_en.txt]

11:32:17 [first:F3565357_en.txt] waiting 10s before call...
11:32:33 [first:F3565357_en.txt] call OK
11:32:33 [second:F3565357_en.txt] waiting 10s before call...
11:32:45 [second:F3565357_en.txt] call OK
11:32:45 [third:F3565357_en.txt] waiting 10s before call...
11:32:59 [third:F3565357_en.txt] call OK

Processing feedback documents from blob:  79%|███████▉  | 27/34 [18:07<04:53, 41.91s/doc, F3565369_en.txt]

11:32:59 [first:F3565369_en.txt] waiting 10s before call...
11:33:14 [first:F3565369_en.txt] call OK
11:33:14 [second:F3565369_en.txt] waiting 10s before call...
11:33:28 [second:F3565369_en.txt] call OK
11:33:28 [third:F3565369_en.txt] waiting 10s before call...
11:33:40 [third:F3565369_en.txt] call OK

Processing feedback documents from blob:  82%|████████▏ | 28/34 [18:49<04:11, 41.85s/doc, F3565421_en.txt]

11:33:40 [first:F3565421_en.txt] waiting 10s before call...
11:33:55 [first:F3565421_en.txt] call OK
11:33:55 [second:F3565421_en.txt] waiting 10s before call...
11:34:10 [second:F3565421_en.txt] call OK
11:34:10 [third:F3565421_en.txt] waiting 10s before call...
11:34:22 [third:F3565421_en.txt] call OK

Processing feedback documents from blob:  85%|████████▌ | 29/34 [19:31<03:29, 41.88s/doc, F3565446_en.txt]

11:34:22 [first:F3565446_en.txt] waiting 10s before call...
11:34:42 [first:F3565446_en.txt] call OK
11:34:42 [second:F3565446_en.txt] waiting 10s before call...
11:34:54 [second:F3565446_en.txt] call OK
11:34:54 [third:F3565446_en.txt] waiting 10s before call...
11:35:07 [third:F3565446_en.txt] call OK

Processing feedback documents from blob:  88%|████████▊ | 30/34 [20:15<02:50, 42.59s/doc, F3565491_en.txt]

[SAVED] checkpoint with 30 results → C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_translation_results_checkpoint_20251104_113507.json
11:35:07 [first:F3565491_en.txt] waiting 10s before call...
11:35:22 [first:F3565491_en.txt] call OK
11:35:22 [second:F3565491_en.txt] waiting 10s before call...
11:35:35 [second:F3565491_en.txt] call OK
11:35:35 [third:F3565491_en.txt] waiting 10s before call...
11:35:49 [third:F3565491_en.txt] call OK

Processing feedback documents from blob:  91%|█████████ | 31/34 [20:57<02:07, 42.47s/doc, F3565493_en.txt]

11:35:49 [first:F3565493_en.txt] waiting 10s before call...
11:36:03 [first:F3565493_en.txt] call OK
11:36:03 [second:F3565493_en.txt] waiting 10s before call...
11:36:18 [second:F3565493_en.txt] call OK
11:36:18 [third:F3565493_en.txt] waiting 10s before call...
11:36:30 [third:F3565493_en.txt] call OK

Processing feedback documents from blob:  94%|█████████▍| 32/34 [21:39<01:24, 42.15s/doc, F3565495_en.txt]

11:36:30 [first:F3565495_en.txt] waiting 10s before call...
11:36:43 [first:F3565495_en.txt] call OK
11:36:43 [second:F3565495_en.txt] waiting 10s before call...
11:36:56 [second:F3565495_en.txt] call OK
11:36:56 [third:F3565495_en.txt] waiting 10s before call...
11:37:09 [third:F3565495_en.txt] call OK

Processing feedback documents from blob:  97%|█████████▋| 33/34 [22:17<00:41, 41.05s/doc, F3565520_en.txt]

11:37:09 [first:F3565520_en.txt] waiting 10s before call...
11:37:23 [first:F3565520_en.txt] call OK
11:37:23 [second:F3565520_en.txt] waiting 10s before call...
11:37:35 [second:F3565520_en.txt] call OK
11:37:35 [third:F3565520_en.txt] waiting 10s before call...
11:37:47 [third:F3565520_en.txt] call OK

Processing feedback documents from blob: 100%|██████████| 34/34 [22:56<00:00, 40.49s/doc, F3565520_en.txt]

[DONE] All results saved to C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\feedback_translation_results.json

In [28]:
results[:3]

[{'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': ['It cannot be overlooked that it concerns critical points of concern from an ethical point of view and the safety of citizens’ health and therefore requires careful assessment. (page 1)',
   'An assessment to overcome vetoes that are often placed under the precautionary principle often used ideologically (page 1)'],
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3551675'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': ['Indeed, in the light of everything we have experienced in recent years, it is clear that legislation is being made to allow some people to enrich themselves on the back of citizens by ignoring their safety and health. (page 1)'],
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3551693'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3551766'}]

In [26]:
len(results)

34

In [27]:
# Sort the 'Feedback reference' of these filtered rows
sorted_refs = filtered_fb["Feedback reference"].sort_values().tolist()

# Assign these sorted references to your results
for i, r in enumerate(results):
    if i < len(sorted_refs):
        r["reference"] = sorted_refs[i]

In [29]:
# Let's assume 'results' is your updated list of dictionaries
with open(Path(output_folder)/'brussels_fb_translation_results.json', 'w', encoding='utf-8') as f:
    json.dump(results, f, ensure_ascii=False, indent=2)

In [30]:
import re

def replace_page_with_feedback(lst):
    if isinstance(lst, list):
        return [
            re.sub(r"\(page\s*\d+\)", "(from feedback translation)", s) if isinstance(s, str) else s
            for s in lst
        ]
    return lst

for d in results:
    for k, v in d.items():
        if isinstance(v, list):
            d[k] = replace_page_with_feedback(v)

In [32]:
# Let's assume 'results' is your updated list of dictionaries
with open(Path(output_folder)/'brussels_fb_translation_page_replaced.json', 'w', encoding='utf-8') as f:
    json.dump(results, f, ensure_ascii=False, indent=2)

In [33]:
results[:5]

[{'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': ['It cannot be overlooked that it concerns critical points of concern from an ethical point of view and the safety of citizens’ health and therefore requires careful assessment. (from feedback translation)',
   'An assessment to overcome vetoes that are often placed under the precautionary principle often used ideologically (from feedback translation)'],
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3551675'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': ['Indeed, in the light of everything we have experienced in recent years, it is clear that legislation is being made to allow some people to enrich themselves on the back of citizens by ignoring their safety and health. (from feedback translation)'],
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3551693'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3551766'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': None,
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': None,
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': None,
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3551820'},
 {'ATMP': None,
  'ATMP_gene_therapies': None,
  'ATMP_cell_therapies': None,
  'ATMP_tissue_engineered_products': None,
  'ATMP_personalised_medicine': None,
  'Access_to_Markets_hurdles': None,
  'Access_to_Markets_strategies': ['Finally, I learn that “The Biotechnology Regulation will include a series of measures to create an environment to accelerate the transition of biotechnology products from the laboratory to the factory and to the market, while maintaining the highest safety standards for the protection of the population and the environment.” (from feedback translation)'],
  'VC_Investments_IPO': None,
  'Manufacturing_Capabilities': ['Finally, I learn that “The Biotechnology Regulation will include a series of measures to create an environment to accelerate the transition of biotechnology products from the laboratory to the factory and to the market, while maintaining the highest safety standards for the protection of the population and the environment.” (from feedback translation)'],
  'Incubation_and_Acceleration': None,
  'Talent_Retention': None,
  'Upskilling_Reskilling': None,
  'AI_Challenges': ['The same applies to ‘AI’ incorrectly named. It is not intelligence, but just a calculation. It will be used above all to justify the filing of patents on genetic sequences without having to request the right of use to those people in the South who have agreed to give their knowledge. (from feedback translation)'],
  'AI_Development_and_Deployment': None,
  'Global_Collaboration': None,
  'Biosecurity': None,
  'Biosecurity_Nucleic_Acid_Screening': None,
  'reference': 'F3551923'}]

In [34]:
import json
from pathlib import Path



with (output_folder / 'brussels_merged_results.json').open(encoding='utf-8') as f:
    pp = json.load(f)

with (output_folder / 'brussels_fb_translation_page_replaced.json').open(encoding='utf-8') as f:
    fb = json.load(f)

# Build a lookup for pp by reference
pp_refs = {d['reference']: d for d in pp if 'reference' in d}

for fb_dict in fb:
    ref = fb_dict.get('reference')
    if ref in pp_refs:
        pp_dict = pp_refs[ref]
        for k, v in fb_dict.items():
            if k == "reference":
                continue
            # Merge lists, else set/overwrite
            if v is not None:
                if k in pp_dict and isinstance(pp_dict[k], list) and isinstance(v, list):
                    pp_dict[k].extend(v)
                else:
                    pp_dict[k] = v
    else:
        pp.append(fb_dict)

# Save merged result
with (output_folder / 'brussels_merged_results_translation_added.json').open('w', encoding='utf-8') as f:
    json.dump(pp, f, ensure_ascii=False, indent=2)

In [35]:
import pandas as pd

# Convert list of dicts to DataFrame
df = pd.DataFrame(pp)

# Make sure both 'reference' and 'title' are present
columns = df.columns.tolist()
first_cols = [col for col in ['reference', 'title'] if col in columns]
other_cols = [col for col in columns if col not in first_cols]
ordered_cols = first_cols + other_cols

# Reorder
df = df[ordered_cols]


# Save to Excel
df.to_excel(Path(output_folder) / 'brussels_final_merged_translation_added.xlsx', index=False)