In [1]:
from dotenv import load_dotenv
import os
from pathlib import Path
from openai import AzureOpenAI
from embeddings import UserDocumentCollection
import os, json, re
import pandas as pd

import numpy as np
from pypdf import PdfReader
import win32com.client as win32
from time import sleep

In [16]:
load_dotenv()

True

In [3]:
folder_path = os.environ.get("FOLDER_PATH")

In [9]:
container_name="brussels-docs"
colect = UserDocumentCollection(container_name)


for p in sorted([p for p in Path(folder_path).iterdir() if p.is_file()]):
    file_path = str(p)
    with open(file_path, "rb") as file_obj:
        colect.add_file_to_blob_container(file_path, file_obj)

colect.create_user_search_index()
colect.create_data_source_connection()
colect.create_user_skillset()
colect.create_user_indexer()

2025-09-02 09:42:30.762 | INFO     | embeddings:get_container:66 - Container 'brussels-docs' already exists.
2025-09-02 09:42:30.901 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3552803-Feedback Paper On the European Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:30.934 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3553888-cpme.2025-092.FINAL.Statement.Biotech.Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:30.963 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3554271-Koppert submission for the biotech act consultations.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:31.006 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3559517-EBSA Position Paper - OMNIBUS - 20250416 (1).pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:31.125 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3561326-PhageEU Proposals for Amendments_Pharmaceutical Package_March 2025.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:31.146 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3563493-WACKER Submission Bioeconomy.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:31.214 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3563646-250604_Stellungnahme der Hamilton Bonaduz AG zum geplanten Europäischen Biotech Rechtsakt.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:31.238 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3563652-Biotech input Artemis Def.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:31.430 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3563668-Plant ETP Contribution - Call for evidence Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:31.831 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3563901-EU Biotech Act Position Paper V1.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:31.854 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3563910-Food Fermentation Europe_Biotech Act Call for Evidence, June 2025.docx' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:31.979 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3563929-CFE response to Biotech Act proposal.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:32.018 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564074-GFI-E Call for evidence Biotech act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:32.100 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564102-EBU_BioTech Act_Submission_June 2025 (1).pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:32.159 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564121-BiotechAct_Fraunhofer.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:32.258 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564204-Biotech Act_ Luke.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:32.298 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564210-Amgen_position paper Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:32.447 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564218-CAE Position_Biotech Act_Call for Evidence.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:32.766 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564228-CropLifeEurope_Simplification proposals for GM & Bioppps_.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:32.918 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564247-2025-06-06 A.I.S.E. feedback to the European Commission Call for Evidence on the Biotech Act .pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:32.948 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564250-BIO Deutschland_ Comments on the EU Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:33.009 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564253-Postion paper Biocontrol.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:33.188 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564264-ACDV - Contribution Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:33.458 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564266-Leading, not lagging - putting mental health at the core of Europe s innovation and competitiveness agenda.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:33.634 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564268-INRAE Contribution to EU Biotech Act_VF.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:33.701 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564270-25_EU_11.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:34.325 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564380-Biotech Act open consultation DSW 2025.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:34.350 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564435-VK_Akt o biotechnologiích_CZ_.docx' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:34.492 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564477-MBB Biotech Act Call for Evidence_June 2025.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:34.566 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564478-20250609_Biotech Act consultation - SPRING.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:34.642 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564488-MediQuills_Response_to_EU's_Biotech_Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:34.750 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564504-250410 respuesta MAPA EUSurvey - Survey.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:34.884 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564682-Reco EU biotech EWPA EWPM 10.06.2025.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:34.970 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564687-Biotech Act June 2025 _FoodDrinkEurope Feedback.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:35.050 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564728-ESMO Response - Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:35.091 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564760-250610_Hollandbio_input_CfE_BiotechAct.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:35.151 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564769-Written Contribution EFfCI -Biotech Act (1).pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:35.215 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564784-QbD Group Feedback on EU Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:35.233 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564813-Reviews and position papers_Annex.docx' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:35.295 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564816-250610 ANOVE Comentarios Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:35.420 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564818-FINAL_EuropaBio Position EU Biotech Act_10062025.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:35.456 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564833-EHA recommendations - Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:35.489 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564836-20250610 AseBio response Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:35.524 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564841-20250610 Biovia - Call for evidence - EU Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:35.554 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564842-EU Biotech  Act_EC Public Consultation_HIPRA.docx' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:35.615 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564843-ARM Call for Evidence Response Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:35.693 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564846-2025_06_11_Call for evidence Biotech Act_CNRS.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:35.768 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564851-2025-023 EPF Response to the Call for Evidence on the European Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:35.875 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564862-J&J Placing the life science sector at the core of the Competitiveness Compass_FINAL.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:35.923 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564899-Biotech act_Klaudia Kozusznik_A4BEE.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:35.945 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564900-June 2025 _ Contribution AFE _ Biotech Act.docx' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:35.992 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564901-GSK contribution for the Call for Evidence, Biotech Act, 10 June 2025.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:36.014 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564912-ACRO FINAL Comment - Biotech Act Call for Evidence.docx' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:36.035 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564918-EU Biotech submission.docx' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:36.151 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564919-Pandemic Action Network response to the EU Biotech Act call for evidence_1006225.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:36.332 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564930-25.0367.2 - Biotech Act - Euroseeds input to call for evidence.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:36.527 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564965-RD Moonshot_Contribution to the consultation EU Biotech Act_FINAL.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:36.566 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564967-Call for Evidence Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:36.678 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564970-EU BioTech act_VTT messages.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:36.698 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564976-2025_biotech consultation.docx' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:36.771 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564981-Submission for EU Biotech Act Call for Evidence_Pour Demain Europe.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:36.808 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564997-ErVimmune - Réflexions sur le financement des biotech UE ENG 10062025 .pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:36.843 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3564998-EPF’s response to the Call for evidence on the EU Biotect Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:36.916 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565010-EFPIA Annex_BioTech Act_Call for evidence_Final.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:37.017 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565025-Joint HNP Position Paper Biotechnology mrt 2024.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:37.210 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565034-20250611- CNCPI- contribution European Biotech Act .pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:37.260 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565040-bioMerieux contribution_EU Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:37.301 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565042-Cepi response to Call for Evidence_Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:37.419 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565064-EUCOPE_Proposals Biotech Act_final_Jun25.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:37.449 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565089-Novamont_Biotech Act consultation.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:37.762 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565090-CORBION_POSITION BIOTECH ACT.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:37.845 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565110-Biocontrol-Coalition-BiotechAct-final.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:37.870 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565113-20250611_Helmholtz_BiotechAct_final.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:37.905 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565115-20250519_LSMA_Biotech Act call for evidence.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:38.230 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565117-ECL Policy paper The potential for academic development of medicines in Europe.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:39.004 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565118-EFFCA FEMS Publication on NGTs (2024) & Labelling Solution.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:39.100 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565143-Biotech Act Call for Evidence, attachment.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:39.264 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565157-Ley Biotecnologia comentarios.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:39.421 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565164-2025-06-04 Stellungnahme Pro Generika EU Biotech Act_Entwurf_final.docx' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:39.449 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565165-MedTech Europe Biotech Act Call for Evidence Draft response June 2025 FINAL.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:39.484 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565166-25-06-11_Biotech-Act_Call_Evidence_SupplLiterature_BfN.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:39.642 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565172-Eurogroup for Animals - Call for evidence on the Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:39.742 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565207-Response to the Call for Evidence on the European Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:39.832 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565208-AnimalhealthEurope_Feedback - Biotech Act (fin).pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:39.904 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565224-Feedback on Biotech Act_Rigshospitalet_Copenhagen University Hospital.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:39.948 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565229-EUBiotechAct_ FIB_final.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:39.993 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565230-Pfizer Response to the EU Biotech Act Call for Evidence.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:40.083 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565232-IFOAMEU_Biotech Act_public consultation_input.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:40.158 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565236-Lif's and SwedensBIO's Biotech act position paper.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:40.188 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565249-Novo Nordisk Foundation - Call for evidence EU Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:40.351 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565251-FIN_DIB_EU BioTech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:40.384 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565252-DanishChamberofCommerce_Callforevidence_BiotechAct.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:40.415 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565256-EU Biotech Act call for evidence_PRI response_Submitted.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:40.510 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565277-Roche feedback EU Biotech Act - Call for Evidence - 11 June 2025.pdf' already exists in container 'brussels-docs'. Skipping upload.
2025-09-02 09:42:40.609 | WARNING  | embeddings:add_file_to_blob_container:99 - File 'F3565281-Position paper WEWIS Biotech Act.pdf' already exists in container 'brussels-docs'. Skipping upload.

In [6]:
user_prompt = """
Extract the following fields ONLY from that document; do not invent facts.

Return ONE JSON object with exactly these keys and types:
- "title": string (Do not give back the document name. Instead, find what is the title that appears in the first page of document ?)
- "organisation": array of strings (What is the organizations that wrote this the document)
- "summary": string (summarise the document that you already possess in 4-6 sentences capturing the essentials; suitable for one spreadsheet cell, written in British English)
- "main themes": array of up to 10 short theme phrases (ranked by prominence, written in British English; do not pad with guesses)

Rules:
- Base your answer ONLY on the provided content; do not rely on outside knowledge.
- If a field is not present, set it to null (or [] for arrays).
- Preserve the document's original title (do not translate it); the "summary" and "main_themes" must be in British English.
- Output VALID JSON and NOTHING ELSE (no markdown fences, no prose, no citations like [doc1])."""

In [7]:
pillars_prompt = """Below are concise definitions of five challenges that motivate a new Biotechnology Act:

- VC (Access to Capital): Biotech requires large upfront funding for long R&D, trials, regulation, and scale-up; early bootstrapping helps, but VC/PE/strategic capital typically catalyze growth and Europe faces persistent risk-capital gaps and foreign exits.
- Clusters (Biotech clusters & technology centers): Co-located hubs concentrate talent, infrastructure, and investment, enabling public–private partnerships, sector specialization, shared services (regulatory/funding/market access), and internationalization.
- Skills (Reskilling & upskilling): Biomanufacturing needs deep process expertise (e.g., fermentation, molecular methods) plus cross-cutting data/AI, sustainability, systems thinking, and entrepreneurship; agile VET/HE and lifelong learning are critical.
- AI/data (Use of data & AI): AI (incl. GenAI) turns large scientific/process datasets into gains across discovery, engineering, and operations (e.g., target ID, CRISPR guide design, digital twins), with outcomes dependent on data quality, validation, and governance.
- Dual-use/security (Awareness of misuse risks): Attention to potential dual-use concerns and biosecurity, including risks of misuse such as development of bioweapons, uncontrolled pathogens, or other harmful applications. May appear in the context of regulation, funding decisions, or calls for responsible innovation and safeguards.


TASK: For each challenge, check whether the document makes a substantive reference to it. 
If yes, return a MAXIMUM TWO-SENTENCE summary in BRITISH ENGLISH of how the document addresses that challenge (what it says, proposes, or evidences). If not present, set the value to null.
Return ONE JSON object with EXACTLY these keys (values are either a string ≤2 sentences or null):
{
  "VC": <string or null>,
  "clusters": <string or null>,
  "skills": <string or null>,
  "AI/data": <string or null>,
  "dual_use/security": <string or null>
}

Rules:
- Base your answer ONLY on the provided content; do not rely on outside knowledge.
- Do not invent facts; if uncertain, use null.
- Output VALID JSON and NOTHING ELSE (no markdown fences, no prose, no citations)."""

In [17]:
client = AzureOpenAI(
    azure_endpoint=os.environ["AZURE_COGNITIVE_SERVICES_ENDPOINT"],
    api_key=os.environ["AZURE_COGNITIVE_API"],
    api_version="2024-10-21",  # 2024-02-01+ supports data_sources
)

### FIRST TEST BY FILTERING FOR A SINGLE DOCUMENT

In [5]:

def odata_escape(s: str) -> str:
    # OData string literals escape single quotes by doubling them
    return s.replace("'", "''")

In [ ]:
#doc_name = 'F3554271-Koppert submission for the biotech act consultations.pdf'        
doc_name='F3552803-Feedback Paper On the European Biotech Act.pdf'

completion = client.chat.completions.create(
    model="gpt-4.1",
    messages=[{"role": "user", 
               "content": user_prompt}],
    extra_body={
        "data_sources": [
            {
                "type": "azure_search",
                "parameters": {
                    "endpoint": os.environ["AZURE_AI_SEARCH_ENDPOINT"],
                    "index_name": f"{container_name}_index",
                    "authentication": {
                        "type": "api_key",
                        "key": os.environ["AZURE_AI_SEARCH_API_KEY"],
                    },

                    # Map fields so citations show nice titles/paths (optional but handy)
                    "fields_mapping": {
                        "title_field": "title",
                        "filepath_field": "filepath",
                        "url_field": "url",
                        
                    },

                    # B) If you stored the doc name in a custom field
                    "filter": f"title eq '{odata_escape(doc_name)}'",


                    "in_scope": True,        # keep the answer grounded to retrieved docs
                    # "strictness": 4,       # (optional) tighten relevance
                    # "top_n_documents": 5,  # (optional) fewer chunks for stricter focus
                },
            }
        ],
    },
)

print(completion.choices[0].message.content)

In [10]:
def extract_information(doc_name):
    completion = client.chat.completions.create(
        model="gpt-4.1",
        messages=[{"role": "user", "content": f"You already possess the document {doc_name} that contain all necessary information to answer following questions. \n" + user_prompt, }],
        response_format={"type": "json_object"},
        extra_body={
            "data_sources": [
                {
                    "type": "azure_search",
                    "parameters": {
                        "endpoint": os.environ["AZURE_AI_SEARCH_ENDPOINT"],
                        "index_name": f"{container_name}_index",
                        "authentication": {
                            "type": "api_key",
                            "key": os.environ["AZURE_AI_SEARCH_API_KEY"],
                        },
                        "fields_mapping": {
                            "title_field": "title",
                            "filepath_field": "filepath",
                            "url_field": "url",
                        },
                        "filter": f"title eq '{odata_escape(doc_name)}'",
                        "in_scope": True,
                        # "strictness": 4,
                        # "top_n_documents": 5,
                    },
                }
            ],
        },
    )
    raw = completion.choices[0].message.content or ""
    try:
        return json.loads(raw)  # now it should be valid JSON
    except json.JSONDecodeError:
        # Fallback: return your schema with nulls so the loop doesn't crash
        return {
            "title": None,
            "organization": [],
            "summary": None,
            "main themes": [],
        }

In [11]:
def extract_pillars(doc_name):
    completion = client.chat.completions.create(
        model="gpt-4.1",
        messages=[{"role": "user", "content": f"You already possess the document {doc_name} that contain all necessary information to answer following questions. \n" + pillars_prompt, }],
        response_format={"type": "json_object"},
        extra_body={
            "data_sources": [
                {
                    "type": "azure_search",
                    "parameters": {
                        "endpoint": os.environ["AZURE_AI_SEARCH_ENDPOINT"],
                        "index_name": f"{container_name}_index",
                        "authentication": {
                            "type": "api_key",
                            "key": os.environ["AZURE_AI_SEARCH_API_KEY"],
                        },
                        "fields_mapping": {
                            "title_field": "title",
                            "filepath_field": "filepath",
                            "url_field": "url",
                        },
                        "filter": f"title eq '{odata_escape(doc_name)}'",
                        "in_scope": True,
                        # "strictness": 4,
                        # "top_n_documents": 5,
                    },
                }
            ],
        },
    )
    raw = completion.choices[0].message.content or ""
    try:
        return json.loads(raw)  # now it should be valid JSON
    except json.JSONDecodeError:
        # Fallback: return your schema with nulls so the loop doesn't crash
        return {
            "VC": None,
            "clusters": None,
            "skills": None,
            "AI/data": None,
            "dual_use/security": None
        }

In [78]:
doc_name='F3552803-Feedback Paper On the European Biotech Act.pdf'
extract_pillars(doc_name)

{'VC': 'The document highlights that the EU biotech investment landscape is fragmented, with only 5% of global venture capital compared to 52% in the US, and calls for the establishment of an EU Biotech Investment Facility with blended finance instruments, equity guarantees, and scale-up funding. It also recommends partnering with European stock exchanges to facilitate IPO pathways and reduce reliance on US listings.',
 'clusters': None,
 'skills': "There is a noted mismatch between the labour market and biotech's evolving skills needs, particularly in areas like bioprocess engineering, data science, and regulatory affairs. The document proposes EU-wide talent fellowships and embedding entrepreneurship curricula within Horizon Europe and Erasmus+ to upskill PhD candidates in innovation management and commercialisation.",
 'AI/data': 'The document stresses the importance of access to real-world data, AI-enhanced simulations, and supercomputing resources for biotech SMEs, and recommends ensuring biotech-specific access to the European Health Data Space, federated datasets, and AI Factories. It also advocates for the creation of an EU Biotech-AI Alliance to encourage cross-sector R&D and mandates interoperability standards and ethical safeguards.',
 'dual_use/security': 'The document raises concerns about dual-use biotechnology risks, including biosecurity and the potential misuse of biotech in health and agriculture. It calls for a biotechnology security strategy to address dual-use risks, IP protection, and international standards, and recommends incentivising regional manufacturing and de-risking supply chains.'}

## LOOP OVER ALL DOCUMENTS

In [104]:

from time import sleep, strftime
from openai import APIConnectionError, BadRequestError
import re

def call_once_with_wait(fn, *args, delay=10, label=None, **kwargs):
    who = f"[{label}]" if label else ""
    print(f"{strftime('%H:%M:%S')} {who} waiting {delay}s before call...", flush=True)
    sleep(delay)
    try:
        out = fn(*args, **kwargs)
        print(f"{strftime('%H:%M:%S')} {who} call OK", flush=True)
        return out
    except BadRequestError as e:
        s = str(e)
        if "Rate limit is exceeded" in s:
            m = re.search(r"Try again in\s+(\d+)\s+seconds?", s, re.I)
            wait_s = int(m.group(1)) + 1 if m else max(5, delay)
            print(f"{strftime('%H:%M:%S')} {who} 429 rate limit → waiting {wait_s}s, then retrying once...", flush=True)
            sleep(wait_s)
            out = fn(*args, **kwargs)
            print(f"{strftime('%H:%M:%S')} {who} retry OK", flush=True)
            return out
        print(f"{strftime('%H:%M:%S')} {who} BadRequestError (not rate-limit): {e}", flush=True)
        raise
    except APIConnectionError as e:
        print(f"{strftime('%H:%M:%S')} {who} connection error → waiting 5s, then retrying once... ({e})", flush=True)
        sleep(5)
        out = fn(*args, **kwargs)
        print(f"{strftime('%H:%M:%S')} {who} retry OK", flush=True)
        return out
    except Exception as e:
        print(f"{strftime('%H:%M:%S')} {who} unexpected error: {e}", flush=True)
        raise

In [ ]:
dir_path = Path(folder_path)  # folder_path already exists
docs = sorted([p.name for p in dir_path.iterdir() if p.is_file()])

results = []
for doc in docs:
    doc_name = doc
    info    = call_once_with_wait(extract_information, doc_name, delay=10, label=f"info:{doc_name}")
    pillars = call_once_with_wait(extract_pillars, doc_name, delay=10, label=f"pillars:{doc_name}")
    results.append({**info, **pillars})

In [105]:
from tqdm.auto import tqdm

dir_path = Path(folder_path)
docs = sorted([p.name for p in dir_path.iterdir() if p.is_file()])

results, errors = [], []
pbar = tqdm(docs, desc="Processing documents", unit="doc", total=len(docs))

for doc in pbar:
    pbar.set_postfix_str(doc)  # show current file name on the bar
    try:
        info    = call_once_with_wait(extract_information, doc, delay=10, label=f"info:{doc}")
        pillars = call_once_with_wait(extract_pillars,     doc, delay=10, label=f"pillars:{doc}")
        results.append({**info, **pillars})
    except Exception as e:
        errors.append((doc, repr(e)))
        pbar.write(f"[ERROR] {doc}: {e}")

# Optional: inspect errors afterwards
# print(errors)

Processing documents:   0%|          | 0/149 [00:00<?, ?doc/s, F3552803-Feedback Paper On the European Biotech Act.pdf]

18:21:55 [info:F3552803-Feedback Paper On the European Biotech Act.pdf] waiting 10s before call...

18:22:12 [info:F3552803-Feedback Paper On the European Biotech Act.pdf] call OK
18:22:12 [pillars:F3552803-Feedback Paper On the European Biotech Act.pdf] waiting 10s before call...
18:22:29 [pillars:F3552803-Feedback Paper On the European Biotech Act.pdf] call OK

Processing documents:   1%|          | 1/149 [00:34<1:25:39, 34.73s/doc, F3553888-cpme.2025-092.FINAL.Statement.Biotech.Act.pdf]

18:22:29 [info:F3553888-cpme.2025-092.FINAL.Statement.Biotech.Act.pdf] waiting 10s before call...
18:22:44 [info:F3553888-cpme.2025-092.FINAL.Statement.Biotech.Act.pdf] call OK
18:22:44 [pillars:F3553888-cpme.2025-092.FINAL.Statement.Biotech.Act.pdf] waiting 10s before call...
18:22:58 [pillars:F3553888-cpme.2025-092.FINAL.Statement.Biotech.Act.pdf] call OK

Processing documents:   1%|▏         | 2/149 [01:03<1:16:25, 31.19s/doc, F3554271-Koppert submission for the biotech act consultations.pdf]

18:22:58 [info:F3554271-Koppert submission for the biotech act consultations.pdf] waiting 10s before call...
18:23:15 [info:F3554271-Koppert submission for the biotech act consultations.pdf] call OK
18:23:15 [pillars:F3554271-Koppert submission for the biotech act consultations.pdf] waiting 10s before call...
18:23:29 [pillars:F3554271-Koppert submission for the biotech act consultations.pdf] call OK

Processing documents:   2%|▏         | 3/149 [01:34<1:16:04, 31.26s/doc, F3559517-EBSA Position Paper - OMNIBUS - 20250416 (1).pdf]

18:23:29 [info:F3559517-EBSA Position Paper - OMNIBUS - 20250416 (1).pdf] waiting 10s before call...
18:23:47 [info:F3559517-EBSA Position Paper - OMNIBUS - 20250416 (1).pdf] call OK
18:23:47 [pillars:F3559517-EBSA Position Paper - OMNIBUS - 20250416 (1).pdf] waiting 10s before call...
18:24:04 [pillars:F3559517-EBSA Position Paper - OMNIBUS - 20250416 (1).pdf] call OK

Processing documents:   3%|▎         | 4/149 [02:09<1:18:49, 32.62s/doc, F3561326-PhageEU Proposals for Amendments_Pharmaceutical Package_March 2025.pdf]

18:24:04 [info:F3561326-PhageEU Proposals for Amendments_Pharmaceutical Package_March 2025.pdf] waiting 10s before call...
18:24:21 [info:F3561326-PhageEU Proposals for Amendments_Pharmaceutical Package_March 2025.pdf] call OK
18:24:21 [pillars:F3561326-PhageEU Proposals for Amendments_Pharmaceutical Package_March 2025.pdf] waiting 10s before call...
18:24:35 [pillars:F3561326-PhageEU Proposals for Amendments_Pharmaceutical Package_March 2025.pdf] call OK

Processing documents:   3%|▎         | 5/149 [02:40<1:16:52, 32.03s/doc, F3563493-WACKER Submission Bioeconomy.pdf]

18:24:35 [info:F3563493-WACKER Submission Bioeconomy.pdf] waiting 10s before call...
18:24:51 [info:F3563493-WACKER Submission Bioeconomy.pdf] call OK
18:24:51 [pillars:F3563493-WACKER Submission Bioeconomy.pdf] waiting 10s before call...
18:25:04 [pillars:F3563493-WACKER Submission Bioeconomy.pdf] call OK

Processing documents:   4%|▍         | 6/149 [03:09<1:14:10, 31.12s/doc, F3563646-250604_Stellungnahme der Hamilton Bonaduz AG zum geplanten Europäischen Biotech Rechtsakt.pdf]

18:25:04 [info:F3563646-250604_Stellungnahme der Hamilton Bonaduz AG zum geplanten Europäischen Biotech Rechtsakt.pdf] waiting 10s before call...
18:25:21 [info:F3563646-250604_Stellungnahme der Hamilton Bonaduz AG zum geplanten Europäischen Biotech Rechtsakt.pdf] call OK
18:25:21 [pillars:F3563646-250604_Stellungnahme der Hamilton Bonaduz AG zum geplanten Europäischen Biotech Rechtsakt.pdf] waiting 10s before call...
18:25:38 [pillars:F3563646-250604_Stellungnahme der Hamilton Bonaduz AG zum geplanten Europäischen Biotech Rechtsakt.pdf] call OK

Processing documents:   5%|▍         | 7/149 [03:42<1:15:09, 31.76s/doc, F3563652-Biotech input Artemis Def.pdf]

18:25:38 [info:F3563652-Biotech input Artemis Def.pdf] waiting 10s before call...
18:25:53 [info:F3563652-Biotech input Artemis Def.pdf] call OK
18:25:53 [pillars:F3563652-Biotech input Artemis Def.pdf] waiting 10s before call...
18:26:06 [pillars:F3563652-Biotech input Artemis Def.pdf] call OK

Processing documents:   5%|▌         | 8/149 [04:11<1:11:58, 30.63s/doc, F3563668-Plant ETP Contribution - Call for evidence Biotech Act.pdf]

18:26:06 [info:F3563668-Plant ETP Contribution - Call for evidence Biotech Act.pdf] waiting 10s before call...
18:26:22 [info:F3563668-Plant ETP Contribution - Call for evidence Biotech Act.pdf] call OK
18:26:22 [pillars:F3563668-Plant ETP Contribution - Call for evidence Biotech Act.pdf] waiting 10s before call...
18:26:36 [pillars:F3563668-Plant ETP Contribution - Call for evidence Biotech Act.pdf] call OK

Processing documents:   6%|▌         | 9/149 [04:41<1:11:08, 30.49s/doc, F3563901-EU Biotech Act Position Paper V1.pdf]

18:26:36 [info:F3563901-EU Biotech Act Position Paper V1.pdf] waiting 10s before call...
18:26:53 [info:F3563901-EU Biotech Act Position Paper V1.pdf] call OK
18:26:53 [pillars:F3563901-EU Biotech Act Position Paper V1.pdf] waiting 10s before call...
18:27:09 [pillars:F3563901-EU Biotech Act Position Paper V1.pdf] call OK

Processing documents:   7%|▋         | 10/149 [05:13<1:12:07, 31.13s/doc, F3563910-Food Fermentation Europe_Biotech Act Call for Evidence, June 2025.docx]

18:27:09 [info:F3563910-Food Fermentation Europe_Biotech Act Call for Evidence, June 2025.docx] waiting 10s before call...
18:27:24 [info:F3563910-Food Fermentation Europe_Biotech Act Call for Evidence, June 2025.docx] call OK
18:27:24 [pillars:F3563910-Food Fermentation Europe_Biotech Act Call for Evidence, June 2025.docx] waiting 10s before call...
18:27:38 [pillars:F3563910-Food Fermentation Europe_Biotech Act Call for Evidence, June 2025.docx] call OK

Processing documents:   7%|▋         | 11/149 [05:43<1:10:15, 30.55s/doc, F3563929-CFE response to Biotech Act proposal.pdf]

18:27:38 [info:F3563929-CFE response to Biotech Act proposal.pdf] waiting 10s before call...
18:27:54 [info:F3563929-CFE response to Biotech Act proposal.pdf] call OK
18:27:54 [pillars:F3563929-CFE response to Biotech Act proposal.pdf] waiting 10s before call...
18:28:10 [pillars:F3563929-CFE response to Biotech Act proposal.pdf] call OK

Processing documents:   8%|▊         | 12/149 [06:15<1:10:45, 30.99s/doc, F3564074-GFI-E Call for evidence Biotech act.pdf]

18:28:10 [info:F3564074-GFI-E Call for evidence Biotech act.pdf] waiting 10s before call...
18:28:27 [info:F3564074-GFI-E Call for evidence Biotech act.pdf] call OK
18:28:27 [pillars:F3564074-GFI-E Call for evidence Biotech act.pdf] waiting 10s before call...
18:28:42 [pillars:F3564074-GFI-E Call for evidence Biotech act.pdf] call OK

Processing documents:   9%|▊         | 13/149 [06:47<1:11:07, 31.38s/doc, F3564102-EBU_BioTech Act_Submission_June 2025 (1).pdf]

18:28:42 [info:F3564102-EBU_BioTech Act_Submission_June 2025 (1).pdf] waiting 10s before call...
18:28:58 [info:F3564102-EBU_BioTech Act_Submission_June 2025 (1).pdf] call OK
18:28:58 [pillars:F3564102-EBU_BioTech Act_Submission_June 2025 (1).pdf] waiting 10s before call...
18:29:12 [pillars:F3564102-EBU_BioTech Act_Submission_June 2025 (1).pdf] call OK

Processing documents:   9%|▉         | 14/149 [07:17<1:09:45, 31.00s/doc, F3564121-BiotechAct_Fraunhofer.pdf]

18:29:12 [info:F3564121-BiotechAct_Fraunhofer.pdf] waiting 10s before call...
18:29:29 [info:F3564121-BiotechAct_Fraunhofer.pdf] call OK
18:29:29 [pillars:F3564121-BiotechAct_Fraunhofer.pdf] waiting 10s before call...
18:29:44 [pillars:F3564121-BiotechAct_Fraunhofer.pdf] call OK

Processing documents:  10%|█         | 15/149 [07:49<1:09:46, 31.24s/doc, F3564204-Biotech Act_ Luke.pdf]

18:29:44 [info:F3564204-Biotech Act_ Luke.pdf] waiting 10s before call...
18:30:01 [info:F3564204-Biotech Act_ Luke.pdf] call OK
18:30:01 [pillars:F3564204-Biotech Act_ Luke.pdf] waiting 10s before call...
18:30:18 [pillars:F3564204-Biotech Act_ Luke.pdf] call OK

Processing documents:  11%|█         | 16/149 [08:23<1:11:05, 32.07s/doc, F3564210-Amgen_position paper Biotech Act.pdf]

18:30:18 [info:F3564210-Amgen_position paper Biotech Act.pdf] waiting 10s before call...
18:30:36 [info:F3564210-Amgen_position paper Biotech Act.pdf] call OK
18:30:36 [pillars:F3564210-Amgen_position paper Biotech Act.pdf] waiting 10s before call...
18:30:53 [pillars:F3564210-Amgen_position paper Biotech Act.pdf] call OK

Processing documents:  11%|█▏        | 17/149 [08:58<1:12:48, 33.10s/doc, F3564218-CAE Position_Biotech Act_Call for Evidence.pdf]

18:30:53 [info:F3564218-CAE Position_Biotech Act_Call for Evidence.pdf] waiting 10s before call...
18:31:11 [info:F3564218-CAE Position_Biotech Act_Call for Evidence.pdf] call OK
18:31:11 [pillars:F3564218-CAE Position_Biotech Act_Call for Evidence.pdf] waiting 10s before call...
18:31:25 [pillars:F3564218-CAE Position_Biotech Act_Call for Evidence.pdf] call OK

Processing documents:  12%|█▏        | 18/149 [09:30<1:11:03, 32.54s/doc, F3564228-CropLifeEurope_Simplification proposals for GM & Bioppps_.pdf]

18:31:25 [info:F3564228-CropLifeEurope_Simplification proposals for GM & Bioppps_.pdf] waiting 10s before call...
18:31:42 [info:F3564228-CropLifeEurope_Simplification proposals for GM & Bioppps_.pdf] call OK
18:31:42 [pillars:F3564228-CropLifeEurope_Simplification proposals for GM & Bioppps_.pdf] waiting 10s before call...
18:31:56 [pillars:F3564228-CropLifeEurope_Simplification proposals for GM & Bioppps_.pdf] call OK

Processing documents:  13%|█▎        | 19/149 [10:01<1:09:42, 32.17s/doc, F3564247-2025-06-06 A.I.S.E. feedback to the European Commission Call for Evidence on the Biotech Act .pdf]

18:31:56 [info:F3564247-2025-06-06 A.I.S.E. feedback to the European Commission Call for Evidence on the Biotech Act .pdf] waiting 10s before call...
18:32:15 [info:F3564247-2025-06-06 A.I.S.E. feedback to the European Commission Call for Evidence on the Biotech Act .pdf] call OK
18:32:15 [pillars:F3564247-2025-06-06 A.I.S.E. feedback to the European Commission Call for Evidence on the Biotech Act .pdf] waiting 10s before call...
18:32:29 [pillars:F3564247-2025-06-06 A.I.S.E. feedback to the European Commission Call for Evidence on the Biotech Act .pdf] call OK

Processing documents:  13%|█▎        | 20/149 [10:34<1:09:47, 32.46s/doc, F3564250-BIO Deutschland_ Comments on the EU Biotech Act.pdf]

18:32:29 [info:F3564250-BIO Deutschland_ Comments on the EU Biotech Act.pdf] waiting 10s before call...
18:32:44 [info:F3564250-BIO Deutschland_ Comments on the EU Biotech Act.pdf] call OK
18:32:44 [pillars:F3564250-BIO Deutschland_ Comments on the EU Biotech Act.pdf] waiting 10s before call...
18:32:58 [pillars:F3564250-BIO Deutschland_ Comments on the EU Biotech Act.pdf] call OK

Processing documents:  14%|█▍        | 21/149 [11:03<1:06:59, 31.40s/doc, F3564253-Postion paper Biocontrol.pdf]

18:32:58 [info:F3564253-Postion paper Biocontrol.pdf] waiting 10s before call...
18:33:15 [info:F3564253-Postion paper Biocontrol.pdf] call OK
18:33:15 [pillars:F3564253-Postion paper Biocontrol.pdf] waiting 10s before call...
18:33:29 [pillars:F3564253-Postion paper Biocontrol.pdf] call OK

Processing documents:  15%|█▍        | 22/149 [11:34<1:06:15, 31.30s/doc, F3564264-ACDV - Contribution Biotech Act.pdf]

18:33:29 [info:F3564264-ACDV - Contribution Biotech Act.pdf] waiting 10s before call...
18:33:46 [info:F3564264-ACDV - Contribution Biotech Act.pdf] call OK
18:33:46 [pillars:F3564264-ACDV - Contribution Biotech Act.pdf] waiting 10s before call...
18:34:00 [pillars:F3564264-ACDV - Contribution Biotech Act.pdf] call OK

Processing documents:  15%|█▌        | 23/149 [12:05<1:05:17, 31.09s/doc, F3564266-Leading, not lagging - putting mental health at the core of Europe s innovation and competitiveness agenda.pdf]

18:34:00 [info:F3564266-Leading, not lagging - putting mental health at the core of Europe s innovation and competitiveness agenda.pdf] waiting 10s before call...
18:34:18 [info:F3564266-Leading, not lagging - putting mental health at the core of Europe s innovation and competitiveness agenda.pdf] call OK
18:34:18 [pillars:F3564266-Leading, not lagging - putting mental health at the core of Europe s innovation and competitiveness agenda.pdf] waiting 10s before call...
18:34:33 [pillars:F3564266-Leading, not lagging - putting mental health at the core of Europe s innovation and competitiveness agenda.pdf] call OK

Processing documents:  16%|█▌        | 24/149 [12:38<1:06:16, 31.81s/doc, F3564268-INRAE Contribution to EU Biotech Act_VF.pdf]

18:34:33 [info:F3564268-INRAE Contribution to EU Biotech Act_VF.pdf] waiting 10s before call...
18:34:50 [info:F3564268-INRAE Contribution to EU Biotech Act_VF.pdf] call OK
18:34:50 [pillars:F3564268-INRAE Contribution to EU Biotech Act_VF.pdf] waiting 10s before call...
18:35:14 [pillars:F3564268-INRAE Contribution to EU Biotech Act_VF.pdf] call OK

Processing documents:  17%|█▋        | 25/149 [13:19<1:11:07, 34.42s/doc, F3564270-25_EU_11.pdf]

18:35:14 [info:F3564270-25_EU_11.pdf] waiting 10s before call...
18:35:29 [info:F3564270-25_EU_11.pdf] call OK
18:35:29 [pillars:F3564270-25_EU_11.pdf] waiting 10s before call...
18:35:42 [pillars:F3564270-25_EU_11.pdf] call OK

Processing documents:  17%|█▋        | 26/149 [13:47<1:06:52, 32.62s/doc, F3564380-Biotech Act open consultation DSW 2025.pdf]

18:35:42 [info:F3564380-Biotech Act open consultation DSW 2025.pdf] waiting 10s before call...
18:35:59 [info:F3564380-Biotech Act open consultation DSW 2025.pdf] call OK
18:35:59 [pillars:F3564380-Biotech Act open consultation DSW 2025.pdf] waiting 10s before call...
18:36:14 [pillars:F3564380-Biotech Act open consultation DSW 2025.pdf] call OK

Processing documents:  18%|█▊        | 27/149 [14:19<1:05:57, 32.44s/doc, F3564435-VK_Akt o biotechnologiích_CZ_.docx]

18:36:14 [info:F3564435-VK_Akt o biotechnologiích_CZ_.docx] waiting 10s before call...
18:36:31 [info:F3564435-VK_Akt o biotechnologiích_CZ_.docx] call OK
18:36:31 [pillars:F3564435-VK_Akt o biotechnologiích_CZ_.docx] waiting 10s before call...
18:36:44 [pillars:F3564435-VK_Akt o biotechnologiích_CZ_.docx] call OK

Processing documents:  19%|█▉        | 28/149 [14:48<1:03:35, 31.53s/doc, F3564477-MBB Biotech Act Call for Evidence_June 2025.pdf]

18:36:44 [info:F3564477-MBB Biotech Act Call for Evidence_June 2025.pdf] waiting 10s before call...
18:36:59 [info:F3564477-MBB Biotech Act Call for Evidence_June 2025.pdf] call OK
18:36:59 [pillars:F3564477-MBB Biotech Act Call for Evidence_June 2025.pdf] waiting 10s before call...
18:37:11 [pillars:F3564477-MBB Biotech Act Call for Evidence_June 2025.pdf] call OK

Processing documents:  19%|█▉        | 29/149 [15:16<1:00:49, 30.42s/doc, F3564478-20250609_Biotech Act consultation - SPRING.pdf]

18:37:11 [info:F3564478-20250609_Biotech Act consultation - SPRING.pdf] waiting 10s before call...
18:37:27 [info:F3564478-20250609_Biotech Act consultation - SPRING.pdf] call OK
18:37:27 [pillars:F3564478-20250609_Biotech Act consultation - SPRING.pdf] waiting 10s before call...
18:37:42 [pillars:F3564478-20250609_Biotech Act consultation - SPRING.pdf] call OK

Processing documents:  20%|██        | 30/149 [15:46<1:00:11, 30.35s/doc, F3564488-MediQuills_Response_to_EU's_Biotech_Act.pdf]

18:37:42 [info:F3564488-MediQuills_Response_to_EU's_Biotech_Act.pdf] waiting 10s before call...
18:38:03 [info:F3564488-MediQuills_Response_to_EU's_Biotech_Act.pdf] call OK
18:38:03 [pillars:F3564488-MediQuills_Response_to_EU's_Biotech_Act.pdf] waiting 10s before call...
18:38:22 [pillars:F3564488-MediQuills_Response_to_EU's_Biotech_Act.pdf] call OK

Processing documents:  21%|██        | 31/149 [16:27<1:05:48, 33.46s/doc, F3564504-250410 respuesta MAPA EUSurvey - Survey.pdf]

18:38:22 [info:F3564504-250410 respuesta MAPA EUSurvey - Survey.pdf] waiting 10s before call...
18:38:49 [info:F3564504-250410 respuesta MAPA EUSurvey - Survey.pdf] call OK
18:38:49 [pillars:F3564504-250410 respuesta MAPA EUSurvey - Survey.pdf] waiting 10s before call...
18:39:03 [pillars:F3564504-250410 respuesta MAPA EUSurvey - Survey.pdf] call OK

Processing documents:  21%|██▏       | 32/149 [17:08<1:09:22, 35.58s/doc, F3564682-Reco EU biotech EWPA EWPM 10.06.2025.pdf]

18:39:03 [info:F3564682-Reco EU biotech EWPA EWPM 10.06.2025.pdf] waiting 10s before call...
18:39:21 [info:F3564682-Reco EU biotech EWPA EWPM 10.06.2025.pdf] call OK
18:39:21 [pillars:F3564682-Reco EU biotech EWPA EWPM 10.06.2025.pdf] waiting 10s before call...
18:39:37 [pillars:F3564682-Reco EU biotech EWPA EWPM 10.06.2025.pdf] call OK

Processing documents:  22%|██▏       | 33/149 [17:41<1:07:44, 35.04s/doc, F3564687-Biotech Act June 2025 _FoodDrinkEurope Feedback.pdf]

18:39:37 [info:F3564687-Biotech Act June 2025 _FoodDrinkEurope Feedback.pdf] waiting 10s before call...
18:39:53 [info:F3564687-Biotech Act June 2025 _FoodDrinkEurope Feedback.pdf] call OK
18:39:53 [pillars:F3564687-Biotech Act June 2025 _FoodDrinkEurope Feedback.pdf] waiting 10s before call...
18:41:33 [pillars:F3564687-Biotech Act June 2025 _FoodDrinkEurope Feedback.pdf] call OK

Processing documents:  23%|██▎       | 34/149 [19:38<1:54:07, 59.54s/doc, F3564728-ESMO Response - Biotech Act.pdf]

18:41:33 [info:F3564728-ESMO Response - Biotech Act.pdf] waiting 10s before call...
18:41:49 [info:F3564728-ESMO Response - Biotech Act.pdf] call OK
18:41:49 [pillars:F3564728-ESMO Response - Biotech Act.pdf] waiting 10s before call...
18:42:03 [pillars:F3564728-ESMO Response - Biotech Act.pdf] call OK

Processing documents:  23%|██▎       | 35/149 [20:07<1:35:52, 50.46s/doc, F3564760-250610_Hollandbio_input_CfE_BiotechAct.pdf]

18:42:03 [info:F3564760-250610_Hollandbio_input_CfE_BiotechAct.pdf] waiting 10s before call...
18:42:19 [info:F3564760-250610_Hollandbio_input_CfE_BiotechAct.pdf] call OK
18:42:19 [pillars:F3564760-250610_Hollandbio_input_CfE_BiotechAct.pdf] waiting 10s before call...
18:42:33 [pillars:F3564760-250610_Hollandbio_input_CfE_BiotechAct.pdf] call OK

Processing documents:  24%|██▍       | 36/149 [20:38<1:23:40, 44.43s/doc, F3564769-Written Contribution EFfCI -Biotech Act (1).pdf]

18:42:33 [info:F3564769-Written Contribution EFfCI -Biotech Act (1).pdf] waiting 10s before call...
18:42:49 [info:F3564769-Written Contribution EFfCI -Biotech Act (1).pdf] call OK
18:42:49 [pillars:F3564769-Written Contribution EFfCI -Biotech Act (1).pdf] waiting 10s before call...
18:43:06 [pillars:F3564769-Written Contribution EFfCI -Biotech Act (1).pdf] call OK

Processing documents:  25%|██▍       | 37/149 [21:10<1:16:22, 40.91s/doc, F3564784-QbD Group Feedback on EU Biotech Act.pdf]

18:43:06 [info:F3564784-QbD Group Feedback on EU Biotech Act.pdf] waiting 10s before call...
18:43:20 [info:F3564784-QbD Group Feedback on EU Biotech Act.pdf] call OK
18:43:20 [pillars:F3564784-QbD Group Feedback on EU Biotech Act.pdf] waiting 10s before call...
18:43:34 [pillars:F3564784-QbD Group Feedback on EU Biotech Act.pdf] call OK

Processing documents:  26%|██▌       | 38/149 [21:39<1:08:48, 37.19s/doc, F3564813-Reviews and position papers_Annex.docx]

18:43:34 [info:F3564813-Reviews and position papers_Annex.docx] waiting 10s before call...
18:43:49 [info:F3564813-Reviews and position papers_Annex.docx] call OK
18:43:49 [pillars:F3564813-Reviews and position papers_Annex.docx] waiting 10s before call...
18:44:03 [pillars:F3564813-Reviews and position papers_Annex.docx] call OK

Processing documents:  26%|██▌       | 39/149 [22:07<1:03:21, 34.56s/doc, F3564816-250610 ANOVE Comentarios Biotech Act.pdf]

18:44:03 [info:F3564816-250610 ANOVE Comentarios Biotech Act.pdf] waiting 10s before call...
18:44:20 [info:F3564816-250610 ANOVE Comentarios Biotech Act.pdf] call OK
18:44:20 [pillars:F3564816-250610 ANOVE Comentarios Biotech Act.pdf] waiting 10s before call...
18:44:33 [pillars:F3564816-250610 ANOVE Comentarios Biotech Act.pdf] call OK

Processing documents:  27%|██▋       | 40/149 [22:38<1:00:28, 33.29s/doc, F3564818-FINAL_EuropaBio Position EU Biotech Act_10062025.pdf]

18:44:33 [info:F3564818-FINAL_EuropaBio Position EU Biotech Act_10062025.pdf] waiting 10s before call...
18:44:49 [info:F3564818-FINAL_EuropaBio Position EU Biotech Act_10062025.pdf] call OK
18:44:49 [pillars:F3564818-FINAL_EuropaBio Position EU Biotech Act_10062025.pdf] waiting 10s before call...
18:45:06 [pillars:F3564818-FINAL_EuropaBio Position EU Biotech Act_10062025.pdf] call OK

Processing documents:  28%|██▊       | 41/149 [23:11<59:52, 33.26s/doc, F3564833-EHA recommendations - Biotech Act.pdf]

18:45:06 [info:F3564833-EHA recommendations - Biotech Act.pdf] waiting 10s before call...
18:45:22 [info:F3564833-EHA recommendations - Biotech Act.pdf] call OK
18:45:22 [pillars:F3564833-EHA recommendations - Biotech Act.pdf] waiting 10s before call...
18:45:37 [pillars:F3564833-EHA recommendations - Biotech Act.pdf] call OK

Processing documents:  28%|██▊       | 42/149 [23:41<57:49, 32.42s/doc, F3564836-20250610 AseBio response Biotech Act.pdf]

18:45:37 [info:F3564836-20250610 AseBio response Biotech Act.pdf] waiting 10s before call...
18:45:54 [info:F3564836-20250610 AseBio response Biotech Act.pdf] call OK
18:45:54 [pillars:F3564836-20250610 AseBio response Biotech Act.pdf] waiting 10s before call...
18:46:09 [pillars:F3564836-20250610 AseBio response Biotech Act.pdf] call OK

Processing documents:  29%|██▉       | 43/149 [24:14<57:08, 32.34s/doc, F3564841-20250610 Biovia - Call for evidence - EU Biotech Act.pdf]

18:46:09 [info:F3564841-20250610 Biovia - Call for evidence - EU Biotech Act.pdf] waiting 10s before call...
18:46:25 [info:F3564841-20250610 Biovia - Call for evidence - EU Biotech Act.pdf] call OK
18:46:25 [pillars:F3564841-20250610 Biovia - Call for evidence - EU Biotech Act.pdf] waiting 10s before call...
18:46:40 [pillars:F3564841-20250610 Biovia - Call for evidence - EU Biotech Act.pdf] call OK

Processing documents:  30%|██▉       | 44/149 [24:45<56:16, 32.16s/doc, F3564842-EU Biotech  Act_EC Public Consultation_HIPRA.docx]

18:46:40 [info:F3564842-EU Biotech  Act_EC Public Consultation_HIPRA.docx] waiting 10s before call...
18:46:56 [info:F3564842-EU Biotech  Act_EC Public Consultation_HIPRA.docx] call OK
18:46:56 [pillars:F3564842-EU Biotech  Act_EC Public Consultation_HIPRA.docx] waiting 10s before call...
18:47:09 [pillars:F3564842-EU Biotech  Act_EC Public Consultation_HIPRA.docx] call OK

Processing documents:  30%|███       | 45/149 [25:14<54:04, 31.19s/doc, F3564843-ARM Call for Evidence Response Biotech Act.pdf]

18:47:09 [info:F3564843-ARM Call for Evidence Response Biotech Act.pdf] waiting 10s before call...
18:47:25 [info:F3564843-ARM Call for Evidence Response Biotech Act.pdf] call OK
18:47:25 [pillars:F3564843-ARM Call for Evidence Response Biotech Act.pdf] waiting 10s before call...
18:47:43 [pillars:F3564843-ARM Call for Evidence Response Biotech Act.pdf] call OK

Processing documents:  31%|███       | 46/149 [25:47<54:34, 31.79s/doc, F3564846-2025_06_11_Call for evidence Biotech Act_CNRS.pdf]

18:47:43 [info:F3564846-2025_06_11_Call for evidence Biotech Act_CNRS.pdf] waiting 10s before call...
18:48:00 [info:F3564846-2025_06_11_Call for evidence Biotech Act_CNRS.pdf] call OK
18:48:00 [pillars:F3564846-2025_06_11_Call for evidence Biotech Act_CNRS.pdf] waiting 10s before call...
18:48:20 [pillars:F3564846-2025_06_11_Call for evidence Biotech Act_CNRS.pdf] call OK

Processing documents:  32%|███▏      | 47/149 [26:25<56:56, 33.50s/doc, F3564851-2025-023 EPF Response to the Call for Evidence on the European Biotech Act.pdf]

18:48:20 [info:F3564851-2025-023 EPF Response to the Call for Evidence on the European Biotech Act.pdf] waiting 10s before call...
18:48:36 [info:F3564851-2025-023 EPF Response to the Call for Evidence on the European Biotech Act.pdf] call OK
18:48:36 [pillars:F3564851-2025-023 EPF Response to the Call for Evidence on the European Biotech Act.pdf] waiting 10s before call...
18:48:49 [pillars:F3564851-2025-023 EPF Response to the Call for Evidence on the European Biotech Act.pdf] call OK

Processing documents:  32%|███▏      | 48/149 [26:54<54:15, 32.23s/doc, F3564862-J&J Placing the life science sector at the core of the Competitiveness Compass_FINAL.pdf]

18:48:49 [info:F3564862-J&J Placing the life science sector at the core of the Competitiveness Compass_FINAL.pdf] waiting 10s before call...
18:49:05 [info:F3564862-J&J Placing the life science sector at the core of the Competitiveness Compass_FINAL.pdf] call OK
18:49:05 [pillars:F3564862-J&J Placing the life science sector at the core of the Competitiveness Compass_FINAL.pdf] waiting 10s before call...
18:49:20 [pillars:F3564862-J&J Placing the life science sector at the core of the Competitiveness Compass_FINAL.pdf] call OK

Processing documents:  33%|███▎      | 49/149 [27:25<52:58, 31.78s/doc, F3564899-Biotech act_Klaudia Kozusznik_A4BEE.pdf]

18:49:20 [info:F3564899-Biotech act_Klaudia Kozusznik_A4BEE.pdf] waiting 10s before call...
18:49:35 [info:F3564899-Biotech act_Klaudia Kozusznik_A4BEE.pdf] call OK
18:49:35 [pillars:F3564899-Biotech act_Klaudia Kozusznik_A4BEE.pdf] waiting 10s before call...
18:49:51 [pillars:F3564899-Biotech act_Klaudia Kozusznik_A4BEE.pdf] call OK

Processing documents:  34%|███▎      | 50/149 [27:56<52:00, 31.52s/doc, F3564900-June 2025 _ Contribution AFE _ Biotech Act.docx]

18:49:51 [info:F3564900-June 2025 _ Contribution AFE _ Biotech Act.docx] waiting 10s before call...
18:50:09 [info:F3564900-June 2025 _ Contribution AFE _ Biotech Act.docx] call OK
18:50:09 [pillars:F3564900-June 2025 _ Contribution AFE _ Biotech Act.docx] waiting 10s before call...
18:50:25 [pillars:F3564900-June 2025 _ Contribution AFE _ Biotech Act.docx] call OK

Processing documents:  34%|███▍      | 51/149 [28:29<52:32, 32.17s/doc, F3564901-GSK contribution for the Call for Evidence, Biotech Act, 10 June 2025.pdf]

18:50:25 [info:F3564901-GSK contribution for the Call for Evidence, Biotech Act, 10 June 2025.pdf] waiting 10s before call...
18:50:40 [info:F3564901-GSK contribution for the Call for Evidence, Biotech Act, 10 June 2025.pdf] call OK
18:50:40 [pillars:F3564901-GSK contribution for the Call for Evidence, Biotech Act, 10 June 2025.pdf] waiting 10s before call...
18:50:54 [pillars:F3564901-GSK contribution for the Call for Evidence, Biotech Act, 10 June 2025.pdf] call OK

Processing documents:  35%|███▍      | 52/149 [28:59<50:45, 31.39s/doc, F3564912-ACRO FINAL Comment - Biotech Act Call for Evidence.docx]

18:50:54 [info:F3564912-ACRO FINAL Comment - Biotech Act Call for Evidence.docx] waiting 10s before call...
18:51:11 [info:F3564912-ACRO FINAL Comment - Biotech Act Call for Evidence.docx] call OK
18:51:11 [pillars:F3564912-ACRO FINAL Comment - Biotech Act Call for Evidence.docx] waiting 10s before call...
18:51:24 [pillars:F3564912-ACRO FINAL Comment - Biotech Act Call for Evidence.docx] call OK

Processing documents:  36%|███▌      | 53/149 [29:29<49:40, 31.05s/doc, F3564918-EU Biotech submission.docx]

18:51:24 [info:F3564918-EU Biotech submission.docx] waiting 10s before call...
18:51:42 [info:F3564918-EU Biotech submission.docx] call OK
18:51:42 [pillars:F3564918-EU Biotech submission.docx] waiting 10s before call...
18:51:58 [pillars:F3564918-EU Biotech submission.docx] call OK

Processing documents:  36%|███▌      | 54/149 [30:03<50:21, 31.81s/doc, F3564919-Pandemic Action Network response to the EU Biotech Act call for evidence_1006225.pdf]

18:51:58 [info:F3564919-Pandemic Action Network response to the EU Biotech Act call for evidence_1006225.pdf] waiting 10s before call...
18:52:15 [info:F3564919-Pandemic Action Network response to the EU Biotech Act call for evidence_1006225.pdf] call OK
18:52:15 [pillars:F3564919-Pandemic Action Network response to the EU Biotech Act call for evidence_1006225.pdf] waiting 10s before call...
18:52:31 [pillars:F3564919-Pandemic Action Network response to the EU Biotech Act call for evidence_1006225.pdf] call OK

Processing documents:  37%|███▋      | 55/149 [30:36<50:24, 32.17s/doc, F3564930-25.0367.2 - Biotech Act - Euroseeds input to call for evidence.pdf]

18:52:31 [info:F3564930-25.0367.2 - Biotech Act - Euroseeds input to call for evidence.pdf] waiting 10s before call...
18:52:47 [info:F3564930-25.0367.2 - Biotech Act - Euroseeds input to call for evidence.pdf] call OK
18:52:47 [pillars:F3564930-25.0367.2 - Biotech Act - Euroseeds input to call for evidence.pdf] waiting 10s before call...
18:53:01 [pillars:F3564930-25.0367.2 - Biotech Act - Euroseeds input to call for evidence.pdf] call OK

Processing documents:  38%|███▊      | 56/149 [31:06<48:47, 31.48s/doc, F3564965-RD Moonshot_Contribution to the consultation EU Biotech Act_FINAL.pdf]

18:53:01 [info:F3564965-RD Moonshot_Contribution to the consultation EU Biotech Act_FINAL.pdf] waiting 10s before call...
18:53:18 [info:F3564965-RD Moonshot_Contribution to the consultation EU Biotech Act_FINAL.pdf] call OK
18:53:18 [pillars:F3564965-RD Moonshot_Contribution to the consultation EU Biotech Act_FINAL.pdf] waiting 10s before call...
18:53:36 [pillars:F3564965-RD Moonshot_Contribution to the consultation EU Biotech Act_FINAL.pdf] call OK

Processing documents:  38%|███▊      | 57/149 [31:41<49:53, 32.54s/doc, F3564967-Call for Evidence Biotech Act.pdf]

18:53:36 [info:F3564967-Call for Evidence Biotech Act.pdf] waiting 10s before call...
18:53:54 [info:F3564967-Call for Evidence Biotech Act.pdf] call OK
18:53:54 [pillars:F3564967-Call for Evidence Biotech Act.pdf] waiting 10s before call...
18:54:11 [pillars:F3564967-Call for Evidence Biotech Act.pdf] call OK

Processing documents:  39%|███▉      | 58/149 [32:16<50:31, 33.32s/doc, F3564970-EU BioTech act_VTT messages.pdf]

18:54:11 [info:F3564970-EU BioTech act_VTT messages.pdf] waiting 10s before call...
18:54:29 [info:F3564970-EU BioTech act_VTT messages.pdf] call OK
18:54:29 [pillars:F3564970-EU BioTech act_VTT messages.pdf] waiting 10s before call...
18:54:46 [pillars:F3564970-EU BioTech act_VTT messages.pdf] call OK

Processing documents:  40%|███▉      | 59/149 [32:50<50:31, 33.69s/doc, F3564976-2025_biotech consultation.docx]

18:54:46 [info:F3564976-2025_biotech consultation.docx] waiting 10s before call...
18:55:01 [info:F3564976-2025_biotech consultation.docx] call OK
18:55:01 [pillars:F3564976-2025_biotech consultation.docx] waiting 10s before call...
18:55:14 [pillars:F3564976-2025_biotech consultation.docx] call OK

Processing documents:  40%|████      | 60/149 [33:19<47:32, 32.05s/doc, F3564981-Submission for EU Biotech Act Call for Evidence_Pour Demain Europe.pdf]

18:55:14 [info:F3564981-Submission for EU Biotech Act Call for Evidence_Pour Demain Europe.pdf] waiting 10s before call...
18:55:36 [info:F3564981-Submission for EU Biotech Act Call for Evidence_Pour Demain Europe.pdf] call OK
18:55:36 [pillars:F3564981-Submission for EU Biotech Act Call for Evidence_Pour Demain Europe.pdf] waiting 10s before call...
18:55:52 [pillars:F3564981-Submission for EU Biotech Act Call for Evidence_Pour Demain Europe.pdf] call OK

Processing documents:  41%|████      | 61/149 [33:57<49:53, 34.02s/doc, F3564997-ErVimmune - Réflexions sur le financement des biotech UE ENG 10062025 .pdf]

18:55:52 [info:F3564997-ErVimmune - Réflexions sur le financement des biotech UE ENG 10062025 .pdf] waiting 10s before call...
18:56:09 [info:F3564997-ErVimmune - Réflexions sur le financement des biotech UE ENG 10062025 .pdf] call OK
18:56:09 [pillars:F3564997-ErVimmune - Réflexions sur le financement des biotech UE ENG 10062025 .pdf] waiting 10s before call...
18:56:24 [pillars:F3564997-ErVimmune - Réflexions sur le financement des biotech UE ENG 10062025 .pdf] call OK

Processing documents:  42%|████▏     | 62/149 [34:29<48:11, 33.23s/doc, F3564998-EPF’s response to the Call for evidence on the EU Biotect Act.pdf]

18:56:24 [info:F3564998-EPF’s response to the Call for evidence on the EU Biotect Act.pdf] waiting 10s before call...
18:56:39 [info:F3564998-EPF’s response to the Call for evidence on the EU Biotect Act.pdf] call OK
18:56:39 [pillars:F3564998-EPF’s response to the Call for evidence on the EU Biotect Act.pdf] waiting 10s before call...
18:56:54 [pillars:F3564998-EPF’s response to the Call for evidence on the EU Biotect Act.pdf] call OK

Processing documents:  42%|████▏     | 63/149 [34:58<46:06, 32.17s/doc, F3565010-EFPIA Annex_BioTech Act_Call for evidence_Final.pdf]

18:56:54 [info:F3565010-EFPIA Annex_BioTech Act_Call for evidence_Final.pdf] waiting 10s before call...
18:57:11 [info:F3565010-EFPIA Annex_BioTech Act_Call for evidence_Final.pdf] call OK
18:57:11 [pillars:F3565010-EFPIA Annex_BioTech Act_Call for evidence_Final.pdf] waiting 10s before call...
18:57:27 [pillars:F3565010-EFPIA Annex_BioTech Act_Call for evidence_Final.pdf] call OK

Processing documents:  43%|████▎     | 64/149 [35:32<46:10, 32.60s/doc, F3565025-Joint HNP Position Paper Biotechnology mrt 2024.pdf]

18:57:27 [info:F3565025-Joint HNP Position Paper Biotechnology mrt 2024.pdf] waiting 10s before call...
18:57:44 [info:F3565025-Joint HNP Position Paper Biotechnology mrt 2024.pdf] call OK
18:57:44 [pillars:F3565025-Joint HNP Position Paper Biotechnology mrt 2024.pdf] waiting 10s before call...
18:57:59 [pillars:F3565025-Joint HNP Position Paper Biotechnology mrt 2024.pdf] call OK

Processing documents:  44%|████▎     | 65/149 [36:04<45:18, 32.37s/doc, F3565034-20250611- CNCPI- contribution European Biotech Act .pdf]

18:57:59 [info:F3565034-20250611- CNCPI- contribution European Biotech Act .pdf] waiting 10s before call...
18:58:18 [info:F3565034-20250611- CNCPI- contribution European Biotech Act .pdf] call OK
18:58:18 [pillars:F3565034-20250611- CNCPI- contribution European Biotech Act .pdf] waiting 10s before call...
18:58:32 [pillars:F3565034-20250611- CNCPI- contribution European Biotech Act .pdf] call OK

Processing documents:  44%|████▍     | 66/149 [36:37<44:57, 32.50s/doc, F3565040-bioMerieux contribution_EU Biotech Act.pdf]

18:58:32 [info:F3565040-bioMerieux contribution_EU Biotech Act.pdf] waiting 10s before call...
18:58:47 [info:F3565040-bioMerieux contribution_EU Biotech Act.pdf] call OK
18:58:47 [pillars:F3565040-bioMerieux contribution_EU Biotech Act.pdf] waiting 10s before call...
18:59:00 [pillars:F3565040-bioMerieux contribution_EU Biotech Act.pdf] call OK

Processing documents:  45%|████▍     | 67/149 [37:05<42:31, 31.11s/doc, F3565042-Cepi response to Call for Evidence_Biotech Act.pdf]

18:59:00 [info:F3565042-Cepi response to Call for Evidence_Biotech Act.pdf] waiting 10s before call...
18:59:15 [info:F3565042-Cepi response to Call for Evidence_Biotech Act.pdf] call OK
18:59:15 [pillars:F3565042-Cepi response to Call for Evidence_Biotech Act.pdf] waiting 10s before call...
18:59:29 [pillars:F3565042-Cepi response to Call for Evidence_Biotech Act.pdf] call OK

Processing documents:  46%|████▌     | 68/149 [37:34<41:10, 30.50s/doc, F3565064-EUCOPE_Proposals Biotech Act_final_Jun25.pdf]

18:59:29 [info:F3565064-EUCOPE_Proposals Biotech Act_final_Jun25.pdf] waiting 10s before call...
18:59:46 [info:F3565064-EUCOPE_Proposals Biotech Act_final_Jun25.pdf] call OK
18:59:46 [pillars:F3565064-EUCOPE_Proposals Biotech Act_final_Jun25.pdf] waiting 10s before call...
19:00:03 [pillars:F3565064-EUCOPE_Proposals Biotech Act_final_Jun25.pdf] call OK

Processing documents:  46%|████▋     | 69/149 [38:08<42:01, 31.52s/doc, F3565089-Novamont_Biotech Act consultation.pdf]

19:00:03 [info:F3565089-Novamont_Biotech Act consultation.pdf] waiting 10s before call...
19:00:20 [info:F3565089-Novamont_Biotech Act consultation.pdf] call OK
19:00:20 [pillars:F3565089-Novamont_Biotech Act consultation.pdf] waiting 10s before call...
19:00:34 [pillars:F3565089-Novamont_Biotech Act consultation.pdf] call OK

Processing documents:  47%|████▋     | 70/149 [38:39<41:18, 31.37s/doc, F3565090-CORBION_POSITION BIOTECH ACT.pdf]

19:00:34 [info:F3565090-CORBION_POSITION BIOTECH ACT.pdf] waiting 10s before call...
19:00:51 [info:F3565090-CORBION_POSITION BIOTECH ACT.pdf] call OK
19:00:51 [pillars:F3565090-CORBION_POSITION BIOTECH ACT.pdf] waiting 10s before call...
19:01:06 [pillars:F3565090-CORBION_POSITION BIOTECH ACT.pdf] call OK

Processing documents:  48%|████▊     | 71/149 [39:10<40:58, 31.51s/doc, F3565110-Biocontrol-Coalition-BiotechAct-final.pdf]

19:01:06 [info:F3565110-Biocontrol-Coalition-BiotechAct-final.pdf] waiting 10s before call...
19:01:23 [info:F3565110-Biocontrol-Coalition-BiotechAct-final.pdf] call OK
19:01:23 [pillars:F3565110-Biocontrol-Coalition-BiotechAct-final.pdf] waiting 10s before call...
19:01:38 [pillars:F3565110-Biocontrol-Coalition-BiotechAct-final.pdf] call OK

Processing documents:  48%|████▊     | 72/149 [39:42<40:39, 31.68s/doc, F3565113-20250611_Helmholtz_BiotechAct_final.pdf]

19:01:38 [info:F3565113-20250611_Helmholtz_BiotechAct_final.pdf] waiting 10s before call...
19:01:54 [info:F3565113-20250611_Helmholtz_BiotechAct_final.pdf] call OK
19:01:54 [pillars:F3565113-20250611_Helmholtz_BiotechAct_final.pdf] waiting 10s before call...
19:02:09 [pillars:F3565113-20250611_Helmholtz_BiotechAct_final.pdf] call OK

Processing documents:  49%|████▉     | 73/149 [40:14<40:07, 31.68s/doc, F3565115-20250519_LSMA_Biotech Act call for evidence.pdf]

19:02:09 [info:F3565115-20250519_LSMA_Biotech Act call for evidence.pdf] waiting 10s before call...
19:02:26 [info:F3565115-20250519_LSMA_Biotech Act call for evidence.pdf] call OK
19:02:26 [pillars:F3565115-20250519_LSMA_Biotech Act call for evidence.pdf] waiting 10s before call...
19:02:43 [pillars:F3565115-20250519_LSMA_Biotech Act call for evidence.pdf] call OK

Processing documents:  50%|████▉     | 74/149 [40:48<40:21, 32.29s/doc, F3565117-ECL Policy paper The potential for academic development of medicines in Europe.pdf]

19:02:43 [info:F3565117-ECL Policy paper The potential for academic development of medicines in Europe.pdf] waiting 10s before call...
19:03:01 [info:F3565117-ECL Policy paper The potential for academic development of medicines in Europe.pdf] call OK
19:03:01 [pillars:F3565117-ECL Policy paper The potential for academic development of medicines in Europe.pdf] waiting 10s before call...
19:03:17 [pillars:F3565117-ECL Policy paper The potential for academic development of medicines in Europe.pdf] call OK

Processing documents:  50%|█████     | 75/149 [41:22<40:27, 32.80s/doc, F3565118-EFFCA FEMS Publication on NGTs (2024) & Labelling Solution.pdf]

19:03:17 [info:F3565118-EFFCA FEMS Publication on NGTs (2024) & Labelling Solution.pdf] waiting 10s before call...
19:03:35 [info:F3565118-EFFCA FEMS Publication on NGTs (2024) & Labelling Solution.pdf] call OK
19:03:35 [pillars:F3565118-EFFCA FEMS Publication on NGTs (2024) & Labelling Solution.pdf] waiting 10s before call...
19:03:51 [pillars:F3565118-EFFCA FEMS Publication on NGTs (2024) & Labelling Solution.pdf] call OK

Processing documents:  51%|█████     | 76/149 [41:56<40:30, 33.30s/doc, F3565143-Biotech Act Call for Evidence, attachment.pdf]

19:03:51 [info:F3565143-Biotech Act Call for Evidence, attachment.pdf] waiting 10s before call...
19:04:09 [info:F3565143-Biotech Act Call for Evidence, attachment.pdf] call OK
19:04:09 [pillars:F3565143-Biotech Act Call for Evidence, attachment.pdf] waiting 10s before call...
19:04:27 [pillars:F3565143-Biotech Act Call for Evidence, attachment.pdf] call OK

Processing documents:  52%|█████▏    | 77/149 [42:32<40:41, 33.91s/doc, F3565157-Ley Biotecnologia comentarios.pdf]

19:04:27 [info:F3565157-Ley Biotecnologia comentarios.pdf] waiting 10s before call...
19:04:44 [info:F3565157-Ley Biotecnologia comentarios.pdf] call OK
19:04:44 [pillars:F3565157-Ley Biotecnologia comentarios.pdf] waiting 10s before call...
19:04:57 [pillars:F3565157-Ley Biotecnologia comentarios.pdf] call OK

Processing documents:  52%|█████▏    | 78/149 [43:02<38:54, 32.89s/doc, F3565164-2025-06-04 Stellungnahme Pro Generika EU Biotech Act_Entwurf_final.docx]

19:04:57 [info:F3565164-2025-06-04 Stellungnahme Pro Generika EU Biotech Act_Entwurf_final.docx] waiting 10s before call...
19:05:13 [info:F3565164-2025-06-04 Stellungnahme Pro Generika EU Biotech Act_Entwurf_final.docx] call OK
19:05:13 [pillars:F3565164-2025-06-04 Stellungnahme Pro Generika EU Biotech Act_Entwurf_final.docx] waiting 10s before call...
19:05:29 [pillars:F3565164-2025-06-04 Stellungnahme Pro Generika EU Biotech Act_Entwurf_final.docx] call OK

Processing documents:  53%|█████▎    | 79/149 [43:34<37:55, 32.51s/doc, F3565165-MedTech Europe Biotech Act Call for Evidence Draft response June 2025 FINAL.pdf]

19:05:29 [info:F3565165-MedTech Europe Biotech Act Call for Evidence Draft response June 2025 FINAL.pdf] waiting 10s before call...
19:05:45 [info:F3565165-MedTech Europe Biotech Act Call for Evidence Draft response June 2025 FINAL.pdf] call OK
19:05:45 [pillars:F3565165-MedTech Europe Biotech Act Call for Evidence Draft response June 2025 FINAL.pdf] waiting 10s before call...
19:05:59 [pillars:F3565165-MedTech Europe Biotech Act Call for Evidence Draft response June 2025 FINAL.pdf] call OK

Processing documents:  54%|█████▎    | 80/149 [44:04<36:31, 31.76s/doc, F3565166-25-06-11_Biotech-Act_Call_Evidence_SupplLiterature_BfN.pdf]

19:05:59 [info:F3565166-25-06-11_Biotech-Act_Call_Evidence_SupplLiterature_BfN.pdf] waiting 10s before call...
19:06:16 [info:F3565166-25-06-11_Biotech-Act_Call_Evidence_SupplLiterature_BfN.pdf] call OK
19:06:16 [pillars:F3565166-25-06-11_Biotech-Act_Call_Evidence_SupplLiterature_BfN.pdf] waiting 10s before call...
19:06:32 [pillars:F3565166-25-06-11_Biotech-Act_Call_Evidence_SupplLiterature_BfN.pdf] call OK

Processing documents:  54%|█████▍    | 81/149 [44:36<36:16, 32.00s/doc, F3565172-Eurogroup for Animals - Call for evidence on the Biotech Act.pdf]

19:06:32 [info:F3565172-Eurogroup for Animals - Call for evidence on the Biotech Act.pdf] waiting 10s before call...
19:06:48 [info:F3565172-Eurogroup for Animals - Call for evidence on the Biotech Act.pdf] call OK
19:06:48 [pillars:F3565172-Eurogroup for Animals - Call for evidence on the Biotech Act.pdf] waiting 10s before call...
19:07:08 [pillars:F3565172-Eurogroup for Animals - Call for evidence on the Biotech Act.pdf] call OK

Processing documents:  55%|█████▌    | 82/149 [45:13<37:17, 33.40s/doc, F3565207-Response to the Call for Evidence on the European Biotech Act.pdf]

19:07:08 [info:F3565207-Response to the Call for Evidence on the European Biotech Act.pdf] waiting 10s before call...
19:07:25 [info:F3565207-Response to the Call for Evidence on the European Biotech Act.pdf] call OK
19:07:25 [pillars:F3565207-Response to the Call for Evidence on the European Biotech Act.pdf] waiting 10s before call...
19:07:38 [pillars:F3565207-Response to the Call for Evidence on the European Biotech Act.pdf] call OK

Processing documents:  56%|█████▌    | 83/149 [45:43<35:40, 32.43s/doc, F3565208-AnimalhealthEurope_Feedback - Biotech Act (fin).pdf]

19:07:38 [info:F3565208-AnimalhealthEurope_Feedback - Biotech Act (fin).pdf] waiting 10s before call...
19:07:55 [info:F3565208-AnimalhealthEurope_Feedback - Biotech Act (fin).pdf] call OK
19:07:55 [pillars:F3565208-AnimalhealthEurope_Feedback - Biotech Act (fin).pdf] waiting 10s before call...
19:08:15 [pillars:F3565208-AnimalhealthEurope_Feedback - Biotech Act (fin).pdf] call OK

Processing documents:  56%|█████▋    | 84/149 [46:20<36:33, 33.75s/doc, F3565224-Feedback on Biotech Act_Rigshospitalet_Copenhagen University Hospital.pdf]

19:08:15 [info:F3565224-Feedback on Biotech Act_Rigshospitalet_Copenhagen University Hospital.pdf] waiting 10s before call...
19:08:31 [info:F3565224-Feedback on Biotech Act_Rigshospitalet_Copenhagen University Hospital.pdf] call OK
19:08:31 [pillars:F3565224-Feedback on Biotech Act_Rigshospitalet_Copenhagen University Hospital.pdf] waiting 10s before call...
19:08:45 [pillars:F3565224-Feedback on Biotech Act_Rigshospitalet_Copenhagen University Hospital.pdf] call OK

Processing documents:  57%|█████▋    | 85/149 [46:50<34:53, 32.72s/doc, F3565229-EUBiotechAct_ FIB_final.pdf]

19:08:45 [info:F3565229-EUBiotechAct_ FIB_final.pdf] waiting 10s before call...
19:09:01 [info:F3565229-EUBiotechAct_ FIB_final.pdf] call OK
19:09:01 [pillars:F3565229-EUBiotechAct_ FIB_final.pdf] waiting 10s before call...
19:09:14 [pillars:F3565229-EUBiotechAct_ FIB_final.pdf] call OK

Processing documents:  58%|█████▊    | 86/149 [47:19<33:02, 31.48s/doc, F3565230-Pfizer Response to the EU Biotech Act Call for Evidence.pdf]

19:09:14 [info:F3565230-Pfizer Response to the EU Biotech Act Call for Evidence.pdf] waiting 10s before call...
19:09:29 [info:F3565230-Pfizer Response to the EU Biotech Act Call for Evidence.pdf] call OK
19:09:29 [pillars:F3565230-Pfizer Response to the EU Biotech Act Call for Evidence.pdf] waiting 10s before call...
19:09:45 [pillars:F3565230-Pfizer Response to the EU Biotech Act Call for Evidence.pdf] call OK

Processing documents:  58%|█████▊    | 87/149 [47:49<32:13, 31.18s/doc, F3565232-IFOAMEU_Biotech Act_public consultation_input.pdf]

19:09:45 [info:F3565232-IFOAMEU_Biotech Act_public consultation_input.pdf] waiting 10s before call...
19:10:02 [info:F3565232-IFOAMEU_Biotech Act_public consultation_input.pdf] call OK
19:10:02 [pillars:F3565232-IFOAMEU_Biotech Act_public consultation_input.pdf] waiting 10s before call...
19:10:19 [pillars:F3565232-IFOAMEU_Biotech Act_public consultation_input.pdf] call OK

Processing documents:  59%|█████▉    | 88/149 [48:24<32:50, 32.30s/doc, F3565236-Lif's and SwedensBIO's Biotech act position paper.pdf]

19:10:19 [info:F3565236-Lif's and SwedensBIO's Biotech act position paper.pdf] waiting 10s before call...
19:10:37 [info:F3565236-Lif's and SwedensBIO's Biotech act position paper.pdf] call OK
19:10:37 [pillars:F3565236-Lif's and SwedensBIO's Biotech act position paper.pdf] waiting 10s before call...
19:10:54 [pillars:F3565236-Lif's and SwedensBIO's Biotech act position paper.pdf] call OK

Processing documents:  60%|█████▉    | 89/149 [48:59<32:57, 32.95s/doc, F3565249-Novo Nordisk Foundation - Call for evidence EU Biotech Act.pdf]

19:10:54 [info:F3565249-Novo Nordisk Foundation - Call for evidence EU Biotech Act.pdf] waiting 10s before call...
19:11:11 [info:F3565249-Novo Nordisk Foundation - Call for evidence EU Biotech Act.pdf] call OK
19:11:11 [pillars:F3565249-Novo Nordisk Foundation - Call for evidence EU Biotech Act.pdf] waiting 10s before call...
19:11:28 [pillars:F3565249-Novo Nordisk Foundation - Call for evidence EU Biotech Act.pdf] call OK

Processing documents:  60%|██████    | 90/149 [49:33<32:41, 33.24s/doc, F3565251-FIN_DIB_EU BioTech Act.pdf]

19:11:28 [info:F3565251-FIN_DIB_EU BioTech Act.pdf] waiting 10s before call...
19:11:45 [info:F3565251-FIN_DIB_EU BioTech Act.pdf] call OK
19:11:45 [pillars:F3565251-FIN_DIB_EU BioTech Act.pdf] waiting 10s before call...
19:12:01 [pillars:F3565251-FIN_DIB_EU BioTech Act.pdf] call OK

Processing documents:  61%|██████    | 91/149 [50:06<32:05, 33.20s/doc, F3565252-DanishChamberofCommerce_Callforevidence_BiotechAct.pdf]

19:12:01 [info:F3565252-DanishChamberofCommerce_Callforevidence_BiotechAct.pdf] waiting 10s before call...
19:12:20 [info:F3565252-DanishChamberofCommerce_Callforevidence_BiotechAct.pdf] call OK
19:12:20 [pillars:F3565252-DanishChamberofCommerce_Callforevidence_BiotechAct.pdf] waiting 10s before call...
19:12:35 [pillars:F3565252-DanishChamberofCommerce_Callforevidence_BiotechAct.pdf] call OK

Processing documents:  62%|██████▏   | 92/149 [50:40<31:54, 33.58s/doc, F3565256-EU Biotech Act call for evidence_PRI response_Submitted.pdf]

19:12:35 [info:F3565256-EU Biotech Act call for evidence_PRI response_Submitted.pdf] waiting 10s before call...
19:12:51 [info:F3565256-EU Biotech Act call for evidence_PRI response_Submitted.pdf] call OK
19:12:51 [pillars:F3565256-EU Biotech Act call for evidence_PRI response_Submitted.pdf] waiting 10s before call...
19:13:04 [pillars:F3565256-EU Biotech Act call for evidence_PRI response_Submitted.pdf] call OK

Processing documents:  62%|██████▏   | 93/149 [51:09<29:54, 32.05s/doc, F3565277-Roche feedback EU Biotech Act - Call for Evidence - 11 June 2025.pdf]

19:13:04 [info:F3565277-Roche feedback EU Biotech Act - Call for Evidence - 11 June 2025.pdf] waiting 10s before call...
19:13:23 [info:F3565277-Roche feedback EU Biotech Act - Call for Evidence - 11 June 2025.pdf] call OK
19:13:23 [pillars:F3565277-Roche feedback EU Biotech Act - Call for Evidence - 11 June 2025.pdf] waiting 10s before call...
19:13:39 [pillars:F3565277-Roche feedback EU Biotech Act - Call for Evidence - 11 June 2025.pdf] call OK

Processing documents:  63%|██████▎   | 94/149 [51:44<30:08, 32.88s/doc, F3565281-Position paper WEWIS Biotech Act.pdf]

19:13:39 [info:F3565281-Position paper WEWIS Biotech Act.pdf] waiting 10s before call...
19:13:54 [info:F3565281-Position paper WEWIS Biotech Act.pdf] call OK
19:13:54 [pillars:F3565281-Position paper WEWIS Biotech Act.pdf] waiting 10s before call...
19:14:09 [pillars:F3565281-Position paper WEWIS Biotech Act.pdf] call OK

Processing documents:  64%|██████▍   | 95/149 [52:14<28:49, 32.03s/doc, F3565286-20250611 BASF Position_Biotech Act - FINAL.pdf]

19:14:09 [info:F3565286-20250611 BASF Position_Biotech Act - FINAL.pdf] waiting 10s before call...
19:14:25 [info:F3565286-20250611 BASF Position_Biotech Act - FINAL.pdf] call OK
19:14:25 [pillars:F3565286-20250611 BASF Position_Biotech Act - FINAL.pdf] waiting 10s before call...
19:14:40 [pillars:F3565286-20250611 BASF Position_Biotech Act - FINAL.pdf] call OK

Processing documents:  64%|██████▍   | 96/149 [52:45<28:04, 31.78s/doc, F3565287-AMFEP Response to the Call for Evidence on the Biotech Act - 11 June.pdf]

19:14:40 [info:F3565287-AMFEP Response to the Call for Evidence on the Biotech Act - 11 June.pdf] waiting 10s before call...
19:14:57 [info:F3565287-AMFEP Response to the Call for Evidence on the Biotech Act - 11 June.pdf] call OK
19:14:57 [pillars:F3565287-AMFEP Response to the Call for Evidence on the Biotech Act - 11 June.pdf] waiting 10s before call...
19:15:11 [pillars:F3565287-AMFEP Response to the Call for Evidence on the Biotech Act - 11 June.pdf] call OK

Processing documents:  65%|██████▌   | 97/149 [53:16<27:24, 31.63s/doc, F3565290-UniSR_European Biotech Act_Extended.pdf]

19:15:11 [info:F3565290-UniSR_European Biotech Act_Extended.pdf] waiting 10s before call...
19:15:24 [info:F3565290-UniSR_European Biotech Act_Extended.pdf] call OK
19:15:24 [pillars:F3565290-UniSR_European Biotech Act_Extended.pdf] waiting 10s before call...
19:15:40 [pillars:F3565290-UniSR_European Biotech Act_Extended.pdf] call OK

Processing documents:  66%|██████▌   | 98/149 [53:45<26:05, 30.69s/doc, F3565295-2025-06-10 Biotech Call for Evidence.pdf]

19:15:40 [info:F3565295-2025-06-10 Biotech Call for Evidence.pdf] waiting 10s before call...
19:15:57 [info:F3565295-2025-06-10 Biotech Call for Evidence.pdf] call OK
19:15:57 [pillars:F3565295-2025-06-10 Biotech Call for Evidence.pdf] waiting 10s before call...
19:16:13 [pillars:F3565295-2025-06-10 Biotech Call for Evidence.pdf] call OK

Processing documents:  66%|██████▋   | 99/149 [54:18<26:09, 31.39s/doc, F3565302-EAHP relevant position papers.pdf]

19:16:13 [info:F3565302-EAHP relevant position papers.pdf] waiting 10s before call...
19:16:30 [info:F3565302-EAHP relevant position papers.pdf] call OK
19:16:30 [pillars:F3565302-EAHP relevant position papers.pdf] waiting 10s before call...
19:16:47 [pillars:F3565302-EAHP relevant position papers.pdf] call OK

Processing documents:  67%|██████▋   | 100/149 [54:52<26:15, 32.15s/doc, F3565307-Call for Evidence_BiotechAct11062025FINAL.pdf]

19:16:47 [info:F3565307-Call for Evidence_BiotechAct11062025FINAL.pdf] waiting 10s before call...
19:17:03 [info:F3565307-Call for Evidence_BiotechAct11062025FINAL.pdf] call OK
19:17:03 [pillars:F3565307-Call for Evidence_BiotechAct11062025FINAL.pdf] waiting 10s before call...
19:17:21 [pillars:F3565307-Call for Evidence_BiotechAct11062025FINAL.pdf] call OK

Processing documents:  68%|██████▊   | 101/149 [55:25<26:09, 32.70s/doc, F3565312-European Biosolutions Coalition_Call for Evidens_Biotech Act_EBC.pdf]

19:17:21 [info:F3565312-European Biosolutions Coalition_Call for Evidens_Biotech Act_EBC.pdf] waiting 10s before call...
19:17:38 [info:F3565312-European Biosolutions Coalition_Call for Evidens_Biotech Act_EBC.pdf] call OK
19:17:38 [pillars:F3565312-European Biosolutions Coalition_Call for Evidens_Biotech Act_EBC.pdf] waiting 10s before call...
19:17:54 [pillars:F3565312-European Biosolutions Coalition_Call for Evidens_Biotech Act_EBC.pdf] call OK

Processing documents:  68%|██████▊   | 102/149 [55:59<25:46, 32.90s/doc, F3565317-BiotechAct_Impact_GASB.pdf]

19:17:54 [info:F3565317-BiotechAct_Impact_GASB.pdf] waiting 10s before call...
19:18:10 [info:F3565317-BiotechAct_Impact_GASB.pdf] call OK
19:18:10 [pillars:F3565317-BiotechAct_Impact_GASB.pdf] waiting 10s before call...
19:18:24 [pillars:F3565317-BiotechAct_Impact_GASB.pdf] call OK

Processing documents:  69%|██████▉   | 103/149 [56:29<24:34, 32.06s/doc, F3565319-Attractiveness-of-the-Vaccines-Industry_June2023.pdf]

19:18:24 [info:F3565319-Attractiveness-of-the-Vaccines-Industry_June2023.pdf] waiting 10s before call...
19:18:41 [info:F3565319-Attractiveness-of-the-Vaccines-Industry_June2023.pdf] call OK
19:18:41 [pillars:F3565319-Attractiveness-of-the-Vaccines-Industry_June2023.pdf] waiting 10s before call...
19:18:57 [pillars:F3565319-Attractiveness-of-the-Vaccines-Industry_June2023.pdf] call OK

Processing documents:  70%|██████▉   | 104/149 [57:02<24:19, 32.43s/doc, F3565323-Johns Hopkins Center for Health Security Call for Evidence Response on EU Biotech Act.pdf]

19:18:57 [info:F3565323-Johns Hopkins Center for Health Security Call for Evidence Response on EU Biotech Act.pdf] waiting 10s before call...
19:19:14 [info:F3565323-Johns Hopkins Center for Health Security Call for Evidence Response on EU Biotech Act.pdf] call OK
19:19:14 [pillars:F3565323-Johns Hopkins Center for Health Security Call for Evidence Response on EU Biotech Act.pdf] waiting 10s before call...
19:19:29 [pillars:F3565323-Johns Hopkins Center for Health Security Call for Evidence Response on EU Biotech Act.pdf] call OK

Processing documents:  70%|███████   | 105/149 [57:34<23:40, 32.28s/doc, F3565339-AstraZeeca_BiotechAct_submission.pdf]

19:19:29 [info:F3565339-AstraZeeca_BiotechAct_submission.pdf] waiting 10s before call...
19:19:47 [info:F3565339-AstraZeeca_BiotechAct_submission.pdf] call OK
19:19:47 [pillars:F3565339-AstraZeeca_BiotechAct_submission.pdf] waiting 10s before call...
19:20:00 [pillars:F3565339-AstraZeeca_BiotechAct_submission.pdf] call OK

Processing documents:  71%|███████   | 106/149 [58:05<22:53, 31.94s/doc, F3565340-2025 06 11_IBBIS Submission_EU Biotech Act.pdf]

19:20:00 [info:F3565340-2025 06 11_IBBIS Submission_EU Biotech Act.pdf] waiting 10s before call...
19:20:19 [info:F3565340-2025 06 11_IBBIS Submission_EU Biotech Act.pdf] call OK
19:20:19 [pillars:F3565340-2025 06 11_IBBIS Submission_EU Biotech Act.pdf] waiting 10s before call...
19:20:34 [pillars:F3565340-2025 06 11_IBBIS Submission_EU Biotech Act.pdf] call OK

Processing documents:  72%|███████▏  | 107/149 [58:39<22:41, 32.43s/doc, F3565342-Humane World Animals_EU Biotech Act.pdf]

19:20:34 [info:F3565342-Humane World Animals_EU Biotech Act.pdf] waiting 10s before call...
19:20:51 [info:F3565342-Humane World Animals_EU Biotech Act.pdf] call OK
19:20:51 [pillars:F3565342-Humane World Animals_EU Biotech Act.pdf] waiting 10s before call...
19:21:06 [pillars:F3565342-Humane World Animals_EU Biotech Act.pdf] call OK

Processing documents:  72%|███████▏  | 108/149 [59:11<22:08, 32.41s/doc, F3565344-2025-06-11 IBMA input to Biotech Act call for evidence.pdf]

19:21:06 [info:F3565344-2025-06-11 IBMA input to Biotech Act call for evidence.pdf] waiting 10s before call...
19:21:23 [info:F3565344-2025-06-11 IBMA input to Biotech Act call for evidence.pdf] call OK
19:21:23 [pillars:F3565344-2025-06-11 IBMA input to Biotech Act call for evidence.pdf] waiting 10s before call...
19:21:37 [pillars:F3565344-2025-06-11 IBMA input to Biotech Act call for evidence.pdf] call OK

Processing documents:  73%|███████▎  | 109/149 [59:41<21:09, 31.73s/doc, F3565349-Biotech Act call for evidence - Cefic reply_20250611.pdf]

19:21:37 [info:F3565349-Biotech Act call for evidence - Cefic reply_20250611.pdf] waiting 10s before call...
19:21:53 [info:F3565349-Biotech Act call for evidence - Cefic reply_20250611.pdf] call OK
19:21:53 [pillars:F3565349-Biotech Act call for evidence - Cefic reply_20250611.pdf] waiting 10s before call...
19:22:07 [pillars:F3565349-Biotech Act call for evidence - Cefic reply_20250611.pdf] call OK

Processing documents:  74%|███████▍  | 110/149 [1:00:12<20:27, 31.48s/doc, F3565354-Lif's and SwedensBIO's Biotech act position paper.pdf]

19:22:07 [info:F3565354-Lif's and SwedensBIO's Biotech act position paper.pdf] waiting 10s before call...
19:22:25 [info:F3565354-Lif's and SwedensBIO's Biotech act position paper.pdf] call OK
19:22:25 [pillars:F3565354-Lif's and SwedensBIO's Biotech act position paper.pdf] waiting 10s before call...
19:22:41 [pillars:F3565354-Lif's and SwedensBIO's Biotech act position paper.pdf] call OK

Processing documents:  74%|███████▍  | 111/149 [1:00:46<20:21, 32.14s/doc, F3565358-EU CONSULTATION BIOTECH ACT - submitted 06112025.pdf]

19:22:41 [info:F3565358-EU CONSULTATION BIOTECH ACT - submitted 06112025.pdf] waiting 10s before call...
19:22:58 [info:F3565358-EU CONSULTATION BIOTECH ACT - submitted 06112025.pdf] call OK
19:22:58 [pillars:F3565358-EU CONSULTATION BIOTECH ACT - submitted 06112025.pdf] waiting 10s before call...
19:23:12 [pillars:F3565358-EU CONSULTATION BIOTECH ACT - submitted 06112025.pdf] call OK

Processing documents:  75%|███████▌  | 112/149 [1:01:17<19:37, 31.83s/doc, F3565359-Biotech Act Consultation response from the Triangle AU_INRAE_WUR _June 2025.pdf]

19:23:12 [info:F3565359-Biotech Act Consultation response from the Triangle AU_INRAE_WUR _June 2025.pdf] waiting 10s before call...
19:23:29 [info:F3565359-Biotech Act Consultation response from the Triangle AU_INRAE_WUR _June 2025.pdf] call OK
19:23:29 [pillars:F3565359-Biotech Act Consultation response from the Triangle AU_INRAE_WUR _June 2025.pdf] waiting 10s before call...
19:23:45 [pillars:F3565359-Biotech Act Consultation response from the Triangle AU_INRAE_WUR _June 2025.pdf] call OK

Processing documents:  76%|███████▌  | 113/149 [1:01:50<19:19, 32.20s/doc, F3565361-EIT Food_Response_to Call for Evidence IA Biotech Act_FINAL.pdf]

19:23:45 [info:F3565361-EIT Food_Response_to Call for Evidence IA Biotech Act_FINAL.pdf] waiting 10s before call...
19:24:01 [info:F3565361-EIT Food_Response_to Call for Evidence IA Biotech Act_FINAL.pdf] call OK
19:24:01 [pillars:F3565361-EIT Food_Response_to Call for Evidence IA Biotech Act_FINAL.pdf] waiting 10s before call...
19:24:18 [pillars:F3565361-EIT Food_Response_to Call for Evidence IA Biotech Act_FINAL.pdf] call OK

Processing documents:  77%|███████▋  | 114/149 [1:02:23<18:48, 32.25s/doc, F3565366-Description Microbs 2025.pdf]

19:24:18 [info:F3565366-Description Microbs 2025.pdf] waiting 10s before call...
19:24:34 [info:F3565366-Description Microbs 2025.pdf] call OK
19:24:34 [pillars:F3565366-Description Microbs 2025.pdf] waiting 10s before call...
19:24:47 [pillars:F3565366-Description Microbs 2025.pdf] call OK

Processing documents:  77%|███████▋  | 115/149 [1:02:52<17:48, 31.43s/doc, F3565367-CEPI Submission to the EU Biotech Act Call for Evidence_Attachment.docx]

19:24:47 [info:F3565367-CEPI Submission to the EU Biotech Act Call for Evidence_Attachment.docx] waiting 10s before call...
19:25:03 [info:F3565367-CEPI Submission to the EU Biotech Act Call for Evidence_Attachment.docx] call OK
19:25:03 [pillars:F3565367-CEPI Submission to the EU Biotech Act Call for Evidence_Attachment.docx] waiting 10s before call...
19:25:18 [pillars:F3565367-CEPI Submission to the EU Biotech Act Call for Evidence_Attachment.docx] call OK

Processing documents:  78%|███████▊  | 116/149 [1:03:23<17:12, 31.28s/doc, F3565369-Synpa_contribution_biotechact_11062025.pdf]

19:25:18 [info:F3565369-Synpa_contribution_biotechact_11062025.pdf] waiting 10s before call...
19:25:36 [info:F3565369-Synpa_contribution_biotechact_11062025.pdf] call OK
19:25:36 [pillars:F3565369-Synpa_contribution_biotechact_11062025.pdf] waiting 10s before call...
19:25:53 [pillars:F3565369-Synpa_contribution_biotechact_11062025.pdf] call OK

Processing documents:  79%|███████▊  | 117/149 [1:03:58<17:16, 32.39s/doc, F3565371-EU Biotech Act - EBC Contribution.pdf]

19:25:53 [info:F3565371-EU Biotech Act - EBC Contribution.pdf] waiting 10s before call...
19:26:08 [info:F3565371-EU Biotech Act - EBC Contribution.pdf] call OK
19:26:08 [pillars:F3565371-EU Biotech Act - EBC Contribution.pdf] waiting 10s before call...
19:26:22 [pillars:F3565371-EU Biotech Act - EBC Contribution.pdf] call OK

Processing documents:  79%|███████▉  | 118/149 [1:04:27<16:13, 31.41s/doc, F3565376-ESIP-Feedback_Call-for-Evidence_for-an-Impact-Assessment_European-Biotech-Act_11-06-2025.pdf]

19:26:22 [info:F3565376-ESIP-Feedback_Call-for-Evidence_for-an-Impact-Assessment_European-Biotech-Act_11-06-2025.pdf] waiting 10s before call...
19:26:38 [info:F3565376-ESIP-Feedback_Call-for-Evidence_for-an-Impact-Assessment_European-Biotech-Act_11-06-2025.pdf] call OK
19:26:38 [pillars:F3565376-ESIP-Feedback_Call-for-Evidence_for-an-Impact-Assessment_European-Biotech-Act_11-06-2025.pdf] waiting 10s before call...
19:26:52 [pillars:F3565376-ESIP-Feedback_Call-for-Evidence_for-an-Impact-Assessment_European-Biotech-Act_11-06-2025.pdf] call OK

Processing documents:  80%|███████▉  | 119/149 [1:04:57<15:26, 30.89s/doc, F3565383-New Harvest NL EUBiotechAct.pdf]

19:26:52 [info:F3565383-New Harvest NL EUBiotechAct.pdf] waiting 10s before call...
19:27:08 [info:F3565383-New Harvest NL EUBiotechAct.pdf] call OK
19:27:08 [pillars:F3565383-New Harvest NL EUBiotechAct.pdf] waiting 10s before call...
19:27:25 [pillars:F3565383-New Harvest NL EUBiotechAct.pdf] call OK

Processing documents:  81%|████████  | 120/149 [1:05:30<15:18, 31.66s/doc, F3565386-20250611-EBIC-BiotechAct-Submission.pdf]

19:27:25 [info:F3565386-20250611-EBIC-BiotechAct-Submission.pdf] waiting 10s before call...
19:27:42 [info:F3565386-20250611-EBIC-BiotechAct-Submission.pdf] call OK
19:27:42 [pillars:F3565386-20250611-EBIC-BiotechAct-Submission.pdf] waiting 10s before call...
19:27:57 [pillars:F3565386-20250611-EBIC-BiotechAct-Submission.pdf] call OK

Processing documents:  81%|████████  | 121/149 [1:06:02<14:43, 31.56s/doc, F3565387-BIC contribution to Biotech Act call for evidence FV 1.pdf]

19:27:57 [info:F3565387-BIC contribution to Biotech Act call for evidence FV 1.pdf] waiting 10s before call...
19:28:13 [info:F3565387-BIC contribution to Biotech Act call for evidence FV 1.pdf] call OK
19:28:13 [pillars:F3565387-BIC contribution to Biotech Act call for evidence FV 1.pdf] waiting 10s before call...
19:28:27 [pillars:F3565387-BIC contribution to Biotech Act call for evidence FV 1.pdf] call OK

Processing documents:  82%|████████▏ | 122/149 [1:06:32<14:02, 31.20s/doc, F3565388-2025 Biotech Act Call for evidence - IFF contribution FINAL - CASE STUDIES.pdf]

19:28:27 [info:F3565388-2025 Biotech Act Call for evidence - IFF contribution FINAL - CASE STUDIES.pdf] waiting 10s before call...
19:28:44 [info:F3565388-2025 Biotech Act Call for evidence - IFF contribution FINAL - CASE STUDIES.pdf] call OK
19:28:44 [pillars:F3565388-2025 Biotech Act Call for evidence - IFF contribution FINAL - CASE STUDIES.pdf] waiting 10s before call...
19:28:58 [pillars:F3565388-2025 Biotech Act Call for evidence - IFF contribution FINAL - CASE STUDIES.pdf] call OK

Processing documents:  83%|████████▎ | 123/149 [1:07:03<13:31, 31.20s/doc, F3565395-Lallemand Call for evidence EU Biotech Act.pdf]

19:28:58 [info:F3565395-Lallemand Call for evidence EU Biotech Act.pdf] waiting 10s before call...
19:29:16 [info:F3565395-Lallemand Call for evidence EU Biotech Act.pdf] call OK
19:29:16 [pillars:F3565395-Lallemand Call for evidence EU Biotech Act.pdf] waiting 10s before call...
19:29:29 [pillars:F3565395-Lallemand Call for evidence EU Biotech Act.pdf] call OK

Processing documents:  83%|████████▎ | 124/149 [1:07:34<13:00, 31.22s/doc, F3565399-Response from the European Respiratory Society (ERS) and the European Lung Foundation (ELF) to the European Commission Call for Evidence on the European Biotech Act.pdf]

19:29:29 [info:F3565399-Response from the European Respiratory Society (ERS) and the European Lung Foundation (ELF) to the European Commission Call for Evidence on the European Biotech Act.pdf] waiting 10s before call...
19:29:47 [info:F3565399-Response from the European Respiratory Society (ERS) and the European Lung Foundation (ELF) to the European Commission Call for Evidence on the European Biotech Act.pdf] call OK
19:29:47 [pillars:F3565399-Response from the European Respiratory Society (ERS) and the European Lung Foundation (ELF) to the European Commission Call for Evidence on the European Biotech Act.pdf] waiting 10s before call...
19:30:02 [pillars:F3565399-Response from the European Respiratory Society (ERS) and the European Lung Foundation (ELF) to the European Commission Call for Evidence on the European Biotech Act.pdf] call OK

Processing documents:  84%|████████▍ | 125/149 [1:08:07<12:38, 31.61s/doc, F3565405-20250611_Pharma Deutschland_Call for Evidence_Biotech Act.pdf]

19:30:02 [info:F3565405-20250611_Pharma Deutschland_Call for Evidence_Biotech Act.pdf] waiting 10s before call...
19:30:19 [info:F3565405-20250611_Pharma Deutschland_Call for Evidence_Biotech Act.pdf] call OK
19:30:19 [pillars:F3565405-20250611_Pharma Deutschland_Call for Evidence_Biotech Act.pdf] waiting 10s before call...
19:30:34 [pillars:F3565405-20250611_Pharma Deutschland_Call for Evidence_Biotech Act.pdf] call OK

Processing documents:  85%|████████▍ | 126/149 [1:08:39<12:09, 31.71s/doc, F3565413-20250611IPAEUROPE Biotech Act Call for Evidence.pdf]

19:30:34 [info:F3565413-20250611IPAEUROPE Biotech Act Call for Evidence.pdf] waiting 10s before call...
19:30:51 [info:F3565413-20250611IPAEUROPE Biotech Act Call for Evidence.pdf] call OK
19:30:51 [pillars:F3565413-20250611IPAEUROPE Biotech Act Call for Evidence.pdf] waiting 10s before call...
19:31:04 [pillars:F3565413-20250611IPAEUROPE Biotech Act Call for Evidence.pdf] call OK

Processing documents:  85%|████████▌ | 127/149 [1:09:09<11:25, 31.18s/doc, F3565422-EU Biotech Act_CSL Response.pdf]

19:31:04 [info:F3565422-EU Biotech Act_CSL Response.pdf] waiting 10s before call...
19:31:21 [info:F3565422-EU Biotech Act_CSL Response.pdf] call OK
19:31:21 [pillars:F3565422-EU Biotech Act_CSL Response.pdf] waiting 10s before call...
19:31:36 [pillars:F3565422-EU Biotech Act_CSL Response.pdf] call OK

Processing documents:  86%|████████▌ | 128/149 [1:09:41<11:01, 31.52s/doc, F3565426-AmchamEU_aeu_call_for_evidence_response_on_biotech_act.pdf]

19:31:36 [info:F3565426-AmchamEU_aeu_call_for_evidence_response_on_biotech_act.pdf] waiting 10s before call...
19:31:53 [info:F3565426-AmchamEU_aeu_call_for_evidence_response_on_biotech_act.pdf] call OK
19:31:53 [pillars:F3565426-AmchamEU_aeu_call_for_evidence_response_on_biotech_act.pdf] waiting 10s before call...
19:32:09 [pillars:F3565426-AmchamEU_aeu_call_for_evidence_response_on_biotech_act.pdf] call OK

Processing documents:  87%|████████▋ | 129/149 [1:10:14<10:35, 31.80s/doc, F3565431-Utrecht Region_Consultation European Commission Biotech Act.pdf]

19:32:09 [info:F3565431-Utrecht Region_Consultation European Commission Biotech Act.pdf] waiting 10s before call...
19:32:25 [info:F3565431-Utrecht Region_Consultation European Commission Biotech Act.pdf] call OK
19:32:25 [pillars:F3565431-Utrecht Region_Consultation European Commission Biotech Act.pdf] waiting 10s before call...
19:32:43 [pillars:F3565431-Utrecht Region_Consultation European Commission Biotech Act.pdf] call OK

Processing documents:  87%|████████▋ | 130/149 [1:10:47<10:16, 32.43s/doc, F3565435-Ecolab Position Paper on Supply Chain Resilience for Medicines and Boosting Biotechnology and Biomanufacturing in Europe.pdf]

19:32:43 [info:F3565435-Ecolab Position Paper on Supply Chain Resilience for Medicines and Boosting Biotechnology and Biomanufacturing in Europe.pdf] waiting 10s before call...
19:33:01 [info:F3565435-Ecolab Position Paper on Supply Chain Resilience for Medicines and Boosting Biotechnology and Biomanufacturing in Europe.pdf] call OK
19:33:01 [pillars:F3565435-Ecolab Position Paper on Supply Chain Resilience for Medicines and Boosting Biotechnology and Biomanufacturing in Europe.pdf] waiting 10s before call...
19:33:15 [pillars:F3565435-Ecolab Position Paper on Supply Chain Resilience for Medicines and Boosting Biotechnology and Biomanufacturing in Europe.pdf] call OK

Processing documents:  88%|████████▊ | 131/149 [1:11:20<09:43, 32.40s/doc, F3565438-EIT Health response to the call for evidence on the Biotech Act.pdf]

19:33:15 [info:F3565438-EIT Health response to the call for evidence on the Biotech Act.pdf] waiting 10s before call...
19:33:32 [info:F3565438-EIT Health response to the call for evidence on the Biotech Act.pdf] call OK
19:33:32 [pillars:F3565438-EIT Health response to the call for evidence on the Biotech Act.pdf] waiting 10s before call...
19:33:48 [pillars:F3565438-EIT Health response to the call for evidence on the Biotech Act.pdf] call OK

Processing documents:  89%|████████▊ | 132/149 [1:11:53<09:16, 32.75s/doc, F3565441-Biotech Act - Call for evidence - FAMHP.pdf]

19:33:48 [info:F3565441-Biotech Act - Call for evidence - FAMHP.pdf] waiting 10s before call...
19:34:06 [info:F3565441-Biotech Act - Call for evidence - FAMHP.pdf] call OK
19:34:06 [pillars:F3565441-Biotech Act - Call for evidence - FAMHP.pdf] waiting 10s before call...
19:34:22 [pillars:F3565441-Biotech Act - Call for evidence - FAMHP.pdf] call OK

Processing documents:  89%|████████▉ | 133/149 [1:12:27<08:49, 33.11s/doc, F3565444-2025-06 EU Biotech Position_FINAL (3).pdf]

19:34:22 [info:F3565444-2025-06 EU Biotech Position_FINAL (3).pdf] waiting 10s before call...
19:34:39 [info:F3565444-2025-06 EU Biotech Position_FINAL (3).pdf] call OK
19:34:39 [pillars:F3565444-2025-06 EU Biotech Position_FINAL (3).pdf] waiting 10s before call...
19:34:54 [pillars:F3565444-2025-06 EU Biotech Position_FINAL (3).pdf] call OK

Processing documents:  90%|████████▉ | 134/149 [1:12:59<08:10, 32.68s/doc, F3565463-M-Bios White paper - Biotech Act proposal - key points 20250611-FINAL.pdf]

19:34:54 [info:F3565463-M-Bios White paper - Biotech Act proposal - key points 20250611-FINAL.pdf] waiting 10s before call...
19:35:12 [info:F3565463-M-Bios White paper - Biotech Act proposal - key points 20250611-FINAL.pdf] call OK
19:35:12 [pillars:F3565463-M-Bios White paper - Biotech Act proposal - key points 20250611-FINAL.pdf] waiting 10s before call...
19:35:28 [pillars:F3565463-M-Bios White paper - Biotech Act proposal - key points 20250611-FINAL.pdf] call OK

Processing documents:  91%|█████████ | 135/149 [1:13:32<07:40, 32.90s/doc, F3565466-Submission_Biotech_dsm-firmenich_11-6-2025.pdf]

19:35:28 [info:F3565466-Submission_Biotech_dsm-firmenich_11-6-2025.pdf] waiting 10s before call...
19:35:45 [info:F3565466-Submission_Biotech_dsm-firmenich_11-6-2025.pdf] call OK
19:35:45 [pillars:F3565466-Submission_Biotech_dsm-firmenich_11-6-2025.pdf] waiting 10s before call...
19:35:59 [pillars:F3565466-Submission_Biotech_dsm-firmenich_11-6-2025.pdf] call OK

Processing documents:  91%|█████████▏| 136/149 [1:14:04<07:03, 32.59s/doc, F3565477-CLTR_EUBiotechAct_Submission.pdf]

19:35:59 [info:F3565477-CLTR_EUBiotechAct_Submission.pdf] waiting 10s before call...
19:36:16 [info:F3565477-CLTR_EUBiotechAct_Submission.pdf] call OK
19:36:16 [pillars:F3565477-CLTR_EUBiotechAct_Submission.pdf] waiting 10s before call...
19:36:32 [pillars:F3565477-CLTR_EUBiotechAct_Submission.pdf] call OK

Processing documents:  92%|█████████▏| 137/149 [1:14:37<06:31, 32.59s/doc, F3565481-EURORDIS Response Biotech Act CfE.pdf]

19:36:32 [info:F3565481-EURORDIS Response Biotech Act CfE.pdf] waiting 10s before call...
19:36:51 [info:F3565481-EURORDIS Response Biotech Act CfE.pdf] call OK
19:36:51 [pillars:F3565481-EURORDIS Response Biotech Act CfE.pdf] waiting 10s before call...
19:37:09 [pillars:F3565481-EURORDIS Response Biotech Act CfE.pdf] call OK

Processing documents:  93%|█████████▎| 138/149 [1:15:14<06:13, 33.94s/doc, F3565484-Preparation input EU Biotech Act - Call for evidence - 11062025.docx]

19:37:09 [info:F3565484-Preparation input EU Biotech Act - Call for evidence - 11062025.docx] waiting 10s before call...
19:37:30 [info:F3565484-Preparation input EU Biotech Act - Call for evidence - 11062025.docx] call OK
19:37:30 [pillars:F3565484-Preparation input EU Biotech Act - Call for evidence - 11062025.docx] waiting 10s before call...
19:37:47 [pillars:F3565484-Preparation input EU Biotech Act - Call for evidence - 11062025.docx] call OK

Processing documents:  93%|█████████▎| 139/149 [1:15:52<05:52, 35.24s/doc, F3565496-2025 06 11 Stockholm Trio_input_Biotech Act_FINAL.pdf]

19:37:47 [info:F3565496-2025 06 11 Stockholm Trio_input_Biotech Act_FINAL.pdf] waiting 10s before call...
19:38:06 [info:F3565496-2025 06 11 Stockholm Trio_input_Biotech Act_FINAL.pdf] call OK
19:38:06 [pillars:F3565496-2025 06 11 Stockholm Trio_input_Biotech Act_FINAL.pdf] waiting 10s before call...
19:38:23 [pillars:F3565496-2025 06 11 Stockholm Trio_input_Biotech Act_FINAL.pdf] call OK

Processing documents:  94%|█████████▍| 140/149 [1:16:28<05:18, 35.38s/doc, F3565499-SecureDNA Evidence for EU Biotech Act 06.11.2025.pdf]

19:38:23 [info:F3565499-SecureDNA Evidence for EU Biotech Act 06.11.2025.pdf] waiting 10s before call...
19:38:40 [info:F3565499-SecureDNA Evidence for EU Biotech Act 06.11.2025.pdf] call OK
19:38:40 [pillars:F3565499-SecureDNA Evidence for EU Biotech Act 06.11.2025.pdf] waiting 10s before call...
19:38:54 [pillars:F3565499-SecureDNA Evidence for EU Biotech Act 06.11.2025.pdf] call OK

Processing documents:  95%|█████████▍| 141/149 [1:16:59<04:33, 34.19s/doc, F3565503-New Genomic Techniques applied to food cultures a po w erful contribution to inno v a ti v e, safe, and sustainable food products.pdf]

19:38:54 [info:F3565503-New Genomic Techniques applied to food cultures a po w erful contribution to inno v a ti v e, safe, and sustainable food products.pdf] waiting 10s before call...
19:39:13 [info:F3565503-New Genomic Techniques applied to food cultures a po w erful contribution to inno v a ti v e, safe, and sustainable food products.pdf] call OK
19:39:13 [pillars:F3565503-New Genomic Techniques applied to food cultures a po w erful contribution to inno v a ti v e, safe, and sustainable food products.pdf] waiting 10s before call...
19:39:28 [pillars:F3565503-New Genomic Techniques applied to food cultures a po w erful contribution to inno v a ti v e, safe, and sustainable food products.pdf] call OK

Processing documents:  95%|█████████▌| 142/149 [1:17:33<03:57, 33.97s/doc, F3565509-DK feedback to Call for Evidence for Biotech Act.pdf]

19:39:28 [info:F3565509-DK feedback to Call for Evidence for Biotech Act.pdf] waiting 10s before call...
19:39:46 [info:F3565509-DK feedback to Call for Evidence for Biotech Act.pdf] call OK
19:39:46 [pillars:F3565509-DK feedback to Call for Evidence for Biotech Act.pdf] waiting 10s before call...
19:40:02 [pillars:F3565509-DK feedback to Call for Evidence for Biotech Act.pdf] call OK

Processing documents:  96%|█████████▌| 143/149 [1:18:07<03:24, 34.03s/doc, F3565510-Have your Say Plantum.pdf]

19:40:02 [info:F3565510-Have your Say Plantum.pdf] waiting 10s before call...
19:40:17 [info:F3565510-Have your Say Plantum.pdf] call OK
19:40:17 [pillars:F3565510-Have your Say Plantum.pdf] waiting 10s before call...
19:40:31 [pillars:F3565510-Have your Say Plantum.pdf] call OK

Processing documents:  97%|█████████▋| 144/149 [1:18:36<02:42, 32.59s/doc, F3565520-201809-ST0918EN-tyfa (1).pdf]

19:40:31 [info:F3565520-201809-ST0918EN-tyfa (1).pdf] waiting 10s before call...
19:40:50 [info:F3565520-201809-ST0918EN-tyfa (1).pdf] call OK
19:40:50 [pillars:F3565520-201809-ST0918EN-tyfa (1).pdf] waiting 10s before call...
19:41:04 [pillars:F3565520-201809-ST0918EN-tyfa (1).pdf] call OK

Processing documents:  97%|█████████▋| 145/149 [1:19:09<02:10, 32.69s/doc, F3565521-06112025_GLBS_Biotech_Act_Consultation_Contribution.pdf]

19:41:04 [info:F3565521-06112025_GLBS_Biotech_Act_Consultation_Contribution.pdf] waiting 10s before call...
19:41:21 [info:F3565521-06112025_GLBS_Biotech_Act_Consultation_Contribution.pdf] call OK
19:41:21 [pillars:F3565521-06112025_GLBS_Biotech_Act_Consultation_Contribution.pdf] waiting 10s before call...
19:41:36 [pillars:F3565521-06112025_GLBS_Biotech_Act_Consultation_Contribution.pdf] call OK

Processing documents:  98%|█████████▊| 146/149 [1:19:41<01:37, 32.36s/doc, F3565526-BBEPP statement_BiotechAct_June2025.pdf]

19:41:36 [info:F3565526-BBEPP statement_BiotechAct_June2025.pdf] waiting 10s before call...
19:41:52 [info:F3565526-BBEPP statement_BiotechAct_June2025.pdf] call OK
19:41:52 [pillars:F3565526-BBEPP statement_BiotechAct_June2025.pdf] waiting 10s before call...
19:42:06 [pillars:F3565526-BBEPP statement_BiotechAct_June2025.pdf] call OK

Processing documents:  99%|█████████▊| 147/149 [1:20:11<01:03, 31.73s/doc, F3565532-BiotechAct_VPHi.pdf]

19:42:06 [info:F3565532-BiotechAct_VPHi.pdf] waiting 10s before call...
19:42:23 [info:F3565532-BiotechAct_VPHi.pdf] call OK
19:42:23 [pillars:F3565532-BiotechAct_VPHi.pdf] waiting 10s before call...
19:42:37 [pillars:F3565532-BiotechAct_VPHi.pdf] call OK

Processing documents:  99%|█████████▉| 148/149 [1:20:42<00:31, 31.58s/doc, F3582124-Q12_cfe_biotech_act_Fondazione Telethon.docx]

19:42:37 [info:F3582124-Q12_cfe_biotech_act_Fondazione Telethon.docx] waiting 10s before call...
19:42:54 [info:F3582124-Q12_cfe_biotech_act_Fondazione Telethon.docx] call OK
19:42:54 [pillars:F3582124-Q12_cfe_biotech_act_Fondazione Telethon.docx] waiting 10s before call...
19:43:08 [pillars:F3582124-Q12_cfe_biotech_act_Fondazione Telethon.docx] call OK

Processing documents: 100%|██████████| 149/149 [1:21:13<00:00, 32.71s/doc, F3582124-Q12_cfe_biotech_act_Fondazione Telethon.docx]

In [106]:
# --- make a DataFrame with your exact columns ---
def _tolist(x):
    if isinstance(x, list):
        return x
    return [x] if x else []

def _tostr_or_none(x):
    if x is None:
        return None
    return x if isinstance(x, str) else str(x)

rows = []
for r in results:
    rows.append({
        "title": r.get("title"),
        "organisation": _tolist(r.get("organisation")),     # keep as list
        "page_number": r.get("page_number"),
        "summary": r.get("summary"),
        "main themes": _tolist(r.get("main themes")),       # keep as list
        "VC": _tostr_or_none(r.get("VC")),                  # strings or None
        "clusters": _tostr_or_none(r.get("clusters")),
        "skills": _tostr_or_none(r.get("skills")),
        "AI/data": _tostr_or_none(r.get("AI/data")),
        "dual_use/security":_tostr_or_none(r.get("dual_use/security"))
    })

df = pd.DataFrame(
    rows,
    columns=["title", "organisation", "page_number", "summary", "main themes",
             "VC", "clusters", "skills", "AI/data","dual_use/security"]
)

In [107]:
df

,title,organisation,page_number,summary,main themes,VC,clusters,skills,AI/data,dual_use/security
0,Feedback on the European Biotech Act,[RareGen Youth Network],None,This document provides feedback on the Europea...,"[Regulatory fragmentation and bottlenecks, Mar...",The document highlights persistent gaps in ris...,The document discusses the importance of biote...,A shortage of skilled biotech professionals is...,The document stresses the growing importance o...,The document raises concerns about dual-use ri...
1,Statement on the European Commission call for ...,[Standing Committee of European Doctors (CPME)],None,The document is a statement from the Standing ...,"[Biotech Act consultation, Transparency in the...",The document urges the European Commission to ...,None,None,None,None
2,Koppert’s Contribution to the EU Biotech Act C...,[Koppert],None,Koppert's submission to the EU Biotech Act con...,"[Biocontrol inclusion in EU Biotech Act, Regul...",The document highlights the need for the EU to...,It advocates for the creation of EU innovation...,None,The document proposes supporting public–privat...,None
3,Maturing Biological Risk Management for EU com...,[European Biosafety Association (EBSA)],None,This position paper by the European Biosafety ...,"[Regulatory simplification in life sciences, B...",None,None,None,None,The document highlights the need for a unified...
4,PhageEU proposals for amendments to Pharmaceut...,[PhageEU Coalition],None,This document proposes amendments to the EU Ph...,[Integration of phage therapies into EU pharma...,The document highlights that explicit inclusio...,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...
144,An agroecological Europe in 2050: multifunctio...,"[IDDRI, AScA]",None,This document presents the TYFA (Ten Years for...,"[Agroecological transition, Biodiversity resto...",None,None,None,None,None
145,Feedback on the Call for Evidence on the Biote...,[GreenLight Biosciences],None,This document provides GreenLight Biosciences'...,"[Regulatory simplification for biocontrol, Fun...",The document highlights significant funding ch...,The document advocates for the creation of res...,It notes that while Europe has a strong talent...,None,None
146,Organisational Background,[Bio Base Europe Pilot Plant],None,The document outlines the role of Bio Base Eur...,[Open access pilot and demonstration facilitie...,The document highlights that European support ...,None,The document stresses the importance of ensuri...,The document advocates for modernising pilot a...,None
147,Virtual Physiological Human Institute for Inte...,[Virtual Physiological Human Institute IVZW - ...,None,This document presents the Virtual Physiologic...,"[Digital technologies in biotechnology, Artifi...",None,None,None,The document highlights the strategic applicat...,None
148,Questionnaire for the Call for Evidence on the...,[Fondazione Telethon],None,Fondazione Telethon welcomes the European Comm...,"[Biotech product market acceleration, Support ...",The document highlights the fragile business c...,It emphasises the importance of specialised tr...,"The document calls for a bold, well-funded ini...",None,None

### Using PdfReader for page count

In [108]:
paths = sorted([p for p in Path(folder_path).iterdir() if p.is_file()])[:len(df)]

# Optional: DOCX/DOC via Microsoft Word (Windows only)
try:
    WORD_AVAILABLE = True
    word = win32.gencache.EnsureDispatch("Word.Application")
    word.Visible = False
except Exception:
    WORD_AVAILABLE = False
    word = None

def count_pages(p: Path):
    suf = p.suffix.lower()
    if suf == ".pdf":
        try:
            with open(p, "rb") as f:
                r = PdfReader(f)
                if getattr(r, "is_encrypted", False):
                    try: r.decrypt("")
                    except Exception: return np.nan
                return len(r.pages)
        except Exception:
            return np.nan
    if suf in (".docx", ".doc") and WORD_AVAILABLE:
        try:
            doc = word.Documents.Open(str(p))
            pages = int(doc.ComputeStatistics(2))  # 2 = wdStatisticPages
            doc.Close(False)
            return pages
        except Exception:
            return np.nan
    return np.nan

page_counts = pd.Series([count_pages(p) for p in paths], index=df.index).astype("Int64")

if word: 
    try: word.Quit()
    except Exception: pass

if "page_number" in df.columns:
    df = df.drop(columns=["page_number"])
df.insert(2, "page_number", page_counts)


df.insert(0, "file_name", pd.Series(docs[:len(df)], index=df.index))

Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 20 0 (offset 0)
Ignoring wrong pointing object 34 0 (offset 0)
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 9 0 (offset 0)
Ignoring wrong pointing object 11 0 (offset 0)
Ignoring wrong pointing object 13 0 (offset 0)
Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 17 0 (offset 0)
Ignoring wrong pointing object 19 0 (offset 0)
Ignoring wrong pointing object 49 0 (offset 0)
Ignoring wrong pointing object 54 0 (offset 0)
Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 9 0 (offset 0)
Ignoring wrong pointing object 11 0 (offset 0)
Ignoring wrong pointing object 14 0 (offset 0)
Ignoring wrong pointing object 23 0 (offset 0)
Ignoring wrong pointing object 28 0 (offset 0)
Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 13 0 (offset 0)
Ignoring wrong pointing object 16 0 (offset 0)
Ignoring wrong pointing object 18 0 (offset 0)
Ignoring wrong pointing object 25 0 (offset 0)
Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 11 0 (offset 0)
Ignoring wrong pointing object 13 0 (offset 0)
Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 17 0 (offset 0)
Ignoring wrong pointing object 19 0 (offset 0)
Ignoring wrong pointing object 26 0 (offset 0)
Ignoring wrong pointing object 28 0 (offset 0)
Ignoring wrong pointing object 34 0 (offset 0)
Ignoring wrong pointing object 36 0 (offset 0)
Ignoring wrong pointing object 38 0 (offset 0)
Ignoring wrong pointing object 49 0 (offset 0)
Ignoring wrong pointing object 66 0 (offset 0)
Ignoring wrong pointing object 74 0 (offset 0)
Ignoring wrong pointing object 76 0 (offset 0)
Ignoring wrong pointing object 78 0 (offset 0)
Ignoring wrong pointing object 94 0 (offset 0)
Ignoring wrong pointing object 122 0 (offset 0)
Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 35 0 (offset 0)

In [110]:
output_folder = Path(folder_path).parent / "results"
xlsx_path = Path(output_folder) / "RAG_all_results.xlsx"

df.to_excel(xlsx_path, index=False)
print(f"Saved: {xlsx_path}")

Saved: C:\Users\YağmurAslan\OneDrive - Technopolis Group Ltd\RAG_Brussels\results\RAG_all_results.xlsx

In [111]:
df[-30:]

,file_name,title,organisation,page_number,summary,main themes,VC,clusters,skills,AI/data,dual_use/security
119,F3565383-New Harvest NL EUBiotechAct.pdf,In support of The EU Biotech Act by Stichting ...,[Stichting New Harvest Netherlands],4,This document presents recommendations from St...,"[Cellular agriculture and novel foods, Regulat...",The document recommends that the EU create its...,The document proposes the creation of open acc...,The document calls for boosting research and a...,The document emphasises the importance of shar...,None
120,F3565386-20250611-EBIC-BiotechAct-Submission.pdf,EBIC’s Contribution to the European Commission...,[European Biostimulants Industry Council (EBIC)],4,This document presents EBIC's feedback on the ...,"[Regulatory coherence for biostimulants, Marke...",The document highlights that regulatory fragme...,None,None,None,None
121,F3565387-BIC contribution to Biotech Act call ...,BIC contribution to the call for evidence on E...,[BIC],2,The document provides BIC's input to the EU Bi...,"[Expanding the scope of the EU Biotech Act, St...",The document highlights the persistent challen...,None,The document stresses the necessity of investi...,None,None
122,F3565388-2025 Biotech Act Call for evidence - ...,IFF case studies for Call for Evidence on Biot...,[IFF],3,This document presents IFF's contributions to ...,"[Regulatory classification of biomaterials, Su...",The document highlights that current EU regula...,None,None,None,None
123,F3565395-Lallemand Call for evidence EU Biotec...,LALLEMAND’S COMMENTS TO THE EUROPEAN COMMISSIO...,[Lallemand],4,The document presents Lallemand's response to ...,[Broad and ambitious scope for the Biotech Act...,None,None,The document highlights that Europe's biotechn...,None,None
124,F3565399-Response from the European Respirator...,Response from the European Respiratory Society...,"[European Respiratory Society (ERS), European ...",3,The document is a response from the European R...,[Regulatory simplification with safety safegua...,None,None,The document highlights the need to strengthen...,The document supports the development of digit...,None
125,F3565405-20250611_Pharma Deutschland_Call for ...,POSITION PAPER of Pharma Deutschland e.V. on t...,[Pharma Deutschland e.V.],4,This position paper by Pharma Deutschland e.V....,"[Standardisation of regulatory requirements, R...",The document highlights the need to enhance in...,None,None,"The document recommends establishing agile, se...",None
126,F3565413-20250611IPAEUROPE Biotech Act Call fo...,INTERNATIONAL PROBIOTICS ASSOCIATION EUROPE,[International Probiotics Association Europe],3,The document highlights the transformative pot...,"[Fermentation technology and biosolutions, EU ...",None,None,None,The document proposes integrating data and AI ...,None
127,F3565422-EU Biotech Act_CSL Response.pdf,CSL Response to Call for Evidence for the EU B...,"[CSL, CSL Behring, CSL Vifor, CSL Seqirus]",4,This document is CSL's response to the Europea...,"[Regulatory harmonisation and simplification, ...",The document suggests considering the implemen...,The document recommends prioritising the devel...,The document calls for increased EU funding an...,The document advocates for advancing risk-adap...,None
128,F3565426-AmchamEU_aeu_call_for_evidence_respon...,Response to the Commission’s call for evidence...,[American Chamber of Commerce to the European ...,3,This document is AmCham EU's response to the E...,"[Regulatory coherence in biotech, Global compe...",The document highlights the need for EU-level ...,The document notes that European biotech clust...,None,The document states that AI and advanced compu...,The document recommends that the Biotech Act s...
129,F3565431-Utrecht Region_Consultation European ...,Consultation European Commission Biotech Act,[Utrecht Region],8,The document outlines the Utrecht Region's res...,"[Access to funding, Innovation infrastructure,...",The document highlights a structural gap in ac...,The document describes the Utrecht region as a...,The document notes significant challenges in a...,The document discusses the potential of AI-dri...,The document states that the Biotech Act must ...
130,F3565435-Ecolab Position Paper on Supply Chain...,Ecolab Position Paper on Supply Chain Resilien...,[Ecolab],6,This position paper highlights Europe's leadin...,"[Supply chain resilience for medicines, Biotec...",None,None,The document encourages the European Commissio...,None,None
131,F3565438-EIT Health response to the call for e...,EIT Health response to the call for evidence o...,[EIT Health],6,The document outlines EIT Health's recommendat...,"[Access to finance for biotech start-ups, Redu...",The document highlights that European biotech ...,The document emphasises the importance of inno...,The document stresses the need to invest in sp...,The document underscores the critical role of ...,None
132,F3565441-Biotech Act - Call for evidence - FAM...,FAMHP’s contribution to the call for evidence ...,[FAMHP],3,The document is a contribution from FAMHP to t...,"[Regulatory harmonisation, Biotechnology innov...",The document highlights a significant misalign...,None,None,The document acknowledges the growing importan...,The document notes that AI can play a role in ...
133,F3565444-2025-06 EU Biotech Position_FINAL (3)...,Recommendations for the EU Biotech Act,[Bayer],8,The document outlines Bayer's recommendations ...,"[Regulatory simplification for biotechnology, ...",None,None,None,The document highlights concerns regarding the...,None
134,F3565463-M-Bios White paper - Biotech Act prop...,EU Biotech Act: Delivering on Strategic autono...,[Medicines for Europe],10,This white paper highlights Europe's leadershi...,"[Biosimilar medicines leadership, Biosimilar v...",The document highlights the need for prioritis...,The document recommends mapping and supporting...,The document emphasises the importance of deve...,None,None
135,F3565466-Submission_Biotech_dsm-firmenich_11-6...,Leveraging the full potential of modern biotec...,[dsm-firmenich],5,This document outlines dsm-firmenich's recomme...,[Modern biotechnology's role in addressing glo...,The document highlights that public funding fo...,None,None,None,None
136,F3565477-CLTR_EUBiotechAct_Submission.pdf,Response to: European Biotech Act,"[The Centre for Long-Term Resilience, Alpenglo...",11,This submission from the Centre for Long-Term ...,"[Biosecurity and risk management, Synthetic nu...",The document highlights a critical financing g...,It proposes the development of strategic biote...,None,The document discusses the transformative role...,The document repeatedly emphasises the importa...
137,F3565481-EURORDIS Response Biotech Act CfE.pdf,EURORDIS Response Biotech Act CfE,[EURORDIS - Rare Diseases Europe],27,This document presents EURORDIS's response to ...,"[Rare diseases as a biotech priority, Unmet pa...",The document highlights the persistent challen...,The document advocates for the development of ...,It calls for investment in upskilling clinicia...,The document discusses the transformative pote...,None
138,F3565484-Preparation input EU Biotech Act - Ca...,Input EU Biotech Act – Call for Evidence – Inp...,"[Bio.be/essenscia, Belgian Life Sciences Indus...",5,The document provides input for the EU Biotech...,"[Regulatory process simplification, Clinical t...",The document proposes the creation of a coordi...,It recommends installing recognised EU Centres...,The document calls for a coordinated pan-Europ...,It advocates for a future-proof digital tools ...,None
139,F3565496-2025 06 11 Stockholm Trio_input_Biote...,Comments and input to the Call for evidence fo...,"[University Alliance Stockholm Trio, Karolinsk...",7,This document provides the University Alliance...,"[Data-driven innovation and AI in biotech, Reg...",The document highlights the need for improved ...,The document discusses the potential of creati...,It underscores the key role of universities in...,The document identifies access to data as a ma...,The document calls for further analysis of eth...
140,F3565499-SecureDNA Evidence for EU Biotech Act...,SecureDNA Foundation Response to the European ...,"[SecureDNA Foundation, Egger Dommer Bär AG]",4,The document presents SecureDNA Foundation's r...,"[Mandatory nucleic acid synthesis screening, E...",None,None,None,The document highlights the growing integratio...,The document repeatedly emphasises the need fo...
141,F3565503-New Genomic Techniques applied to foo...,New Genomic Techniques applied to food culture...,"[Sacco, Lesaffre, Lallemand SAS, Novonesis, IF...",7,This document reviews the application of nontr...,"[Nontransgenic New Genomic Techniques (NGTs), ...",The document notes that the current EU regulat...,None,None,None,None
142,F3565509-DK feedback to Call for Evidence for ...,Danish feedback to the call for evidence for t...,"[Danish Government, Danish Veterinary and Food...",7,This document presents the Danish Government's...,"[Regulatory streamlining and simplification, B...",The document highlights the central challenge ...,The document encourages support for biotech cl...,"To attract necessary talent, the document stat...",The document recognises artificial intelligenc...,None
143,F3565510-Have your Say Plantum.pdf,Attn.: Olivér Várhelyi,[Plantum],2,"This document is a letter from Plantum, the Du...","[Support for EU Biotech Act, Importance of bio...",None,The document highlights the importance of publ...,It calls for investment in education and train...,The document advocates for open and fair acces...,None
144,F3565520-201809-ST0918EN-tyfa (1).pdf,An agroecological Europe in 2050: multifunctio...,"[IDDRI, AScA]",74,This document presents the TYFA (Ten Years for...,"[Agroecological transition, Biodiversity resto...",None,None,None,None,None
145,F3565521-06112025_GLBS_Biotech_Act_Consultatio...,Feedback on the Call for Evidence on the Biote...,[GreenLight Biosciences],3,This document provides GreenLight Biosciences'...,"[Regulatory simplification for biocontrol, Fun...",The document highlights significant funding ch...,The document advocates for the creation of res...,It notes that while Europe has a strong talent...,None,None
146,F3565526-BBEPP statement_BiotechAct_June2025.pdf,Organisational Background,[Bio Base Europe Pilot Plant],3,The document outlines the role of Bio Base Eur...,[Open access pilot and demonstration facilitie...,The document highlights that European support ...,None,The document stresses the importance of ensuri...,The document advocates for modernising pilot a...,None
147,F3565532-BiotechAct_VPHi.pdf,Virtual Physiological Human Institute for Inte...,[Virtual Physiological Human Institute IVZW - ...,5,This document presents the Virtual Physiologic...,"[Digital technologies in biotechnology, Artifi...",None,None,None,The document highlights the strategic applicat...,None
148,F3582124-Q12_cfe_biotech_act_Fondazione Teleth...,Questionnaire for the Call for Evidence on the...,[Fondazione Telethon],2,Fondazione Telethon welcomes the European Comm...,"[Biotech product market acceleration, Support ...",The document highlights the fragile business c...,It emphasises the importance of specialised tr...,"The document calls for a bold, well-funded ini...",None,None

### Treating the Missings

In [36]:
output_folder = Path(folder_path).parent / "results"
xlsx_path = Path(output_folder) / "RAG_all_results.xlsx"
df = pd.read_excel(xlsx_path)

In [38]:
       
doc_name='F3565290-UniSR_European Biotech Act_Extended.pdf'
#doc_name='F3564682-Reco EU biotech EWPA EWPM 10.06.2025.pdf'

completion = client.chat.completions.create(
    model="gpt-4.1",
    messages=[{"role": "user", 
               "content": user_prompt}],
    extra_body={
        "data_sources": [
            {
                "type": "azure_search",
                "parameters": {
                    "endpoint": os.environ["AZURE_AI_SEARCH_ENDPOINT"],
                    "index_name": f"{container_name}_index",
                    "authentication": {
                        "type": "api_key",
                        "key": os.environ["AZURE_AI_SEARCH_API_KEY"],
                    },

                    # Map fields so citations show nice titles/paths (optional but handy)
                    "fields_mapping": {
                        "title_field": "title",
                        "filepath_field": "filepath",
                        "url_field": "url",
                        
                    },

                    # B) If you stored the doc name in a custom field
                    "filter": f"title eq '{odata_escape(doc_name)}'",


                    "in_scope": True,        # keep the answer grounded to retrieved docs
                    # "strictness": 4,       # (optional) tighten relevance
                    # "top_n_documents": 5,  # (optional) fewer chunks for stricter focus
                },
            }
        ],
    },
)

print(completion.choices[0].message.content)

{
  "title": "Contribution to the Consultation on the Future European Biotech Act",
  "organisation": ["Università Vita-Salute San Raffaele"],
  "summary": "The document is a contribution from Università Vita-Salute San Raffaele to the European Commission's consultation on the future European Biotech Act. It welcomes the initiative and provides recommendations to strengthen Europe's position in biotechnology. Key suggestions include enhanced support for academic centres, streamlined regulatory processes, and the creation of a 'Single Biotech Permit' for EU-wide operations. The document also advocates for a dedicated translational track for biotech projects and harmonised tax incentives for private investment. Additionally, it highlights the importance of secure and efficient access to anonymised patient data. The overall aim is to reduce barriers and accelerate innovation in the European biotech sector.",
  "main themes": [
    "Support for academic biotech research",
    "Regulatory streamlining",
    "Single Biotech Permit",
    "Translational track for biotech projects",
    "Tax incentives for biotech investment",
    "Data access and security",
    "Innovation acceleration",
    "EU-wide harmonisation"
  ]
}

In [39]:

extract_pillars(doc_name)

{'VC': 'The document proposes an EU framework for tax relief to incentivise high-risk investment in biotech, including tax credits, capital gains tax deferrals, and favourable treatment of convertible instruments. It argues that harmonising such incentives would create a more predictable and attractive landscape for both European and international investors.',
 'clusters': 'The document recommends dedicated support for academic centres to play a leading role in future biotech clusters and centres of excellence across the EU. It also suggests the creation of themed pan-European biotech accelerators to systematically transform research outputs into companies with access to capital, talent, and infrastructure.',
 'skills': None,
 'AI/data': 'The document highlights the importance of real-world data and AI in accelerating the development of innovative therapies, calling for dedicated support for AI technologies that leverage such data. It emphasises the need for collaboration between biotech companies, academic institutions, and healthcare providers to ensure data quality, interoperability, and robust interpretation.',
 'dual_use/security': None}

In [40]:
main_themes = [
    "Support for academic biotech research",
    "Regulatory streamlining",
    "Single Biotech Permit",
    "Translational track for biotech projects",
    "Tax incentives for biotech investment",
    "Data access and security",
    "Innovation acceleration",
    "EU-wide harmonisation"
  ]

print(main_themes)

['Support for academic biotech research', 'Regulatory streamlining', 'Single Biotech Permit', 'Translational track for biotech projects', 'Tax incentives for biotech investment', 'Data access and security', 'Innovation acceleration', 'EU-wide harmonisation']